.TH "/home/niall/Projects/Eclipse/cryomesh/src/structures/Bundle.cpp" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/structures/Bundle.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Bundle.h'\fP
.br
\fC#include 'utilities/SequencerChannels.h'\fP
.br
\fC#include <boost/uuid/uuid_io.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::structures\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::structures::operator<<\fP (std::ostream &os, const Bundle &bundle)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
