.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/structures/Cluster.cpp" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/structures/Cluster.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Cluster.h'\fP
.br
\fC#include <list>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'common/Maths.h'\fP
.br
\fC#include 'Fibre.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::structures\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::structures::operator<<\fP (std::ostream &os, const Cluster &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
