.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/manipulators/ClusterAnalysisData.h" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/manipulators/ClusterAnalysisData.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common/Tagged\&.h'\fP
.br
\fC#include 'common/Cycle\&.h'\fP
.br
\fC#include 'common/TimeKeeper\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::manipulators::ClusterAnalysisData\fP"
.br
.ti -1c
.RI "struct \fBcryomesh::manipulators::ClusterAnalysisData::RangeEnergy\fP"
.br
.RI "\fIStruct representing the value extrapolated over a history range\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.RI "\fI\fBConnector\&.h\fP\&. \fP"
.ti -1c
.RI "namespace \fBcryomesh::manipulators\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
