.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/structures/Cluster.h" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/structures/Cluster.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'components/NodeMap\&.h'\fP
.br
\fC#include 'components/ConnectionMap\&.h'\fP
.br
\fC#include 'spacial/Spacial\&.h'\fP
.br
\fC#include 'spacial/Point\&.h'\fP
.br
\fC#include <structures/NodeMesh\&.h>\fP
.br
\fC#include <boost/uuid/uuid\&.hpp>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include <components/Node\&.h>\fP
.br
\fC#include <components/Connection\&.h>\fP
.br
\fC#include 'common/Connector\&.h'\fP
.br
\fC#include 'common/Tagged\&.h'\fP
.br
\fC#include 'common/Debuggable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::structures::Cluster\fP"
.br
.RI "\fIA \fBCluster\fP is a collection of self-contained nodes and connections along with an associated \fBMesh\fP, that can be connected up to one another\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.RI "\fI\fBConnector\&.h\fP\&. \fP"
.ti -1c
.RI "namespace \fBcryomesh::manipulators\fP"
.br
.ti -1c
.RI "namespace \fBcryomesh::structures\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
