.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/ConnectionMap.h" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/ConnectionMap.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common/KeyMappedCollection.h'\fP
.br
\fC#include 'common/TimeKeeper.h'\fP
.br
\fC#include 'state/ActivityPattern.h'\fP
.br
\fC#include 'common/Cycle.h'\fP
.br
\fC#include <boost/uuid/uuid.hpp>\fP
.br
\fC#include <boost/shared_ptr.hpp>\fP
.br
\fC#include 'Connection.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::components::ConnectionMap\fP"
.br
.RI "\fIHelper class for \fBConnectionMap\fP to KeyMappedCollection mapping. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::components\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
