.TH "/home/niall/Projects/Eclipse/cryomesh/src/components/Connection.h" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/components/Connection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Node.h'\fP
.br
\fC#include 'common/Connector.h'\fP
.br
\fC#include 'common/Tagged.h'\fP
.br
\fC#include 'manager/DatabaseObject.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::components::Connection\fP"
.br
.RI "\fI\fBConnection\fP class to manage the transfer of Impulses between Nodes. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::components\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
