.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/common/Connector.h" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/common/Connector.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common/Cycle.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <boost/shared_ptr.hpp>\fP
.br
\fC#include <boost/uuid/uuid.hpp>\fP
.br
\fC#include 'common/Misc.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::common::Connector< U, T >\fP"
.br
.RI "\fI\fBConnector\fP is a template to add connectable functionality between two classes. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::common\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
