.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/manager/Creator.h" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/manager/Creator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config/ConfigTranslator\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include <structures/Bundle\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::manager::Creator\fP"
.br
.RI "\fIClass to take in a config file of ConfigTranslator form and parse the commands to create a full cryomesh object\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.RI "\fI\fBConnector\&.h\fP\&. \fP"
.ti -1c
.RI "namespace \fBcryomesh::manager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
