.TH "cryomesh::dataobjects" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::dataobjects \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataObject\fP"
.br
.RI "\fIClass to contain all the useful data about an object. \fP"
.ti -1c
.RI "class \fBDataObjectController\fP"
.br
.RI "\fIClass used to interface with data objects. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
