.TH "cryomesh::structures::Cluster" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::structures::Cluster \- 
.PP
A \fBCluster\fP is a collection of self-contained nodes and connections along with an associated \fBMesh\fP, that can be connected up to one another\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cluster\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEnergyFractionMethod\fP { \fBENERGY_FRACTION_BY_CLUSTER_COUNT\fP, \fBENERGY_FRACTION_BY_NODE_COUNT\fP, \fBENERGY_FRACTION_NULL\fP }"
.br
.ti -1c
.RI "enum \fBValueTypeSpecifier\fP { \fBAsIncrement\fP, \fBAsDecrement\fP, \fBAsMinumum\fP, \fBAsAbsolute\fP }"
.br
.RI "\fIEnum to force value type of a parameter\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCluster\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBCluster\fP (int nodeCount, int connectivity)"
.br
.RI "\fIConstructor with number of nodes and connectivity\&. \fP"
.ti -1c
.RI "\fBCluster\fP (int nodeCount, int connectivity, const spacial::Point bounding_box)"
.br
.ti -1c
.RI "virtual \fB~Cluster\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.RI "\fIUpdate all elements\&. \fP"
.ti -1c
.RI "void \fBupdateEnergy\fP (double total_energy)"
.br
.ti -1c
.RI "void \fBsetEnergyFractionMethod\fP (\fBEnergyFractionMethod\fP method, double max_energy_fraction)"
.br
.ti -1c
.RI "\fBEnergyFractionMethod\fP \fBgetEnergyFractionMethod\fP () const "
.br
.ti -1c
.RI "void \fBwarpNodes\fP ()"
.br
.ti -1c
.RI "void \fBrunAnalyser\fP ()"
.br
.ti -1c
.RI "virtual void \fBcreateConnectivity\fP (const int connectivity=1)"
.br
.RI "\fICreate connections between all nodes\&. \fP"
.ti -1c
.RI "const std::map
.br
< boost::uuids::uuid, 
.br
boost::shared_ptr
.br
< \fBcomponents::Node\fP > > & \fBgetNodes\fP () const "
.br
.RI "\fIGet all nodes\&. \fP"
.ti -1c
.RI "const std::map
.br
< boost::uuids::uuid, 
.br
boost::shared_ptr
.br
< \fBcomponents::Connection\fP > > & \fBgetConnections\fP () const "
.br
.RI "\fIGet all connections\&. \fP"
.ti -1c
.RI "const \fBcommon::Connector\fP
.br
< \fBCluster\fP, \fBFibre\fP > & \fBgetConnector\fP () const "
.br
.RI "\fIGet the connector for this \fBCluster\fP\&. \fP"
.ti -1c
.RI "\fBcommon::Connector\fP< \fBCluster\fP, 
.br
\fBFibre\fP > & \fBgetMutableConnector\fP ()"
.br
.RI "\fIGet the mutable connector for this \fBCluster\fP\&. \fP"
.ti -1c
.RI "const \fBcomponents::NodeMap\fP & \fBgetNodeMap\fP () const "
.br
.RI "\fIGet the NodeMap for this \fBCluster\fP\&. \fP"
.ti -1c
.RI "const \fBcomponents::ConnectionMap\fP & \fBgetConnectionMap\fP () const "
.br
.ti -1c
.RI "\fBcomponents::NodeMap\fP & \fBgetMutableNodeMap\fP ()"
.br
.RI "\fIGet the mutable NodeMap for this \fBCluster\fP\&. \fP"
.ti -1c
.RI "\fBcomponents::ConnectionMap\fP & \fBgetMutableConnectionMap\fP ()"
.br
.ti -1c
.RI "int \fBgetTriggeredNodeCount\fP (const int indicator=0) const "
.br
.RI "\fIGet the total fired nodes in this cluster currently\&. \fP"
.ti -1c
.RI "int \fBgetActiveNodeCount\fP (const int indicator=0) const "
.br
.RI "\fIGet the total active nodes in this cluster currently\&. \fP"
.ti -1c
.RI "int \fBgetLiveNodeCount\fP () const "
.br
.RI "\fIGet the total live nodes in this cluster currently, ie those with at least one impulse\&. \fP"
.ti -1c
.RI "double \fBgetEnergy\fP () const "
.br
.ti -1c
.RI "void \fBsetEnergy\fP (double d)"
.br
.ti -1c
.RI "double \fBgetMaxEnergyFraction\fP () const "
.br
.ti -1c
.RI "const boost::shared_ptr
.br
< \fBmanipulators::ClusterArchitect\fP > \fBgetClusterArchitect\fP () const "
.br
.ti -1c
.RI "boost::shared_ptr
.br
< \fBmanipulators::ClusterArchitect\fP > \fBgetMutableClusterArchitect\fP ()"
.br
.ti -1c
.RI "const boost::shared_ptr< \fBNodeMesh\fP > \fBgetMesh\fP () const "
.br
.ti -1c
.RI "boost::shared_ptr< \fBNodeMesh\fP > \fBgetMutableMesh\fP ()"
.br
.ti -1c
.RI "virtual void \fBenableDebug\fP (bool b)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const double \fBSELF_CONNECTED_NODES_FRACTION\fP = 0\&.1"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdateConnectivity\fP (const int connectivity, \fBValueTypeSpecifier\fP asValue=\fBAsIncrement\fP)"
.br
.RI "\fIUpdate connectivity so that each node has at least param number of connections\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBenergy\fP"
.br
.ti -1c
.RI "\fBcomponents::NodeMap\fP \fBnodes\fP"
.br
.ti -1c
.RI "\fBcomponents::ConnectionMap\fP \fBconnections\fP"
.br
.ti -1c
.RI "boost::shared_ptr< \fBNodeMesh\fP > \fBmesh\fP"
.br
.ti -1c
.RI "\fBcommon::Connector\fP< \fBCluster\fP, \fBFibre\fP > \fBconnector\fP"
.br
.ti -1c
.RI "boost::shared_ptr
.br
< \fBmanipulators::ClusterArchitect\fP > \fBclusterArchitect\fP"
.br
.ti -1c
.RI "\fBEnergyFractionMethod\fP \fBenergyFractionMethod\fP"
.br
.ti -1c
.RI "double \fBmaxEnergyFraction\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBCluster\fP &obj)"
.br
.RI "\fITo stream operator\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A \fBCluster\fP is a collection of self-contained nodes and connections along with an associated \fBMesh\fP, that can be connected up to one another\&. 
.PP
Definition at line 41 of file Cluster\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBcryomesh::structures::Cluster::EnergyFractionMethod\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIENERGY_FRACTION_BY_CLUSTER_COUNT \fP\fP
.TP
\fB\fIENERGY_FRACTION_BY_NODE_COUNT \fP\fP
.TP
\fB\fIENERGY_FRACTION_NULL \fP\fP

.PP
Definition at line 45 of file Cluster\&.h\&.
.SS "enum \fBcryomesh::structures::Cluster::ValueTypeSpecifier\fP"
.PP
Enum to force value type of a parameter\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIAsIncrement \fP\fP
.TP
\fB\fIAsDecrement \fP\fP
.TP
\fB\fIAsMinumum \fP\fP
.TP
\fB\fIAsAbsolute \fP\fP

.PP
Definition at line 53 of file Cluster\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::structures::Cluster::Cluster\fP ()"
.PP
Default constructor\&. 
.PP
Definition at line 22 of file Cluster\&.cpp\&.
.SS "\fBcryomesh::structures::Cluster::Cluster\fP (intnodeCount, intconnectivity)"
.PP
Constructor with number of nodes and connectivity\&. \fBParameters:\fP
.RS 4
\fIint\fP nodeCount Number of nodes to make 
.br
\fIint\fP connectivity Connectivity to start with 
.RE
.PP

.PP
Definition at line 35 of file Cluster\&.cpp\&.
.PP
References clusterArchitect\&.
.SS "\fBcryomesh::structures::Cluster::Cluster\fP (intnodeCount, intconnectivity, const spacial::Pointbounding_box)"
.PP
Definition at line 28 of file Cluster\&.cpp\&.
.PP
References clusterArchitect\&.
.SS "\fBcryomesh::structures::Cluster::~Cluster\fP ()\fC [virtual]\fP"
.PP
Destructor\&. 
.PP
Definition at line 42 of file Cluster\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBcryomesh::structures::Cluster::createConnectivity\fP (const intconnectivity = \fC1\fP)\fC [virtual]\fP"
.PP
Create connections between all nodes\&. \fBParameters:\fP
.RS 4
\fIint\fP connectivity The number of connections between each node 
.RE
.PP

.PP
Definition at line 89 of file Cluster\&.cpp\&.
.PP
References AsIncrement, and updateConnectivity()\&.
.SS "void \fBcryomesh::structures::Cluster::enableDebug\fP (boolb)\fC [virtual]\fP"
.PP
Definition at line 306 of file Cluster\&.cpp\&.
.PP
References connections, and nodes\&.
.SS "int \fBcryomesh::structures::Cluster::getActiveNodeCount\fP (const intindicator = \fC0\fP) const"
.PP
Get the total active nodes in this cluster currently\&. \fBParameters:\fP
.RS 4
\fIint\fP Set >0 for only positive active nodes, <0 for negative, 0 for all (default)
.RE
.PP
\fBReturns:\fP
.RS 4
int The total count of currently active nodes 
.RE
.PP

.PP
Definition at line 263 of file Cluster\&.cpp\&.
.PP
References getNodes()\&.
.SS "const boost::shared_ptr< \fBmanipulators::ClusterArchitect\fP > \fBcryomesh::structures::Cluster::getClusterArchitect\fP () const"
.PP
Definition at line 72 of file Cluster\&.cpp\&.
.PP
References clusterArchitect\&.
.SS "const \fBcomponents::ConnectionMap\fP & \fBcryomesh::structures::Cluster::getConnectionMap\fP () const"
.PP
Definition at line 222 of file Cluster\&.cpp\&.
.PP
References connections\&.
.PP
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), and cryomesh::manipulators::ClusterArchitect::getRandomConnections()\&.
.SS "const std::map< boost::uuids::uuid, boost::shared_ptr< \fBcomponents::Connection\fP > > & \fBcryomesh::structures::Cluster::getConnections\fP () const"
.PP
Get all connections\&. \fBReturns:\fP
.RS 4
std::map<boost::uuids::uuid, boost::shared_ptr< components::Connection > > Return all Connections 
.RE
.PP

.PP
Definition at line 204 of file Cluster\&.cpp\&.
.PP
References connections\&.
.PP
Referenced by cryomesh::structures::operator<<()\&.
.SS "const \fBcommon::Connector\fP< \fBCluster\fP, \fBFibre\fP > & \fBcryomesh::structures::Cluster::getConnector\fP () const"
.PP
Get the connector for this \fBCluster\fP\&. \fBReturns:\fP
.RS 4
common::Connector<Cluster, Fibre> The connector for this \fBCluster\fP 
.RE
.PP

.PP
Definition at line 208 of file Cluster\&.cpp\&.
.PP
References connector\&.
.SS "double \fBcryomesh::structures::Cluster::getEnergy\fP () const"
.PP
Definition at line 54 of file Cluster\&.cpp\&.
.PP
References energy\&.
.PP
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), and cryomesh::structures::NodeMesh::warpNodes()\&.
.SS "\fBCluster::EnergyFractionMethod\fP \fBcryomesh::structures::Cluster::getEnergyFractionMethod\fP () const"
.PP
Definition at line 68 of file Cluster\&.cpp\&.
.PP
References energyFractionMethod\&.
.SS "int \fBcryomesh::structures::Cluster::getLiveNodeCount\fP () const"
.PP
Get the total live nodes in this cluster currently, ie those with at least one impulse\&. \fBReturns:\fP
.RS 4
int The total count of currently live nodes 
.RE
.PP

.PP
Definition at line 312 of file Cluster\&.cpp\&.
.PP
References getNodes()\&.
.SS "double \fBcryomesh::structures::Cluster::getMaxEnergyFraction\fP () const"
.PP
Definition at line 60 of file Cluster\&.cpp\&.
.PP
References maxEnergyFraction\&.
.PP
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster()\&.
.SS "const boost::shared_ptr<\fBNodeMesh\fP> \fBcryomesh::structures::Cluster::getMesh\fP () const\fC [inline]\fP"
.PP
Definition at line 184 of file Cluster\&.h\&.
.PP
References mesh\&.
.SS "boost::shared_ptr< \fBmanipulators::ClusterArchitect\fP > \fBcryomesh::structures::Cluster::getMutableClusterArchitect\fP ()"
.PP
Definition at line 76 of file Cluster\&.cpp\&.
.PP
References clusterArchitect\&.
.SS "\fBcomponents::ConnectionMap\fP & \fBcryomesh::structures::Cluster::getMutableConnectionMap\fP ()"
.PP
Definition at line 225 of file Cluster\&.cpp\&.
.PP
References connections\&.
.PP
Referenced by cryomesh::manipulators::ClusterArchitect::createConnection(), cryomesh::manipulators::ClusterArchitect::createRandomConnections(), cryomesh::manipulators::ClusterArchitect::deleteConnection(), cryomesh::manipulators::ClusterArchitect::destroyRandomConnections(), cryomesh::manipulators::ClusterArchitect::destroyRandomNodes(), and cryomesh::manipulators::ClusterArchitect::getRandomConnections()\&.
.SS "\fBcommon::Connector\fP< \fBCluster\fP, \fBFibre\fP > & \fBcryomesh::structures::Cluster::getMutableConnector\fP ()"
.PP
Get the mutable connector for this \fBCluster\fP\&. \fBReturns:\fP
.RS 4
common::Connector<Cluster, Fibre> The mutable onnector for this \fBCluster\fP 
.RE
.PP

.PP
Definition at line 212 of file Cluster\&.cpp\&.
.PP
References connector\&.
.SS "boost::shared_ptr<\fBNodeMesh\fP> \fBcryomesh::structures::Cluster::getMutableMesh\fP ()\fC [inline]\fP"
.PP
Definition at line 187 of file Cluster\&.h\&.
.PP
References mesh\&.
.SS "\fBcomponents::NodeMap\fP & \fBcryomesh::structures::Cluster::getMutableNodeMap\fP ()"
.PP
Get the mutable NodeMap for this \fBCluster\fP\&. \fBReturns:\fP
.RS 4
\fBcomponents::NodeMap\fP The mutable NodeMap for this \fBCluster\fP 
.RE
.PP

.PP
Definition at line 219 of file Cluster\&.cpp\&.
.PP
References nodes\&.
.PP
Referenced by cryomesh::manipulators::ClusterArchitect::createRandomConnections(), cryomesh::manipulators::ClusterArchitect::createRandomNodes(), cryomesh::manipulators::ClusterArchitect::destroyRandomNodes(), and cryomesh::manipulators::ClusterArchitect::getRandomNodes()\&.
.SS "const \fBcomponents::NodeMap\fP & \fBcryomesh::structures::Cluster::getNodeMap\fP () const"
.PP
Get the NodeMap for this \fBCluster\fP\&. \fBReturns:\fP
.RS 4
\fBcomponents::NodeMap\fP The NodeMap for this \fBCluster\fP 
.RE
.PP

.PP
Definition at line 216 of file Cluster\&.cpp\&.
.PP
References nodes\&.
.PP
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), cryomesh::manipulators::ClusterArchitect::createRandomNodes(), cryomesh::manipulators::ClusterArchitect::getRandomNodes(), and cryomesh::structures::operator<<()\&.
.SS "const std::map< boost::uuids::uuid, boost::shared_ptr< \fBcomponents::Node\fP > > & \fBcryomesh::structures::Cluster::getNodes\fP () const"
.PP
Get all nodes\&. \fBReturns:\fP
.RS 4
std::map<boost::uuids::uuid, boost::shared_ptr< components::Node > > Return all nodes 
.RE
.PP

.PP
Definition at line 200 of file Cluster\&.cpp\&.
.PP
References nodes\&.
.PP
Referenced by getActiveNodeCount(), getLiveNodeCount(), getTriggeredNodeCount(), cryomesh::structures::NodeMesh::NodeMesh(), cryomesh::structures::operator<<(), cryomesh::structures::NodeMesh::regenerateNeighbourhoods(), and cryomesh::structures::Mesh::update()\&.
.SS "int \fBcryomesh::structures::Cluster::getTriggeredNodeCount\fP (const intindicator = \fC0\fP) const"
.PP
Get the total fired nodes in this cluster currently\&. \fBParameters:\fP
.RS 4
\fIint\fP Set >0 for only positive triggered nodes, <0 for negative, 0 for all (default)
.RE
.PP
\fBReturns:\fP
.RS 4
int The total count of currently triggered nodes 
.RE
.PP

.PP
Definition at line 228 of file Cluster\&.cpp\&.
.PP
References getNodes(), cryomesh::components::Node::Negative, cryomesh::components::Node::None, and cryomesh::components::Node::Positive\&.
.SS "void \fBcryomesh::structures::Cluster::runAnalyser\fP ()"
.PP
Definition at line 85 of file Cluster\&.cpp\&.
.PP
References clusterArchitect\&.
.SS "void \fBcryomesh::structures::Cluster::setEnergy\fP (doubled)"
.PP
Definition at line 57 of file Cluster\&.cpp\&.
.PP
References energy\&.
.SS "void \fBcryomesh::structures::Cluster::setEnergyFractionMethod\fP (\fBEnergyFractionMethod\fPmethod, doublemax_energy_fraction)"
.PP
Definition at line 63 of file Cluster\&.cpp\&.
.PP
References energyFractionMethod, and maxEnergyFraction\&.
.SS "void \fBcryomesh::structures::Cluster::update\fP ()"
.PP
Update all elements\&. 
.PP
Definition at line 45 of file Cluster\&.cpp\&.
.PP
References connections, mesh, nodes, cryomesh::components::NodeMap::update(), and cryomesh::components::ConnectionMap::update()\&.
.SS "void \fBcryomesh::structures::Cluster::updateConnectivity\fP (const intconnectivity, \fBValueTypeSpecifier\fPasValue = \fC\fBAsIncrement\fP\fP)\fC [protected, virtual]\fP"
.PP
Update connectivity so that each node has at least param number of connections\&. \fBParameters:\fP
.RS 4
\fIint\fP connectivity The least connectivity to ensure 
.RE
.PP

.PP
Definition at line 93 of file Cluster\&.cpp\&.
.PP
References AsIncrement, AsMinumum, clusterArchitect, nodes, and SELF_CONNECTED_NODES_FRACTION\&.
.PP
Referenced by createConnectivity()\&.
.SS "void \fBcryomesh::structures::Cluster::updateEnergy\fP (doubletotal_energy)"
.SS "void \fBcryomesh::structures::Cluster::warpNodes\fP ()"
.PP
Definition at line 80 of file Cluster\&.cpp\&.
.PP
References mesh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBCluster\fP &obj)\fC [friend]\fP"
.PP
To stream operator\&. \fBParameters:\fP
.RS 4
\fIstd::ostream\fP & os The output stream 
.br
\fIconst\fP \fBCluster\fP & obj The object to stream
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream & The output stream 
.RE
.PP

.PP
Definition at line 331 of file Cluster\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "boost::shared_ptr<\fBmanipulators::ClusterArchitect\fP> \fBcryomesh::structures::Cluster::clusterArchitect\fP\fC [private]\fP"
.PP
Definition at line 247 of file Cluster\&.h\&.
.PP
Referenced by Cluster(), getClusterArchitect(), getMutableClusterArchitect(), runAnalyser(), and updateConnectivity()\&.
.SS "\fBcomponents::ConnectionMap\fP \fBcryomesh::structures::Cluster::connections\fP\fC [private]\fP"
.PP
Definition at line 231 of file Cluster\&.h\&.
.PP
Referenced by enableDebug(), getConnectionMap(), getConnections(), getMutableConnectionMap(), and update()\&.
.SS "\fBcommon::Connector\fP<\fBCluster\fP, \fBFibre\fP> \fBcryomesh::structures::Cluster::connector\fP\fC [private]\fP"
.PP
Definition at line 245 of file Cluster\&.h\&.
.PP
Referenced by getConnector(), and getMutableConnector()\&.
.SS "double \fBcryomesh::structures::Cluster::energy\fP\fC [private]\fP"
.PP
Definition at line 217 of file Cluster\&.h\&.
.PP
Referenced by getEnergy(), and setEnergy()\&.
.SS "\fBEnergyFractionMethod\fP \fBcryomesh::structures::Cluster::energyFractionMethod\fP\fC [private]\fP"
.PP
Definition at line 248 of file Cluster\&.h\&.
.PP
Referenced by getEnergyFractionMethod(), and setEnergyFractionMethod()\&.
.SS "double \fBcryomesh::structures::Cluster::maxEnergyFraction\fP\fC [private]\fP"
.PP
Definition at line 249 of file Cluster\&.h\&.
.PP
Referenced by getMaxEnergyFraction(), and setEnergyFractionMethod()\&.
.SS "boost::shared_ptr<\fBNodeMesh\fP> \fBcryomesh::structures::Cluster::mesh\fP\fC [private]\fP"
.PP
Definition at line 238 of file Cluster\&.h\&.
.PP
Referenced by getMesh(), getMutableMesh(), update(), and warpNodes()\&.
.SS "\fBcomponents::NodeMap\fP \fBcryomesh::structures::Cluster::nodes\fP\fC [private]\fP"
.PP
Definition at line 224 of file Cluster\&.h\&.
.PP
Referenced by enableDebug(), getMutableNodeMap(), getNodeMap(), getNodes(), update(), and updateConnectivity()\&.
.SS "const double \fBcryomesh::structures::Cluster::SELF_CONNECTED_NODES_FRACTION\fP = 0\&.1\fC [static]\fP"
.PP
Definition at line 204 of file Cluster\&.h\&.
.PP
Referenced by updateConnectivity()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
