cryomesh::manager::DatabaseObject
NAME
cryomesh::manager::DatabaseObject -
SYNOPSIS
#include <DatabaseObject.h>
Inherited by cryomesh::manager::ConnectionDatabaseObject, cryomesh::manager::NodeDatabaseObject, and cryomesh::manager::PatternDatabaseObject.
Public Member Functions
DatabaseObject ()
virtual ~DatabaseObject ()
std::string getKey (const std::string &key) const
Return the string object associated with a key.
virtual std::string getInsert (const std::string &table) const =0
Get the string that can be used to insert the sql data.
Static Public Member Functions
static std::string findValue (const std::string &entry, const std::map< std::string, std::string > &map)
Find entries value in map or return null.
static std::map< std::string,
std::string > getColumnMapFromEntry (const std::string &entry)"
Parse a string database entry, extract columns and values and return a map.
template<class T > static std::string toString (T obj)
Convert an templated object that can be piped to a stream to a string.
Protected Attributes
std::map< std::string,
std::string > columns"
Detailed Description
Definition at line 21 of file DatabaseObject.h.
Constructor & Destructor Documentation
cryomesh::manager::DatabaseObject::DatabaseObject () [inline]
Definition at line 23 of file DatabaseObject.h.
virtual cryomesh::manager::DatabaseObject::~DatabaseObject () [inline, virtual]
Definition at line 25 of file DatabaseObject.h.
Member Function Documentation
static std::string cryomesh::manager::DatabaseObject::findValue (const std::string &entry, const std::map< std::string, std::string > &map) [inline, static]
Find entries value in map or return null. Parameters:
std::string Entry to find
std::map<std::string,std::string map to search
Returns:
Value of entry
Definition at line 59 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
static std::map<std::string, std::string> cryomesh::manager::DatabaseObject::getColumnMapFromEntry (const std::string &entry) [inline, static]
Parse a string database entry, extract columns and values and return a map.
Definition at line 72 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
virtual std::string cryomesh::manager::DatabaseObject::getInsert (const std::string &table) const [pure virtual]
Get the string that can be used to insert the sql data. Returns:
the sql command string to insert into this table
Implemented in cryomesh::manager::ConnectionDatabaseObject, cryomesh::manager::NodeDatabaseObject, and cryomesh::manager::PatternDatabaseObject.
Referenced by cryomesh::manager::DatabaseManager::insertConnection(), cryomesh::manager::DatabaseManager::insertNode(), and cryomesh::manager::DatabaseManager::insertOutputPattern().
std::string cryomesh::manager::DatabaseObject::getKey (const std::string &key) const [inline]
Return the string object associated with a key. ::string The key to search for
Returns:
std::string The object associated with the search key, '' if not found
Definition at line 37 of file DatabaseObject.h.
References columns.
Referenced by cryomesh::manager::PatternDatabaseObject::getInsert(), cryomesh::manager::NodeDatabaseObject::getInsert(), and cryomesh::manager::ConnectionDatabaseObject::getInsert().
template<class T > static std::string cryomesh::manager::DatabaseObject::toString (Tobj) [inline, static]
Convert an templated object that can be piped to a stream to a string. Parameters:
T The object to get a string for
Definition at line 108 of file DatabaseObject.h.
Member Data Documentation
std::map<std::string, std::string> cryomesh::manager::DatabaseObject::columns [protected]
Definition at line 119 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), getKey(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
Author
Generated automatically by Doxygen for cryomesh from the source code.