cryomesh::spacial
NAME
cryomesh::spacial -
SYNOPSIS
Classes
class Degree
class Point
class Radian
class SphericalPoint
Functions
std::ostream & operator<< (std::ostream &os, const Point &obj)
std::ostream & operator<< (std::ostream &os, const SphericalPoint &obj)
Function Documentation
std::ostream& cryomesh::spacial::operator<< (std::ostream &os, const Point &obj)
Definition at line 104 of file Point.cpp.
std::ostream& cryomesh::spacial::operator<< (std::ostream &os, const SphericalPoint &obj)
Definition at line 159 of file SphericalPoint.cpp.
References cryomesh::spacial::SphericalPoint::getPhi(), cryomesh::spacial::SphericalPoint::getRadius(), cryomesh::spacial::SphericalPoint::getTheta(), and cryomesh::spacial::Radian::toDegrees().
Author
Generated automatically by Doxygen for cryomesh from the source code.