.TH "cryomesh::state::Pattern" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::state::Pattern \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pattern\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPattern\fP ()"
.br
.ti -1c
.RI "\fBPattern\fP (const \fBPattern\fP &)"
.br
.ti -1c
.RI "\fBPattern\fP (const std::string &)"
.br
.ti -1c
.RI "\fBPattern\fP (const std::vector< bool > &)"
.br
.ti -1c
.RI "\fBPattern\fP (const \fBBinaryString\fP &obj)"
.br
.ti -1c
.RI "virtual \fB~Pattern\fP ()"
.br
.ti -1c
.RI "\fBPattern\fP & \fBoperator=\fP (const \fBPattern\fP &)"
.br
.ti -1c
.RI "double \fBcompare\fP (const \fBPattern\fP &) const "
.br
.ti -1c
.RI "bool \fBisAllZeroes\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPattern\fP &) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPattern\fP &) const "
.br
.ti -1c
.RI "std::vector< bool > \fBgetPattern\fP () const "
.br
.ti -1c
.RI "std::string \fBgetString\fP () const "
.br
.ti -1c
.RI "void \fBsetPattern\fP (const std::vector< bool > &)"
.br
.ti -1c
.RI "int \fBgetId\fP () const "
.br
.ti -1c
.RI "void \fBsetId\fP (int)"
.br
.ti -1c
.RI "int \fBgetWidth\fP () const "
.br
.ti -1c
.RI "int \fBgetSize\fP () const "
.br
.ti -1c
.RI "const \fBBinaryString\fP & \fBgetBinaryString\fP () const "
.br
.ti -1c
.RI "\fBBinaryString\fP & \fBgetMutableBinaryString\fP ()"
.br
.ti -1c
.RI "const boost::shared_ptr
.br
< \fBPatternTag\fP > \fBgetPatternTag\fP () const "
.br
.ti -1c
.RI "void \fBsetPatternTag\fP (boost::shared_ptr< \fBPatternTag\fP > pt)"
.br
.ti -1c
.RI "boost::shared_ptr
.br
< \fBmanager::DatabaseObject\fP > \fBgetDatabaseObject\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetIds\fP ()"
.br
.ti -1c
.RI "static int \fBassignIds\fP ()"
.br
.ti -1c
.RI "static void \fBsetIds\fP (int)"
.br
.ti -1c
.RI "static std::string \fBpatternToString\fP (const std::vector< bool > &vec)"
.br
.ti -1c
.RI "static std::vector< bool > \fBstringToPattern\fP (const std::string &)"
.br
.ti -1c
.RI "static \fBPattern\fP \fBgetRandom\fP (unsigned int width, double fraction=0\&.5)"
.br
.RI "\fIGenerate a random pattern of width\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.ti -1c
.RI "void \fBinitialise\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBinaryString\fP \fBbinaryString\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "boost::shared_ptr< \fBPatternTag\fP > \fBpatternTag\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static int \fBids\fP = 1"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBPattern\fP &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file Pattern\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::state::Pattern::Pattern\fP ()"
.PP
Definition at line 31 of file Pattern\&.cpp\&.
.PP
References initialise()\&.
.PP
Referenced by getRandom()\&.
.SS "\fBcryomesh::state::Pattern::Pattern\fP (const \fBPattern\fP &pat)"
.PP
Definition at line 35 of file Pattern\&.cpp\&.
.PP
References initialise()\&.
.SS "\fBcryomesh::state::Pattern::Pattern\fP (const std::string &str)"
.PP
Definition at line 43 of file Pattern\&.cpp\&.
.PP
References initialise()\&.
.SS "\fBcryomesh::state::Pattern::Pattern\fP (const std::vector< bool > &pat)"
.PP
Definition at line 39 of file Pattern\&.cpp\&.
.PP
References initialise()\&.
.SS "\fBcryomesh::state::Pattern::Pattern\fP (const \fBBinaryString\fP &obj)"
.SS "\fBcryomesh::state::Pattern::~Pattern\fP ()\fC [virtual]\fP"
.PP
Definition at line 47 of file Pattern\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int \fBcryomesh::state::Pattern::assignIds\fP ()\fC [static]\fP"
.PP
Definition at line 212 of file Pattern\&.cpp\&.
.PP
References ids\&.
.SS "double \fBcryomesh::state::Pattern::compare\fP (const \fBPattern\fP &obj) const"
.PP
Definition at line 63 of file Pattern\&.cpp\&.
.PP
References getPattern()\&.
.SS "const \fBBinaryString\fP & \fBcryomesh::state::Pattern::getBinaryString\fP () const"
.PP
Definition at line 159 of file Pattern\&.cpp\&.
.PP
References binaryString\&.
.PP
Referenced by operator=()\&.
.SS "boost::shared_ptr< \fBmanager::DatabaseObject\fP > \fBcryomesh::state::Pattern::getDatabaseObject\fP () const"
.PP
Definition at line 229 of file Pattern\&.cpp\&.
.PP
References cryomesh::common::TimeKeeper::getCycle(), getString(), cryomesh::common::TimeKeeper::getTimeKeeper(), and cryomesh::common::Cycle::toULInt()\&.
.SS "int \fBcryomesh::state::Pattern::getId\fP () const"
.PP
Definition at line 142 of file Pattern\&.cpp\&.
.PP
References id\&.
.PP
Referenced by operator<(), cryomesh::state::operator<<(), and operator=()\&.
.SS "int \fBcryomesh::state::Pattern::getIds\fP ()\fC [static]\fP"
.PP
Definition at line 218 of file Pattern\&.cpp\&.
.PP
References ids\&.
.PP
Referenced by cryomesh::state::PatternTagById::getEndTag()\&.
.SS "\fBBinaryString\fP & \fBcryomesh::state::Pattern::getMutableBinaryString\fP ()"
.PP
Definition at line 162 of file Pattern\&.cpp\&.
.PP
References binaryString\&.
.SS "std::vector< bool > \fBcryomesh::state::Pattern::getPattern\fP () const"
.PP
Definition at line 133 of file Pattern\&.cpp\&.
.PP
References binaryString, and cryomesh::state::BinaryString::getBools()\&.
.PP
Referenced by compare(), cryomesh::structures::Fibre::forceFireNodes(), getString(), operator==(), and cryomesh::structures::Fibre::trigger()\&.
.SS "const boost::shared_ptr< \fBPatternTag\fP > \fBcryomesh::state::Pattern::getPatternTag\fP () const"
.PP
Definition at line 205 of file Pattern\&.cpp\&.
.PP
References patternTag\&.
.SS "\fBPattern\fP \fBcryomesh::state::Pattern::getRandom\fP (unsigned intwidth, doublefraction = \fC0\&.5\fP)\fC [static]\fP"
.PP
Generate a random pattern of width\&. \fBParameters:\fP
.RS 4
\fIunsigned\fP int Width of pattern to generate 
.br
\fIdouble\fP Fraction of pattern to activate, default to 0\&.5 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPattern\fP The random pattern 
.RE
.PP

.PP
Definition at line 21 of file Pattern\&.cpp\&.
.PP
References Pattern()\&.
.PP
Referenced by cryomesh::structures::Fibre::trigger()\&.
.SS "int \fBcryomesh::state::Pattern::getSize\fP () const"
.PP
Definition at line 155 of file Pattern\&.cpp\&.
.PP
References binaryString, and cryomesh::state::BinaryString::getWidth()\&.
.PP
Referenced by cryomesh::structures::Fibre::forceFireNodes(), and getWidth()\&.
.SS "std::string \fBcryomesh::state::Pattern::getString\fP () const"
.PP
Definition at line 136 of file Pattern\&.cpp\&.
.PP
References getPattern(), and patternToString()\&.
.PP
Referenced by getDatabaseObject(), and cryomesh::state::operator<<()\&.
.SS "int \fBcryomesh::state::Pattern::getWidth\fP () const"
.PP
Definition at line 151 of file Pattern\&.cpp\&.
.PP
References getSize()\&.
.SS "void \fBcryomesh::state::Pattern::initialise\fP ()\fC [private]\fP"
.PP
Definition at line 237 of file Pattern\&.cpp\&.
.PP
References patternTag\&.
.PP
Referenced by operator=(), and Pattern()\&.
.SS "bool \fBcryomesh::state::Pattern::isAllZeroes\fP () const"
.PP
Definition at line 60 of file Pattern\&.cpp\&.
.PP
References binaryString, and cryomesh::state::BinaryString::isAllZeroes()\&.
.SS "bool cryomesh::state::Pattern::operator< (const \fBPattern\fP &obj) const"
.PP
Definition at line 129 of file Pattern\&.cpp\&.
.PP
References getId()\&.
.SS "\fBPattern\fP & cryomesh::state::Pattern::operator= (const \fBPattern\fP &obj)"
.PP
Definition at line 51 of file Pattern\&.cpp\&.
.PP
References binaryString, getBinaryString(), getId(), initialise(), and setId()\&.
.SS "bool cryomesh::state::Pattern::operator== (const \fBPattern\fP &obj) const"
.PP
Definition at line 115 of file Pattern\&.cpp\&.
.PP
References getPattern()\&.
.SS "std::string \fBcryomesh::state::Pattern::patternToString\fP (const std::vector< bool > &vec)\fC [static]\fP"
.PP
Definition at line 166 of file Pattern\&.cpp\&.
.PP
Referenced by getString()\&.
.SS "template<class Archive > void \fBcryomesh::state::Pattern::serialize\fP (Archive &ar, const unsigned intversion)\fC [inline, private]\fP"
.PP
Definition at line 30 of file Pattern\&.h\&.
.PP
References binaryString, id, and ids\&.
.SS "void \fBcryomesh::state::Pattern::setId\fP (intnew_id)"
.PP
Definition at line 145 of file Pattern\&.cpp\&.
.PP
Referenced by operator=()\&.
.SS "void \fBcryomesh::state::Pattern::setIds\fP (intis)\fC [static]\fP"
.PP
Definition at line 222 of file Pattern\&.cpp\&.
.PP
References ids\&.
.SS "void \fBcryomesh::state::Pattern::setPattern\fP (const std::vector< bool > &pat)"
.PP
Definition at line 139 of file Pattern\&.cpp\&.
.PP
References binaryString, and cryomesh::state::BinaryString::setBinaryString()\&.
.SS "void \fBcryomesh::state::Pattern::setPatternTag\fP (boost::shared_ptr< \fBPatternTag\fP >pt)"
.PP
Definition at line 208 of file Pattern\&.cpp\&.
.PP
References patternTag\&.
.SS "std::vector< bool > \fBcryomesh::state::Pattern::stringToPattern\fP (const std::string &str)\fC [static]\fP"
.PP
Definition at line 184 of file Pattern\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"
.PP
Definition at line 28 of file Pattern\&.h\&.
.SS "std::ostream& operator<< (std::ostream &os, const \fBPattern\fP &obj)\fC [friend]\fP"
.PP
Definition at line 242 of file Pattern\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBinaryString\fP \fBcryomesh::state::Pattern::binaryString\fP\fC [private]\fP"
.PP
Definition at line 115 of file Pattern\&.h\&.
.PP
Referenced by getBinaryString(), getMutableBinaryString(), getPattern(), getSize(), isAllZeroes(), operator=(), serialize(), and setPattern()\&.
.SS "int \fBcryomesh::state::Pattern::id\fP\fC [private]\fP"
.PP
Definition at line 117 of file Pattern\&.h\&.
.PP
Referenced by getId(), and serialize()\&.
.SS "int \fBcryomesh::state::Pattern::ids\fP = 1\fC [static, private]\fP"
.PP
Definition at line 128 of file Pattern\&.h\&.
.PP
Referenced by assignIds(), getIds(), serialize(), and setIds()\&.
.SS "boost::shared_ptr<\fBPatternTag\fP> \fBcryomesh::state::Pattern::patternTag\fP\fC [private]\fP"
.PP
Definition at line 120 of file Pattern\&.h\&.
.PP
Referenced by getPatternTag(), initialise(), and setPatternTag()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
