cryomesh::components::Connection
NAME
cryomesh::components::Connection -
Connection class to manage the transfer of Impulses between Nodes.
SYNOPSIS
#include <Connection.h>
Public Member Functions
Connection ()
Constructor for Connection.
virtual ~Connection ()
Destructor for Connection.
virtual void update ()
Update the Connection.
virtual const
common::Connector< Connection,
Node > & getConnector () const "
Get the Connector object for this Connection input.
virtual common::Connector
< Connection, Node > & getMutableConnector ()"
Get the mutable Connector object for this Connection.
boost::shared_ptr< Impulse > add (boost::shared_ptr< Impulse > impulse)
Add an Impulse to this connection.
boost::shared_ptr< Impulse > remove (boost::shared_ptr< Impulse > impulse)
Add an Impulse to this connection.
boost::shared_ptr< Impulse > remove (Impulse &impulse)
Remove an Impulse from this connection.
const ImpulseCollection & getImpulses () const
Get the impulse collection.
ImpulseCollection & getMutableImpulses ()
Get the mutable impulse collection.
const boost::shared_ptr
< components::ActivityTimerDistance > getActivityTimer () const "
The get activity timer for this object.
boost::shared_ptr
< components::ActivityTimerDistance > getMutableActivityTimer ()"
The get mutable activity timer for this object.
boost::shared_ptr
< manager::DatabaseObject > getDatabaseObject () const "
Return a database object for this object.
void updatePosition ()
Update position.
void connectInput (boost::shared_ptr< Node > node)
void connectOutput (boost::shared_ptr< Node > node)
void disconnect ()
void disconnectInput ()
void disconnectOutput ()
bool isPrimaryInputConnection () const
bool isPrimaryOutputConnection () const
virtual void enableDebug (bool b)
Protected Attributes
boost::shared_ptr
< common::Connector
< Connection, Node > > connector"
ImpulseCollection impulses
boost::shared_ptr
< components::ActivityTimerDistance > activityTimer"
Friends
std::ostream & operator<< (std::ostream &os, const Connection &obj)
To stream operator.
Detailed Description
Connection class to manage the transfer of Impulses between Nodes.
A Connection represents the 'journey' made by Impulses as they travel between a start Node and an end Node. They can be spatially based or more abstract representations of this journey. As each clock moment passes Impulses are propagated in some way 'closer' to their end Node. Impulses can be altered by the Mesh on each cycle. When Impulses reach the 'end' of their journey they are passed to the end Node for accumulation. Connections can also be bi-directional, an Impulse from a start Node could be in some way 'reflected' back to that node. Perhaps once in a 'weighted' reflection to be accumulated by the start Node, or even in a constant per-cycle reflection as the original Impulse 'moves along' the Connection
Definition at line 37 of file Connection.h.
Constructor & Destructor Documentation
cryomesh::components::Connection::Connection ()
Constructor for Connection. Constructor
Definition at line 16 of file Connection.cpp.
cryomesh::components::Connection::~Connection () [virtual]
Destructor for Connection. Destructor
Definition at line 22 of file Connection.cpp.
Member Function Documentation
boost::shared_ptr< Impulse > cryomesh::components::Connection::add (boost::shared_ptr< Impulse >impulse)
Add an Impulse to this connection. Parameters:
boost::shared_ptr<Impulse> impulse The Impulse to add
Returns:
boost::shared_ptr<Impulse> The Impulse added, null if none added
Definition at line 86 of file Connection.cpp.
References activityTimer, and impulses.
Referenced by cryomesh::components::Node::emitImpulse().
void cryomesh::components::Connection::connectInput (boost::shared_ptr< Node >node)
Definition at line 177 of file Connection.cpp.
References getMutableConnector().
void cryomesh::components::Connection::connectOutput (boost::shared_ptr< Node >node)
Definition at line 180 of file Connection.cpp.
References getMutableConnector().
void cryomesh::components::Connection::disconnect ()
Definition at line 183 of file Connection.cpp.
References disconnectInput(), and disconnectOutput().
void cryomesh::components::Connection::disconnectInput ()
Definition at line 188 of file Connection.cpp.
References getConnector(), and getMutableConnector().
Referenced by disconnect().
void cryomesh::components::Connection::disconnectOutput ()
Definition at line 207 of file Connection.cpp.
References getConnector(), and getMutableConnector().
Referenced by disconnect().
void cryomesh::components::Connection::enableDebug (boolb) [virtual]
Definition at line 242 of file Connection.cpp.
const boost::shared_ptr< components::ActivityTimerDistance > cryomesh::components::Connection::getActivityTimer () const
The get activity timer for this object. const ActiveImpulseCollection & Connection::getActiveImpulses() const { return this->activeImpulses; }
Returns:
boost::shared_ptr<ActivityTimer>
ActiveImpulseCollection & Connection::getMutableActiveImpulses() { return this->activeImpulses; }
Definition at line 132 of file Connection.cpp.
References activityTimer.
const common::Connector< Connection, Node > & cryomesh::components::Connection::getConnector () const [virtual]
Get the Connector object for this Connection input. Returns:
common::Connector<Connection, Node> The connector for this Connection
Definition at line 78 of file Connection.cpp.
References connector.
Referenced by disconnectInput(), disconnectOutput(), getDatabaseObject(), isPrimaryInputConnection(), isPrimaryOutputConnection(), and cryomesh::components::operator<<().
boost::shared_ptr< manager::DatabaseObject > cryomesh::components::Connection::getDatabaseObject () const
Return a database object for this object. Returns:
DatabaseObject
Definition at line 140 of file Connection.cpp.
References getConnector(), cryomesh::common::TimeKeeper::getCycle(), getImpulses(), and cryomesh::common::TimeKeeper::getTimeKeeper().
const ImpulseCollection & cryomesh::components::Connection::getImpulses () const
Get the impulse collection. Returns:
const ImpulseCollection & The impulse collection
Definition at line 114 of file Connection.cpp.
References impulses.
Referenced by cryomesh::components::Node::emitImpulse(), getDatabaseObject(), and cryomesh::components::operator<<().
boost::shared_ptr< components::ActivityTimerDistance > cryomesh::components::Connection::getMutableActivityTimer ()
The get mutable activity timer for this object. Returns:
boost::shared_ptr<ActivityTimer>
Definition at line 136 of file Connection.cpp.
References activityTimer.
common::Connector< Connection, Node > & cryomesh::components::Connection::getMutableConnector () [virtual]
Get the mutable Connector object for this Connection. Returns:
common::Connector<Connection, Node> The connector for this Connection
Definition at line 82 of file Connection.cpp.
References connector.
Referenced by connectInput(), connectOutput(), disconnectInput(), and disconnectOutput().
ImpulseCollection & cryomesh::components::Connection::getMutableImpulses ()
Get the mutable impulse collection. Returns:
ImpulseCollection & The mutable impulse collection
Definition at line 118 of file Connection.cpp.
References impulses.
bool cryomesh::components::Connection::isPrimaryInputConnection () const
Definition at line 227 of file Connection.cpp.
References getConnector().
Referenced by cryomesh::components::operator<<().
bool cryomesh::components::Connection::isPrimaryOutputConnection () const
Definition at line 235 of file Connection.cpp.
References getConnector().
Referenced by cryomesh::components::operator<<().
boost::shared_ptr< Impulse > cryomesh::components::Connection::remove (boost::shared_ptr< Impulse >impulse)
Add an Impulse to this connection. Parameters:
Impulse & impulse The Impulse to add
Returns:
boost::shared_ptr<Impulse> The Impulse added, null if none added boost::shared_ptr<Impulse> add(Impulse & impulse); Remove an Impulse from this connection
Parameters:
boost::shared_ptr<Impulse> impulse The impulse to remove
Returns:
boost::shared_ptr<Impulse> The Impulse removed, null if none removed
Definition at line 106 of file Connection.cpp.
References impulses.
boost::shared_ptr< Impulse > cryomesh::components::Connection::remove (Impulse &impulse)
Remove an Impulse from this connection. Parameters:
Impulse & impulse The impulse to remove
Returns:
boost::shared_ptr<Impulse> The Impulse removed, null if none removed
Definition at line 110 of file Connection.cpp.
References impulses.
void cryomesh::components::Connection::update () [virtual]
Update the Connection. Update our collection of impulses. If any reach the 'endpoint' of the connection then pass them on to our end Nodes
Definition at line 25 of file Connection.cpp.
References connector, cryomesh::components::ImpulseCollection::decrementActivityTimers(), impulses, cryomesh::components::ImpulseCollection::LessThanOrEqualTo, and cryomesh::components::ImpulseCollection::removeByActivityTimerValue().
void cryomesh::components::Connection::updatePosition ()
Update position.
Definition at line 160 of file Connection.cpp.
References activityTimer, connector, and cryomesh::components::ActivityTimerDistance::MIN_DISTANCE.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Connection &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Connection & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 245 of file Connection.cpp.
Member Data Documentation
boost::shared_ptr<components::ActivityTimerDistance> cryomesh::components::Connection::activityTimer [protected]
Definition at line 211 of file Connection.h.
Referenced by add(), getActivityTimer(), getMutableActivityTimer(), and updatePosition().
boost::shared_ptr<common::Connector<Connection, Node> > cryomesh::components::Connection::connector [protected]
Definition at line 197 of file Connection.h.
Referenced by getConnector(), getMutableConnector(), update(), and updatePosition().
ImpulseCollection cryomesh::components::Connection::impulses [protected]
Definition at line 204 of file Connection.h.
Referenced by add(), getImpulses(), getMutableImpulses(), remove(), and update().
Author
Generated automatically by Doxygen for cryomesh from the source code.