cryomesh::manager::DatabaseManager
NAME
cryomesh::manager::DatabaseManager -
Database manager creates and maintains a database of mesh related objects and data.
SYNOPSIS
#include <DatabaseManager.h>
Public Member Functions
DatabaseManager (const std::string &dbfile=DEFAULT_DATABASE)
Default constructor using a filename as the database or a default Opens the file or creates it and creates the tables if it doesnt exist.
virtual ~DatabaseManager ()
Default destructor closes the database.
bool isDatabaseAccessable () const
Check if the database is accessible.
void createTables ()
Create all needed tables.
void clearTables ()
Clear all tables.
std::string clearTable (const std::string &table)
Clear all values in a table.
std::string dropTable (const std::string &table)
Drop a table from database.
std::string insertNode (const DatabaseObject &db_object)
Insert a node data object into the table.
std::string insertConnection (const DatabaseObject &db_object)
Insert a connection data object into the table.
std::string selectNode (const std::string &uuid, const common::Cycle &cycle)
Select unique node entry.
std::string selectConnection (const std::string &uuid, const common::Cycle &cycle)
Select unique column entry.
std::string selectNodeValue (const std::string &uuid, const common::Cycle &cycle, const std::string &column)
Select unique node column entry.
std::string selectConnectionValue (const std::string &uuid, const common::Cycle &cycle, const std::string &column)
Select unique column column entry.
std::string selectValue (const std::string &table, const std::string &uuid, const common::Cycle &cycle, const std::string &column)
Select unique column column entry from table.
std::string selectNodes (const std::string &criteria='')
Select nodes by a criteria string eg, 'id=erwrs324 AND cycle=1'.
std::string selectConnections (const std::string &criteria='')
Select connections by a criteria string eg, 'id=erwrs324 AND cycle=1'.
std::string deleteNode (const std::string &id)
Delete node by uuid.
std::string deleteNodes (const std::string &criteria='')
Delete nodes by a criteria string eg, 'id=erwrs324 AND cycle=1'.
std::string deleteConnection (const std::string &id)
Delete connection by uuid.
std::string deleteConnections (const std::string &criteria='')
Delete nodes by a criteria string eg, 'id=erwrs324 AND cycle=1'.
std::string deleteSelected (const std::string &table, const std::string &criteria='')
Delete objects from a table by a criteria string eg, 'id=erwrs324 AND cycle=1'.
int countNodes (const std::string &criteria='')
Count nodes by a criteria string eg, 'cycle=1'.
int countConnections (const std::string &criteria='')
Count connections by a criteria string eg, 'cycle=1'.
int countRows (const std::string &table, const std::string &criteria='')
Count objects from a table by a criteria string eg, 'cycle=1'.
std::string updateNode (const std::string &uuid_str, const common::Cycle &cycle, const std::string &options)
update node from using options list
std::string updateConnection (const std::string &uuid_str, const common::Cycle &cycle, const std::string &options)
update node from using options list
std::string updateByUUID (const std::string &uuid_str, const common::Cycle &cycle, const std::string &options, const std::string &table)
update object from a table using options list
std::string select (const std::string &table, const std::string &criteria='')
Select all columns from table using criteria.
std::string deleteAll (const std::string &table)
delete all data from table
std::string deleteAllByCycle (const common::Cycle &cycle, int comparison_type)
delete all by cycle
std::string deleteNodesByCycle (const common::Cycle &cycle, int comparison_type)
delete nodes by cycle
std::string deleteConnectionsByCycle (const common::Cycle &cycle, int comparison_type)
delete connections by cycle
std::string deleteByCycle (const std::string &table, const common::Cycle &cycle, int comparison_type)
delete objects from table by cycle
std::ostream & printHistory (std::ostream &os, const common::Cycle &cycle)
Print sql history to output stream.
std::ostream & printHistory (std::ostream &os, unsigned int countback=1)
Print sql history to output stream.
Static Public Member Functions
static int databaseCallback (void *unused, int argc, char **argv, char **columnName)
Function that is called on finishing an sql command.
Static Public Attributes
static const std::string DEFAULT_DATABASE = 'default.db'
static const NodeTableFormat NODES_TABLE_FORMAT
static const ConnectionTableFormat CONNECTIONS_TABLE_FORMAT
Default connection table format.
Protected Member Functions
std::string sqlCommand (const std::string &command)
Run a provided sql command string.
std::string sqlCommandBySelection (const std::string &table, const std::string &command, const std::string &criteria)
Static Protected Member Functions
static const std::multimap< common::Cycle, std::pair< std::string, std::string > > & addHistoryEntry (const std::string &command, const std::string &results, std::multimap< common::Cycle, std::pair< std::string, std::string > > &map)
Add an entry to a historical multimap.
static const std::multimap< common::Cycle, std::pair< std::string, std::string > > & addHistoryEntry (const std::string &command, const std::vector< std::string > &results, std::multimap< common::Cycle, std::pair< std::string, std::string > > &map)
Add an list of entries to a historical multimap.
Protected Attributes
sqlite3 * database
int errorCode
char * errorMessage
bool databaseAccess
Database accessable.
std::multimap< common::Cycle, std::pair< std::string, std::string > > sqlResults
std::vector< std::string > sqlResultsBuffer
Static Protected Attributes
static const common::Cycle MAX_COMMAND_HISTORY = common::Cycle(100)
Detailed Description
Database manager creates and maintains a database of mesh related objects and data.
Definition at line 30 of file DatabaseManager.h.
Constructor & Destructor Documentation
cryomesh::manager::DatabaseManager::DatabaseManager (const std::string &dbfile = DEFAULT_DATABASE)
Default constructor using a filename as the database or a default Opens the file or creates it and creates the tables if it doesnt exist. Parameters:
std::string The name of the database to open/create
Definition at line 57 of file DatabaseManager.cpp.
cryomesh::manager::DatabaseManager::~DatabaseManager () [virtual]
Default destructor closes the database.
Definition at line 82 of file DatabaseManager.cpp.
Member Function Documentation
const std::multimap< common::Cycle, std::pair< std::string, std::string > > & cryomesh::manager::DatabaseManager::addHistoryEntry (const std::string &command, const std::string &results, std::multimap< common::Cycle, std::pair< std::string, std::string > > &map) [static, protected]
Add an entry to a historical multimap. Parameters:
std::string Entry to add
std::multimap<std::string,std::string> Map to add entry to
Returns:
std::multimap<std::string, std::string> Return the modified map
Definition at line 320 of file DatabaseManager.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper(), and MAX_COMMAND_HISTORY.
Referenced by addHistoryEntry().
const std::multimap< common::Cycle, std::pair< std::string, std::string > > & cryomesh::manager::DatabaseManager::addHistoryEntry (const std::string &command, const std::vector< std::string > &results, std::multimap< common::Cycle, std::pair< std::string, std::string > > &map) [static, protected]
Add an list of entries to a historical multimap. Parameters:
std::vector<std::string> Entries to add
std::multimap<std::string,std::string> Map to add entry to
Returns:
std::multimap<std::string, std::string> Return the modified map
Definition at line 301 of file DatabaseManager.cpp.
References addHistoryEntry().
std::string cryomesh::manager::DatabaseManager::clearTable (const std::string &table)
Clear all values in a table. Parameters:
std::string The table to clear
Returns:
std::string The result of the sql query
Definition at line 101 of file DatabaseManager.cpp.
void cryomesh::manager::DatabaseManager::clearTables ()
Clear all tables.
Definition at line 96 of file DatabaseManager.cpp.
int cryomesh::manager::DatabaseManager::countConnections (const std::string &criteria = '')
Count connections by a criteria string eg, 'cycle=1'. Parameters:
std::string The criteria to match
Returns:
int The result of the count
Definition at line 184 of file DatabaseManager.cpp.
int cryomesh::manager::DatabaseManager::countNodes (const std::string &criteria = '')
Count nodes by a criteria string eg, 'cycle=1'. Parameters:
std::string The criteria to match
Returns:
int The result of the count
Definition at line 181 of file DatabaseManager.cpp.
int cryomesh::manager::DatabaseManager::countRows (const std::string &table, const std::string &criteria = '')
Count objects from a table by a criteria string eg, 'cycle=1'. Parameters:
std::string The table to count from
std::string The criteria to match
Returns:
int The result of the count
Definition at line 188 of file DatabaseManager.cpp.
void cryomesh::manager::DatabaseManager::createTables ()
Create all needed tables.
Definition at line 91 of file DatabaseManager.cpp.
int cryomesh::manager::DatabaseManager::databaseCallback (void *unused, intargc, char **argv, char **columnName) [static]
Function that is called on finishing an sql command.
Definition at line 28 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteAll (const std::string &table)
delete all data from table Parameters:
std::string Name of table
Returns:
std::string sql query results
std::string cryomesh::manager::DatabaseManager::deleteAllByCycle (const common::Cycle &cycle, intcomparison_type)
delete all by cycle Parameters:
common::Cycle Cycle to compare against
int The type of comparison to make, <0 for less than, ==0 for equals, and >0 for greater than
Returns:
std::string sql query results
Definition at line 235 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteByCycle (const std::string &table, const common::Cycle &cycle, intcomparison_type)
delete objects from table by cycle Parameters:
std::string The table to delete from
common::Cycle Cycle to compare against
int The type of comparison to make, <0 for less than, ==0 for equals, and >0 for greater than
Returns:
std::string sql query results
Definition at line 248 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteConnection (const std::string &id)
Delete connection by uuid. Parameters:
std::string The uuid to match
Returns:
std::string Result of sql query
Definition at line 165 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteConnections (const std::string &criteria = '')
Delete nodes by a criteria string eg, 'id=erwrs324 AND cycle=1'. Parameters:
std::string The criteria to match
Returns:
std::string Result of sql query
Definition at line 171 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteConnectionsByCycle (const common::Cycle &cycle, intcomparison_type)
delete connections by cycle Parameters:
common::Cycle Cycle to compare against
int The type of comparison to make, <0 for less than, ==0 for equals, and >0 for greater than
Returns:
std::string sql query results
Definition at line 244 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteNode (const std::string &id)
Delete node by uuid. Parameters:
std::string The uuid to match
Returns:
std::string Result of sql query
Definition at line 155 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteNodes (const std::string &criteria = '')
Delete nodes by a criteria string eg, 'id=erwrs324 AND cycle=1'. Parameters:
std::string The criteria to match
Returns:
std::string Result of sql query
Definition at line 161 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteNodesByCycle (const common::Cycle &cycle, intcomparison_type)
delete nodes by cycle Parameters:
common::Cycle Cycle to compare against
int The type of comparison to make, <0 for less than, ==0 for equals, and >0 for greater than
Returns:
std::string sql query results
Definition at line 240 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::deleteSelected (const std::string &table, const std::string &criteria = '')
Delete objects from a table by a criteria string eg, 'id=erwrs324 AND cycle=1'. Parameters:
std::string The table to delete from
std::string The criteria to match
Returns:
std::string Result of sql query
Definition at line 175 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::dropTable (const std::string &table)
Drop a table from database. Parameters:
std::string The table to drop
Returns:
std::string The result of the sql query
Definition at line 228 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::insertConnection (const DatabaseObject &db_object)
Insert a connection data object into the table. Parameters:
DatabaseObject Database object to insert as a node
Returns:
std::string Result of sql query
Definition at line 110 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::insertNode (const DatabaseObject &db_object)
Insert a node data object into the table. Parameters:
DatabaseObject Database object to insert as a node
Returns:
std::string Result of sql query
Definition at line 107 of file DatabaseManager.cpp.
bool cryomesh::manager::DatabaseManager::isDatabaseAccessable () const
Check if the database is accessible. Returns:
bool True if deemed accessible, false otherwise
Definition at line 87 of file DatabaseManager.cpp.
std::ostream & cryomesh::manager::DatabaseManager::printHistory (std::ostream &os, const common::Cycle &cycle)
Print sql history to output stream. Parameters:
std::ostream Output stream to print to
Cycle The cycle to print information on
Returns:
std::ostream Return the supplied output stream
Definition at line 343 of file DatabaseManager.cpp.
References sqlResults.
std::ostream & cryomesh::manager::DatabaseManager::printHistory (std::ostream &os, unsigned intcountback = 1)
Print sql history to output stream. Parameters:
std::ostream Output stream to print to
unsigned int Muber of cycles of previous history to print
Returns:
std::ostream Return the supplied output stream
Definition at line 333 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::select (const std::string &table, const std::string &criteria = '')
Select all columns from table using criteria. Parameters:
std::string Name of table
std::string Selection criteria
Returns:
std::string sql query results
Definition at line 151 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::selectConnection (const std::string &uuid, const common::Cycle &cycle)
Select unique column entry. Parameters:
std::string The uuid of the node
Cycle The cycle to select on, to force uniqueness
Returns:
std::string The value of the entry
Definition at line 120 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::selectConnections (const std::string &criteria = '')
Select connections by a criteria string eg, 'id=erwrs324 AND cycle=1'. Parameters:
std::string The criteria to match
Returns:
std::string Result of sql query
Definition at line 148 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::selectConnectionValue (const std::string &uuid, const common::Cycle &cycle, const std::string &column)
Select unique column column entry. Parameters:
std::string The uuid of the node
Cycle The cycle to select on, to force uniqueness
std::string The column to select
Returns:
std::string The value of the entry
Definition at line 131 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::selectNode (const std::string &uuid, const common::Cycle &cycle)
Select unique node entry. Parameters:
std::string The uuid of the node
Cycle The cycle to select on, to force uniqueness
Returns:
std::string The value of the entry
Definition at line 114 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::selectNodes (const std::string &criteria = '')
Select nodes by a criteria string eg, 'id=erwrs324 AND cycle=1'. Parameters:
std::string The criteria to match
Returns:
std::string Result of sql query
Definition at line 145 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::selectNodeValue (const std::string &uuid, const common::Cycle &cycle, const std::string &column)
Select unique node column entry. Parameters:
std::string The uuid of the node
Cycle The cycle to select on, to force uniqueness
std::string The column to select
Returns:
std::string The value of the entry
Definition at line 127 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::selectValue (const std::string &table, const std::string &uuid, const common::Cycle &cycle, const std::string &column)
Select unique column column entry from table. Parameters:
std::string The table to utilise
std::string The uuid of the node
Cycle The cycle to select on, to force uniqueness
std::string The column to select
Returns:
std::string The value of the entry
Definition at line 135 of file DatabaseManager.cpp.
std::string cryomesh::manager::DatabaseManager::sqlCommand (const std::string &command) [protected]
Run a provided sql command string. Parameters:
std::string The command string to run
Returns:
std::vector<std::string> vector of results
Definition at line 264 of file DatabaseManager.cpp.
Referenced by sqlCommandBySelection(), and updateByUUID().
std::string cryomesh::manager::DatabaseManager::sqlCommandBySelection (const std::string &table, const std::string &command, const std::string &criteria) [protected]
Definition at line 217 of file DatabaseManager.cpp.
References sqlCommand().
std::string cryomesh::manager::DatabaseManager::updateByUUID (const std::string &uuid_str, const common::Cycle &cycle, const std::string &options, const std::string &table)
update object from a table using options list Parameters:
std::string The id to match
common::Cycle The cycle to match
std::string The options to set
std::string The table to use
Returns:
int The result of the count
Definition at line 210 of file DatabaseManager.cpp.
References sqlCommand(), and cryomesh::common::Cycle::toLInt().
Referenced by updateConnection(), and updateNode().
std::string cryomesh::manager::DatabaseManager::updateConnection (const std::string &uuid_str, const common::Cycle &cycle, const std::string &options)
update node from using options list Parameters:
std::string The id to match
common::Cycle The cycle to match
std::string The options to set
Returns:
int The result of the count
Definition at line 206 of file DatabaseManager.cpp.
References updateByUUID().
std::string cryomesh::manager::DatabaseManager::updateNode (const std::string &uuid_str, const common::Cycle &cycle, const std::string &options)
update node from using options list Parameters:
std::string The id to match
common::Cycle The cycle to match
std::string The options to set
Returns:
int The result of the count
Definition at line 202 of file DatabaseManager.cpp.
References updateByUUID().
Member Data Documentation
const ConnectionTableFormat cryomesh::manager::DatabaseManager::CONNECTIONS_TABLE_FORMAT [static]
Default connection table format.
Definition at line 471 of file DatabaseManager.h.
sqlite3* cryomesh::manager::DatabaseManager::database [protected]
Definition at line 480 of file DatabaseManager.h.
bool cryomesh::manager::DatabaseManager::databaseAccess [protected]
Database accessable.
Definition at line 501 of file DatabaseManager.h.
const std::string cryomesh::manager::DatabaseManager::DEFAULT_DATABASE = 'default.db' [static]
Definition at line 454 of file DatabaseManager.h.
int cryomesh::manager::DatabaseManager::errorCode [protected]
Definition at line 487 of file DatabaseManager.h.
char* cryomesh::manager::DatabaseManager::errorMessage [protected]
Definition at line 494 of file DatabaseManager.h.
const common::Cycle cryomesh::manager::DatabaseManager::MAX_COMMAND_HISTORY = common::Cycle(100) [static, protected]
Definition at line 522 of file DatabaseManager.h.
Referenced by addHistoryEntry().
const NodeTableFormat cryomesh::manager::DatabaseManager::NODES_TABLE_FORMAT [static]
Definition at line 466 of file DatabaseManager.h.
std::multimap<common::Cycle, std::pair<std::string, std::string> > cryomesh::manager::DatabaseManager::sqlResults [protected]
Definition at line 508 of file DatabaseManager.h.
Referenced by printHistory().
std::vector<std::string> cryomesh::manager::DatabaseManager::sqlResultsBuffer [protected]
Definition at line 515 of file DatabaseManager.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.