cryomesh::structures::NodeMesh
NAME
cryomesh::structures::NodeMesh -
Mesh of nodes and their neighbouring nodes and distances.
SYNOPSIS
#include <NodeMesh.h>
Classes
struct NeighbourhoodRanges
Struct to capture some statistics data on a nodes neighbourhood.
Public Types
enum InterpolationStyle { INVERSE_R, INVERSE_R2 }
Stype to use when interpolating values.
Public Member Functions
NodeMesh (Cluster &clus)
Constructor to create a node mesh from a cluster.
NodeMesh (Cluster &clus, double max_radius)
Constructor to create a node mesh from at minimum, a cluster and an optional maximum neighbour radius.
virtual ~NodeMesh ()
Default destructor.
void update ()
Per cycle update calls.
void warpNodes ()
Merge the interpolated activities with the actual node activities.
void regenerateNeighbourhoods ()
Regenerate the neighbourhood nodes and distances.
void regenerateActivities ()
Recalculate the applied interpolated activity at all nodes from their neighbours.
NeighbourhoodRanges getNeighbourRanges () const
Return a pair of pairs.
const NeighbourhoodMap & getNodeNeighbourhoodMap () const
Get the neighbourhood map.
const std::map
< boost::shared_ptr
< components::Node >, double > & getNeighbourhoodActivities () const "
Get the neighbourhood activities.
std::ostream & printNeighbourhoods (std::ostream &os) const
Print the neighbourhood map.
std::ostream & printNeighbourhoodActivities (std::ostream &os) const
Print the neighbourhood activities.
Protected Member Functions
double getInterpolatedActivity (const std::map< boost::shared_ptr< cryomesh::components::Node >, double > &all_neighbours, const InterpolationStyle style=INVERSE_R) const
Use a list of neighbours and their distances to generated an interpolated activity value at the central node.
double getDecayRate () const
Get the spacial decay rate for activities.
Static Protected Attributes
static const double MAX_RADIUS_FRACTION_OF_BOUNDING_BOX = (1.0 / 100.0)
static const double INTERPOLATED_ACTIVITY_SCALING_FACTOR = (1.0 / 100.0)
Private Attributes
NeighbourhoodMap nodeNeighbourhoodMap
std::map< boost::shared_ptr
< components::Node >, double > neighbourhoodActivities"
Cluster & cluster
double maximumNeighbourhoodRadius
const double decayRate
Friends
std::ostream & operator<< (std::ostream &os, const NodeMesh &obj)
To stream operator.
Detailed Description
Mesh of nodes and their neighbouring nodes and distances.
Definition at line 34 of file NodeMesh.h.
Member Enumeration Documentation
enum cryomesh::structures::NodeMesh::InterpolationStyle
Stype to use when interpolating values.
Enumerator:
INVERSE_R
INVERSE_R2
Definition at line 50 of file NodeMesh.h.
Constructor & Destructor Documentation
cryomesh::structures::NodeMesh::NodeMesh (Cluster &clus)
Constructor to create a node mesh from a cluster. Parameters:
Cluster The cluster associated with this node mesh
Definition at line 22 of file NodeMesh.cpp.
References cluster, cryomesh::structures::Cluster::getNodes(), maximumNeighbourhoodRadius, and regenerateNeighbourhoods().
cryomesh::structures::NodeMesh::NodeMesh (Cluster &clus, doublemax_radius)
Constructor to create a node mesh from at minimum, a cluster and an optional maximum neighbour radius. Parameters:
Cluster The cluster associated with this node mesh
double Maximum radius cutoff point for neighbourhood distance
Definition at line 43 of file NodeMesh.cpp.
References regenerateNeighbourhoods().
cryomesh::structures::NodeMesh::~NodeMesh () [virtual]
Default destructor.
Definition at line 48 of file NodeMesh.cpp.
Member Function Documentation
double cryomesh::structures::NodeMesh::getDecayRate () const [protected]
Get the spacial decay rate for activities. Returns:
double The spacial decay rate
Definition at line 216 of file NodeMesh.cpp.
References decayRate.
Referenced by getInterpolatedActivity().
double cryomesh::structures::NodeMesh::getInterpolatedActivity (const std::map< boost::shared_ptr< cryomesh::components::Node >, double > &all_neighbours, const InterpolationStylestyle = INVERSE_R) const [protected]
Use a list of neighbours and their distances to generated an interpolated activity value at the central node. Parameters:
std::map<boost::shared_ptr<cryomesh::components::Node>,double> List of all the neighbour nodes and their distances to their central node
InterpolationStyle Which method to use to interpolate the central activity
Returns:
double The interpolated activity
Definition at line 164 of file NodeMesh.cpp.
References getDecayRate().
Referenced by regenerateActivities().
const std::map< boost::shared_ptr< components::Node >, double > & cryomesh::structures::NodeMesh::getNeighbourhoodActivities () const
Get the neighbourhood activities. Returns:
std::map<boost::shared_ptr<components::Node>, double> The neighbourhood activities
Definition at line 261 of file NodeMesh.cpp.
References neighbourhoodActivities.
NodeMesh::NeighbourhoodRanges cryomesh::structures::NodeMesh::getNeighbourRanges () const
Return a pair of pairs. the first representing the min/max of neighbour counts, the second the min/max of distances
Returns:
NeighbourhoodRanges min/max of neighbour counts and min/max of distances
Definition at line 220 of file NodeMesh.cpp.
References cryomesh::structures::NodeMesh::NeighbourhoodRanges::maximumNeighbourCount, cryomesh::structures::NodeMesh::NeighbourhoodRanges::maximumNeighbourDistance, cryomesh::structures::NodeMesh::NeighbourhoodRanges::minimumNeighbourCount, cryomesh::structures::NodeMesh::NeighbourhoodRanges::minimumNeighbourDistance, and nodeNeighbourhoodMap.
const NeighbourhoodMap & cryomesh::structures::NodeMesh::getNodeNeighbourhoodMap () const
Get the neighbourhood map. Returns:
NeighbourhoodMap The neighbourhood map
Definition at line 258 of file NodeMesh.cpp.
References nodeNeighbourhoodMap.
std::ostream & cryomesh::structures::NodeMesh::printNeighbourhoodActivities (std::ostream &os) const
Print the neighbourhood activities. Parameters:
std::ostream The output stream
Returns:
std::ostream The output stream
Definition at line 287 of file NodeMesh.cpp.
References neighbourhoodActivities.
Referenced by cryomesh::structures::operator<<(), regenerateNeighbourhoods(), and update().
std::ostream & cryomesh::structures::NodeMesh::printNeighbourhoods (std::ostream &os) const
Print the neighbourhood map. Parameters:
std::ostream The output stream
Returns:
std::ostream The output stream
Definition at line 265 of file NodeMesh.cpp.
References nodeNeighbourhoodMap.
Referenced by cryomesh::structures::operator<<(), regenerateNeighbourhoods(), and update().
void cryomesh::structures::NodeMesh::regenerateActivities ()
Recalculate the applied interpolated activity at all nodes from their neighbours.
Definition at line 146 of file NodeMesh.cpp.
References getInterpolatedActivity(), neighbourhoodActivities, and nodeNeighbourhoodMap.
Referenced by update().
void cryomesh::structures::NodeMesh::regenerateNeighbourhoods ()
Regenerate the neighbourhood nodes and distances.
Definition at line 99 of file NodeMesh.cpp.
References cluster, cryomesh::structures::Cluster::getNodes(), maximumNeighbourhoodRadius, neighbourhoodActivities, nodeNeighbourhoodMap, printNeighbourhoodActivities(), and printNeighbourhoods().
Referenced by NodeMesh().
void cryomesh::structures::NodeMesh::update ()
Per cycle update calls.
Definition at line 51 of file NodeMesh.cpp.
References printNeighbourhoodActivities(), printNeighbourhoods(), and regenerateActivities().
void cryomesh::structures::NodeMesh::warpNodes ()
Merge the interpolated activities with the actual node activities.
Definition at line 65 of file NodeMesh.cpp.
References cluster, cryomesh::structures::Cluster::getEnergy(), and neighbourhoodActivities.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const NodeMesh &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const NodeMesh & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 306 of file NodeMesh.cpp.
Member Data Documentation
Cluster& cryomesh::structures::NodeMesh::cluster [private]
Definition at line 219 of file NodeMesh.h.
Referenced by NodeMesh(), regenerateNeighbourhoods(), and warpNodes().
const double cryomesh::structures::NodeMesh::decayRate [private]
Definition at line 233 of file NodeMesh.h.
Referenced by getDecayRate().
const double cryomesh::structures::NodeMesh::INTERPOLATED_ACTIVITY_SCALING_FACTOR = (1.0 / 100.0) [static, protected]
Definition at line 196 of file NodeMesh.h.
const double cryomesh::structures::NodeMesh::MAX_RADIUS_FRACTION_OF_BOUNDING_BOX = (1.0 / 100.0) [static, protected]
Definition at line 189 of file NodeMesh.h.
double cryomesh::structures::NodeMesh::maximumNeighbourhoodRadius [private]
Definition at line 226 of file NodeMesh.h.
Referenced by NodeMesh(), and regenerateNeighbourhoods().
std::map<boost::shared_ptr<components::Node>, double> cryomesh::structures::NodeMesh::neighbourhoodActivities [private]
Definition at line 212 of file NodeMesh.h.
Referenced by getNeighbourhoodActivities(), printNeighbourhoodActivities(), regenerateActivities(), regenerateNeighbourhoods(), and warpNodes().
NeighbourhoodMap cryomesh::structures::NodeMesh::nodeNeighbourhoodMap [private]
Definition at line 205 of file NodeMesh.h.
Referenced by getNeighbourRanges(), getNodeNeighbourhoodMap(), printNeighbourhoods(), regenerateActivities(), and regenerateNeighbourhoods().
Author
Generated automatically by Doxygen for cryomesh from the source code.