.TH "cryomesh::manager" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::manager \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectionDatabaseObject\fP"
.br
.ti -1c
.RI "class \fBCreator\fP"
.br
.RI "\fIClass to take in a config file of ConfigTranslator form and parse the commands to create a full cryomesh object. \fP"
.ti -1c
.RI "class \fBCryoManager\fP"
.br
.RI "\fIControl manager for cryomesh's. \fP"
.ti -1c
.RI "class \fBDatabaseManager\fP"
.br
.RI "\fIDatabase manager creates and maintains a database of mesh related objects and data. \fP"
.ti -1c
.RI "class \fBDatabaseObject\fP"
.br
.ti -1c
.RI "class \fBNodeDatabaseObject\fP"
.br
.ti -1c
.RI "struct \fBTableFormat\fP"
.br
.RI "\fIGeneral structure of a table. \fP"
.ti -1c
.RI "struct \fBNodeTableFormat\fP"
.br
.RI "\fIStruct representing a node table structure. \fP"
.ti -1c
.RI "struct \fBConnectionTableFormat\fP"
.br
.RI "\fIStruct representing a connections table structure. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
