cryomesh::structures::Cluster
NAME
cryomesh::structures::Cluster -
A Cluster is a collection of self-contained nodes and connections along with an associated Mesh, that can be connected up to one another.
SYNOPSIS
#include <Cluster.h>
Public Types
enum EnergyFractionMethod { ENERGY_FRACTION_BY_CLUSTER_COUNT, ENERGY_FRACTION_BY_NODE_COUNT, ENERGY_FRACTION_NULL }
enum ValueTypeSpecifier { AsIncrement, AsDecrement, AsMinumum, AsAbsolute }
Enum to force value type of a parameter.
Public Member Functions
Cluster ()
Default constructor.
Cluster (int nodeCount, int connectivity)
Constructor with number of nodes and connectivity.
Cluster (int nodeCount, int connectivity, const spacial::Point bounding_box)
virtual ~Cluster ()
Destructor.
void update ()
Update all elements.
void updateEnergy (double total_energy)
void setEnergyFractionMethod (EnergyFractionMethod method, double max_energy_fraction)
EnergyFractionMethod getEnergyFractionMethod () const
void warpNodes ()
void runAnalyser ()
virtual void createConnectivity (const int connectivity=1)
Create connections between all nodes.
const std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Node > > & getNodes () const "
Get all nodes.
const std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Connection > > & getConnections () const "
Get all connections.
const common::Connector
< Cluster, Fibre > & getConnector () const "
Get the connector for this Cluster.
common::Connector< Cluster,
Fibre > & getMutableConnector ()"
Get the mutable connector for this Cluster.
const components::NodeMap & getNodeMap () const
Get the NodeMap for this Cluster.
const components::ConnectionMap & getConnectionMap () const
components::NodeMap & getMutableNodeMap ()
Get the mutable NodeMap for this Cluster.
components::ConnectionMap & getMutableConnectionMap ()
int getTriggeredNodeCount (const int indicator=0) const
Get the total fired nodes in this cluster currently.
int getActiveNodeCount (const int indicator=0) const
Get the total active nodes in this cluster currently.
int getLiveNodeCount () const
Get the total live nodes in this cluster currently, ie those with at least one impulse.
double getEnergy () const
void setEnergy (double d)
double getMaxEnergyFraction () const
const boost::shared_ptr
< manipulators::ClusterArchitect > getClusterArchitect () const "
boost::shared_ptr
< manipulators::ClusterArchitect > getMutableClusterArchitect ()"
const boost::shared_ptr< NodeMesh > getMesh () const
boost::shared_ptr< NodeMesh > getMutableMesh ()
virtual void enableDebug (bool b)
Static Public Attributes
static const double SELF_CONNECTED_NODES_FRACTION = 0.1
Protected Member Functions
virtual void updateConnectivity (const int connectivity, ValueTypeSpecifier asValue=AsIncrement)
Update connectivity so that each node has at least param number of connections.
Private Attributes
double energy
components::NodeMap nodes
components::ConnectionMap connections
boost::shared_ptr< NodeMesh > mesh
common::Connector< Cluster, Fibre > connector
boost::shared_ptr
< manipulators::ClusterArchitect > clusterArchitect"
EnergyFractionMethod energyFractionMethod
double maxEnergyFraction
Friends
std::ostream & operator<< (std::ostream &os, const Cluster &obj)
To stream operator.
Detailed Description
A Cluster is a collection of self-contained nodes and connections along with an associated Mesh, that can be connected up to one another.
Definition at line 41 of file Cluster.h.
Member Enumeration Documentation
enum cryomesh::structures::Cluster::EnergyFractionMethod
Enumerator:
ENERGY_FRACTION_BY_CLUSTER_COUNT
ENERGY_FRACTION_BY_NODE_COUNT
ENERGY_FRACTION_NULL
Definition at line 45 of file Cluster.h.
enum cryomesh::structures::Cluster::ValueTypeSpecifier
Enum to force value type of a parameter.
Enumerator:
AsIncrement
AsDecrement
AsMinumum
AsAbsolute
Definition at line 53 of file Cluster.h.
Constructor & Destructor Documentation
cryomesh::structures::Cluster::Cluster ()
Default constructor.
Definition at line 22 of file Cluster.cpp.
cryomesh::structures::Cluster::Cluster (intnodeCount, intconnectivity)
Constructor with number of nodes and connectivity. Parameters:
int nodeCount Number of nodes to make
int connectivity Connectivity to start with
Definition at line 35 of file Cluster.cpp.
References clusterArchitect.
cryomesh::structures::Cluster::Cluster (intnodeCount, intconnectivity, const spacial::Pointbounding_box)
Definition at line 28 of file Cluster.cpp.
References clusterArchitect.
cryomesh::structures::Cluster::~Cluster () [virtual]
Destructor.
Definition at line 42 of file Cluster.cpp.
Member Function Documentation
void cryomesh::structures::Cluster::createConnectivity (const intconnectivity = 1) [virtual]
Create connections between all nodes. Parameters:
int connectivity The number of connections between each node
Definition at line 89 of file Cluster.cpp.
References AsIncrement, and updateConnectivity().
void cryomesh::structures::Cluster::enableDebug (boolb) [virtual]
Definition at line 306 of file Cluster.cpp.
References connections, and nodes.
int cryomesh::structures::Cluster::getActiveNodeCount (const intindicator = 0) const
Get the total active nodes in this cluster currently. Parameters:
int Set >0 for only positive active nodes, <0 for negative, 0 for all (default)
Returns:
int The total count of currently active nodes
Definition at line 263 of file Cluster.cpp.
References getNodes().
const boost::shared_ptr< manipulators::ClusterArchitect > cryomesh::structures::Cluster::getClusterArchitect () const
Definition at line 72 of file Cluster.cpp.
References clusterArchitect.
const components::ConnectionMap & cryomesh::structures::Cluster::getConnectionMap () const
Definition at line 222 of file Cluster.cpp.
References connections.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), and cryomesh::manipulators::ClusterArchitect::getRandomConnections().
const std::map< boost::uuids::uuid, boost::shared_ptr< components::Connection > > & cryomesh::structures::Cluster::getConnections () const
Get all connections. Returns:
std::map<boost::uuids::uuid, boost::shared_ptr< components::Connection > > Return all Connections
Definition at line 204 of file Cluster.cpp.
References connections.
Referenced by cryomesh::structures::operator<<().
const common::Connector< Cluster, Fibre > & cryomesh::structures::Cluster::getConnector () const
Get the connector for this Cluster. Returns:
common::Connector<Cluster, Fibre> The connector for this Cluster
Definition at line 208 of file Cluster.cpp.
References connector.
double cryomesh::structures::Cluster::getEnergy () const
Definition at line 54 of file Cluster.cpp.
References energy.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), and cryomesh::structures::NodeMesh::warpNodes().
Cluster::EnergyFractionMethod cryomesh::structures::Cluster::getEnergyFractionMethod () const
Definition at line 68 of file Cluster.cpp.
References energyFractionMethod.
int cryomesh::structures::Cluster::getLiveNodeCount () const
Get the total live nodes in this cluster currently, ie those with at least one impulse. Returns:
int The total count of currently live nodes
Definition at line 312 of file Cluster.cpp.
References getNodes().
double cryomesh::structures::Cluster::getMaxEnergyFraction () const
Definition at line 60 of file Cluster.cpp.
References maxEnergyFraction.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster().
const boost::shared_ptr<NodeMesh> cryomesh::structures::Cluster::getMesh () const [inline]
Definition at line 184 of file Cluster.h.
References mesh.
boost::shared_ptr< manipulators::ClusterArchitect > cryomesh::structures::Cluster::getMutableClusterArchitect ()
Definition at line 76 of file Cluster.cpp.
References clusterArchitect.
components::ConnectionMap & cryomesh::structures::Cluster::getMutableConnectionMap ()
Definition at line 225 of file Cluster.cpp.
References connections.
Referenced by cryomesh::manipulators::ClusterArchitect::createConnection(), cryomesh::manipulators::ClusterArchitect::createRandomConnections(), cryomesh::manipulators::ClusterArchitect::deleteConnection(), cryomesh::manipulators::ClusterArchitect::destroyRandomConnections(), cryomesh::manipulators::ClusterArchitect::destroyRandomNodes(), and cryomesh::manipulators::ClusterArchitect::getRandomConnections().
common::Connector< Cluster, Fibre > & cryomesh::structures::Cluster::getMutableConnector ()
Get the mutable connector for this Cluster. Returns:
common::Connector<Cluster, Fibre> The mutable onnector for this Cluster
Definition at line 212 of file Cluster.cpp.
References connector.
boost::shared_ptr<NodeMesh> cryomesh::structures::Cluster::getMutableMesh () [inline]
Definition at line 187 of file Cluster.h.
References mesh.
components::NodeMap & cryomesh::structures::Cluster::getMutableNodeMap ()
Get the mutable NodeMap for this Cluster. Returns:
components::NodeMap The mutable NodeMap for this Cluster
Definition at line 219 of file Cluster.cpp.
References nodes.
Referenced by cryomesh::manipulators::ClusterArchitect::createRandomConnections(), cryomesh::manipulators::ClusterArchitect::createRandomNodes(), cryomesh::manipulators::ClusterArchitect::destroyRandomNodes(), and cryomesh::manipulators::ClusterArchitect::getRandomNodes().
const components::NodeMap & cryomesh::structures::Cluster::getNodeMap () const
Get the NodeMap for this Cluster. Returns:
components::NodeMap The NodeMap for this Cluster
Definition at line 216 of file Cluster.cpp.
References nodes.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), cryomesh::manipulators::ClusterArchitect::createRandomNodes(), cryomesh::manipulators::ClusterArchitect::getRandomNodes(), and cryomesh::structures::operator<<().
const std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > & cryomesh::structures::Cluster::getNodes () const
Get all nodes. Returns:
std::map<boost::uuids::uuid, boost::shared_ptr< components::Node > > Return all nodes
Definition at line 200 of file Cluster.cpp.
References nodes.
Referenced by getActiveNodeCount(), getLiveNodeCount(), getTriggeredNodeCount(), cryomesh::structures::NodeMesh::NodeMesh(), cryomesh::structures::operator<<(), cryomesh::structures::NodeMesh::regenerateNeighbourhoods(), and cryomesh::structures::Mesh::update().
int cryomesh::structures::Cluster::getTriggeredNodeCount (const intindicator = 0) const
Get the total fired nodes in this cluster currently. Parameters:
int Set >0 for only positive triggered nodes, <0 for negative, 0 for all (default)
Returns:
int The total count of currently triggered nodes
Definition at line 228 of file Cluster.cpp.
References getNodes(), cryomesh::components::Node::Negative, cryomesh::components::Node::None, and cryomesh::components::Node::Positive.
void cryomesh::structures::Cluster::runAnalyser ()
Definition at line 85 of file Cluster.cpp.
References clusterArchitect.
void cryomesh::structures::Cluster::setEnergy (doubled)
Definition at line 57 of file Cluster.cpp.
References energy.
void cryomesh::structures::Cluster::setEnergyFractionMethod (EnergyFractionMethodmethod, doublemax_energy_fraction)
Definition at line 63 of file Cluster.cpp.
References energyFractionMethod, and maxEnergyFraction.
void cryomesh::structures::Cluster::update ()
Update all elements.
Definition at line 45 of file Cluster.cpp.
References connections, mesh, nodes, cryomesh::components::NodeMap::update(), and cryomesh::components::ConnectionMap::update().
void cryomesh::structures::Cluster::updateConnectivity (const intconnectivity, ValueTypeSpecifierasValue = AsIncrement) [protected, virtual]
Update connectivity so that each node has at least param number of connections. Parameters:
int connectivity The least connectivity to ensure
Definition at line 93 of file Cluster.cpp.
References AsIncrement, AsMinumum, clusterArchitect, nodes, and SELF_CONNECTED_NODES_FRACTION.
Referenced by createConnectivity().
void cryomesh::structures::Cluster::updateEnergy (doubletotal_energy)
void cryomesh::structures::Cluster::warpNodes ()
Definition at line 80 of file Cluster.cpp.
References mesh.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Cluster &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Cluster & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 331 of file Cluster.cpp.
Member Data Documentation
boost::shared_ptr<manipulators::ClusterArchitect> cryomesh::structures::Cluster::clusterArchitect [private]
Definition at line 247 of file Cluster.h.
Referenced by Cluster(), getClusterArchitect(), getMutableClusterArchitect(), runAnalyser(), and updateConnectivity().
components::ConnectionMap cryomesh::structures::Cluster::connections [private]
Definition at line 231 of file Cluster.h.
Referenced by enableDebug(), getConnectionMap(), getConnections(), getMutableConnectionMap(), and update().
common::Connector<Cluster, Fibre> cryomesh::structures::Cluster::connector [private]
Definition at line 245 of file Cluster.h.
Referenced by getConnector(), and getMutableConnector().
double cryomesh::structures::Cluster::energy [private]
Definition at line 217 of file Cluster.h.
Referenced by getEnergy(), and setEnergy().
EnergyFractionMethod cryomesh::structures::Cluster::energyFractionMethod [private]
Definition at line 248 of file Cluster.h.
Referenced by getEnergyFractionMethod(), and setEnergyFractionMethod().
double cryomesh::structures::Cluster::maxEnergyFraction [private]
Definition at line 249 of file Cluster.h.
Referenced by getMaxEnergyFraction(), and setEnergyFractionMethod().
boost::shared_ptr<NodeMesh> cryomesh::structures::Cluster::mesh [private]
Definition at line 238 of file Cluster.h.
Referenced by getMesh(), getMutableMesh(), update(), and warpNodes().
components::NodeMap cryomesh::structures::Cluster::nodes [private]
Definition at line 224 of file Cluster.h.
Referenced by enableDebug(), getMutableNodeMap(), getNodeMap(), getNodes(), update(), and updateConnectivity().
const double cryomesh::structures::Cluster::SELF_CONNECTED_NODES_FRACTION = 0.1 [static]
Definition at line 204 of file Cluster.h.
Referenced by updateConnectivity().
Author
Generated automatically by Doxygen for cryomesh from the source code.