cryomesh::state::PatternTagById
NAME
cryomesh::state::PatternTagById -
SYNOPSIS
#include <PatternTagById.h>
Inherits cryomesh::state::PatternTag.
Public Member Functions
PatternTagById (int d)
virtual ~PatternTagById ()
virtual std::string getTag () const
virtual void setTag (std::string tg)
virtual std::string moveTag ()
virtual std::string moveTag (int i)
virtual std::string getStartTag () const
virtual std::string getEndTag () const
virtual void setStartTag (std::string tg)
virtual void setEndTag (std::string tg)
virtual boost::shared_ptr
< PatternTag > getGlobalTag ()"
Private Attributes
std::string id
Static Private Attributes
static boost::shared_ptr
< PatternTagById > globalTag = boost::shared_ptr<PatternTagById>(new PatternTagById(1))"
Detailed Description
Definition at line 14 of file PatternTagById.h.
Constructor & Destructor Documentation
cryomesh::state::PatternTagById::PatternTagById (intd)
Definition at line 15 of file PatternTagById.cpp.
cryomesh::state::PatternTagById::~PatternTagById () [virtual]
Definition at line 21 of file PatternTagById.cpp.
Member Function Documentation
std::string cryomesh::state::PatternTagById::getEndTag () const [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 43 of file PatternTagById.cpp.
References cryomesh::state::Pattern::getIds().
Referenced by setEndTag().
boost::shared_ptr< PatternTag > cryomesh::state::PatternTagById::getGlobalTag () [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 56 of file PatternTagById.cpp.
References globalTag.
std::string cryomesh::state::PatternTagById::getStartTag () const [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 40 of file PatternTagById.cpp.
Referenced by setStartTag().
std::string cryomesh::state::PatternTagById::getTag () const [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 23 of file PatternTagById.cpp.
References id.
Referenced by moveTag().
std::string cryomesh::state::PatternTagById::moveTag () [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 29 of file PatternTagById.cpp.
std::string cryomesh::state::PatternTagById::moveTag (inti) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 32 of file PatternTagById.cpp.
References getTag().
void cryomesh::state::PatternTagById::setEndTag (std::stringtg) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 53 of file PatternTagById.cpp.
References getEndTag().
void cryomesh::state::PatternTagById::setStartTag (std::stringtg) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 50 of file PatternTagById.cpp.
References getStartTag().
void cryomesh::state::PatternTagById::setTag (std::stringtg) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 26 of file PatternTagById.cpp.
Member Data Documentation
boost::shared_ptr< PatternTagById > cryomesh::state::PatternTagById::globalTag = boost::shared_ptr<PatternTagById>(new PatternTagById(1)) [static, private]
Definition at line 29 of file PatternTagById.h.
Referenced by getGlobalTag().
std::string cryomesh::state::PatternTagById::id [private]
Definition at line 30 of file PatternTagById.h.
Referenced by getTag().
Author
Generated automatically by Doxygen for cryomesh from the source code.