cryomesh::structures::FibreMap
NAME
cryomesh::structures::FibreMap -
SYNOPSIS
#include <FibreMap.h>
Public Member Functions
FibreMap ()
virtual ~FibreMap ()
virtual void update ()
Friends
std::ostream & operator<< (std::ostream &os, const FibreMap &objs)
Detailed Description
Definition at line 18 of file FibreMap.h.
Constructor & Destructor Documentation
cryomesh::structures::FibreMap::FibreMap () [inline]
Definition at line 20 of file FibreMap.h.
virtual cryomesh::structures::FibreMap::~FibreMap () [inline, virtual]
Definition at line 22 of file FibreMap.h.
Member Function Documentation
virtual void cryomesh::structures::FibreMap::update () [inline, virtual]
Definition at line 24 of file FibreMap.h.
Referenced by cryomesh::structures::Bundle::update(), cryomesh::structures::Bundle::updatePrimaryInputFibres(), and cryomesh::structures::Bundle::updatePrimaryOutputFibres().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const FibreMap &objs) [friend]
Definition at line 40 of file FibreMap.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.