.TH "cryomesh::structures::NodeMesh::NeighbourhoodRanges" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::structures::NodeMesh::NeighbourhoodRanges \- 
.PP
Struct to capture some statistics data on a nodes neighbourhood.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NodeMesh.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBminimumNeighbourCount\fP"
.br
.ti -1c
.RI "int \fBmaximumNeighbourCount\fP"
.br
.ti -1c
.RI "double \fBminimumNeighbourDistance\fP"
.br
.ti -1c
.RI "double \fBmaximumNeighbourDistance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct to capture some statistics data on a nodes neighbourhood. 
.PP
Definition at line 40 of file NodeMesh.h.
.SH "Member Data Documentation"
.PP 
.SS "int \fBcryomesh::structures::NodeMesh::NeighbourhoodRanges::maximumNeighbourCount\fP"
.PP
Definition at line 42 of file NodeMesh.h.
.SS "double \fBcryomesh::structures::NodeMesh::NeighbourhoodRanges::maximumNeighbourDistance\fP"
.PP
Definition at line 44 of file NodeMesh.h.
.SS "int \fBcryomesh::structures::NodeMesh::NeighbourhoodRanges::minimumNeighbourCount\fP"
.PP
Definition at line 41 of file NodeMesh.h.
.SS "double \fBcryomesh::structures::NodeMesh::NeighbourhoodRanges::minimumNeighbourDistance\fP"
.PP
Definition at line 43 of file NodeMesh.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
