cryomesh::structures::Bundle
NAME
cryomesh::structures::Bundle -
A Bundle is the collection of clusters and fibres, it represents the system as a whole.
SYNOPSIS
#include <Bundle.h>
Inherits cryomesh::common::Loggable.
Public Types
enum LoggingDepth { SUMMARY, MAX }
Enum representing print detail.
Public Member Functions
Bundle ()
Default contructor.
virtual ~Bundle ()
Default destructor.
void update ()
Update all bundle components.
virtual boost::shared_ptr
< Cluster > createCluster (int nodeSize, int nodeConnectivity)"
Create a cluster with a size and connectivity.
virtual boost::shared_ptr< Fibre > connectCluster (boost::uuids::uuid inputClusterUUID, boost::uuids::uuid outputClusterUUID, int fibreWidth)
Connect clusters specified by uuids with a fibre of width.
virtual boost::shared_ptr< Fibre > connectCluster (boost::uuids::uuid clusterUUID, const Fibre::FibreType &type, int fibreWidth)
Connect clusters specified by uuids with a fibre of width.
virtual boost::shared_ptr< Fibre > connectPrimaryInputCluster (boost::uuids::uuid patchanid, boost::uuids::uuid clusterUUID)
Helper access function for specialised connection.
virtual boost::shared_ptr< Fibre > connectPrimaryOutputCluster (boost::uuids::uuid patchanid, boost::uuids::uuid clusterUUID)
Helper access function for specialised connection.
std::vector< boost::shared_ptr
< Fibre > > autoConnectPrimaryInputClusters (const std::vector< boost::uuids::uuid > &cluster_uuids)"
std::vector< boost::shared_ptr
< Fibre > > autoConnectPrimaryOutputClusters (const std::vector< boost::uuids::uuid > &cluster_uuids)"
virtual std::vector
< boost::shared_ptr< Fibre > > autoConnectPrimaryInputClusters (std::vector< boost::shared_ptr< Cluster > > list)"
virtual std::vector
< boost::shared_ptr< Fibre > > autoConnectPrimaryOutputClusters (std::vector< boost::shared_ptr< Cluster > > list)"
virtual std::vector
< boost::shared_ptr
< state::PatternChannel > > getDisconnectedRealInputPatternChannels ()"
virtual std::vector
< boost::shared_ptr
< state::PatternChannel > > getDisconnectedRealOutputPatternChannels ()"
virtual boost::shared_ptr< Fibre > connectLoopbackCluster (boost::uuids::uuid clusterUUID, int fibreWidth)
Helper access function for specialised connection.
virtual void loadChannels (const std::string &ifstr)
Load in the pattern channels from a filename of a pattern dataset.
const ClusterMap & getClusters () const
Get the clusters in this bundle.
const FibreMap & getFibres () const
Get the mutable clusters in this bundle.
const FibreMap & getInputFibres () const
Get the input fibres of this bundle.
FibreMap & getMutableInputFibres ()
Get the mutable input fibres of this bundle.
const FibreMap & getOutputFibres () const
Get the output fibres of this bundle.
FibreMap & getMutableOutputFibres ()
Get the mutable output fibres of this bundle.
const state::PatternChannelMap & getRealInputChannelsMap () const
Get the real input pattern channels of this bundle.
const state::PatternChannelMap & getRealOutputChannelsMap () const
Get the real output pattern channels of this bundle.
const state::PatternChannelMap & getActualInputChannelsMap () const
Get the actual input pattern channels of this bundle.
const state::PatternChannelMap & getActualOutputChannelsMap () const
Get the real output pattern channels of this bundle.
const std::map
< boost::uuids::uuid,
boost::uuids::uuid > & getRealFibrePatternChannelMap () const "
Get the map of fibres to their associated pattern channels.
const std::map
< boost::uuids::uuid,
boost::uuids::uuid > & getActualFibrePatternChannelMap () const "
const boost::shared_ptr
< utilities::Statistician > getStatistician () const "
Get the Statistician.
boost::shared_ptr
< utilities::Statistician > getMutableStatistician ()"
double getEnergy () const
Get the last calculated energy of the bundle.
virtual bool checkStructure () const
Run a system structure check.
virtual bool checkFibreStructure () const
Check the structure of Fibres.
virtual bool checkChannelStructure () const
Check the structure of Channels.
virtual void enableDebug (bool b)
virtual void enableDebugClusters (bool b)
virtual void enableDebugFibres (bool b)
virtual std::ostream & print (std::ostream &os, const common::Loggable::LoggingDepth depth=SUMMARY) const
Print the bundle to stream.
std::ostream & printChannels (std::ostream &os) const
Print the channels to stream.
std::ostream & printFibreMaps (std::ostream &os) const
std::ostream & printFibreMap (std::ostream &os, const std::map< boost::uuids::uuid, boost::uuids::uuid > &fibre_map) const
Protected Member Functions
virtual void updatePrimaryInputFibres ()
Get the next patterns from channels and apply them to their mapped fibres.
virtual void updatePrimaryOutputFibres ()
Get the patterns from primary output fibres and apply them to their mapped pattern channels.
virtual double matchOutputChannelsSum () const
Compare the output channels of primary output fibres to expected output channel patterns.
virtual void updateStatistician ()
Update the statistician if debugging is enabled.
void setEnergy (double d)
Set the energy of the bundle.
ClusterMap & getMutableClusters ()
template<class T > std::ostream & printSearch (std::ostream &os, const boost::uuids::uuid &uuid, const std::map< boost::uuids::uuid, boost::shared_ptr< T > > &map) const
Print out a uuid search.
Private Member Functions
const boost::shared_ptr
< state::PatternChannel > getRealPrimaryInputChannelByFibre (const boost::uuids::uuid fibre_uuid) const "
const boost::shared_ptr
< state::PatternChannel > getRealPrimaryOutputChannelByFibre (const boost::uuids::uuid fibre_uuid) const "
const boost::shared_ptr
< state::PatternChannel > getActualPrimaryInputChannelByFibre (const boost::uuids::uuid fibre_uuid) const "
const boost::shared_ptr
< state::PatternChannel > getActualPrimaryOutputChannelByFibre (const boost::uuids::uuid fibre_uuid) const "
const boost::shared_ptr< Fibre > getPrimaryInputFibreByRealChannel (const boost::uuids::uuid pattern_channel_uuid) const
Helper method to take a uuid and find its correspondingly mapped object Take an input PatternChannel uuid and find the input Fibre its mapped to.
const boost::shared_ptr< Fibre > getPrimaryOutputFibreByRealChannel (const boost::uuids::uuid pattern_channel_uuid) const
Helper method to take a uuid and find its correspondingly mapped object Take an output PatternChannel uuid and find the output Fibre its mapped to.
const boost::shared_ptr< Fibre > getPrimaryInputFibreByActualChannel (const boost::uuids::uuid pattern_channel_uuid) const
const boost::shared_ptr< Fibre > getPrimaryOutputFibreByActualChannel (const boost::uuids::uuid pattern_channel_uuid) const
const boost::shared_ptr< Fibre > getPrimaryFibreByChannel (const boost::uuids::uuid id, const FibreMap &map, const std::map< boost::uuids::uuid, boost::uuids::uuid > &fibrepattern_channelmap) const
Helper method to take a uuid and find its correspondingly mapped object Take an channel uuid and find the Fibre its mapped to inside the supplied map.
const boost::shared_ptr
< state::PatternChannel > getPrimaryChannelByFibre (const boost::uuids::uuid id, const state::PatternChannelMap &map, const std::map< boost::uuids::uuid, boost::uuids::uuid > &fibrepattern_channelmap) const "
Helper method to take a uuid and find its correspondingly mapped object Take an Fibre uuid and find the PatternChannel its mapped to inside the supplied map.
Private Attributes
ClusterMap clusters
FibreMap fibres
state::PatternChannelMap realInputChannelsMap
state::PatternChannelMap realOutputChannelsMap
state::PatternChannelMap actualInputChannelsMap
state::PatternChannelMap actualOutputChannelsMap
FibreMap inputFibres
FibreMap outputFibres
boost::shared_ptr
< utilities::Statistician > statistician"
Statistics object to generate useful info on the bundle.
double energy
Last energy calculation of the output channel matching.
std::map< boost::uuids::uuid,
boost::uuids::uuid > realFibrePatternChannelMap"
std::map< boost::uuids::uuid,
boost::uuids::uuid > actualFibrePatternChannelMap"
Cluster::EnergyFractionMethod energyFractionMethod
Friends
std::ostream & operator<< (std::ostream &os, const Bundle &obj)
To stream operator.
Detailed Description
A Bundle is the collection of clusters and fibres, it represents the system as a whole.
Definition at line 29 of file Bundle.h.
Member Enumeration Documentation
enum cryomesh::common::Loggable::LoggingDepth [inherited]
Enum representing print detail.
Enumerator:
SUMMARY
MAX
Definition at line 23 of file Loggable.h.
Constructor & Destructor Documentation
cryomesh::structures::Bundle::Bundle ()
Default contructor.
Definition at line 17 of file Bundle.cpp.
cryomesh::structures::Bundle::~Bundle () [virtual]
Default destructor.
Definition at line 23 of file Bundle.cpp.
Member Function Documentation
std::vector< boost::shared_ptr< Fibre > > cryomesh::structures::Bundle::autoConnectPrimaryInputClusters (const std::vector< boost::uuids::uuid > &cluster_uuids)
Definition at line 206 of file Bundle.cpp.
References getMutableClusters().
std::vector< boost::shared_ptr< Fibre > > cryomesh::structures::Bundle::autoConnectPrimaryInputClusters (std::vector< boost::shared_ptr< Cluster > >list) [virtual]
Definition at line 254 of file Bundle.cpp.
References connectPrimaryInputCluster(), and getDisconnectedRealInputPatternChannels().
std::vector< boost::shared_ptr< Fibre > > cryomesh::structures::Bundle::autoConnectPrimaryOutputClusters (const std::vector< boost::uuids::uuid > &cluster_uuids)
Definition at line 231 of file Bundle.cpp.
References getMutableClusters().
std::vector< boost::shared_ptr< Fibre > > cryomesh::structures::Bundle::autoConnectPrimaryOutputClusters (std::vector< boost::shared_ptr< Cluster > >list) [virtual]
Definition at line 301 of file Bundle.cpp.
References connectPrimaryOutputCluster(), and getDisconnectedRealOutputPatternChannels().
bool cryomesh::structures::Bundle::checkChannelStructure () const [virtual]
Check the structure of Channels. Returns:
bool True if structure tests pass, false otherwise
Definition at line 558 of file Bundle.cpp.
Referenced by checkStructure().
bool cryomesh::structures::Bundle::checkFibreStructure () const [virtual]
Check the structure of Fibres. Returns:
bool True if structure tests pass, false otherwise
Definition at line 477 of file Bundle.cpp.
References getClusters(), getFibres(), getInputFibres(), and getOutputFibres().
Referenced by checkStructure().
bool cryomesh::structures::Bundle::checkStructure () const [virtual]
Run a system structure check. Returns:
bool True if system passes all tests, false otherwise
Definition at line 561 of file Bundle.cpp.
References checkChannelStructure(), and checkFibreStructure().
boost::shared_ptr< Fibre > cryomesh::structures::Bundle::connectCluster (boost::uuids::uuidinputClusterUUID, boost::uuids::uuidoutputClusterUUID, intfibreWidth) [virtual]
Connect clusters specified by uuids with a fibre of width. Parameters:
boost::uuids::uuid inputClusterUUID UUID of input cluster
boost::uuids::uuid outputClusterUUID UUID of output cluster
int width Width of fibre to create
Returns:
The new fibre created, possible null
Definition at line 61 of file Bundle.cpp.
References clusters, and fibres.
Referenced by connectLoopbackCluster(), connectPrimaryInputCluster(), and connectPrimaryOutputCluster().
boost::shared_ptr< Fibre > cryomesh::structures::Bundle::connectCluster (boost::uuids::uuidclusterUUID, const Fibre::FibreType &type, intfibreWidth) [virtual]
Connect clusters specified by uuids with a fibre of width. Parameters:
boost::uuids::uuid clusterUUID UUID of cluster to connect to fibre
const Fibre::FibreType & type Type of fibre connection to make
int width Width of fibre to create
Returns:
The new fibre created, possible null
Definition at line 78 of file Bundle.cpp.
References clusters, fibres, inputFibres, cryomesh::structures::Fibre::LoopbackFibre, outputFibres, cryomesh::structures::Fibre::PrimaryInputFibre, and cryomesh::structures::Fibre::PrimaryOutputFibre.
boost::shared_ptr< Fibre > cryomesh::structures::Bundle::connectLoopbackCluster (boost::uuids::uuidclusterUUID, intfibreWidth) [virtual]
Helper access function for specialised connection. Parameters:
const Fibre::FibreType & type Type of fibre connection to make
int width Width of fibre to create
Returns:
The new fibre created, possible null
Definition at line 392 of file Bundle.cpp.
References connectCluster(), and cryomesh::structures::Fibre::LoopbackFibre.
boost::shared_ptr< Fibre > cryomesh::structures::Bundle::connectPrimaryInputCluster (boost::uuids::uuidpatchanid, boost::uuids::uuidclusterUUID) [virtual]
Helper access function for specialised connection. Parameters:
boost::uuids::uuid PatternChannel to map the fibre to
const Fibre::FibreType & type Type of fibre connection to make
Returns:
The new fibre created, possible null
Definition at line 110 of file Bundle.cpp.
References actualFibrePatternChannelMap, actualInputChannelsMap, connectCluster(), cryomesh::state::PatternChannel::Input, cryomesh::structures::Fibre::PrimaryInputFibre, realFibrePatternChannelMap, and realInputChannelsMap.
Referenced by autoConnectPrimaryInputClusters().
boost::shared_ptr< Fibre > cryomesh::structures::Bundle::connectPrimaryOutputCluster (boost::uuids::uuidpatchanid, boost::uuids::uuidclusterUUID) [virtual]
Helper access function for specialised connection. Parameters:
boost::uuids::uuid PatternChannel to map the fibre to
const Fibre::FibreType & type Type of fibre connection to make
Returns:
The new fibre created, possible null
Definition at line 157 of file Bundle.cpp.
References actualFibrePatternChannelMap, actualOutputChannelsMap, connectCluster(), cryomesh::state::PatternChannel::Output, cryomesh::structures::Fibre::PrimaryOutputFibre, realFibrePatternChannelMap, and realOutputChannelsMap.
Referenced by autoConnectPrimaryOutputClusters().
boost::shared_ptr< Cluster > cryomesh::structures::Bundle::createCluster (intnodeSize, intnodeConnectivity) [virtual]
Create a cluster with a size and connectivity. Parameters:
int The number of nodes to create
int The connectivity of the nodes
Returns:
boost::shared_ptr<Cluster> The cluster that was created
Definition at line 54 of file Bundle.cpp.
References clusters, and energyFractionMethod.
void cryomesh::structures::Bundle::enableDebug (boolb) [virtual]
Definition at line 412 of file Bundle.cpp.
References enableDebugClusters(), and enableDebugFibres().
void cryomesh::structures::Bundle::enableDebugClusters (boolb) [virtual]
Definition at line 417 of file Bundle.cpp.
References clusters.
Referenced by enableDebug().
void cryomesh::structures::Bundle::enableDebugFibres (boolb) [virtual]
Definition at line 420 of file Bundle.cpp.
References fibres.
Referenced by enableDebug().
const std::map< boost::uuids::uuid, boost::uuids::uuid > & cryomesh::structures::Bundle::getActualFibrePatternChannelMap () const
Definition at line 463 of file Bundle.cpp.
References actualFibrePatternChannelMap.
Referenced by printFibreMaps().
const state::PatternChannelMap & cryomesh::structures::Bundle::getActualInputChannelsMap () const
Get the actual input pattern channels of this bundle. Returns:
PatternChannelMap The map of actual input pattern channels of this bundle
Definition at line 453 of file Bundle.cpp.
References actualInputChannelsMap.
const state::PatternChannelMap & cryomesh::structures::Bundle::getActualOutputChannelsMap () const
Get the real output pattern channels of this bundle. Returns:
PatternChannelMap The map of actual output pattern channels of this bundle
Definition at line 456 of file Bundle.cpp.
References actualOutputChannelsMap.
const boost::shared_ptr< state::PatternChannel > cryomesh::structures::Bundle::getActualPrimaryInputChannelByFibre (const boost::uuids::uuidfibre_uuid) const [private]
Definition at line 711 of file Bundle.cpp.
References actualFibrePatternChannelMap, actualInputChannelsMap, and getPrimaryChannelByFibre().
Referenced by updatePrimaryInputFibres().
const boost::shared_ptr< state::PatternChannel > cryomesh::structures::Bundle::getActualPrimaryOutputChannelByFibre (const boost::uuids::uuidfibre_uuid) const [private]
Definition at line 715 of file Bundle.cpp.
References actualFibrePatternChannelMap, actualOutputChannelsMap, and getPrimaryChannelByFibre().
Referenced by matchOutputChannelsSum(), and updatePrimaryOutputFibres().
const ClusterMap & cryomesh::structures::Bundle::getClusters () const
Get the clusters in this bundle. Returns:
ClusterMap The map of clusters in this bundle
Definition at line 408 of file Bundle.cpp.
References clusters.
Referenced by checkFibreStructure(), cryomesh::utilities::Statistician::getActiveNodesPerCluster(), cryomesh::utilities::Statistician::getTriggeredNodesPerCluster(), print(), and cryomesh::utilities::Statistician::update().
std::vector< boost::shared_ptr< state::PatternChannel > > cryomesh::structures::Bundle::getDisconnectedRealInputPatternChannels () [virtual]
Definition at line 342 of file Bundle.cpp.
References getPrimaryInputFibreByRealChannel(), and realInputChannelsMap.
Referenced by autoConnectPrimaryInputClusters().
std::vector< boost::shared_ptr< state::PatternChannel > > cryomesh::structures::Bundle::getDisconnectedRealOutputPatternChannels () [virtual]
Definition at line 368 of file Bundle.cpp.
References getPrimaryOutputFibreByRealChannel(), and realOutputChannelsMap.
Referenced by autoConnectPrimaryOutputClusters().
double cryomesh::structures::Bundle::getEnergy () const
Get the last calculated energy of the bundle. Returns:
double The last calculated energy
Definition at line 470 of file Bundle.cpp.
References energy.
Referenced by update().
const FibreMap & cryomesh::structures::Bundle::getFibres () const
Get the mutable clusters in this bundle. Returns:
ClusterMap The mutable map of clusters in this bundle
Definition at line 427 of file Bundle.cpp.
References fibres.
Referenced by checkFibreStructure(), print(), and cryomesh::utilities::Statistician::update().
const FibreMap & cryomesh::structures::Bundle::getInputFibres () const
Get the input fibres of this bundle. Returns:
FibreMap The map of input fibres of this bundle
Definition at line 431 of file Bundle.cpp.
References inputFibres.
Referenced by checkFibreStructure(), print(), and cryomesh::utilities::Statistician::update().
ClusterMap & cryomesh::structures::Bundle::getMutableClusters () [protected]
Definition at line 424 of file Bundle.cpp.
References clusters.
Referenced by autoConnectPrimaryInputClusters(), and autoConnectPrimaryOutputClusters().
FibreMap & cryomesh::structures::Bundle::getMutableInputFibres ()
Get the mutable input fibres of this bundle. Returns:
FibreMap The map of mutable input fibres of this bundle
Definition at line 435 of file Bundle.cpp.
References inputFibres.
FibreMap & cryomesh::structures::Bundle::getMutableOutputFibres ()
Get the mutable output fibres of this bundle. Returns:
FibreMap The map of mutable output fibres of this bundle
Definition at line 443 of file Bundle.cpp.
References outputFibres.
boost::shared_ptr< utilities::Statistician > cryomesh::structures::Bundle::getMutableStatistician ()
Definition at line 473 of file Bundle.cpp.
References statistician.
const FibreMap & cryomesh::structures::Bundle::getOutputFibres () const
Get the output fibres of this bundle. Returns:
FibreMap The map of output fibres of this bundle
Definition at line 439 of file Bundle.cpp.
References outputFibres.
Referenced by checkFibreStructure(), matchOutputChannelsSum(), print(), and cryomesh::utilities::Statistician::update().
const boost::shared_ptr< state::PatternChannel > cryomesh::structures::Bundle::getPrimaryChannelByFibre (const boost::uuids::uuidid, const state::PatternChannelMap &map, const std::map< boost::uuids::uuid, boost::uuids::uuid > &fibrepattern_channelmap) const [private]
Helper method to take a uuid and find its correspondingly mapped object Take an Fibre uuid and find the PatternChannel its mapped to inside the supplied map. Parameters:
boost::uuids::uuid The uuid of the Fibre
PatternChannelMap The map to search for a mapping from
Returns:
boost::shared_ptr<PatternChannel> The PatternChannel object the Fibre with this uuid is mapped to, null if not found
Definition at line 787 of file Bundle.cpp.
Referenced by getActualPrimaryInputChannelByFibre(), getActualPrimaryOutputChannelByFibre(), getRealPrimaryInputChannelByFibre(), and getRealPrimaryOutputChannelByFibre().
const boost::shared_ptr< Fibre > cryomesh::structures::Bundle::getPrimaryFibreByChannel (const boost::uuids::uuidid, const FibreMap &map, const std::map< boost::uuids::uuid, boost::uuids::uuid > &fibrepattern_channelmap) const [private]
Helper method to take a uuid and find its correspondingly mapped object Take an channel uuid and find the Fibre its mapped to inside the supplied map. Parameters:
boost::uuids::uuid The uuid of the PatternChannel
FibreMap The map to search for a mapping from
Returns:
boost::shared_ptr<Fibre> The Fibre object the PatternChannel with this uuid is mapped to, null if not found
Definition at line 736 of file Bundle.cpp.
Referenced by getPrimaryInputFibreByActualChannel(), getPrimaryInputFibreByRealChannel(), getPrimaryOutputFibreByActualChannel(), and getPrimaryOutputFibreByRealChannel().
const boost::shared_ptr< Fibre > cryomesh::structures::Bundle::getPrimaryInputFibreByActualChannel (const boost::uuids::uuidpattern_channel_uuid) const [private]
Definition at line 728 of file Bundle.cpp.
References actualFibrePatternChannelMap, getPrimaryFibreByChannel(), and inputFibres.
const boost::shared_ptr< Fibre > cryomesh::structures::Bundle::getPrimaryInputFibreByRealChannel (const boost::uuids::uuidpattern_channel_uuid) const [private]
Helper method to take a uuid and find its correspondingly mapped object Take an input PatternChannel uuid and find the input Fibre its mapped to. Parameters:
boost::uuids::uuid The uuid of the input PatternChannel
Returns:
boost::shared_ptr<Fibre> The input Fibre object the input PatternChannel with this uuid is mapped to, null if not found
Definition at line 720 of file Bundle.cpp.
References getPrimaryFibreByChannel(), inputFibres, and realFibrePatternChannelMap.
Referenced by getDisconnectedRealInputPatternChannels(), and updatePrimaryInputFibres().
const boost::shared_ptr< Fibre > cryomesh::structures::Bundle::getPrimaryOutputFibreByActualChannel (const boost::uuids::uuidpattern_channel_uuid) const [private]
Definition at line 732 of file Bundle.cpp.
References actualFibrePatternChannelMap, getPrimaryFibreByChannel(), and outputFibres.
const boost::shared_ptr< Fibre > cryomesh::structures::Bundle::getPrimaryOutputFibreByRealChannel (const boost::uuids::uuidpattern_channel_uuid) const [private]
Helper method to take a uuid and find its correspondingly mapped object Take an output PatternChannel uuid and find the output Fibre its mapped to. Parameters:
boost::uuids::uuid The uuid of the output PatternChannel
Returns:
boost::shared_ptr<Fibre> The output Fibre object the output PatternChannel with this uuid is mapped to, null if not found
Definition at line 724 of file Bundle.cpp.
References getPrimaryFibreByChannel(), outputFibres, and realFibrePatternChannelMap.
Referenced by getDisconnectedRealOutputPatternChannels().
const std::map< boost::uuids::uuid, boost::uuids::uuid > & cryomesh::structures::Bundle::getRealFibrePatternChannelMap () const
Get the map of fibres to their associated pattern channels. Returns:
std::map<boost::uuids::uuid, boost::uuids::uuid> The map of fibres to their associated pattern channels
Definition at line 460 of file Bundle.cpp.
References realFibrePatternChannelMap.
Referenced by printFibreMaps().
const state::PatternChannelMap & cryomesh::structures::Bundle::getRealInputChannelsMap () const
Get the real input pattern channels of this bundle. Returns:
PatternChannelMap The map of real input pattern channels of this bundle
Definition at line 447 of file Bundle.cpp.
References realInputChannelsMap.
Referenced by cryomesh::utilities::Statistician::update().
const state::PatternChannelMap & cryomesh::structures::Bundle::getRealOutputChannelsMap () const
Get the real output pattern channels of this bundle. Returns:
PatternChannelMap The map of real output pattern channels of this bundle
Definition at line 450 of file Bundle.cpp.
References realOutputChannelsMap.
Referenced by cryomesh::utilities::Statistician::update().
const boost::shared_ptr< state::PatternChannel > cryomesh::structures::Bundle::getRealPrimaryInputChannelByFibre (const boost::uuids::uuidfibre_uuid) const [private]
Definition at line 703 of file Bundle.cpp.
References getPrimaryChannelByFibre(), realFibrePatternChannelMap, and realInputChannelsMap.
const boost::shared_ptr< state::PatternChannel > cryomesh::structures::Bundle::getRealPrimaryOutputChannelByFibre (const boost::uuids::uuidfibre_uuid) const [private]
Definition at line 707 of file Bundle.cpp.
References getPrimaryChannelByFibre(), realFibrePatternChannelMap, and realOutputChannelsMap.
Referenced by matchOutputChannelsSum().
const boost::shared_ptr< utilities::Statistician > cryomesh::structures::Bundle::getStatistician () const
Get the Statistician. Returns:
boost::shared_ptr< Statistician > The current statistician, null pointer if we dont have one
Definition at line 466 of file Bundle.cpp.
References statistician.
void cryomesh::structures::Bundle::loadChannels (const std::string &ifstr) [virtual]
Load in the pattern channels from a filename of a pattern dataset. Parameters:
std::string The full path filename of the pattern data set
Definition at line 396 of file Bundle.cpp.
References cryomesh::utilities::SequencerChannels::readSequences(), realInputChannelsMap, and realOutputChannelsMap.
double cryomesh::structures::Bundle::matchOutputChannelsSum () const [protected, virtual]
Compare the output channels of primary output fibres to expected output channel patterns. Returns:
double The double represesenting the accumulated 'energy' of all matches
Definition at line 652 of file Bundle.cpp.
References getActualPrimaryOutputChannelByFibre(), getOutputFibres(), and getRealPrimaryOutputChannelByFibre().
Referenced by update().
std::ostream & cryomesh::structures::Bundle::print (std::ostream &os, const common::Loggable::LoggingDepthdepth = SUMMARY) const [virtual]
Print the bundle to stream.
Implements cryomesh::common::Loggable.
Definition at line 836 of file Bundle.cpp.
References getClusters(), cryomesh::common::TimeKeeper::getCycle(), getFibres(), getInputFibres(), getOutputFibres(), cryomesh::common::TimeKeeper::getTimeKeeper(), cryomesh::common::Loggable::MAX, printChannels(), printFibreMaps(), and cryomesh::common::Loggable::SUMMARY.
Referenced by cryomesh::structures::operator<<().
std::ostream & cryomesh::structures::Bundle::printChannels (std::ostream &os) const
Print the channels to stream.
Definition at line 868 of file Bundle.cpp.
References actualInputChannelsMap, actualOutputChannelsMap, realInputChannelsMap, and realOutputChannelsMap.
Referenced by print().
std::ostream & cryomesh::structures::Bundle::printFibreMap (std::ostream &os, const std::map< boost::uuids::uuid, boost::uuids::uuid > &fibre_map) const
Definition at line 959 of file Bundle.cpp.
Referenced by printFibreMaps().
std::ostream & cryomesh::structures::Bundle::printFibreMaps (std::ostream &os) const
Definition at line 950 of file Bundle.cpp.
References getActualFibrePatternChannelMap(), getRealFibrePatternChannelMap(), and printFibreMap().
Referenced by print(), and updatePrimaryOutputFibres().
template<class T > std::ostream & cryomesh::structures::Bundle::printSearch (std::ostream &os, const boost::uuids::uuid &uuid, const std::map< boost::uuids::uuid, boost::shared_ptr< T > > &map) const [protected]
Print out a uuid search.
Definition at line 814 of file Bundle.cpp.
void cryomesh::structures::Bundle::setEnergy (doubled) [protected]
Set the energy of the bundle. Parameters:
double The energy to set
Definition at line 686 of file Bundle.cpp.
References energy.
Referenced by update().
void cryomesh::structures::Bundle::update ()
Update all bundle components.
Definition at line 26 of file Bundle.cpp.
References clusters, fibres, getEnergy(), cryomesh::common::TimeKeeper::getTimeKeeper(), matchOutputChannelsSum(), setEnergy(), cryomesh::structures::FibreMap::update(), cryomesh::common::TimeKeeper::update(), updatePrimaryInputFibres(), updatePrimaryOutputFibres(), and updateStatistician().
void cryomesh::structures::Bundle::updatePrimaryInputFibres () [protected, virtual]
Get the next patterns from channels and apply them to their mapped fibres.
Definition at line 568 of file Bundle.cpp.
References getActualPrimaryInputChannelByFibre(), getPrimaryInputFibreByRealChannel(), inputFibres, realInputChannelsMap, and cryomesh::structures::FibreMap::update().
Referenced by update().
void cryomesh::structures::Bundle::updatePrimaryOutputFibres () [protected, virtual]
Get the patterns from primary output fibres and apply them to their mapped pattern channels.
Definition at line 618 of file Bundle.cpp.
References getActualPrimaryOutputChannelByFibre(), outputFibres, printFibreMaps(), and cryomesh::structures::FibreMap::update().
Referenced by update().
void cryomesh::structures::Bundle::updateStatistician () [protected, virtual]
Update the statistician if debugging is enabled.
Definition at line 690 of file Bundle.cpp.
References statistician.
Referenced by update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Bundle &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Bundle & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 973 of file Bundle.cpp.
Member Data Documentation
std::map<boost::uuids::uuid, boost::uuids::uuid> cryomesh::structures::Bundle::actualFibrePatternChannelMap [private]
Definition at line 430 of file Bundle.h.
Referenced by connectPrimaryInputCluster(), connectPrimaryOutputCluster(), getActualFibrePatternChannelMap(), getActualPrimaryInputChannelByFibre(), getActualPrimaryOutputChannelByFibre(), getPrimaryInputFibreByActualChannel(), and getPrimaryOutputFibreByActualChannel().
state::PatternChannelMap cryomesh::structures::Bundle::actualInputChannelsMap [private]
Definition at line 385 of file Bundle.h.
Referenced by connectPrimaryInputCluster(), getActualInputChannelsMap(), getActualPrimaryInputChannelByFibre(), and printChannels().
state::PatternChannelMap cryomesh::structures::Bundle::actualOutputChannelsMap [private]
Definition at line 392 of file Bundle.h.
Referenced by connectPrimaryOutputCluster(), getActualOutputChannelsMap(), getActualPrimaryOutputChannelByFibre(), and printChannels().
ClusterMap cryomesh::structures::Bundle::clusters [private]
Definition at line 357 of file Bundle.h.
Referenced by connectCluster(), createCluster(), enableDebugClusters(), getClusters(), getMutableClusters(), and update().
double cryomesh::structures::Bundle::energy [private]
Last energy calculation of the output channel matching.
Definition at line 416 of file Bundle.h.
Referenced by getEnergy(), and setEnergy().
Cluster::EnergyFractionMethod cryomesh::structures::Bundle::energyFractionMethod [private]
Definition at line 432 of file Bundle.h.
Referenced by createCluster().
FibreMap cryomesh::structures::Bundle::fibres [private]
Definition at line 364 of file Bundle.h.
Referenced by connectCluster(), enableDebugFibres(), getFibres(), and update().
FibreMap cryomesh::structures::Bundle::inputFibres [private]
Definition at line 399 of file Bundle.h.
Referenced by connectCluster(), getInputFibres(), getMutableInputFibres(), getPrimaryInputFibreByActualChannel(), getPrimaryInputFibreByRealChannel(), and updatePrimaryInputFibres().
FibreMap cryomesh::structures::Bundle::outputFibres [private]
Definition at line 406 of file Bundle.h.
Referenced by connectCluster(), getMutableOutputFibres(), getOutputFibres(), getPrimaryOutputFibreByActualChannel(), getPrimaryOutputFibreByRealChannel(), and updatePrimaryOutputFibres().
std::map<boost::uuids::uuid, boost::uuids::uuid> cryomesh::structures::Bundle::realFibrePatternChannelMap [private]
Definition at line 423 of file Bundle.h.
Referenced by connectPrimaryInputCluster(), connectPrimaryOutputCluster(), getPrimaryInputFibreByRealChannel(), getPrimaryOutputFibreByRealChannel(), getRealFibrePatternChannelMap(), getRealPrimaryInputChannelByFibre(), and getRealPrimaryOutputChannelByFibre().
state::PatternChannelMap cryomesh::structures::Bundle::realInputChannelsMap [private]
Definition at line 371 of file Bundle.h.
Referenced by connectPrimaryInputCluster(), getDisconnectedRealInputPatternChannels(), getRealInputChannelsMap(), getRealPrimaryInputChannelByFibre(), loadChannels(), printChannels(), and updatePrimaryInputFibres().
state::PatternChannelMap cryomesh::structures::Bundle::realOutputChannelsMap [private]
Definition at line 378 of file Bundle.h.
Referenced by connectPrimaryOutputCluster(), getDisconnectedRealOutputPatternChannels(), getRealOutputChannelsMap(), getRealPrimaryOutputChannelByFibre(), loadChannels(), and printChannels().
boost::shared_ptr<utilities::Statistician> cryomesh::structures::Bundle::statistician [private]
Statistics object to generate useful info on the bundle.
Definition at line 411 of file Bundle.h.
Referenced by getMutableStatistician(), getStatistician(), and updateStatistician().
Author
Generated automatically by Doxygen for cryomesh from the source code.