.TH "cryomesh::Pointer" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::Pointer \- 
.PP
\fBPointer\fP struct to allow typdef of templated smart pointers.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Defs.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef boost::scoped_ptr< T > \fBscoped_ptr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< T > \fBshared_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> struct cryomesh::Pointer< T >"
\fBPointer\fP struct to allow typdef of templated smart pointers. 
.PP
Definition at line 23 of file Defs.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T > typedef boost::scoped_ptr<T> \fBcryomesh::Pointer\fP< T >::\fBscoped_ptr\fP"
.PP
Definition at line 28 of file Defs.h.
.SS "template<class T > typedef boost::shared_ptr<T> \fBcryomesh::Pointer\fP< T >::\fBshared_ptr\fP"
.PP
Definition at line 29 of file Defs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
