.TH "cryomesh::state::ActivityPattern" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::state::ActivityPattern \- 
.PP
A simple collection of doubles representing a pattern of activities.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ActivityPattern.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBActivityComparison\fP { \fBGreaterThan\fP, \fBLessThan\fP, \fBEqualTo\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActivityPattern\fP ()"
.br
.ti -1c
.RI "virtual \fB~ActivityPattern\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBtoPlusBooleanString\fP () const "
.br
.RI "\fIReturn a string of booleans representing with each element is > 0 or not. \fP"
.ti -1c
.RI "virtual std::list< bool > \fBtoPlusBooleanList\fP () const "
.br
.RI "\fIReturn a vector of booleans representing with each element > 0 or not. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::list< bool > \fBtoBooleanVector\fP (const double cuttoff, const \fBActivityComparison\fP compare) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple collection of doubles representing a pattern of activities. 
.PP
Definition at line 20 of file ActivityPattern.h.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBcryomesh::state::ActivityPattern::ActivityComparison\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIGreaterThan \fP\fP
.TP
\fB\fILessThan \fP\fP
.TP
\fB\fIEqualTo \fP\fP

.PP
Definition at line 22 of file ActivityPattern.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::state::ActivityPattern::ActivityPattern ()"
.PP
Definition at line 19 of file ActivityPattern.cpp.
.SS "cryomesh::state::ActivityPattern::~ActivityPattern ()\fC [virtual]\fP"
.PP
Definition at line 23 of file ActivityPattern.cpp.
.SH "Member Function Documentation"
.PP 
.SS "std::list< bool > cryomesh::state::ActivityPattern::toBooleanVector (const doublecuttoff, const \fBActivityComparison\fPcompare) const\fC [protected]\fP"
.PP
Definition at line 36 of file ActivityPattern.cpp.
.SS "std::list< bool > cryomesh::state::ActivityPattern::toPlusBooleanList () const\fC [virtual]\fP"
.PP
Return a vector of booleans representing with each element > 0 or not. \fBReturns:\fP
.RS 4
std::vector<bool> The vector of booleans 
.RE
.PP

.PP
Definition at line 32 of file ActivityPattern.cpp.
.SS "std::string cryomesh::state::ActivityPattern::toPlusBooleanString () const\fC [virtual]\fP"
.PP
Return a string of booleans representing with each element is > 0 or not. \fBReturns:\fP
.RS 4
std::string The string of booleans 
.RE
.PP

.PP
Definition at line 26 of file ActivityPattern.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
