cryomesh::components::NodeMap
NAME
cryomesh::components::NodeMap -
Helper class for NodeMap to KeyMappedCollection mapping.
SYNOPSIS
#include <NodeMap.h>
Public Member Functions
NodeMap ()
Default constructor.
virtual ~NodeMap ()
Default destructor.
void update ()
Update all entries in the nodemap.
const std::map
< boost::uuids::uuid,
boost::shared_ptr< Node > > getAllPrimaryInputNodes () const "
const std::map
< boost::uuids::uuid,
boost::shared_ptr< Node > > getAllPrimaryOutputNodes () const "
void addRandomImpulses (double positive_bias=0.5)
const std::map
< boost::uuids::uuid,
boost::shared_ptr< Connection > > getAllInputConnections () const "
const std::map
< boost::uuids::uuid,
boost::shared_ptr< Connection > > getAllOutputConnections () const "
const std::map
< boost::uuids::uuid,
boost::shared_ptr< Connection > > getAllConnections () const "
Friends
std::ostream & operator<< (std::ostream &os, const NodeMap &obj)
To stream operator.
Detailed Description
Helper class for NodeMap to KeyMappedCollection mapping.
Definition at line 23 of file NodeMap.h.
Constructor & Destructor Documentation
cryomesh::components::NodeMap::NodeMap () [inline]
Default constructor.
Definition at line 28 of file NodeMap.h.
virtual cryomesh::components::NodeMap::~NodeMap () [inline, virtual]
Default destructor.
Definition at line 35 of file NodeMap.h.
Member Function Documentation
void cryomesh::components::NodeMap::addRandomImpulses (doublepositive_bias = 0.5) [inline]
Definition at line 95 of file NodeMap.h.
References cryomesh::components::Impulse::getRandom().
const std::map<boost::uuids::uuid, boost::shared_ptr<Connection> > cryomesh::components::NodeMap::getAllConnections () const [inline]
Definition at line 149 of file NodeMap.h.
const std::map<boost::uuids::uuid, boost::shared_ptr<Connection> > cryomesh::components::NodeMap::getAllInputConnections () const [inline]
Definition at line 109 of file NodeMap.h.
const std::map<boost::uuids::uuid, boost::shared_ptr<Connection> > cryomesh::components::NodeMap::getAllOutputConnections () const [inline]
Definition at line 129 of file NodeMap.h.
const std::map<boost::uuids::uuid, boost::shared_ptr<Node> > cryomesh::components::NodeMap::getAllPrimaryInputNodes () const [inline]
Definition at line 53 of file NodeMap.h.
Referenced by cryomesh::manipulators::ClusterArchitect::getRandomNodes().
const std::map<boost::uuids::uuid, boost::shared_ptr<Node> > cryomesh::components::NodeMap::getAllPrimaryOutputNodes () const [inline]
Definition at line 74 of file NodeMap.h.
Referenced by cryomesh::manipulators::ClusterArchitect::getRandomNodes().
void cryomesh::components::NodeMap::update () [inline]
Update all entries in the nodemap.
Definition at line 41 of file NodeMap.h.
Referenced by cryomesh::structures::Cluster::update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const NodeMap &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const NodeMap & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 181 of file NodeMap.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.