cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown
NAME
cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown -
Class to hold together information on whether we can act to restructure items.
SYNOPSIS
#include <IClusterAnalyser.h>
Public Member Functions
RestructuringCountdown (int ct=0)
bool isRestructuringEnabled (int var) const
bool isAnyShortRestructuringEnabled () const
bool isAnyMediumRestructuringEnabled () const
bool isAnyLongRestructuringEnabled () const
bool isAnyRestructuringEnabled () const
bool isAllShortRestructuringEnabled () const
bool isAllMediumRestructuringEnabled () const
bool isAllLongRestructuringEnabled () const
bool isAllRestructuringEnabled () const
RestructuringCountdown & operator-- ()
Prefix decrement operator.
void setShortCountdown (int ct)
void setMediumCountdown (int ct)
void setLongCountdown (int ct)
Public Attributes
int shortCreation
int shortDestruction
int mediumCreation
int mediumDestruction
int longCreation
int longDestruction
Friends
std::ostream & operator<< (std::ostream &os, const RestructuringCountdown &obj)
To stream operator.
Detailed Description
Class to hold together information on whether we can act to restructure items.
Definition at line 23 of file IClusterAnalyser.h.
Constructor & Destructor Documentation
cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::RestructuringCountdown (intct = 0) [inline]
Definition at line 24 of file IClusterAnalyser.h.
Member Function Documentation
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAllLongRestructuringEnabled () const [inline]
Definition at line 60 of file IClusterAnalyser.h.
References isRestructuringEnabled(), longCreation, and longDestruction.
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAllMediumRestructuringEnabled () const [inline]
Definition at line 56 of file IClusterAnalyser.h.
References isRestructuringEnabled(), mediumCreation, and mediumDestruction.
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAllRestructuringEnabled () const [inline]
Definition at line 64 of file IClusterAnalyser.h.
References isAnyLongRestructuringEnabled(), isAnyMediumRestructuringEnabled(), and isAnyShortRestructuringEnabled().
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAllShortRestructuringEnabled () const [inline]
Definition at line 52 of file IClusterAnalyser.h.
References isRestructuringEnabled(), shortCreation, and shortDestruction.
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAnyLongRestructuringEnabled () const [inline]
Definition at line 43 of file IClusterAnalyser.h.
References isRestructuringEnabled(), longCreation, and longDestruction.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), isAllRestructuringEnabled(), and isAnyRestructuringEnabled().
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAnyMediumRestructuringEnabled () const [inline]
Definition at line 39 of file IClusterAnalyser.h.
References isRestructuringEnabled(), mediumCreation, and mediumDestruction.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), isAllRestructuringEnabled(), and isAnyRestructuringEnabled().
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAnyRestructuringEnabled () const [inline]
Definition at line 47 of file IClusterAnalyser.h.
References isAnyLongRestructuringEnabled(), isAnyMediumRestructuringEnabled(), and isAnyShortRestructuringEnabled().
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster().
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAnyShortRestructuringEnabled () const [inline]
Definition at line 35 of file IClusterAnalyser.h.
References isRestructuringEnabled(), shortCreation, and shortDestruction.
Referenced by isAllRestructuringEnabled(), and isAnyRestructuringEnabled().
bool cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isRestructuringEnabled (intvar) const [inline]
Definition at line 28 of file IClusterAnalyser.h.
Referenced by isAllLongRestructuringEnabled(), isAllMediumRestructuringEnabled(), isAllShortRestructuringEnabled(), isAnyLongRestructuringEnabled(), isAnyMediumRestructuringEnabled(), and isAnyShortRestructuringEnabled().
RestructuringCountdown& cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::operator-- () [inline]
Prefix decrement operator. Returns:
RestructuringCountdown & Return this
Definition at line 75 of file IClusterAnalyser.h.
References longCreation, longDestruction, mediumCreation, mediumDestruction, shortCreation, and shortDestruction.
void cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::setLongCountdown (intct) [inline]
Definition at line 105 of file IClusterAnalyser.h.
References longCreation, and longDestruction.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster().
void cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::setMediumCountdown (intct) [inline]
Definition at line 101 of file IClusterAnalyser.h.
References mediumCreation, and mediumDestruction.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster().
void cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::setShortCountdown (intct) [inline]
Definition at line 97 of file IClusterAnalyser.h.
References shortCreation, and shortDestruction.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const RestructuringCountdown &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const RestructuringCountdown & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 121 of file IClusterAnalyser.h.
Member Data Documentation
int cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::longCreation
Definition at line 132 of file IClusterAnalyser.h.
Referenced by isAllLongRestructuringEnabled(), isAnyLongRestructuringEnabled(), operator--(), and setLongCountdown().
int cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::longDestruction
Definition at line 133 of file IClusterAnalyser.h.
Referenced by isAllLongRestructuringEnabled(), isAnyLongRestructuringEnabled(), operator--(), and setLongCountdown().
int cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::mediumCreation
Definition at line 130 of file IClusterAnalyser.h.
Referenced by isAllMediumRestructuringEnabled(), isAnyMediumRestructuringEnabled(), operator--(), and setMediumCountdown().
int cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::mediumDestruction
Definition at line 131 of file IClusterAnalyser.h.
Referenced by isAllMediumRestructuringEnabled(), isAnyMediumRestructuringEnabled(), operator--(), and setMediumCountdown().
int cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::shortCreation
Definition at line 128 of file IClusterAnalyser.h.
Referenced by isAllShortRestructuringEnabled(), isAnyShortRestructuringEnabled(), operator--(), and setShortCountdown().
int cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::shortDestruction
Definition at line 129 of file IClusterAnalyser.h.
Referenced by isAllShortRestructuringEnabled(), isAnyShortRestructuringEnabled(), operator--(), and setShortCountdown().
Author
Generated automatically by Doxygen for cryomesh from the source code.