cryomesh::manipulators::ClusterArchitect
NAME
cryomesh::manipulators::ClusterArchitect -
SYNOPSIS
#include <ClusterArchitect.h>
Public Types
enum ConnectionStrategy { ENABLE_SELF_CONNECT = 1, ENABLE_EVEN_DISTRIBUTION = 2 }
Public Member Functions
ClusterArchitect (structures::Cluster &clus, const int max_history_sz=DEFAULT_MAX_HISTORY_SIZE, const int history_stepping_factor=DEFAULT_HISTORY_STEPPING_FACTOR)
virtual ~ClusterArchitect ()
virtual void runAnalysis ()
virtual const std::map< int,
std::list< ClusterAnalysisData > > & getHistories () const "
Get the history of analysis.
void createConnection (boost::shared_ptr< components::Node > nodeStart, boost::shared_ptr< components::Node > nodeEnd, int connectivity=1)
boost::shared_ptr
< components::Connection > deleteConnection (boost::shared_ptr< components::Connection > conn)"
virtual std::set
< boost::shared_ptr
< cryomesh::components::Node > > createRandomNodes (int count, int connectivity=0, int strategy=0)"
Create a number of random nodes.
virtual std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Connection > > createRandomConnections (int count)"
Create a number of random connections.
virtual std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Node > > destroyRandomNodes (int count)"
Destroy random nodes.
virtual std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Connection > > destroyRandomConnections (int count)"
Destroy random connections.
virtual std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Node > > getRandomNodes (const int count, const bool allow_primary)"
Get a collection of random nodes from the cluster.
virtual std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Connection > > getRandomConnections (const int count, const bool allow_primary)"
Get a collection of random connections from the cluster.
int getMaxHistorySize () const
void setMaxHistorySize (int sz)
ClusterAnalysisData getCurrentClusterAnalysisData () const
const std::list
< ClusterAnalysisData > & getCurrentHistory () const "
int getHistorySteppingFactor () const
void setCurrentClusterAnalysisData (ClusterAnalysisData currentClusterAnalysisData)
void setCurrentHistory (std::list< ClusterAnalysisData > currentHistory)
std::ostream & printAllHistory (std::ostream &os)
const structures::Cluster & getCluster () const
const boost::shared_ptr
< IClusterAnalyser > getClusterAnalyser () const "
void setClusterAnalyser (boost::shared_ptr< IClusterAnalyser > clusterAnalyser)
void setHistories (std::map< int, std::list< ClusterAnalysisData > > histories)
Protected Attributes
structures::Cluster & cluster
Static Protected Attributes
static const unsigned int DEFAULT_HISTORY_STEPPING_FACTOR = 2
static const int DEFAULT_MAX_HISTORY_SIZE = 3
static const double DEFAULT_CONNECTIVITY_FRACTION = 0.01
Private Member Functions
void addHistoryEntry (ClusterAnalysisData entry)
void splitHistoryByValue (const std::list< ClusterAnalysisData > &history, double db, int countback, std::map< common::Cycle, ClusterAnalysisData > &below, std::map< common::Cycle, ClusterAnalysisData > &above) const
std::vector< ClusterAnalysisData > getHistoryEntriesInRange (const std::list< ClusterAnalysisData > &history, double min_db, double max_db, int countback=0) const
Get the fraction of history entries from the past count entries that are inside of a range, default is to check all of them.
void reduceContainerSize (std::list< ClusterAnalysisData > &cont, const unsigned int sz)
Private Attributes
std::list< ClusterAnalysisData > currentHistory
std::map< int, std::list
< ClusterAnalysisData > > histories"
Map of all histories, the int represents the cycle seperation, the list is the resultant values/averages.
std::map< int, unsigned int > historiesNewEntries
const int historySteppingFactor
boost::shared_ptr
< IClusterAnalyser > clusterAnalyser"
ClusterAnalysisData currentClusterAnalysisData
int maxHistorySize
Detailed Description
Definition at line 23 of file ClusterArchitect.h.
Member Enumeration Documentation
enum cryomesh::manipulators::ClusterArchitect::ConnectionStrategy
Enumerator:
ENABLE_SELF_CONNECT
ENABLE_EVEN_DISTRIBUTION
Definition at line 26 of file ClusterArchitect.h.
Constructor & Destructor Documentation
cryomesh::manipulators::ClusterArchitect::ClusterArchitect (structures::Cluster &clus, const intmax_history_sz = DEFAULT_MAX_HISTORY_SIZE, const inthistory_stepping_factor = DEFAULT_HISTORY_STEPPING_FACTOR)
Definition at line 29 of file ClusterArchitect.cpp.
References historiesNewEntries, and maxHistorySize.
cryomesh::manipulators::ClusterArchitect::~ClusterArchitect () [virtual]
Definition at line 38 of file ClusterArchitect.cpp.
Member Function Documentation
void cryomesh::manipulators::ClusterArchitect::addHistoryEntry (ClusterAnalysisDataentry) [private]
Definition at line 507 of file ClusterArchitect.cpp.
References clusterAnalyser, currentClusterAnalysisData, currentHistory, getHistorySteppingFactor(), getMaxHistorySize(), histories, historiesNewEntries, printAllHistory(), and reduceContainerSize().
Referenced by runAnalysis().
void cryomesh::manipulators::ClusterArchitect::createConnection (boost::shared_ptr< components::Node >nodeStart, boost::shared_ptr< components::Node >nodeEnd, intconnectivity = 1)
Definition at line 647 of file ClusterArchitect.cpp.
References cluster, and cryomesh::structures::Cluster::getMutableConnectionMap().
Referenced by createRandomNodes().
std::map< boost::uuids::uuid, boost::shared_ptr< components::Connection > > cryomesh::manipulators::ClusterArchitect::createRandomConnections (intcount) [virtual]
Create a number of random connections.
Definition at line 282 of file ClusterArchitect.cpp.
References cluster, cryomesh::structures::Cluster::getMutableConnectionMap(), and cryomesh::structures::Cluster::getMutableNodeMap().
Referenced by runAnalysis().
std::set< boost::shared_ptr< cryomesh::components::Node > > cryomesh::manipulators::ClusterArchitect::createRandomNodes (intcount, intconnectivity = 0, intstrategy = 0) [virtual]
Create a number of random nodes.
Definition at line 57 of file ClusterArchitect.cpp.
References cluster, createConnection(), DEFAULT_CONNECTIVITY_FRACTION, ENABLE_EVEN_DISTRIBUTION, ENABLE_SELF_CONNECT, cryomesh::structures::Cluster::getMutableNodeMap(), cryomesh::structures::Cluster::getNodeMap(), and cryomesh::components::Node::getRandom().
Referenced by runAnalysis().
boost::shared_ptr< components::Connection > cryomesh::manipulators::ClusterArchitect::deleteConnection (boost::shared_ptr< components::Connection >conn)
Definition at line 665 of file ClusterArchitect.cpp.
References cluster, and cryomesh::structures::Cluster::getMutableConnectionMap().
std::map< boost::uuids::uuid, boost::shared_ptr< components::Connection > > cryomesh::manipulators::ClusterArchitect::destroyRandomConnections (intcount) [virtual]
Destroy random connections.
Definition at line 361 of file ClusterArchitect.cpp.
References cluster, cryomesh::structures::Cluster::getMutableConnectionMap(), and getRandomConnections().
Referenced by runAnalysis().
std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > cryomesh::manipulators::ClusterArchitect::destroyRandomNodes (intcount) [virtual]
Destroy random nodes.
Definition at line 333 of file ClusterArchitect.cpp.
References cluster, cryomesh::structures::Cluster::getMutableConnectionMap(), cryomesh::structures::Cluster::getMutableNodeMap(), and getRandomNodes().
Referenced by runAnalysis().
const structures::Cluster & cryomesh::manipulators::ClusterArchitect::getCluster () const
Definition at line 604 of file ClusterArchitect.cpp.
References cluster.
const boost::shared_ptr< IClusterAnalyser > cryomesh::manipulators::ClusterArchitect::getClusterAnalyser () const
Definition at line 608 of file ClusterArchitect.cpp.
References clusterAnalyser.
ClusterAnalysisData cryomesh::manipulators::ClusterArchitect::getCurrentClusterAnalysisData () const
Definition at line 584 of file ClusterArchitect.cpp.
References currentClusterAnalysisData.
const std::list< ClusterAnalysisData > & cryomesh::manipulators::ClusterArchitect::getCurrentHistory () const
Definition at line 588 of file ClusterArchitect.cpp.
References currentHistory.
const std::map< int, std::list< ClusterAnalysisData > > & cryomesh::manipulators::ClusterArchitect::getHistories () const [virtual]
Get the history of analysis. Returns:
const common::SimpleCollection<ClusterAnalysisData> & The container with the history of analysis
Definition at line 491 of file ClusterArchitect.cpp.
References histories.
std::vector< ClusterAnalysisData > cryomesh::manipulators::ClusterArchitect::getHistoryEntriesInRange (const std::list< ClusterAnalysisData > &history, doublemin_db, doublemax_db, intcountback = 0) const [private]
Get the fraction of history entries from the past count entries that are inside of a range, default is to check all of them. Parameters:
double Value for entries to be above
double Value for entries to be below
int Number of past entries to go back
Returns:
std::vector<ClusterAnalysisData> Entries within range
Definition at line 620 of file ClusterArchitect.cpp.
References splitHistoryByValue().
int cryomesh::manipulators::ClusterArchitect::getHistorySteppingFactor () const
Definition at line 592 of file ClusterArchitect.cpp.
References historySteppingFactor.
Referenced by addHistoryEntry(), and cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster().
int cryomesh::manipulators::ClusterArchitect::getMaxHistorySize () const
Definition at line 495 of file ClusterArchitect.cpp.
References maxHistorySize.
Referenced by addHistoryEntry(), and cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster().
std::map< boost::uuids::uuid, boost::shared_ptr< components::Connection > > cryomesh::manipulators::ClusterArchitect::getRandomConnections (const intcount, const boolallow_primary) [virtual]
Get a collection of random connections from the cluster. Parameters:
const int The number of random connections to return
const bool Allow the random connections to be attached primaries, default false
Returns:
std::list<boost::shared_ptr<components::Connection> > List of random connections
Definition at line 440 of file ClusterArchitect.cpp.
References cluster, cryomesh::components::ConnectionMap::getAllPrimaryInputConnections(), cryomesh::components::ConnectionMap::getAllPrimaryOutputConnections(), cryomesh::structures::Cluster::getConnectionMap(), and cryomesh::structures::Cluster::getMutableConnectionMap().
Referenced by destroyRandomConnections().
std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > cryomesh::manipulators::ClusterArchitect::getRandomNodes (const intcount, const boolallow_primary) [virtual]
Get a collection of random nodes from the cluster. Parameters:
const int The number of random nodes to return
const bool Allow the random nodes to be attached primaries, default false
Returns:
std::list<boost::shared_ptr<components::Node> > List of random nodes
Definition at line 388 of file ClusterArchitect.cpp.
References cluster, cryomesh::components::NodeMap::getAllPrimaryInputNodes(), cryomesh::components::NodeMap::getAllPrimaryOutputNodes(), cryomesh::structures::Cluster::getMutableNodeMap(), and cryomesh::structures::Cluster::getNodeMap().
Referenced by destroyRandomNodes().
std::ostream & cryomesh::manipulators::ClusterArchitect::printAllHistory (std::ostream &os)
Definition at line 672 of file ClusterArchitect.cpp.
References currentHistory, and histories.
Referenced by addHistoryEntry().
void cryomesh::manipulators::ClusterArchitect::reduceContainerSize (std::list< ClusterAnalysisData > &cont, const unsigned intsz) [private]
Definition at line 691 of file ClusterArchitect.cpp.
Referenced by addHistoryEntry().
void cryomesh::manipulators::ClusterArchitect::runAnalysis () [virtual]
Definition at line 41 of file ClusterArchitect.cpp.
References addHistoryEntry(), cluster, clusterAnalyser, createRandomConnections(), createRandomNodes(), destroyRandomConnections(), destroyRandomNodes(), cryomesh::manipulators::ClusterAnalysisData::getConnectionsToCreate(), cryomesh::manipulators::ClusterAnalysisData::getConnectionsToDestroy(), cryomesh::manipulators::ClusterAnalysisData::getNodesToCreate(), cryomesh::manipulators::ClusterAnalysisData::getNodesToDestroy(), and histories.
void cryomesh::manipulators::ClusterArchitect::setClusterAnalyser (boost::shared_ptr< IClusterAnalyser >clusterAnalyser)
Definition at line 612 of file ClusterArchitect.cpp.
References clusterAnalyser.
void cryomesh::manipulators::ClusterArchitect::setCurrentClusterAnalysisData (ClusterAnalysisDatacurrentClusterAnalysisData)
Definition at line 596 of file ClusterArchitect.cpp.
References currentClusterAnalysisData.
void cryomesh::manipulators::ClusterArchitect::setCurrentHistory (std::list< ClusterAnalysisData >currentHistory)
Definition at line 600 of file ClusterArchitect.cpp.
References currentHistory.
void cryomesh::manipulators::ClusterArchitect::setHistories (std::map< int, std::list< ClusterAnalysisData > >histories)
Definition at line 616 of file ClusterArchitect.cpp.
References histories.
void cryomesh::manipulators::ClusterArchitect::setMaxHistorySize (intsz)
Definition at line 499 of file ClusterArchitect.cpp.
References maxHistorySize.
void cryomesh::manipulators::ClusterArchitect::splitHistoryByValue (const std::list< ClusterAnalysisData > &history, doubledb, intcountback, std::map< common::Cycle, ClusterAnalysisData > &below, std::map< common::Cycle, ClusterAnalysisData > &above) const [private]
Definition at line 560 of file ClusterArchitect.cpp.
Referenced by getHistoryEntriesInRange().
Member Data Documentation
structures::Cluster& cryomesh::manipulators::ClusterArchitect::cluster [protected]
Definition at line 98 of file ClusterArchitect.h.
Referenced by createConnection(), createRandomConnections(), createRandomNodes(), deleteConnection(), destroyRandomConnections(), destroyRandomNodes(), getCluster(), getRandomConnections(), getRandomNodes(), and runAnalysis().
boost::shared_ptr< IClusterAnalyser > cryomesh::manipulators::ClusterArchitect::clusterAnalyser [private]
Definition at line 131 of file ClusterArchitect.h.
Referenced by addHistoryEntry(), getClusterAnalyser(), runAnalysis(), and setClusterAnalyser().
ClusterAnalysisData cryomesh::manipulators::ClusterArchitect::currentClusterAnalysisData [private]
Definition at line 132 of file ClusterArchitect.h.
Referenced by addHistoryEntry(), getCurrentClusterAnalysisData(), and setCurrentClusterAnalysisData().
std::list<ClusterAnalysisData > cryomesh::manipulators::ClusterArchitect::currentHistory [private]
Definition at line 115 of file ClusterArchitect.h.
Referenced by addHistoryEntry(), getCurrentHistory(), printAllHistory(), and setCurrentHistory().
const double cryomesh::manipulators::ClusterArchitect::DEFAULT_CONNECTIVITY_FRACTION = 0.01 [static, protected]
Definition at line 107 of file ClusterArchitect.h.
Referenced by createRandomNodes().
const unsigned int cryomesh::manipulators::ClusterArchitect::DEFAULT_HISTORY_STEPPING_FACTOR = 2 [static, protected]
Definition at line 105 of file ClusterArchitect.h.
const int cryomesh::manipulators::ClusterArchitect::DEFAULT_MAX_HISTORY_SIZE = 3 [static, protected]
Definition at line 106 of file ClusterArchitect.h.
std::map<int, std::list<ClusterAnalysisData> > cryomesh::manipulators::ClusterArchitect::histories [private]
Map of all histories, the int represents the cycle seperation, the list is the resultant values/averages. eg
mapping of 1 to a list of ClusterAnalysisData is the standard save of every cycles history (up to cutoff)
mapping of 10 means that every 10 cycles are averaged and the result added to the mapped list
Note that mapping steps are recursive, we can only have int keys as multiples of each other, eg {1, 2, 4, 8, etc} or {1, 10, 100, ... } , so { 1, a, a^2, a^3, ... }
Definition at line 127 of file ClusterArchitect.h.
Referenced by addHistoryEntry(), getHistories(), printAllHistory(), runAnalysis(), and setHistories().
std::map<int, unsigned int > cryomesh::manipulators::ClusterArchitect::historiesNewEntries [private]
Definition at line 128 of file ClusterArchitect.h.
Referenced by addHistoryEntry(), and ClusterArchitect().
const int cryomesh::manipulators::ClusterArchitect::historySteppingFactor [private]
Definition at line 129 of file ClusterArchitect.h.
Referenced by getHistorySteppingFactor().
int cryomesh::manipulators::ClusterArchitect::maxHistorySize [private]
Definition at line 134 of file ClusterArchitect.h.
Referenced by ClusterArchitect(), getMaxHistorySize(), and setMaxHistorySize().
Author
Generated automatically by Doxygen for cryomesh from the source code.