.TH "cryomesh::manipulators::IClusterAnalyser::EnergyVariationWeightingMap" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::manipulators::IClusterAnalyser::EnergyVariationWeightingMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IClusterAnalyser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnergyVariationWeightingMap\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< \fBEnergyVariation\fP, double > \fBvariationMap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 150 of file IClusterAnalyser\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::manipulators::IClusterAnalyser::EnergyVariationWeightingMap::EnergyVariationWeightingMap\fP ()\fC [inline]\fP"
.PP
Definition at line 151 of file IClusterAnalyser\&.h\&.
.PP
References cryomesh::manipulators::IClusterAnalyser::HIGH_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::HIGH_POSITIVE, cryomesh::manipulators::IClusterAnalyser::MEDIUM_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::MEDIUM_POSITIVE, cryomesh::manipulators::IClusterAnalyser::OUT_OF_RANGE_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::OUT_OF_RANGE_POSITIVE, cryomesh::manipulators::IClusterAnalyser::SMALL_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::SMALL_POSITIVE, cryomesh::manipulators::IClusterAnalyser::STAGNANT_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::STAGNANT_POSITIVE, variationMap, and cryomesh::manipulators::IClusterAnalyser::ZERO\&.
.SH "Member Data Documentation"
.PP 
.SS "std::map<\fBEnergyVariation\fP, double> \fBcryomesh::manipulators::IClusterAnalyser::EnergyVariationWeightingMap::variationMap\fP"
.PP
Definition at line 165 of file IClusterAnalyser\&.h\&.
.PP
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), EnergyVariationWeightingMap(), and cryomesh::manipulators::ClusterAnalyserBasic::getEnergyVariationMap()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
