cryomesh::manager::NodeDatabaseObject
NAME
cryomesh::manager::NodeDatabaseObject -
SYNOPSIS
#include <NodeDatabaseObject.h>
Inherits cryomesh::manager::DatabaseObject.
Public Member Functions
NodeDatabaseObject (std::string uuid_str, spacial::Point pt, common::Cycle cyc, double act)
Create object from node variables.
NodeDatabaseObject (const std::string &node_table_entry)
Create object from the string of entries in the database node table.
virtual ~NodeDatabaseObject ()
Default destructor.
virtual std::string getInsert (const std::string &table) const
Get the string that can be used to insert the sql data.
std::string getUUID () const
Get uuid variable.
const spacial::Point & getPoint () const
Get point variable.
const common::Cycle & getCycle () const
Get cycle variable.
double getActivity () const
Get activity variable.
std::string getKey (const std::string &key) const
Return the string object associated with a key.
Static Public Member Functions
static std::string findValue (const std::string &entry, const std::map< std::string, std::string > &map)
Find entries value in map or return null.
static std::map< std::string,
std::string > getColumnMapFromEntry (const std::string &entry)"
Parse a string database entry, extract columns and values and return a map.
template<class T > static std::string toString (T obj)
Convert an templated object that can be piped to a stream to a string.
Static Public Attributes
static const std::string ID_TAG = 'id'
static const std::string X_TAG = 'x'
static const std::string Y_TAG = 'y'
static const std::string Z_TAG = 'z'
static const std::string ACTIVITY_TAG = 'activity'
static const std::string CYCLE_TAG = 'cycle'
Protected Attributes
std::map< std::string,
std::string > columns"
Private Attributes
std::string uuid
spacial::Point point
common::Cycle cycle
double activity
Detailed Description
Definition at line 20 of file NodeDatabaseObject.h.
Constructor & Destructor Documentation
cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject (std::stringuuid_str, spacial::Pointpt, common::Cyclecyc, doubleact)
Create object from node variables. Parameters:
std::string The uuid string of the node
spacial::Point Location of the node
Cycle The cycle of the entry
double The activity of the node on the cycle
Definition at line 13 of file NodeDatabaseObject.cpp.
References activity, ACTIVITY_TAG, cryomesh::manager::DatabaseObject::columns, cycle, CYCLE_TAG, ID_TAG, point, cryomesh::common::Cycle::toULInt(), X_TAG, Y_TAG, and Z_TAG.
cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject (const std::string &node_table_entry)
Create object from the string of entries in the database node table. Parameters:
std::string The string of data taken from a node entry in the database node table
Definition at line 23 of file NodeDatabaseObject.cpp.
References activity, cycle, cryomesh::manager::DatabaseObject::findValue(), cryomesh::manager::DatabaseObject::getColumnMapFromEntry(), point, and uuid.
cryomesh::manager::NodeDatabaseObject::~NodeDatabaseObject () [virtual]
Default destructor.
Definition at line 60 of file NodeDatabaseObject.cpp.
Member Function Documentation
static std::string cryomesh::manager::DatabaseObject::findValue (const std::string &entry, const std::map< std::string, std::string > &map) [inline, static, inherited]
Find entries value in map or return null. Parameters:
std::string Entry to find
std::map<std::string,std::string map to search
Returns:
Value of entry
Definition at line 59 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
double cryomesh::manager::NodeDatabaseObject::getActivity () const
Get activity variable. Returns:
double The activity variable
Definition at line 83 of file NodeDatabaseObject.cpp.
References activity.
static std::map<std::string, std::string> cryomesh::manager::DatabaseObject::getColumnMapFromEntry (const std::string &entry) [inline, static, inherited]
Parse a string database entry, extract columns and values and return a map.
Definition at line 72 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
const common::Cycle & cryomesh::manager::NodeDatabaseObject::getCycle () const
Get cycle variable. Returns:
common::Cycle The cycle variable
Definition at line 80 of file NodeDatabaseObject.cpp.
References cycle.
std::string cryomesh::manager::NodeDatabaseObject::getInsert (const std::string &table) const [virtual]
Get the string that can be used to insert the sql data. Returns:
the sql command string to insert into this table
Implements cryomesh::manager::DatabaseObject.
Definition at line 63 of file NodeDatabaseObject.cpp.
References ACTIVITY_TAG, CYCLE_TAG, cryomesh::manager::DatabaseObject::getKey(), ID_TAG, X_TAG, Y_TAG, and Z_TAG.
std::string cryomesh::manager::DatabaseObject::getKey (const std::string &key) const [inline, inherited]
Return the string object associated with a key. ::string The key to search for
Returns:
std::string The object associated with the search key, '' if not found
Definition at line 37 of file DatabaseObject.h.
References cryomesh::manager::DatabaseObject::columns.
Referenced by cryomesh::manager::PatternDatabaseObject::getInsert(), getInsert(), and cryomesh::manager::ConnectionDatabaseObject::getInsert().
const spacial::Point & cryomesh::manager::NodeDatabaseObject::getPoint () const
Get point variable. Returns:
spacial::Point The point variable
Definition at line 77 of file NodeDatabaseObject.cpp.
References point.
std::string cryomesh::manager::NodeDatabaseObject::getUUID () const
Get uuid variable. Returns:
std::string The uuid variable
Definition at line 74 of file NodeDatabaseObject.cpp.
References uuid.
template<class T > static std::string cryomesh::manager::DatabaseObject::toString (Tobj) [inline, static, inherited]
Convert an templated object that can be piped to a stream to a string. Parameters:
T The object to get a string for
Definition at line 108 of file DatabaseObject.h.
Member Data Documentation
double cryomesh::manager::NodeDatabaseObject::activity [private]
Definition at line 158 of file NodeDatabaseObject.h.
Referenced by getActivity(), and NodeDatabaseObject().
const std::string cryomesh::manager::NodeDatabaseObject::ACTIVITY_TAG = 'activity' [static]
Definition at line 122 of file NodeDatabaseObject.h.
Referenced by getInsert(), and NodeDatabaseObject().
std::map<std::string, std::string> cryomesh::manager::DatabaseObject::columns [protected, inherited]
Definition at line 119 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::manager::DatabaseObject::getKey(), NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
common::Cycle cryomesh::manager::NodeDatabaseObject::cycle [private]
Definition at line 151 of file NodeDatabaseObject.h.
Referenced by getCycle(), and NodeDatabaseObject().
const std::string cryomesh::manager::NodeDatabaseObject::CYCLE_TAG = 'cycle' [static]
Definition at line 129 of file NodeDatabaseObject.h.
Referenced by getInsert(), and NodeDatabaseObject().
const std::string cryomesh::manager::NodeDatabaseObject::ID_TAG = 'id' [static]
Definition at line 94 of file NodeDatabaseObject.h.
Referenced by getInsert(), and NodeDatabaseObject().
spacial::Point cryomesh::manager::NodeDatabaseObject::point [private]
Definition at line 144 of file NodeDatabaseObject.h.
Referenced by getPoint(), and NodeDatabaseObject().
std::string cryomesh::manager::NodeDatabaseObject::uuid [private]
Definition at line 137 of file NodeDatabaseObject.h.
Referenced by getUUID(), and NodeDatabaseObject().
const std::string cryomesh::manager::NodeDatabaseObject::X_TAG = 'x' [static]
Definition at line 101 of file NodeDatabaseObject.h.
Referenced by getInsert(), and NodeDatabaseObject().
const std::string cryomesh::manager::NodeDatabaseObject::Y_TAG = 'y' [static]
Definition at line 108 of file NodeDatabaseObject.h.
Referenced by getInsert(), and NodeDatabaseObject().
const std::string cryomesh::manager::NodeDatabaseObject::Z_TAG = 'z' [static]
Definition at line 115 of file NodeDatabaseObject.h.
Referenced by getInsert(), and NodeDatabaseObject().
Author
Generated automatically by Doxygen for cryomesh from the source code.