cryomesh::components::ActivityTimerDistance
NAME
cryomesh::components::ActivityTimerDistance -
SYNOPSIS
#include <ActivityTimerDistance.h>
Inherits cryomesh::components::ActivityTimer.
Public Member Functions
ActivityTimerDistance ()
Constructor.
ActivityTimerDistance (double dist, double dec)
Construct from an initial distance, and a rate of decrement.
virtual ~ActivityTimerDistance ()
ActivityTimerDistance & operator= (const ActivityTimerDistance &obj)
Assignment operator.
bool operator< (const ActivityTimerDistance &obj) const
Less than operator.
bool operator> (const ActivityTimerDistance &obj) const
Greater than operator.
ActivityTimerDistance & operator-- ()
Prefix increment operator.
ActivityTimerDistance operator-- (int)
Postfix decrement operator.
const ActivityTimerDistance operator+ (const ActivityTimerDistance &obj) const
Non-destructive addition operator.
ActivityTimerDistance & operator+= (const ActivityTimerDistance &obj)
Destructive addition and assignment operator.
double getDelay () const
Get the delay.
double getStartingDelay () const
Get the starting delay.
double getDecrement () const
Get the decrement.
void reset ()
Reset the countdown.
virtual bool checkConstraints () const
virtual void enableDebug (bool b)
Static Public Member Functions
static boost::shared_ptr
< ActivityTimerDistance > getRandom ()"
Get a random object.
Static Public Attributes
static const double MIN_DECREMENT_FRACTION = 0.1
static const double MAX_DECREMENT_FRACTION = 1
static const double MIN_DISTANCE = 1.0
static const double MAX_DISTANCE = 100.0
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Private Attributes
double distance
double distance_remaining
double decrement
Friends
std::ostream & operator<< (std::ostream &os, const ActivityTimer &obj)
To stream operator.
Detailed Description
Definition at line 19 of file ActivityTimerDistance.h.
Constructor & Destructor Documentation
cryomesh::components::ActivityTimerDistance::ActivityTimerDistance ()
Constructor.
Definition at line 36 of file ActivityTimerDistance.cpp.
Referenced by getRandom().
cryomesh::components::ActivityTimerDistance::ActivityTimerDistance (doubledist, doubledec)
Construct from an initial distance, and a rate of decrement.
Definition at line 40 of file ActivityTimerDistance.cpp.
cryomesh::components::ActivityTimerDistance::~ActivityTimerDistance () [virtual]
Definition at line 44 of file ActivityTimerDistance.cpp.
Member Function Documentation
bool cryomesh::components::ActivityTimerDistance::checkConstraints () const [virtual]
Definition at line 113 of file ActivityTimerDistance.cpp.
References getDecrement(), getStartingDelay(), and MIN_DISTANCE.
void cryomesh::components::ActivityTimerDistance::enableDebug (boolb) [virtual]
Definition at line 101 of file ActivityTimerDistance.cpp.
double cryomesh::components::ActivityTimerDistance::getDecrement () const
Get the decrement. Returns:
double The decrement of the timer
Definition at line 98 of file ActivityTimerDistance.cpp.
References decrement.
Referenced by checkConstraints(), and print().
double cryomesh::components::ActivityTimerDistance::getDelay () const
Get the delay. Returns:
double The distance delay
Definition at line 90 of file ActivityTimerDistance.cpp.
References distance_remaining.
Referenced by print().
boost::shared_ptr< ActivityTimerDistance > cryomesh::components::ActivityTimerDistance::getRandom () [static]
Get a random object. Returns:
boost::shared_ptr<ActivityTimerDistance> The random object
Definition at line 22 of file ActivityTimerDistance.cpp.
References ActivityTimerDistance(), MAX_DECREMENT_FRACTION, MAX_DISTANCE, MIN_DECREMENT_FRACTION, and MIN_DISTANCE.
double cryomesh::components::ActivityTimerDistance::getStartingDelay () const
Get the starting delay. Returns:
double The starting distance delay
Definition at line 94 of file ActivityTimerDistance.cpp.
References distance.
Referenced by checkConstraints(), and print().
const ActivityTimerDistance cryomesh::components::ActivityTimerDistance::operator+ (const ActivityTimerDistance &obj) const
Non-destructive addition operator. Parameters:
const ActivityTimerDistance & obj RHS addition
Returns:
ActivityTimerDistance New object after addition
Definition at line 76 of file ActivityTimerDistance.cpp.
ActivityTimerDistance & cryomesh::components::ActivityTimerDistance::operator+= (const ActivityTimerDistance &obj)
Destructive addition and assignment operator. Parameters:
const ActivityTimerDistance & obj RHS addition
Returns:
ActivityTimerDistance & This object after addition and assignment
Definition at line 82 of file ActivityTimerDistance.cpp.
References decrement, distance, and distance_remaining.
ActivityTimerDistance & cryomesh::components::ActivityTimerDistance::operator-- ()
Prefix increment operator. Returns:
ActivityTimerDistance & Return this
Definition at line 62 of file ActivityTimerDistance.cpp.
References decrement, and distance_remaining.
ActivityTimerDistance cryomesh::components::ActivityTimerDistance::operator-- (int)
Postfix decrement operator. Returns:
ActivityTimerDistance & Return this
Definition at line 70 of file ActivityTimerDistance.cpp.
bool cryomesh::components::ActivityTimerDistance::operator< (const ActivityTimerDistance &obj) const
Less than operator. Parameters:
const ActivityTimerDistance & obj RHS
Returns:
bool True if < than obj, false otherwise
Definition at line 54 of file ActivityTimerDistance.cpp.
References distance.
ActivityTimerDistance & cryomesh::components::ActivityTimerDistance::operator= (const ActivityTimerDistance &obj)
Assignment operator. Parameters:
const ActivityTimerDistance & obj RHS assignment
Returns:
ActivityTimerDistance & This object after assignment
Definition at line 47 of file ActivityTimerDistance.cpp.
References decrement, distance, and distance_remaining.
bool cryomesh::components::ActivityTimerDistance::operator> (const ActivityTimerDistance &obj) const
Greater than operator. Parameters:
const ActivityTimerDistance & obj RHS
Returns:
bool True if > than obj, false otherwise
Definition at line 58 of file ActivityTimerDistance.cpp.
References distance_remaining.
std::ostream & cryomesh::components::ActivityTimerDistance::print (std::ostream &os) const [protected, virtual]
Implements cryomesh::components::ActivityTimer.
Definition at line 107 of file ActivityTimerDistance.cpp.
References getDecrement(), getDelay(), and getStartingDelay().
void cryomesh::components::ActivityTimerDistance::reset () [virtual]
Reset the countdown.
Implements cryomesh::components::ActivityTimer.
Definition at line 104 of file ActivityTimerDistance.cpp.
References distance, and distance_remaining.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const ActivityTimer &obj) [friend, inherited]
To stream operator. Parameters:
std::ostream & os The output stream
const ActivityTimer & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 47 of file ActivityTimer.h.
Member Data Documentation
double cryomesh::components::ActivityTimerDistance::decrement [private]
Definition at line 196 of file ActivityTimerDistance.h.
Referenced by getDecrement(), operator+=(), operator--(), and operator=().
double cryomesh::components::ActivityTimerDistance::distance [private]
Definition at line 181 of file ActivityTimerDistance.h.
Referenced by getStartingDelay(), operator+=(), operator<(), operator=(), and reset().
double cryomesh::components::ActivityTimerDistance::distance_remaining [private]
Definition at line 188 of file ActivityTimerDistance.h.
Referenced by getDelay(), operator+=(), operator--(), operator=(), operator>(), and reset().
const double cryomesh::components::ActivityTimerDistance::MAX_DECREMENT_FRACTION = 1 [static]
Definition at line 156 of file ActivityTimerDistance.h.
Referenced by getRandom().
const double cryomesh::components::ActivityTimerDistance::MAX_DISTANCE = 100.0 [static]
Definition at line 170 of file ActivityTimerDistance.h.
Referenced by getRandom().
const double cryomesh::components::ActivityTimerDistance::MIN_DECREMENT_FRACTION = 0.1 [static]
Definition at line 149 of file ActivityTimerDistance.h.
Referenced by getRandom().
const double cryomesh::components::ActivityTimerDistance::MIN_DISTANCE = 1.0 [static]
Definition at line 163 of file ActivityTimerDistance.h.
Referenced by checkConstraints(), getRandom(), and cryomesh::components::Connection::updatePosition().
Author
Generated automatically by Doxygen for cryomesh from the source code.