.TH "cryomesh::state::Sequence" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::state::Sequence \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sequence\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSequence\fP ()"
.br
.ti -1c
.RI "virtual \fB~Sequence\fP ()"
.br
.ti -1c
.RI "\fBSequence\fP (const \fBSequence\fP &seq)"
.br
.ti -1c
.RI "\fBSequence\fP (const std::vector< \fBPattern\fP > &input_pats, const std::vector< \fBPattern\fP > &output_pats)"
.br
.ti -1c
.RI "\fBSequence\fP (std::ifstream &ifs)"
.br
.ti -1c
.RI "\fBSequence\fP & \fBoperator=\fP (const \fBSequence\fP &seq)"
.br
.ti -1c
.RI "const \fBPattern\fP & \fBgetCurrentInputPattern\fP () const "
.br
.ti -1c
.RI "const \fBPattern\fP & \fBgetCurrentOutputPattern\fP () const "
.br
.ti -1c
.RI "const \fBPattern\fP & \fBgetAndAdvanceCurrentInputPattern\fP ()"
.br
.ti -1c
.RI "const \fBPattern\fP & \fBgetAndAdvanceCurrentOutputPattern\fP ()"
.br
.ti -1c
.RI "int \fBgetCurrentInputPatternId\fP () const "
.br
.ti -1c
.RI "int \fBgetCurrentOutputPatternId\fP () const "
.br
.ti -1c
.RI "std::list< std::pair< \fBPattern\fP, 
.br
\fBPattern\fP > >::const_iterator \fBgetCurrentIterator\fP () const "
.br
.ti -1c
.RI "void \fBsetCurrentIterator\fP (std::list< std::pair< \fBPattern\fP, \fBPattern\fP > >::const_iterator)"
.br
.ti -1c
.RI "const \fBPattern\fP & \fBgetNextInputPattern\fP ()"
.br
.ti -1c
.RI "const std::list< std::pair
.br
< \fBPattern\fP, \fBPattern\fP > > & \fBgetPatterns\fP () const "
.br
.ti -1c
.RI "void \fBsetPatterns\fP (const std::list< std::pair< \fBPattern\fP, \fBPattern\fP > > &pats)"
.br
.ti -1c
.RI "void \fBsaveToFile\fP (std::ofstream &ofs) const "
.br
.ti -1c
.RI "void \fBloadFromFile\fP (std::ifstream &ifs)"
.br
.ti -1c
.RI "void \fBaddEntry\fP (\fBPattern\fP new_in_pat, \fBPattern\fP new_out_pat)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "double \fBcompareOutput\fP (const \fBSequence\fP &seq) const "
.br
.ti -1c
.RI "double \fBcompareInput\fP (const \fBSequence\fP &seq) const "
.br
.ti -1c
.RI "double \fBcompare\fP (const \fBSequence\fP &seq) const "
.br
.ti -1c
.RI "double \fBcompare\fP (int id, const \fBPattern\fP &pat) const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSequence\fP &obj) const "
.br
.ti -1c
.RI "bool \fBisAllZeroes\fP () const "
.br
.ti -1c
.RI "bool \fBisInputAllZeroes\fP () const "
.br
.ti -1c
.RI "bool \fBisOutputAllZeroes\fP () const "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBINPUT_TAG\fP = '<input>'"
.br
.ti -1c
.RI "static const std::string \fBOUTPUT_TAG\fP = '<output>'"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.ti -1c
.RI "void \fBinitialise\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::list< std::pair< \fBPattern\fP, 
.br
\fBPattern\fP > > \fBpatterns\fP"
.br
.ti -1c
.RI "std::list< std::pair< \fBPattern\fP, 
.br
\fBPattern\fP > >::const_iterator \fBit_patterns\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBSequence\fP &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file Sequence\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::state::Sequence::Sequence\fP ()"
.PP
Definition at line 17 of file Sequence\&.cpp\&.
.PP
References initialise()\&.
.SS "\fBcryomesh::state::Sequence::~Sequence\fP ()\fC [virtual]\fP"
.PP
Definition at line 20 of file Sequence\&.cpp\&.
.SS "\fBcryomesh::state::Sequence::Sequence\fP (const \fBSequence\fP &seq)"
.PP
Definition at line 22 of file Sequence\&.cpp\&.
.PP
References initialise()\&.
.SS "\fBcryomesh::state::Sequence::Sequence\fP (const std::vector< \fBPattern\fP > &input_pats, const std::vector< \fBPattern\fP > &output_pats)"
.PP
Definition at line 25 of file Sequence\&.cpp\&.
.PP
References initialise(), and patterns\&.
.SS "\fBcryomesh::state::Sequence::Sequence\fP (std::ifstream &ifs)"
.PP
Definition at line 44 of file Sequence\&.cpp\&.
.PP
References initialise(), and loadFromFile()\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBcryomesh::state::Sequence::addEntry\fP (\fBPattern\fPnew_in_pat, \fBPattern\fPnew_out_pat)"
.PP
Definition at line 150 of file Sequence\&.cpp\&.
.PP
References patterns\&.
.SS "void \fBcryomesh::state::Sequence::clear\fP ()"
.PP
Definition at line 156 of file Sequence\&.cpp\&.
.PP
References it_patterns, and patterns\&.
.SS "double \fBcryomesh::state::Sequence::compare\fP (const \fBSequence\fP &seq) const"
.PP
Definition at line 253 of file Sequence\&.cpp\&.
.PP
References getPatterns()\&.
.SS "double \fBcryomesh::state::Sequence::compare\fP (intid, const \fBPattern\fP &pat) const"
.PP
Definition at line 331 of file Sequence\&.cpp\&.
.PP
References getPatterns()\&.
.SS "double \fBcryomesh::state::Sequence::compareInput\fP (const \fBSequence\fP &seq) const"
.PP
Definition at line 209 of file Sequence\&.cpp\&.
.PP
References getPatterns()\&.
.SS "double \fBcryomesh::state::Sequence::compareOutput\fP (const \fBSequence\fP &seq) const"
.PP
Definition at line 163 of file Sequence\&.cpp\&.
.PP
References getPatterns()\&.
.SS "const \fBPattern\fP & \fBcryomesh::state::Sequence::getAndAdvanceCurrentInputPattern\fP ()"
.PP
Definition at line 62 of file Sequence\&.cpp\&.
.PP
References getCurrentIterator(), and it_patterns\&.
.SS "const \fBPattern\fP & \fBcryomesh::state::Sequence::getAndAdvanceCurrentOutputPattern\fP ()"
.PP
Definition at line 70 of file Sequence\&.cpp\&.
.PP
References getCurrentIterator(), and it_patterns\&.
.SS "const \fBPattern\fP & \fBcryomesh::state::Sequence::getCurrentInputPattern\fP () const"
.PP
Definition at line 59 of file Sequence\&.cpp\&.
.PP
References getCurrentIterator()\&.
.PP
Referenced by getNextInputPattern()\&.
.SS "int \fBcryomesh::state::Sequence::getCurrentInputPatternId\fP () const"
.PP
Definition at line 75 of file Sequence\&.cpp\&.
.PP
References getCurrentIterator()\&.
.SS "std::list< std::pair< \fBPattern\fP, \fBPattern\fP > >::const_iterator \fBcryomesh::state::Sequence::getCurrentIterator\fP () const"
.PP
Definition at line 83 of file Sequence\&.cpp\&.
.PP
References it_patterns\&.
.PP
Referenced by getAndAdvanceCurrentInputPattern(), getAndAdvanceCurrentOutputPattern(), getCurrentInputPattern(), getCurrentInputPatternId(), getCurrentOutputPattern(), getCurrentOutputPatternId(), and getNextInputPattern()\&.
.SS "const \fBPattern\fP & \fBcryomesh::state::Sequence::getCurrentOutputPattern\fP () const"
.PP
Definition at line 67 of file Sequence\&.cpp\&.
.PP
References getCurrentIterator()\&.
.SS "int \fBcryomesh::state::Sequence::getCurrentOutputPatternId\fP () const"
.PP
Definition at line 79 of file Sequence\&.cpp\&.
.PP
References getCurrentIterator()\&.
.SS "const \fBPattern\fP & \fBcryomesh::state::Sequence::getNextInputPattern\fP ()"
.PP
Definition at line 86 of file Sequence\&.cpp\&.
.PP
References getCurrentInputPattern(), getCurrentIterator(), getPatterns(), it_patterns, patterns, and setCurrentIterator()\&.
.SS "const std::list< std::pair< \fBPattern\fP, \fBPattern\fP > > & \fBcryomesh::state::Sequence::getPatterns\fP () const"
.PP
Definition at line 93 of file Sequence\&.cpp\&.
.PP
References patterns\&.
.PP
Referenced by compare(), compareInput(), compareOutput(), getNextInputPattern(), cryomesh::state::operator<<(), operator=(), operator==(), and saveToFile()\&.
.SS "void \fBcryomesh::state::Sequence::initialise\fP ()\fC [private]\fP"
.PP
Definition at line 437 of file Sequence\&.cpp\&.
.PP
References it_patterns, and patterns\&.
.PP
Referenced by loadFromFile(), operator=(), Sequence(), and setPatterns()\&.
.SS "bool \fBcryomesh::state::Sequence::isAllZeroes\fP () const"
.PP
Definition at line 392 of file Sequence\&.cpp\&.
.PP
References it_patterns, and patterns\&.
.SS "bool \fBcryomesh::state::Sequence::isInputAllZeroes\fP () const"
.PP
Definition at line 407 of file Sequence\&.cpp\&.
.PP
References it_patterns, and patterns\&.
.SS "bool \fBcryomesh::state::Sequence::isOutputAllZeroes\fP () const"
.PP
Definition at line 422 of file Sequence\&.cpp\&.
.PP
References it_patterns, and patterns\&.
.SS "void \fBcryomesh::state::Sequence::loadFromFile\fP (std::ifstream &ifs)"
.PP
Definition at line 116 of file Sequence\&.cpp\&.
.PP
References initialise(), and patterns\&.
.PP
Referenced by Sequence()\&.
.SS "\fBSequence\fP & cryomesh::state::Sequence::operator= (const \fBSequence\fP &seq)"
.PP
Definition at line 50 of file Sequence\&.cpp\&.
.PP
References getPatterns(), initialise(), and patterns\&.
.SS "bool cryomesh::state::Sequence::operator== (const \fBSequence\fP &obj) const"
.PP
Definition at line 349 of file Sequence\&.cpp\&.
.PP
References getPatterns()\&.
.SS "void \fBcryomesh::state::Sequence::saveToFile\fP (std::ofstream &ofs) const"
.PP
Definition at line 100 of file Sequence\&.cpp\&.
.PP
References getPatterns()\&.
.SS "template<class Archive > void \fBcryomesh::state::Sequence::serialize\fP (Archive &ar, const unsigned intversion)\fC [inline, private]\fP"
.PP
Definition at line 29 of file Sequence\&.h\&.
.PP
References patterns\&.
.SS "void \fBcryomesh::state::Sequence::setCurrentIterator\fP (std::list< std::pair< \fBPattern\fP, \fBPattern\fP > >::const_iteratorit)"
.PP
Definition at line 447 of file Sequence\&.cpp\&.
.PP
References it_patterns\&.
.PP
Referenced by getNextInputPattern()\&.
.SS "void \fBcryomesh::state::Sequence::setPatterns\fP (const std::list< std::pair< \fBPattern\fP, \fBPattern\fP > > &pats)"
.PP
Definition at line 96 of file Sequence\&.cpp\&.
.PP
References initialise(), and patterns\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class boost::serialization::access\fC [friend]\fP"
.PP
Definition at line 27 of file Sequence\&.h\&.
.SS "std::ostream& operator<< (std::ostream &os, const \fBSequence\fP &obj)\fC [friend]\fP"
.PP
Definition at line 380 of file Sequence\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::string \fBcryomesh::state::Sequence::INPUT_TAG\fP = '<input>'\fC [static]\fP"
.PP
Definition at line 122 of file Sequence\&.h\&.
.SS "std::list<std::pair<\fBPattern\fP, \fBPattern\fP> >::const_iterator \fBcryomesh::state::Sequence::it_patterns\fP\fC [private]\fP"
.PP
Definition at line 134 of file Sequence\&.h\&.
.PP
Referenced by clear(), getAndAdvanceCurrentInputPattern(), getAndAdvanceCurrentOutputPattern(), getCurrentIterator(), getNextInputPattern(), initialise(), isAllZeroes(), isInputAllZeroes(), isOutputAllZeroes(), and setCurrentIterator()\&.
.SS "const std::string \fBcryomesh::state::Sequence::OUTPUT_TAG\fP = '<output>'\fC [static]\fP"
.PP
Definition at line 123 of file Sequence\&.h\&.
.SS "std::list<std::pair<\fBPattern\fP, \fBPattern\fP> > \fBcryomesh::state::Sequence::patterns\fP\fC [private]\fP"
.PP
Definition at line 130 of file Sequence\&.h\&.
.PP
Referenced by addEntry(), clear(), getNextInputPattern(), getPatterns(), initialise(), isAllZeroes(), isInputAllZeroes(), isOutputAllZeroes(), loadFromFile(), operator=(), Sequence(), serialize(), and setPatterns()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
