.TH "cryomesh::state::PatternTag" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::state::PatternTag \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PatternTag.h>\fP
.PP
Inherited by \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBgetTag\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetTag\fP (std::string tg)=0"
.br
.ti -1c
.RI "virtual std::string \fBmoveTag\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBmoveTag\fP (int i)=0"
.br
.ti -1c
.RI "virtual std::string \fBgetStartTag\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetStartTag\fP (std::string tg)=0"
.br
.ti -1c
.RI "virtual std::string \fBgetEndTag\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetEndTag\fP (std::string tg)=0"
.br
.ti -1c
.RI "virtual boost::shared_ptr< \fBPatternTag\fP > \fBgetGlobalTag\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file PatternTag.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string cryomesh::state::PatternTag::getEndTag () const\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual boost::shared_ptr<\fBPatternTag\fP> cryomesh::state::PatternTag::getGlobalTag ()\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual std::string cryomesh::state::PatternTag::getStartTag () const\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual std::string cryomesh::state::PatternTag::getTag () const\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual std::string cryomesh::state::PatternTag::moveTag (inti)\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual std::string cryomesh::state::PatternTag::moveTag ()\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual void cryomesh::state::PatternTag::setEndTag (std::stringtg)\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual void cryomesh::state::PatternTag::setStartTag (std::stringtg)\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.
.SS "virtual void cryomesh::state::PatternTag::setTag (std::stringtg)\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::state::PatternTagByDate\fP, and \fBcryomesh::state::PatternTagById\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
