.TH "cryomesh::components::NodeMap" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::NodeMap \- 
.PP
Helper class for \fBNodeMap\fP to KeyMappedCollection mapping.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NodeMap.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeMap\fP ()"
.br
.RI "\fIDefault constructor. \fP"
.ti -1c
.RI "virtual \fB~NodeMap\fP ()"
.br
.RI "\fIDefault destructor. \fP"
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.RI "\fIUpdate all entries in the nodemap. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBNodeMap\fP &obj)"
.br
.RI "\fITo stream operator. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Helper class for \fBNodeMap\fP to KeyMappedCollection mapping. 
.PP
Definition at line 23 of file NodeMap.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::components::NodeMap::NodeMap ()\fC [inline]\fP"
.PP
Default constructor. 
.PP
Definition at line 28 of file NodeMap.h.
.SS "virtual cryomesh::components::NodeMap::~NodeMap ()\fC [inline, virtual]\fP"
.PP
Default destructor. 
.PP
Definition at line 34 of file NodeMap.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual void cryomesh::components::NodeMap::update ()\fC [inline, virtual]\fP"
.PP
Update all entries in the nodemap. 
.PP
Definition at line 40 of file NodeMap.h.
.PP
Referenced by cryomesh::structures::Cluster::update().
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBNodeMap\fP &obj)\fC [friend]\fP"
.PP
To stream operator. \fBParameters:\fP
.RS 4
\fIstd::ostream\fP & os The output stream 
.br
\fIconst\fP \fBNodeMap\fP & obj The object to stream
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream & The output stream 
.RE
.PP

.PP
Definition at line 65 of file NodeMap.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
