.TH "cryomesh::structures::FibreMap" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::structures::FibreMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FibreMap.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFibreMap\fP ()"
.br
.ti -1c
.RI "virtual \fB~FibreMap\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBFibreMap\fP &objs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file FibreMap.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::structures::FibreMap::FibreMap ()\fC [inline]\fP"
.PP
Definition at line 20 of file FibreMap.h.
.SS "virtual cryomesh::structures::FibreMap::~FibreMap ()\fC [inline, virtual]\fP"
.PP
Definition at line 22 of file FibreMap.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual void cryomesh::structures::FibreMap::update ()\fC [inline, virtual]\fP"
.PP
Definition at line 24 of file FibreMap.h.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBFibreMap\fP &objs)\fC [friend]\fP"
.PP
Definition at line 40 of file FibreMap.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
