cryomesh::spacial::Point
NAME
cryomesh::spacial::Point -
SYNOPSIS
#include <Point.h>
Public Member Functions
Point ()
Point (double new_x, double new_y, double new_z)
Point (const Point &sp)
Point (const SphericalPoint &sp)
virtual ~Point ()
double getDistance (const Point &start) const
void setToMinimumDistances (double min)
double getX () const
double getY () const
double getZ () const
Point getNormalisedVector () const
bool equals (const Point &obj) const
bool operator== (const Point &obj) const
Point & operator= (const Point &obj)
Point operator+ (const Point &obj) const
Point operator- (const Point &obj) const
Point operator* (double d) const
Private Attributes
double x
double y
double z
Friends
std::ostream & operator<< (std::ostream &os, const Point &obj)
Detailed Description
Definition at line 19 of file Point.h.
Constructor & Destructor Documentation
cryomesh::spacial::Point::Point ()
Definition at line 18 of file Point.cpp.
cryomesh::spacial::Point::Point (doublenew_x, doublenew_y, doublenew_z)
Definition at line 22 of file Point.cpp.
cryomesh::spacial::Point::Point (const Point &sp)
Definition at line 26 of file Point.cpp.
cryomesh::spacial::Point::Point (const SphericalPoint &sp)
Definition at line 29 of file Point.cpp.
cryomesh::spacial::Point::~Point () [virtual]
Definition at line 34 of file Point.cpp.
References getX(), and x.
Member Function Documentation
bool cryomesh::spacial::Point::equals (const Point &obj) const
Definition at line 73 of file Point.cpp.
double cryomesh::spacial::Point::getDistance (const Point &start) const
Definition at line 36 of file Point.cpp.
Referenced by cryomesh::components::Connection::updatePosition().
Point cryomesh::spacial::Point::getNormalisedVector () const
Definition at line 65 of file Point.cpp.
double cryomesh::spacial::Point::getX () const
Definition at line 55 of file Point.cpp.
Referenced by cryomesh::components::Node::getRandom(), cryomesh::spacial::SphericalPoint::SphericalPoint(), and ~Point().
double cryomesh::spacial::Point::getY () const
Definition at line 58 of file Point.cpp.
Referenced by cryomesh::components::Node::getRandom(), and cryomesh::spacial::SphericalPoint::SphericalPoint().
double cryomesh::spacial::Point::getZ () const
Definition at line 61 of file Point.cpp.
Referenced by cryomesh::components::Node::getRandom(), and cryomesh::spacial::SphericalPoint::SphericalPoint().
Point cryomesh::spacial::Point::operator* (doubled) const
Definition at line 100 of file Point.cpp.
Point cryomesh::spacial::Point::operator+ (const Point &obj) const
Definition at line 92 of file Point.cpp.
Point cryomesh::spacial::Point::operator- (const Point &obj) const
Definition at line 96 of file Point.cpp.
Point & cryomesh::spacial::Point::operator= (const Point &obj)
Definition at line 84 of file Point.cpp.
bool cryomesh::spacial::Point::operator== (const Point &obj) const
Definition at line 80 of file Point.cpp.
void cryomesh::spacial::Point::setToMinimumDistances (doublemin)
Definition at line 44 of file Point.cpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Point &obj) [friend]
Definition at line 104 of file Point.cpp.
Member Data Documentation
double cryomesh::spacial::Point::x [private]
Definition at line 47 of file Point.h.
Referenced by ~Point().
double cryomesh::spacial::Point::y [private]
Definition at line 48 of file Point.h.
double cryomesh::spacial::Point::z [private]
Definition at line 49 of file Point.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.