cryomesh::manipulators::ClusterAnalysisData
NAME
cryomesh::manipulators::ClusterAnalysisData -
SYNOPSIS
#include <ClusterAnalysisData.h>
Classes
struct RangeEnergy
Struct representing the value extrapolated over a history range.
Public Member Functions
ClusterAnalysisData ()
ClusterAnalysisData (RangeEnergy cre)
ClusterAnalysisData (RangeEnergy clusterRangeEnergy, double node_creation_weight, double node_destruction_weight, double conn_creation_weight, double conn_destruction_weight, int node_create, int nodes_destroy, int conn_create, int conn_destroy)
ClusterAnalysisData (const ClusterAnalysisData &obj)
virtual ~ClusterAnalysisData ()
RangeEnergy getClusterRangeEnergy () const
double getNodeCreationWeight () const
double getNodeDestructionWeight () const
double getConnectionCreationWeight () const
double getConnectionDestructionWeight () const
int getNodesToDestroy () const
int getConnectionsToDestroy () const
int getNodesToCreate () const
int getConnectionsToCreate () const
void setClusterRangeEnergy (RangeEnergy clusterEnergy)
void setConnectionCreationWeight (double connectionCreationWeight)
void setConnectionDestructionWeight (double connectionDestructionWeight)
void setConnectionsToCreate (int connectionsToCreate)
void setConnectionsToDestroy (int connectionsToDestroy)
void setNodeCreationWeight (double nodeCreationWeight)
void setNodeDestructionWeight (double nodeDestructionWeight)
void setNodesToCreate (int nodesToCreate)
void setNodesToDestroy (int nodesToDestroy)
Private Attributes
RangeEnergy clusterRangeEnergy
double nodeCreationWeight
double nodeDestructionWeight
double connectionCreationWeight
double connectionDestructionWeight
int nodesToCreate
int nodesToDestroy
int connectionsToCreate
int connectionsToDestroy
Friends
std::ostream & operator<< (std::ostream &os, const ClusterAnalysisData &obj)
To stream operator.
Detailed Description
Definition at line 18 of file ClusterAnalysisData.h.
Constructor & Destructor Documentation
cryomesh::manipulators::ClusterAnalysisData::ClusterAnalysisData ()
Definition at line 13 of file ClusterAnalysisData.cpp.
cryomesh::manipulators::ClusterAnalysisData::ClusterAnalysisData (RangeEnergycre)
Definition at line 17 of file ClusterAnalysisData.cpp.
cryomesh::manipulators::ClusterAnalysisData::ClusterAnalysisData (RangeEnergyclusterRangeEnergy, doublenode_creation_weight, doublenode_destruction_weight, doubleconn_creation_weight, doubleconn_destruction_weight, intnode_create, intnodes_destroy, intconn_create, intconn_destroy)
Definition at line 22 of file ClusterAnalysisData.cpp.
cryomesh::manipulators::ClusterAnalysisData::ClusterAnalysisData (const ClusterAnalysisData &obj)
Definition at line 31 of file ClusterAnalysisData.cpp.
cryomesh::manipulators::ClusterAnalysisData::~ClusterAnalysisData () [virtual]
Definition at line 38 of file ClusterAnalysisData.cpp.
Member Function Documentation
ClusterAnalysisData::RangeEnergy cryomesh::manipulators::ClusterAnalysisData::getClusterRangeEnergy () const
Definition at line 41 of file ClusterAnalysisData.cpp.
References clusterRangeEnergy.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster(), and cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies().
double cryomesh::manipulators::ClusterAnalysisData::getConnectionCreationWeight () const
Definition at line 50 of file ClusterAnalysisData.cpp.
References connectionCreationWeight.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies().
double cryomesh::manipulators::ClusterAnalysisData::getConnectionDestructionWeight () const
Definition at line 53 of file ClusterAnalysisData.cpp.
References connectionDestructionWeight.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies().
int cryomesh::manipulators::ClusterAnalysisData::getConnectionsToCreate () const
Definition at line 66 of file ClusterAnalysisData.cpp.
References connectionsToCreate.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies(), and cryomesh::manipulators::ClusterArchitect::runAnalysis().
int cryomesh::manipulators::ClusterAnalysisData::getConnectionsToDestroy () const
Definition at line 60 of file ClusterAnalysisData.cpp.
References connectionsToDestroy.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies(), and cryomesh::manipulators::ClusterArchitect::runAnalysis().
double cryomesh::manipulators::ClusterAnalysisData::getNodeCreationWeight () const
Definition at line 44 of file ClusterAnalysisData.cpp.
References nodeCreationWeight.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies().
double cryomesh::manipulators::ClusterAnalysisData::getNodeDestructionWeight () const
Definition at line 47 of file ClusterAnalysisData.cpp.
References nodeDestructionWeight.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies().
int cryomesh::manipulators::ClusterAnalysisData::getNodesToCreate () const
Definition at line 63 of file ClusterAnalysisData.cpp.
References nodesToCreate.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies(), and cryomesh::manipulators::ClusterArchitect::runAnalysis().
int cryomesh::manipulators::ClusterAnalysisData::getNodesToDestroy () const
Definition at line 57 of file ClusterAnalysisData.cpp.
References nodesToDestroy.
Referenced by cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies(), and cryomesh::manipulators::ClusterArchitect::runAnalysis().
void cryomesh::manipulators::ClusterAnalysisData::setClusterRangeEnergy (RangeEnergyclusterEnergy)
Definition at line 70 of file ClusterAnalysisData.cpp.
References clusterRangeEnergy.
void cryomesh::manipulators::ClusterAnalysisData::setConnectionCreationWeight (doubleconnectionCreationWeight)
Definition at line 74 of file ClusterAnalysisData.cpp.
References connectionCreationWeight.
void cryomesh::manipulators::ClusterAnalysisData::setConnectionDestructionWeight (doubleconnectionDestructionWeight)
Definition at line 78 of file ClusterAnalysisData.cpp.
References connectionDestructionWeight.
void cryomesh::manipulators::ClusterAnalysisData::setConnectionsToCreate (intconnectionsToCreate)
Definition at line 82 of file ClusterAnalysisData.cpp.
References connectionsToCreate.
void cryomesh::manipulators::ClusterAnalysisData::setConnectionsToDestroy (intconnectionsToDestroy)
Definition at line 86 of file ClusterAnalysisData.cpp.
References connectionsToDestroy.
void cryomesh::manipulators::ClusterAnalysisData::setNodeCreationWeight (doublenodeCreationWeight)
Definition at line 90 of file ClusterAnalysisData.cpp.
References nodeCreationWeight.
void cryomesh::manipulators::ClusterAnalysisData::setNodeDestructionWeight (doublenodeDestructionWeight)
Definition at line 94 of file ClusterAnalysisData.cpp.
References nodeDestructionWeight.
void cryomesh::manipulators::ClusterAnalysisData::setNodesToCreate (intnodesToCreate)
Definition at line 98 of file ClusterAnalysisData.cpp.
References nodesToCreate.
void cryomesh::manipulators::ClusterAnalysisData::setNodesToDestroy (intnodesToDestroy)
Definition at line 102 of file ClusterAnalysisData.cpp.
References nodesToDestroy.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const ClusterAnalysisData &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const ClusterAnalysisData & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 147 of file ClusterAnalysisData.h.
Member Data Documentation
RangeEnergy cryomesh::manipulators::ClusterAnalysisData::clusterRangeEnergy [private]
Definition at line 157 of file ClusterAnalysisData.h.
Referenced by getClusterRangeEnergy(), and setClusterRangeEnergy().
double cryomesh::manipulators::ClusterAnalysisData::connectionCreationWeight [private]
Definition at line 175 of file ClusterAnalysisData.h.
Referenced by getConnectionCreationWeight(), and setConnectionCreationWeight().
double cryomesh::manipulators::ClusterAnalysisData::connectionDestructionWeight [private]
Definition at line 181 of file ClusterAnalysisData.h.
Referenced by getConnectionDestructionWeight(), and setConnectionDestructionWeight().
int cryomesh::manipulators::ClusterAnalysisData::connectionsToCreate [private]
Definition at line 185 of file ClusterAnalysisData.h.
Referenced by getConnectionsToCreate(), and setConnectionsToCreate().
int cryomesh::manipulators::ClusterAnalysisData::connectionsToDestroy [private]
Definition at line 186 of file ClusterAnalysisData.h.
Referenced by getConnectionsToDestroy(), and setConnectionsToDestroy().
double cryomesh::manipulators::ClusterAnalysisData::nodeCreationWeight [private]
Definition at line 163 of file ClusterAnalysisData.h.
Referenced by getNodeCreationWeight(), and setNodeCreationWeight().
double cryomesh::manipulators::ClusterAnalysisData::nodeDestructionWeight [private]
Definition at line 169 of file ClusterAnalysisData.h.
Referenced by getNodeDestructionWeight(), and setNodeDestructionWeight().
int cryomesh::manipulators::ClusterAnalysisData::nodesToCreate [private]
Definition at line 183 of file ClusterAnalysisData.h.
Referenced by getNodesToCreate(), and setNodesToCreate().
int cryomesh::manipulators::ClusterAnalysisData::nodesToDestroy [private]
Definition at line 184 of file ClusterAnalysisData.h.
Referenced by getNodesToDestroy(), and setNodesToDestroy().
Author
Generated automatically by Doxygen for cryomesh from the source code.