.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/manager/CryoManager.h" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/manager/CryoManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'Creator\&.h'\fP
.br
\fC#include 'common/TimeKeeper\&.h'\fP
.br
\fC#include 'PatternDatabaseObject\&.h'\fP
.br
\fC#include 'DatabaseManager\&.h'\fP
.br
\fC#include <boost/uuid/uuid_io\&.hpp>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCRYOMANAGER_DEBUG\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBCRYOMANAGER_DEBUG\fP"
.PP
Definition at line 8 of file CryoManager\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
