.TH "cryomesh::state::PatternTagById" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::state::PatternTagById \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PatternTagById\&.h>\fP
.PP
Inherits \fBcryomesh::state::PatternTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPatternTagById\fP (int d)"
.br
.ti -1c
.RI "virtual \fB~PatternTagById\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBgetTag\fP () const "
.br
.ti -1c
.RI "virtual void \fBsetTag\fP (std::string tg)"
.br
.ti -1c
.RI "virtual std::string \fBmoveTag\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBmoveTag\fP (int i)"
.br
.ti -1c
.RI "virtual std::string \fBgetStartTag\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBgetEndTag\fP () const "
.br
.ti -1c
.RI "virtual void \fBsetStartTag\fP (std::string tg)"
.br
.ti -1c
.RI "virtual void \fBsetEndTag\fP (std::string tg)"
.br
.ti -1c
.RI "virtual boost::shared_ptr
.br
< \fBPatternTag\fP > \fBgetGlobalTag\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBid\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static boost::shared_ptr
.br
< \fBPatternTagById\fP > \fBglobalTag\fP = boost::shared_ptr<\fBPatternTagById\fP>(new \fBPatternTagById\fP(1))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file PatternTagById\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::state::PatternTagById::PatternTagById\fP (intd)"
.PP
Definition at line 15 of file PatternTagById\&.cpp\&.
.SS "\fBcryomesh::state::PatternTagById::~PatternTagById\fP ()\fC [virtual]\fP"
.PP
Definition at line 21 of file PatternTagById\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string \fBcryomesh::state::PatternTagById::getEndTag\fP () const\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 43 of file PatternTagById\&.cpp\&.
.PP
References cryomesh::state::Pattern::getIds()\&.
.PP
Referenced by setEndTag()\&.
.SS "boost::shared_ptr< \fBPatternTag\fP > \fBcryomesh::state::PatternTagById::getGlobalTag\fP ()\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 56 of file PatternTagById\&.cpp\&.
.PP
References globalTag\&.
.SS "std::string \fBcryomesh::state::PatternTagById::getStartTag\fP () const\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 40 of file PatternTagById\&.cpp\&.
.PP
Referenced by setStartTag()\&.
.SS "std::string \fBcryomesh::state::PatternTagById::getTag\fP () const\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 23 of file PatternTagById\&.cpp\&.
.PP
References id\&.
.PP
Referenced by moveTag()\&.
.SS "std::string \fBcryomesh::state::PatternTagById::moveTag\fP ()\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 29 of file PatternTagById\&.cpp\&.
.SS "std::string \fBcryomesh::state::PatternTagById::moveTag\fP (inti)\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 32 of file PatternTagById\&.cpp\&.
.PP
References getTag()\&.
.SS "void \fBcryomesh::state::PatternTagById::setEndTag\fP (std::stringtg)\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 53 of file PatternTagById\&.cpp\&.
.PP
References getEndTag()\&.
.SS "void \fBcryomesh::state::PatternTagById::setStartTag\fP (std::stringtg)\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 50 of file PatternTagById\&.cpp\&.
.PP
References getStartTag()\&.
.SS "void \fBcryomesh::state::PatternTagById::setTag\fP (std::stringtg)\fC [virtual]\fP"
.PP
Implements \fBcryomesh::state::PatternTag\fP\&.
.PP
Definition at line 26 of file PatternTagById\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "boost::shared_ptr< \fBPatternTagById\fP > \fBcryomesh::state::PatternTagById::globalTag\fP = boost::shared_ptr<\fBPatternTagById\fP>(new \fBPatternTagById\fP(1))\fC [static, private]\fP"
.PP
Definition at line 29 of file PatternTagById\&.h\&.
.PP
Referenced by getGlobalTag()\&.
.SS "std::string \fBcryomesh::state::PatternTagById::id\fP\fC [private]\fP"
.PP
Definition at line 30 of file PatternTagById\&.h\&.
.PP
Referenced by getTag()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
