.TH "cryomesh::components::ActivityTimer" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::ActivityTimer \- 
.PP
Simple interface class for activity timers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ActivityTimer\&.h>\fP
.PP
Inherited by \fBcryomesh::components::ActivityTimerDistance\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActivityTimer\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "virtual \fB~ActivityTimer\fP ()"
.br
.RI "\fIDefault destructor\&. \fP"
.ti -1c
.RI "virtual void \fBreset\fP ()=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual std::ostream & \fBprint\fP (std::ostream &os) const =0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBActivityTimer\fP &obj)"
.br
.RI "\fITo stream operator\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Simple interface class for activity timers\&. 
.PP
Definition at line 20 of file ActivityTimer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::components::ActivityTimer::ActivityTimer\fP ()\fC [inline]\fP"
.PP
Default constructor\&. 
.PP
Definition at line 25 of file ActivityTimer\&.h\&.
.SS "virtual \fBcryomesh::components::ActivityTimer::~ActivityTimer\fP ()\fC [inline, virtual]\fP"
.PP
Default destructor\&. 
.PP
Definition at line 31 of file ActivityTimer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::ostream& \fBcryomesh::components::ActivityTimer::print\fP (std::ostream &os) const\fC [protected, pure virtual]\fP"
.PP
Implemented in \fBcryomesh::components::ActivityTimerDistance\fP\&.
.SS "virtual void \fBcryomesh::components::ActivityTimer::reset\fP ()\fC [pure virtual]\fP"
.PP
Implemented in \fBcryomesh::components::ActivityTimerDistance\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBActivityTimer\fP &obj)\fC [friend]\fP"
.PP
To stream operator\&. \fBParameters:\fP
.RS 4
\fIstd::ostream\fP & os The output stream 
.br
\fIconst\fP \fBActivityTimer\fP & obj The object to stream
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream & The output stream 
.RE
.PP

.PP
Definition at line 47 of file ActivityTimer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
