cryomesh::state::PatternTagByDate
NAME
cryomesh::state::PatternTagByDate -
SYNOPSIS
#include <PatternTagByDate.h>
Inherits cryomesh::state::PatternTag.
Public Types
enum DateType { ByHour, ByDay, ByWeek, ByMonth, ByYear }
Public Member Functions
template<class Archive > void serialize (Archive &ar, const unsigned int version)
PatternTagByDate (DateType dt)
PatternTagByDate (DateType dt, std::tm start_time, std::tm end_time, std::tm current_time)
virtual ~PatternTagByDate ()
virtual std::string getTag () const
virtual void setTag (std::string tg)
virtual std::string moveTag ()
virtual std::string moveTag (int i)
virtual std::string getStartTag () const
virtual void setStartTag (std::string tg)
virtual std::string getEndTag () const
virtual void setEndTag (std::string tg)
virtual boost::shared_ptr
< PatternTag > getGlobalTag ()"
Static Public Member Functions
static std::tm tagToTm (const std::string &tg)
static std::string tmToTag (const std::tm &t)
static std::tm moveHour (std::tm &ttime, int i)
static std::tm moveDay (std::tm &ttime, int i)
static std::tm moveWeek (std::tm &ttime, int i)
static std::tm moveMonth (std::tm &ttime, int i)
static std::tm moveYear (std::tm &ttime, int i)
static bool isLeapYear (const std::tm &tmtime)
Static Protected Attributes
static std::string GlobalStartTag = ''
static std::string GlobalEndTag = ''
static std::string GlobalCurrentTag = ''
static std::string DateFormat = '%S %M %H %d %m %Y %w %j '
Private Attributes
DateType dateType
std::tm startTime
std::tm endTime
std::tm currentTime
Static Private Attributes
static boost::shared_ptr
< PatternTagByDate > globalTag"
Friends
class boost::serialization::access
Detailed Description
Definition at line 20 of file PatternTagByDate.h.
Member Enumeration Documentation
enum cryomesh::state::PatternTagByDate::DateType
Enumerator:
ByHour
ByDay
ByWeek
ByMonth
ByYear
Definition at line 22 of file PatternTagByDate.h.
Constructor & Destructor Documentation
cryomesh::state::PatternTagByDate::PatternTagByDate (DateTypedt)
Definition at line 22 of file PatternTagByDate.cpp.
cryomesh::state::PatternTagByDate::PatternTagByDate (DateTypedt, std::tmstart_time, std::tmend_time, std::tmcurrent_time)
Definition at line 26 of file PatternTagByDate.cpp.
References GlobalEndTag, GlobalStartTag, globalTag, and startTime.
cryomesh::state::PatternTagByDate::~PatternTagByDate () [virtual]
Definition at line 34 of file PatternTagByDate.cpp.
Member Function Documentation
std::string cryomesh::state::PatternTagByDate::getEndTag () const [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 70 of file PatternTagByDate.cpp.
References endTime, and tmToTag().
boost::shared_ptr< PatternTag > cryomesh::state::PatternTagByDate::getGlobalTag () [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 77 of file PatternTagByDate.cpp.
References globalTag.
std::string cryomesh::state::PatternTagByDate::getStartTag () const [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 64 of file PatternTagByDate.cpp.
References startTime, and tmToTag().
std::string cryomesh::state::PatternTagByDate::getTag () const [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 37 of file PatternTagByDate.cpp.
References currentTime, and tmToTag().
bool cryomesh::state::PatternTagByDate::isLeapYear (const std::tm &tmtime) [static]
Definition at line 206 of file PatternTagByDate.cpp.
Referenced by moveMonth(), and moveYear().
std::tm cryomesh::state::PatternTagByDate::moveDay (std::tm &ttime, inti) [static]
Definition at line 151 of file PatternTagByDate.cpp.
References moveHour().
Referenced by moveMonth(), moveTag(), moveWeek(), and moveYear().
std::tm cryomesh::state::PatternTagByDate::moveHour (std::tm &ttime, inti) [static]
Definition at line 139 of file PatternTagByDate.cpp.
Referenced by moveDay(), and moveTag().
std::tm cryomesh::state::PatternTagByDate::moveMonth (std::tm &ttime, inti) [static]
Definition at line 161 of file PatternTagByDate.cpp.
References isLeapYear(), moveDay(), and moveYear().
Referenced by moveTag().
std::string cryomesh::state::PatternTagByDate::moveTag () [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 43 of file PatternTagByDate.cpp.
References ByDay, ByHour, ByMonth, ByWeek, ByYear, currentTime, dateType, moveDay(), moveHour(), moveMonth(), moveWeek(), moveYear(), and tmToTag().
Referenced by moveTag().
std::string cryomesh::state::PatternTagByDate::moveTag (inti) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 57 of file PatternTagByDate.cpp.
References currentTime, moveTag(), and tmToTag().
std::tm cryomesh::state::PatternTagByDate::moveWeek (std::tm &ttime, inti) [static]
Definition at line 156 of file PatternTagByDate.cpp.
References moveDay().
Referenced by moveTag().
std::tm cryomesh::state::PatternTagByDate::moveYear (std::tm &ttime, inti) [static]
Definition at line 193 of file PatternTagByDate.cpp.
References isLeapYear(), and moveDay().
Referenced by moveMonth(), and moveTag().
template<class Archive > void cryomesh::state::PatternTagByDate::serialize (Archive &ar, const unsigned intversion) [inline]
Definition at line 28 of file PatternTagByDate.h.
References currentTime, dateType, endTime, globalTag, and startTime.
void cryomesh::state::PatternTagByDate::setEndTag (std::stringtg) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 73 of file PatternTagByDate.cpp.
References endTime, and tagToTm().
void cryomesh::state::PatternTagByDate::setStartTag (std::stringtg) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 67 of file PatternTagByDate.cpp.
References startTime, and tagToTm().
void cryomesh::state::PatternTagByDate::setTag (std::stringtg) [virtual]
Implements cryomesh::state::PatternTag.
Definition at line 40 of file PatternTagByDate.cpp.
References currentTime, and tagToTm().
std::tm cryomesh::state::PatternTagByDate::tagToTm (const std::string &tg) [static]
Definition at line 81 of file PatternTagByDate.cpp.
Referenced by setEndTag(), setStartTag(), and setTag().
std::string cryomesh::state::PatternTagByDate::tmToTag (const std::tm &t) [static]
Definition at line 132 of file PatternTagByDate.cpp.
References DateFormat.
Referenced by getEndTag(), getStartTag(), getTag(), and moveTag().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 26 of file PatternTagByDate.h.
Member Data Documentation
std::tm cryomesh::state::PatternTagByDate::currentTime [private]
Definition at line 73 of file PatternTagByDate.h.
Referenced by getTag(), moveTag(), serialize(), and setTag().
std::string cryomesh::state::PatternTagByDate::DateFormat = '%S %M %H %d %m %Y %w %j ' [static, protected]
Definition at line 66 of file PatternTagByDate.h.
Referenced by tmToTag().
DateType cryomesh::state::PatternTagByDate::dateType [private]
Definition at line 70 of file PatternTagByDate.h.
Referenced by moveTag(), and serialize().
std::tm cryomesh::state::PatternTagByDate::endTime [private]
Definition at line 72 of file PatternTagByDate.h.
Referenced by getEndTag(), serialize(), and setEndTag().
std::string cryomesh::state::PatternTagByDate::GlobalCurrentTag = '' [static, protected]
Definition at line 65 of file PatternTagByDate.h.
std::string cryomesh::state::PatternTagByDate::GlobalEndTag = '' [static, protected]
Definition at line 64 of file PatternTagByDate.h.
Referenced by PatternTagByDate().
std::string cryomesh::state::PatternTagByDate::GlobalStartTag = '' [static, protected]
Definition at line 63 of file PatternTagByDate.h.
Referenced by PatternTagByDate().
boost::shared_ptr< PatternTagByDate > cryomesh::state::PatternTagByDate::globalTag [static, private]
Definition at line 69 of file PatternTagByDate.h.
Referenced by getGlobalTag(), PatternTagByDate(), and serialize().
std::tm cryomesh::state::PatternTagByDate::startTime [private]
Definition at line 71 of file PatternTagByDate.h.
Referenced by getStartTag(), PatternTagByDate(), serialize(), and setStartTag().
Author
Generated automatically by Doxygen for cryomesh from the source code.