cryomesh::structures::Fibre
NAME
cryomesh::structures::Fibre -
A Fibre is a collection of connections that connect one structure to another.
SYNOPSIS
#include <Fibre.h>
Public Types
enum ClusterConnectionType { NullCluster = 1, InputCluster = 2, OutputCluster = 4, LoopbackCluster = 8 }
Enum representing the relation of a cluster to this fibre.
enum FibreType { NullFibre, IntermediateFibre, PrimaryInputFibre, PrimaryOutputFibre, LoopbackFibre }
Enum representing the type of this Fibre connection.
Public Member Functions
Fibre (boost::shared_ptr< Cluster > inputCluster, boost::shared_ptr< Cluster > outputCluster, int width)
Construct a fibre between two clusters with width.
Fibre (boost::shared_ptr< Cluster > cluster, const FibreType &type, int width)
Construct a primary fibre with width.
virtual ~Fibre ()
Default destructor.
virtual void update ()
Update all elements.
void trigger (double percentage)
Trigger a random pattern with percentage of the connections to fire.
virtual void trigger ()
Send impulses to the connections based on a complete trigger of all of them.
virtual void trigger (const state::Pattern &pattern)
Send impulses to the connections based on a pattern.
virtual void trigger (std::vector< boost::shared_ptr< components::Impulse > > &triggerImpulses)
Send impulses to the connections.
const common::Connector< Fibre,
Cluster > & getConnector () const "
Get the connector.
common::Connector< Fibre,
Cluster > & getMutableConnector ()"
Get the mutable connector.
const components::ConnectionMap & getConnections () const
Get the connections.
components::ConnectionMap & getMutableConnections ()
Get the mutable connections.
const FibreType & getType () const
Get the type of the fibre.
const std::pair< int, int > countConnections (const std::map< boost::uuids::uuid, boost::shared_ptr< Cluster > > &all_clusters) const
Count all connections of this fibre to a group of clusters.
int isConnected (const boost::shared_ptr< Cluster > &cluster) const
Return type of connection to cluster specified, null if none.
unsigned int getWidth () const
Get width (number of connections) of fibre.
boost::shared_ptr< state::Pattern > getNodesPattern (const std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > all_nodes) const
Get current pattern for firing state of nodes.
boost::shared_ptr< state::Pattern > getInputNodesPattern () const
Get current pattern for firing state of input nodes to the fibre.
boost::shared_ptr< state::Pattern > getOutputNodesPattern () const
Get current pattern for firing state of output nodes to the fibre.
const std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Node > > getNodes (const ClusterConnectionType type) const "
Get the map of nodes to this fibre.
const std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Node > > getInputNodes () const "
Get the map of input nodes to this fibre.
const std::map
< boost::uuids::uuid,
boost::shared_ptr
< components::Node > > getOutputNodes () const "
Get the map of output nodes to this fibre.
void forceFireInputNodes (const state::Pattern &pattern)
Force fire input nodes using a pattern.
void forceFireOutputNodes (const state::Pattern &pattern)
Force fire output nodes using a pattern.
void forceFireNodes (const state::Pattern &pattern, std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > nodes)
Force fire nodes using a pattern.
virtual void enableDebug (bool b)
Protected Member Functions
virtual void setType (const FibreType &tp)
Set the type of this fibre.
virtual void createConnections (int number)
Reset and create a number of connections in this Fibre.
virtual void disconnectAllConnections ()
Disconnect all the connections from clusters.
virtual void connectAllConnections (boost::shared_ptr< Cluster > cluster, ClusterConnectionType type)
Connect all the connections in this Fibre to a cluster of a specified type.
Private Attributes
common::Connector< Fibre, Cluster > connector
components::ConnectionMap connections
FibreType fibreType
Friends
std::ostream & operator<< (std::ostream &os, const Fibre &obj)
Get the activity pattern of the Fibre, 0 for no activity, 1 otherwise.
Detailed Description
A Fibre is a collection of connections that connect one structure to another.
For example, two clusters.
Definition at line 27 of file Fibre.h.
Member Enumeration Documentation
enum cryomesh::structures::Fibre::ClusterConnectionType
Enum representing the relation of a cluster to this fibre.
Enumerator:
NullCluster
InputCluster
OutputCluster
LoopbackCluster
Definition at line 33 of file Fibre.h.
enum cryomesh::structures::Fibre::FibreType
Enum representing the type of this Fibre connection. The type of this Fibre.
Enumerator:
NullFibre
IntermediateFibre
PrimaryInputFibre
PrimaryOutputFibre
LoopbackFibre
Definition at line 42 of file Fibre.h.
Constructor & Destructor Documentation
cryomesh::structures::Fibre::Fibre (boost::shared_ptr< Cluster >inputCluster, boost::shared_ptr< Cluster >outputCluster, intwidth)
Construct a fibre between two clusters with width. Parameters:
boost::shared_ptr<Cluster> The input cluster to this Fibre
boost::shared_ptr<Cluster> The output cluster to this Fibre
int The width of the fibre connection to create
Definition at line 20 of file Fibre.cpp.
References connectAllConnections(), createConnections(), InputCluster, IntermediateFibre, LoopbackFibre, OutputCluster, and setType().
cryomesh::structures::Fibre::Fibre (boost::shared_ptr< Cluster >cluster, const FibreType &type, intwidth)
Construct a primary fibre with width. Parameters:
boost::shared_ptr<Cluster> cluster Cluster to connect to fibre
const FibreType & type Type of fibre connection to make
int width Width of fibre to create
Returns:
The new fibre created, possible null
Definition at line 32 of file Fibre.cpp.
References connectAllConnections(), createConnections(), getType(), InputCluster, OutputCluster, PrimaryInputFibre, PrimaryOutputFibre, and setType().
cryomesh::structures::Fibre::~Fibre () [virtual]
Default destructor.
Definition at line 42 of file Fibre.cpp.
References disconnectAllConnections().
Member Function Documentation
void cryomesh::structures::Fibre::connectAllConnections (boost::shared_ptr< Cluster >cluster, ClusterConnectionTypetype) [protected, virtual]
Connect all the connections in this Fibre to a cluster of a specified type. Parameters:
boost::shared_ptr<Cluster> cluster The cluster to connect to
ClusterConnectionType type The type of cluster we're connecting to
Definition at line 260 of file Fibre.cpp.
References cryomesh::common::Connector< U, T >::connectInput(), connections, connector, cryomesh::common::Connector< U, T >::connectOutput(), InputCluster, and OutputCluster.
Referenced by Fibre().
const std::pair< int, int > cryomesh::structures::Fibre::countConnections (const std::map< boost::uuids::uuid, boost::shared_ptr< Cluster > > &all_clusters) const
Count all connections of this fibre to a group of clusters. Parameters:
std::map<boost::uuids::uuid,boost::shared_ptr<Cluster> > Cluster collection to search for connections to this fibre
Returns:
std::pair<int, int> Pair of input/output connection count to this fibre within the supplied cluster collection
Definition at line 148 of file Fibre.cpp.
References getConnector(), cryomesh::common::Connector< U, T >::getInputs(), and cryomesh::common::Connector< U, T >::getOutputs().
void cryomesh::structures::Fibre::createConnections (intnumber) [protected, virtual]
Reset and create a number of connections in this Fibre. Parameters:
int number Number of connections to create
Definition at line 230 of file Fibre.cpp.
References connections, and disconnectAllConnections().
Referenced by Fibre().
void cryomesh::structures::Fibre::disconnectAllConnections () [protected, virtual]
Disconnect all the connections from clusters.
Definition at line 242 of file Fibre.cpp.
References connections, connector, cryomesh::common::Connector< U, T >::disconnectAllInputs(), and cryomesh::common::Connector< U, T >::disconnectAllOutputs().
Referenced by createConnections(), and ~Fibre().
void cryomesh::structures::Fibre::enableDebug (boolb) [virtual]
Definition at line 445 of file Fibre.cpp.
void cryomesh::structures::Fibre::forceFireInputNodes (const state::Pattern &pattern)
Force fire input nodes using a pattern. Parameters:
Pattern The pattern to fire
Definition at line 406 of file Fibre.cpp.
References forceFireNodes(), and getInputNodes().
void cryomesh::structures::Fibre::forceFireNodes (const state::Pattern &pattern, std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > >nodes)
Force fire nodes using a pattern. Parameters:
Pattern The pattern to fire
std::map<boost::uuids::uuid,boost::shared_ptr<components::Node> > The nodes to fire the pattern on
Definition at line 414 of file Fibre.cpp.
References cryomesh::state::Pattern::getPattern(), and cryomesh::state::Pattern::getSize().
Referenced by forceFireInputNodes(), and forceFireOutputNodes().
void cryomesh::structures::Fibre::forceFireOutputNodes (const state::Pattern &pattern)
Force fire output nodes using a pattern. Parameters:
Pattern The pattern to fire
Definition at line 410 of file Fibre.cpp.
References forceFireNodes(), and getOutputNodes().
const components::ConnectionMap & cryomesh::structures::Fibre::getConnections () const
Get the connections. Returns:
components::ConnectionMap The connection map for this Fibre
Definition at line 128 of file Fibre.cpp.
References connections.
Referenced by getWidth(), cryomesh::structures::operator<<(), and trigger().
const common::Connector< Fibre, Cluster > & cryomesh::structures::Fibre::getConnector () const
Get the connector. Returns:
common::Connector<Fibre, Cluster> & The connector object
Definition at line 121 of file Fibre.cpp.
References connector.
Referenced by countConnections(), and isConnected().
const std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > cryomesh::structures::Fibre::getInputNodes () const
Get the map of input nodes to this fibre. Returns:
std::map<boost::uuid, boost::shared_ptr< components::Node > > The map of input nodes
Definition at line 340 of file Fibre.cpp.
References getNodes(), and InputCluster.
Referenced by forceFireInputNodes(), and getInputNodesPattern().
boost::shared_ptr< state::Pattern > cryomesh::structures::Fibre::getInputNodesPattern () const
Get current pattern for firing state of input nodes to the fibre. Returns:
boost::shared_ptr< state::Pattern > The current firing pattern of the input nodes to the fibre
Definition at line 331 of file Fibre.cpp.
References getInputNodes(), and getNodesPattern().
components::ConnectionMap & cryomesh::structures::Fibre::getMutableConnections ()
Get the mutable connections. Returns:
components::ConnectionMap The mutable connection map for this Fibre
Definition at line 132 of file Fibre.cpp.
References connections.
common::Connector< Fibre, Cluster > & cryomesh::structures::Fibre::getMutableConnector ()
Get the mutable connector. Returns:
common::Connector<Fibre, Cluster> The connector object
Definition at line 125 of file Fibre.cpp.
References connector.
const std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > cryomesh::structures::Fibre::getNodes (const ClusterConnectionTypetype) const
Get the map of nodes to this fibre. Parameters:
ClusterConnectionType The cluster to get the nodes from, eg, InputCluster means get the input nodes
Returns:
std::map<boost::uuid, boost::shared_ptr< components::Node > > The map of nodes
Definition at line 348 of file Fibre.cpp.
References connections, InputCluster, and OutputCluster.
Referenced by getInputNodes(), and getOutputNodes().
boost::shared_ptr< state::Pattern > cryomesh::structures::Fibre::getNodesPattern (const std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > >all_nodes) const
Get current pattern for firing state of nodes. Parameters:
const std::map<boost::uuids::uuid, boost::shared_ptr<components::Node> > The nodes to check for firing pattern
Returns:
boost::shared_ptr< state::Pattern > The current firing pattern of the input nodes to the fibre
Definition at line 302 of file Fibre.cpp.
References cryomesh::components::Node::Positive.
Referenced by getInputNodesPattern(), and getOutputNodesPattern().
const std::map< boost::uuids::uuid, boost::shared_ptr< components::Node > > cryomesh::structures::Fibre::getOutputNodes () const
Get the map of output nodes to this fibre. Returns:
std::map<boost::uuid, boost::shared_ptr< components::Node > > The map of output nodes
Definition at line 344 of file Fibre.cpp.
References getNodes(), and OutputCluster.
Referenced by forceFireOutputNodes(), and getOutputNodesPattern().
boost::shared_ptr< state::Pattern > cryomesh::structures::Fibre::getOutputNodesPattern () const
Get current pattern for firing state of output nodes to the fibre. Returns:
boost::shared_ptr< state::Pattern > The current firing pattern of the output nodes to the fibre
Definition at line 335 of file Fibre.cpp.
References getNodesPattern(), and getOutputNodes().
Referenced by cryomesh::structures::operator<<().
const Fibre::FibreType & cryomesh::structures::Fibre::getType () const
Get the type of the fibre. Returns:
FibreType The type of the fibre connection
Definition at line 136 of file Fibre.cpp.
References fibreType.
Referenced by Fibre().
unsigned int cryomesh::structures::Fibre::getWidth () const
Get width (number of connections) of fibre. Returns:
unsigned int Width of fibre
Definition at line 144 of file Fibre.cpp.
References getConnections().
Referenced by trigger().
int cryomesh::structures::Fibre::isConnected (const boost::shared_ptr< Cluster > &cluster) const
Return type of connection to cluster specified, null if none. Parameters:
boost::shared_ptr<Cluster> cluster Check connection to this cluster
Returns:
const ClusterConnectionType & Connection type to cluster, Null if none
Definition at line 189 of file Fibre.cpp.
References getConnector(), cryomesh::common::Connector< U, T >::getInputs(), cryomesh::common::Connector< U, T >::getOutputs(), InputCluster, LoopbackCluster, and OutputCluster.
void cryomesh::structures::Fibre::setType (const FibreType &tp) [protected, virtual]
Set the type of this fibre. Parameters:
const FibreType & tp The type of this fibre
Definition at line 140 of file Fibre.cpp.
References fibreType.
Referenced by Fibre().
void cryomesh::structures::Fibre::trigger (doublepercentage)
Trigger a random pattern with percentage of the connections to fire. Parameters:
double Fraction of connection to trigger randomly
Definition at line 63 of file Fibre.cpp.
References cryomesh::state::Pattern::getRandom(), getWidth(), and trigger().
void cryomesh::structures::Fibre::trigger () [virtual]
Send impulses to the connections based on a complete trigger of all of them.
Definition at line 54 of file Fibre.cpp.
References getConnections(), and cryomesh::components::Impulse::getTriggerImpulse().
Referenced by trigger().
void cryomesh::structures::Fibre::trigger (const state::Pattern &pattern) [virtual]
Send impulses to the connections based on a pattern. Parameters:
state::Pattern & pattern The pattern to use to create impulses and send to connections
Definition at line 69 of file Fibre.cpp.
References getConnections(), cryomesh::state::Pattern::getPattern(), cryomesh::components::Impulse::getTriggerImpulse(), and trigger().
void cryomesh::structures::Fibre::trigger (std::vector< boost::shared_ptr< components::Impulse > > &triggerImpulses) [virtual]
Send impulses to the connections. Parameters:
const std::vector<boost::shared_ptr< components::Impulse > > & triggerImpulses The impulses to send to connections
Definition at line 90 of file Fibre.cpp.
References connections.
void cryomesh::structures::Fibre::update () [virtual]
Update all elements.
Definition at line 46 of file Fibre.cpp.
References connections, and cryomesh::components::ConnectionMap::update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Fibre &obj) [friend]
Get the activity pattern of the Fibre, 0 for no activity, 1 otherwise. Returns:
Pattern To stream operator
Parameters:
std::ostream & os The output stream
const Fibre & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 449 of file Fibre.cpp.
Member Data Documentation
components::ConnectionMap cryomesh::structures::Fibre::connections [private]
Definition at line 334 of file Fibre.h.
Referenced by connectAllConnections(), createConnections(), disconnectAllConnections(), getConnections(), getMutableConnections(), getNodes(), trigger(), and update().
common::Connector<Fibre, Cluster> cryomesh::structures::Fibre::connector [private]
Definition at line 327 of file Fibre.h.
Referenced by connectAllConnections(), disconnectAllConnections(), getConnector(), and getMutableConnector().
FibreType cryomesh::structures::Fibre::fibreType [private]
Definition at line 341 of file Fibre.h.
Referenced by getType(), and setType().
Author
Generated automatically by Doxygen for cryomesh from the source code.