.TH "cryomesh::state::PatternChannelMap" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::state::PatternChannelMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PatternChannelMap.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPatternChannelMap\fP ()"
.br
.ti -1c
.RI "virtual \fB~PatternChannelMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file PatternChannelMap.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::state::PatternChannelMap::PatternChannelMap ()\fC [inline]\fP"
.PP
Definition at line 20 of file PatternChannelMap.h.
.SS "virtual cryomesh::state::PatternChannelMap::~PatternChannelMap ()\fC [inline, virtual]\fP"
.PP
Definition at line 21 of file PatternChannelMap.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
