cryomesh::state::ActivityPattern
NAME
cryomesh::state::ActivityPattern -
A simple collection of doubles representing a pattern of activities.
SYNOPSIS
#include <ActivityPattern.h>
Inherits SimpleCollection< double >.
Public Types
enum ActivityComparison { GreaterThan, LessThan, EqualTo }
Public Member Functions
ActivityPattern ()
virtual ~ActivityPattern ()
virtual std::string toPlusBooleanString () const
Return a string of booleans representing with each element is > 0 or not.
virtual std::list< bool > toPlusBooleanList () const
Return a vector of booleans representing with each element > 0 or not.
virtual void clear ()
Clear all objects from collection.
virtual void add (doubleobj)
Add object to collection.
virtual void add (const std::initializer_list< double > &list)
Add object to collection by initialiser list.
virtual void add (const std::list< double > &list)
Add object to collection by list.
virtual void remove (doubleobj)
Remove object from collection.
virtual void remove (const std::initializer_list< double > &list)
Remove objects from collection by initialiser list.
virtual void remove (const std::list< double > &list)
Remove objects from collection by list.
virtual double getSum () const
virtual double getMaximum () const
virtual double getMinimum () const
virtual double operator[] (unsigned index) const throw (exceptions::IndexOutOfBoundsException)
Get value at index.
virtual SimpleCollection & invert ()
Invert collection.
virtual SimpleCollection< double > & reverse ()
Reverse collection.
virtual const std::list< double > & getCollection () const
Get underlying collection.
virtual std::list< double > & getMutableCollection ()
Get mutable underlying collection.
virtual int getSize () const
Get underlying collections size.
virtual const SimpleCollection< double > operator+ (const SimpleCollection< double > &obj) const
Non-destructive addition operator.
virtual SimpleCollection< double > & operator+= (const SimpleCollection< double > &obj)
Destructive addition and assignment operator.
virtual bool operator== (const SimpleCollection< double > &obj) const
Comparator operator.
bool operator!= (const SimpleCollection &obj) const
Not comparator operator.
virtual bool operator!= (const SimpleCollection< double > &obj) const =0
Not comparator operator.
std::list< double > & pad (int front_pad, int back_pad, doublepad_value)
Pad Collection.
Protected Member Functions
std::list< bool > toBooleanVector (const double cuttoff, const ActivityComparison compare) const
double getBoundaryValue (bool greater) const
void generateCurve (const double max_y, const unsigned long length)
Generate a curve from boundary value.
Friends
std::ostream & operator<< (std::ostream &out, const SimpleCollection &obj)
To stream operator.
Detailed Description
A simple collection of doubles representing a pattern of activities.
Definition at line 20 of file ActivityPattern.h.
Member Enumeration Documentation
enum cryomesh::state::ActivityPattern::ActivityComparison
Enumerator:
GreaterThan
LessThan
EqualTo
Definition at line 22 of file ActivityPattern.h.
Constructor & Destructor Documentation
cryomesh::state::ActivityPattern::ActivityPattern ()
Definition at line 19 of file ActivityPattern.cpp.
cryomesh::state::ActivityPattern::~ActivityPattern () [virtual]
Definition at line 23 of file ActivityPattern.cpp.
Member Function Documentation
virtual void cryomesh::common::SimpleCollection< double >::add (doubleobj) [inline, virtual, inherited]
Add object to collection. Parameters:
T obj The value to be added to the collection
Returns:
T The value added to the collection
Definition at line 80 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual void cryomesh::common::SimpleCollection< double >::add (const std::initializer_list< double > &list) [inline, virtual, inherited]
Add object to collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be added to the collection
Definition at line 90 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::add().
virtual void cryomesh::common::SimpleCollection< double >::add (const std::list< double > &list) [inline, virtual, inherited]
Add object to collection by list. Parameters:
std::list<T> list The list values to be added to the collection
Definition at line 108 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::add().
virtual void cryomesh::common::SimpleCollection< double >::clear () [inline, virtual, inherited]
Clear all objects from collection.
Definition at line 66 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
void cryomesh::common::SimpleCollection< double >::generateCurve (const doublemax_y, const unsigned longlength) [inline, protected, inherited]
Generate a curve from boundary value. Parameters:
const int max_y Boundary value of curve
const int length Length of Impulse
Definition at line 537 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
double cryomesh::common::SimpleCollection< double >::getBoundaryValue (boolgreater) const [inline, protected, inherited]
Definition at line 500 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual const std::list<double >& cryomesh::common::SimpleCollection< double >::getCollection () const [inline, virtual, inherited]
Get underlying collection. Returns:
const std::list<T> & The collection
Definition at line 298 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual double cryomesh::common::SimpleCollection< double >::getMaximum () const [inline, virtual, inherited]
Definition at line 205 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getBoundaryValue().
virtual double cryomesh::common::SimpleCollection< double >::getMinimum () const [inline, virtual, inherited]
Definition at line 215 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getBoundaryValue().
virtual std::list<double >& cryomesh::common::SimpleCollection< double >::getMutableCollection () [inline, virtual, inherited]
Get mutable underlying collection. Returns:
std::list<T> & The mutable collection
Definition at line 308 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual int cryomesh::common::SimpleCollection< double >::getSize () const [inline, virtual, inherited]
Get underlying collections size. Returns:
int The collections size
Definition at line 318 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual double cryomesh::common::SimpleCollection< double >::getSum () const [inline, virtual, inherited]
Definition at line 185 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual SimpleCollection& cryomesh::common::SimpleCollection< double >::invert () [inline, virtual, inherited]
Invert collection. Reflect the collection in the x axis
Returns:
SimpleCollection & The inverted object
Reimplemented in cryomesh::components::Impulse.
Definition at line 264 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
bool cryomesh::common::SimpleCollection< double >::operator!= (const SimpleCollection< double > &obj) const [inline, inherited]
Not comparator operator. Parameters:
const SimpleCollection & obj RHS object
Returns:
bool True if not equal, false otherwise
Definition at line 432 of file SimpleCollection.h.
virtual bool cryomesh::common::ICollection< SimpleCollection< double > >::operator!= (const SimpleCollection< double > &obj) const [pure virtual, inherited]
Not comparator operator. Parameters:
const T & obj RHS object
Returns:
bool True if not equal, false otherwise
virtual const SimpleCollection<double > cryomesh::common::SimpleCollection< double >::operator+ (const SimpleCollection< double > &obj) const [inline, virtual, inherited]
Non-destructive addition operator. Parameters:
const SimpleCollection<T> & obj RHS addition
Returns:
SimpleCollection<T> New object after addition
Implements cryomesh::common::ICollection< SimpleCollection< double > >.
Definition at line 331 of file SimpleCollection.h.
virtual SimpleCollection<double >& cryomesh::common::SimpleCollection< double >::operator+= (const SimpleCollection< double > &obj) [inline, virtual, inherited]
Destructive addition and assignment operator. Parameters:
const SimpleCollection<T> & obj RHS addition
Returns:
SimpleCollection<T> & This object after addition and assignment
Implements cryomesh::common::ICollection< SimpleCollection< double > >.
Definition at line 346 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getCollection(), and cryomesh::common::SimpleCollection< T >::getMutableCollection().
virtual bool cryomesh::common::SimpleCollection< double >::operator== (const SimpleCollection< double > &obj) const [inline, virtual, inherited]
Comparator operator. Parameters:
const SimpleCollection<T> & obj RHS object
Returns:
bool True if equal, false otherwise
Implements cryomesh::common::ICollection< SimpleCollection< double > >.
Definition at line 390 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getCollection(), and cryomesh::common::Containers::print().
virtual double cryomesh::common::SimpleCollection< double >::operator[] (unsignedindex) const throw (exceptions::IndexOutOfBoundsException) [inline, virtual, inherited]
Get value at index. Parameters:
unsigned index Index to return
Returns:
T Value at index, 0 if out of bounds
Definition at line 228 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getSize(), and cryomesh::common::SimpleCollection< T >::objects.
std::list<double >& cryomesh::common::SimpleCollection< double >::pad (intfront_pad, intback_pad, doublepad_value) [inline, inherited]
Pad Collection. Parameters:
int front_pad Amount of places to pad to front
int back_pad Amount of places to pad to back
T & obj Object to use for pad
Returns:
T & Return the collection
Definition at line 475 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual void cryomesh::common::SimpleCollection< double >::remove (const std::list< double > &list) [inline, virtual, inherited]
Remove objects from collection by list. Parameters:
std::list<T> list The list values to be removed to the collection
Definition at line 167 of file SimpleCollection.h.
virtual void cryomesh::common::SimpleCollection< double >::remove (doubleobj) [inline, virtual, inherited]
Remove object from collection. Parameters:
T obj The object to be removed from the collection
Definition at line 126 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual void cryomesh::common::SimpleCollection< double >::remove (const std::initializer_list< double > &list) [inline, virtual, inherited]
Remove objects from collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be removed from the collection
Definition at line 149 of file SimpleCollection.h.
virtual SimpleCollection<double >& cryomesh::common::SimpleCollection< double >::reverse () [inline, virtual, inherited]
Reverse collection. Reflect the collection in the y axis
Returns:
SimpleCollection<T> & The inverted object
Definition at line 285 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects, and cryomesh::common::SimpleCollection< T >::reverse().
std::list< bool > cryomesh::state::ActivityPattern::toBooleanVector (const doublecuttoff, const ActivityComparisoncompare) const [protected]
Definition at line 36 of file ActivityPattern.cpp.
std::list< bool > cryomesh::state::ActivityPattern::toPlusBooleanList () const [virtual]
Return a vector of booleans representing with each element > 0 or not. Returns:
std::vector<bool> The vector of booleans
Definition at line 32 of file ActivityPattern.cpp.
std::string cryomesh::state::ActivityPattern::toPlusBooleanString () const [virtual]
Return a string of booleans representing with each element is > 0 or not. Returns:
std::string The string of booleans
Definition at line 26 of file ActivityPattern.cpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &out, const SimpleCollection< double > &obj) [friend, inherited]
To stream operator. Parameters:
std::ostream & out The output stream
const SimpleCollection & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 447 of file SimpleCollection.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.