cryomesh::structures::ClusterMap
NAME
cryomesh::structures::ClusterMap -
SYNOPSIS
#include <ClusterMap.h>
Public Types
enum EnergyFractionMethod { ENERGY_FRACTION_BY_CLUSTER_COUNT, ENERGY_FRACTION_BY_NODE_COUNT }
Public Member Functions
ClusterMap ()
void setEnergyFractionMethod (EnergyFractionMethod method)
virtual ~ClusterMap ()
virtual void update ()
void updateClusterEnergies (double total_energy)
double getClusterEnergyByClusterCount (const boost::shared_ptr< Cluster > &cluster, double total_energy) const
Take a total energy and split it evenly between clusters.
double getClusterEnergyByNodeCount (const boost::shared_ptr< Cluster > &cluster, double total_energy) const
Take a total energy and split it between clusters based on fraction of total nodes.
void warpClusterNodes ()
void updateMapData ()
Private Attributes
int totalNodeCount
EnergyFractionMethod energyFractionMethod
Friends
std::ostream & operator<< (std::ostream &os, const ClusterMap &clustermap)
Detailed Description
Definition at line 20 of file ClusterMap.h.
Member Enumeration Documentation
enum cryomesh::structures::ClusterMap::EnergyFractionMethod
Enumerator:
ENERGY_FRACTION_BY_CLUSTER_COUNT
ENERGY_FRACTION_BY_NODE_COUNT
Definition at line 23 of file ClusterMap.h.
Constructor & Destructor Documentation
cryomesh::structures::ClusterMap::ClusterMap () [inline]
Definition at line 26 of file ClusterMap.h.
virtual cryomesh::structures::ClusterMap::~ClusterMap () [inline, virtual]
Definition at line 34 of file ClusterMap.h.
Member Function Documentation
double cryomesh::structures::ClusterMap::getClusterEnergyByClusterCount (const boost::shared_ptr< Cluster > &cluster, doubletotal_energy) const [inline]
Take a total energy and split it evenly between clusters.
Definition at line 91 of file ClusterMap.h.
Referenced by updateClusterEnergies().
double cryomesh::structures::ClusterMap::getClusterEnergyByNodeCount (const boost::shared_ptr< Cluster > &cluster, doubletotal_energy) const [inline]
Take a total energy and split it between clusters based on fraction of total nodes.
Definition at line 100 of file ClusterMap.h.
References totalNodeCount.
Referenced by updateClusterEnergies().
void cryomesh::structures::ClusterMap::setEnergyFractionMethod (EnergyFractionMethodmethod) [inline]
Definition at line 30 of file ClusterMap.h.
References energyFractionMethod.
virtual void cryomesh::structures::ClusterMap::update () [inline, virtual]
Definition at line 38 of file ClusterMap.h.
References totalNodeCount.
void cryomesh::structures::ClusterMap::updateClusterEnergies (doubletotal_energy) [inline]
Definition at line 56 of file ClusterMap.h.
References ENERGY_FRACTION_BY_CLUSTER_COUNT, ENERGY_FRACTION_BY_NODE_COUNT, energyFractionMethod, getClusterEnergyByClusterCount(), and getClusterEnergyByNodeCount().
void cryomesh::structures::ClusterMap::updateMapData () [inline]
Definition at line 128 of file ClusterMap.h.
References totalNodeCount.
void cryomesh::structures::ClusterMap::warpClusterNodes () [inline]
Definition at line 112 of file ClusterMap.h.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const ClusterMap &clustermap) [friend]
Definition at line 144 of file ClusterMap.h.
Member Data Documentation
EnergyFractionMethod cryomesh::structures::ClusterMap::energyFractionMethod [private]
Definition at line 168 of file ClusterMap.h.
Referenced by setEnergyFractionMethod(), and updateClusterEnergies().
int cryomesh::structures::ClusterMap::totalNodeCount [private]
Definition at line 167 of file ClusterMap.h.
Referenced by getClusterEnergyByNodeCount(), update(), and updateMapData().
Author
Generated automatically by Doxygen for cryomesh from the source code.