.TH "cryomesh::components::ActivityTimer" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::ActivityTimer \- 
.PP
Simple interface class for activity timers.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ActivityTimer.h>\fP
.PP
Inherited by \fBcryomesh::components::ActivityTimerDistance\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActivityTimer\fP ()"
.br
.RI "\fIDefault constructor. \fP"
.ti -1c
.RI "virtual \fB~ActivityTimer\fP ()"
.br
.RI "\fIDefault destructor. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Simple interface class for activity timers. 
.PP
Definition at line 18 of file ActivityTimer.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::components::ActivityTimer::ActivityTimer ()\fC [inline]\fP"
.PP
Default constructor. 
.PP
Definition at line 23 of file ActivityTimer.h.
.SS "virtual cryomesh::components::ActivityTimer::~ActivityTimer ()\fC [inline, virtual]\fP"
.PP
Default destructor. 
.PP
Definition at line 29 of file ActivityTimer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
