cryomesh::state::PatternChannel
NAME
cryomesh::state::PatternChannel -
SYNOPSIS
#include <PatternChannel.h>
Public Types
enum PrintFormat { BINARY, TEXT, INTEGER }
enum ChannelDataType { Input, Output, Transitional }
Public Member Functions
PatternChannel (ChannelDataType dt)
PatternChannel (const std::list< boost::shared_ptr< Pattern > > &pats, ChannelDataType dt)
virtual ~PatternChannel ()
PatternChannel (const PatternChannel &obj)
PatternChannel & operator= (const PatternChannel &obj)
Assignment operator.
void addPattern (boost::shared_ptr< Pattern > pat)
void addPatterns (const std::list< boost::shared_ptr< Pattern > > &pats)
void addPatterns (const std::list< boost::shared_ptr< Pattern > > &pats, int position)
std::list< boost::shared_ptr
< Pattern > > removePatterns (const std::list< boost::shared_ptr< Pattern > > &pats)"
std::list< boost::shared_ptr
< Pattern > > removePatterns (const std::list< boost::uuids::uuid > &uuids)"
void clearPatternList ()
std::list< boost::shared_ptr
< Pattern > > forcePatternListSize (int sz)"
std::list< boost::shared_ptr
< Pattern > > forcePatternListSize ()"
const boost::shared_ptr< Pattern > getCurrentPattern ()
const boost::shared_ptr< Pattern > getPatternByCycle (const common::Cycle &cycle)
const boost::shared_ptr< Pattern > getPatternByTag (const boost::shared_ptr< PatternTag > tg) const
const boost::shared_ptr< Pattern > nextPattern ()
const boost::shared_ptr< Pattern > previousPattern ()
double matchGlobally (const PatternChannel &)
double matchSequentially (const PatternChannel &)
virtual void enableDebug (bool b)
ChannelDataType getChannelDataType () const
int getLength () const
const std::map
< boost::shared_ptr
< PatternTag >
, boost::uuids::uuid > & getPatternByTagMap () const "
const boost::shared_ptr< Pattern > getPatternByUUID (const boost::uuids::uuid &id) const
boost::shared_ptr< Pattern > getMutablePatternByUUID (const boost::uuids::uuid &id)
const std::list
< boost::uuids::uuid > & getPatternList () const "
std::list< boost::uuids::uuid >
::iterator getPatternListIterator () const "
const std::map
< boost::uuids::uuid,
boost::shared_ptr< Pattern > > & getPatternMap () const "
int getPatternPosition () const
int getWidth () const
void setWidth (int w)
int getRefID () const
void setRefID (int r)
int getMaxPatternListSize () const
void setMaxPatternListSize (int sz)
std::ostream & printPatternList (std::ostream &os, bool reversed=false) const
std::ostream & printTextFormattedPatternList (std::ostream &os, bool reversed=false) const
std::ostream & printIntegerFormattedPatternList (std::ostream &os, bool reversed) const
std::ostream & printBinaryFormattedPatternList (std::ostream &os, bool reversed) const
std::ostream & printFormattedPatternList (std::ostream &os, const PrintFormat &pf, bool reversed) const
Static Public Member Functions
static unsigned int getRefIDS ()
Static Public Attributes
static const int DEFAULT_MAX_PATTERN_LIST_SIZE = -1
static const unsigned int REFID_CREATE_START = 100000
static unsigned int refIDS = PatternChannel::REFID_CREATE_START
Private Attributes
ChannelDataType channelDataType
int length
int maxPatternListSize
std::map< boost::shared_ptr
< PatternTag >
, boost::uuids::uuid > patternByTagMap"
std::list< boost::uuids::uuid > patternList
std::list< boost::uuids::uuid >
::iterator patternListIterator"
std::map< boost::uuids::uuid,
boost::shared_ptr< Pattern > > patternMap"
int patternPosition
int refID
int width
Friends
std::ostream & operator<< (std::ostream &os, const PatternChannel &obj)
Detailed Description
Definition at line 25 of file PatternChannel.h.
Member Enumeration Documentation
enum cryomesh::state::PatternChannel::ChannelDataType
Enumerator:
Input
Output
Transitional
Definition at line 30 of file PatternChannel.h.
enum cryomesh::state::PatternChannel::PrintFormat
Enumerator:
BINARY
TEXT
INTEGER
Definition at line 27 of file PatternChannel.h.
Constructor & Destructor Documentation
cryomesh::state::PatternChannel::PatternChannel (ChannelDataTypedt)
Definition at line 24 of file PatternChannel.cpp.
References channelDataType, and Input.
cryomesh::state::PatternChannel::PatternChannel (const std::list< boost::shared_ptr< Pattern > > &pats, ChannelDataTypedt)
Definition at line 37 of file PatternChannel.cpp.
References addPatterns(), channelDataType, DEFAULT_MAX_PATTERN_LIST_SIZE, getRefIDS(), Input, maxPatternListSize, Output, patternList, patternListIterator, and refID.
cryomesh::state::PatternChannel::~PatternChannel () [virtual]
Definition at line 59 of file PatternChannel.cpp.
cryomesh::state::PatternChannel::PatternChannel (const PatternChannel &obj)
Definition at line 65 of file PatternChannel.cpp.
References channelDataType, length, maxPatternListSize, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, refID, and width.
Member Function Documentation
void cryomesh::state::PatternChannel::addPattern (boost::shared_ptr< Pattern >pat)
Definition at line 98 of file PatternChannel.cpp.
References addPatterns(), and getLength().
void cryomesh::state::PatternChannel::addPatterns (const std::list< boost::shared_ptr< Pattern > > &pats)
Definition at line 103 of file PatternChannel.cpp.
References getLength().
Referenced by addPattern(), and PatternChannel().
void cryomesh::state::PatternChannel::addPatterns (const std::list< boost::shared_ptr< Pattern > > &pats, intposition)
Definition at line 107 of file PatternChannel.cpp.
References forcePatternListSize(), getLength(), getWidth(), length, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, and setWidth().
void cryomesh::state::PatternChannel::clearPatternList ()
Definition at line 200 of file PatternChannel.cpp.
References length, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, and width.
void cryomesh::state::PatternChannel::enableDebug (boolb) [virtual]
Definition at line 536 of file PatternChannel.cpp.
std::list< boost::shared_ptr< Pattern > > cryomesh::state::PatternChannel::forcePatternListSize (intsz)
Definition at line 209 of file PatternChannel.cpp.
References patternList, and removePatterns().
std::list< boost::shared_ptr< Pattern > > cryomesh::state::PatternChannel::forcePatternListSize ()
Definition at line 233 of file PatternChannel.cpp.
References getMaxPatternListSize().
Referenced by addPatterns(), and setMaxPatternListSize().
PatternChannel::ChannelDataType cryomesh::state::PatternChannel::getChannelDataType () const
Definition at line 498 of file PatternChannel.cpp.
References channelDataType.
const boost::shared_ptr< Pattern > cryomesh::state::PatternChannel::getCurrentPattern ()
Definition at line 241 of file PatternChannel.cpp.
References patternMap.
Referenced by nextPattern(), and previousPattern().
int cryomesh::state::PatternChannel::getLength () const
Definition at line 458 of file PatternChannel.cpp.
References patternList.
Referenced by addPattern(), addPatterns(), and nextPattern().
int cryomesh::state::PatternChannel::getMaxPatternListSize () const
Definition at line 502 of file PatternChannel.cpp.
References maxPatternListSize.
Referenced by forcePatternListSize().
boost::shared_ptr< Pattern > cryomesh::state::PatternChannel::getMutablePatternByUUID (const boost::uuids::uuid &id)
Definition at line 524 of file PatternChannel.cpp.
References patternMap.
const boost::shared_ptr< Pattern > cryomesh::state::PatternChannel::getPatternByCycle (const common::Cycle &cycle)
Definition at line 245 of file PatternChannel.cpp.
References cryomesh::common::TimeKeeper::getCycle(), cryomesh::common::TimeKeeper::getTimeKeeper(), patternList, and patternMap.
const boost::shared_ptr< Pattern > cryomesh::state::PatternChannel::getPatternByTag (const boost::shared_ptr< PatternTag >tg) const
Definition at line 269 of file PatternChannel.cpp.
References patternByTagMap, and patternMap.
const std::map< boost::shared_ptr< PatternTag >, boost::uuids::uuid > & cryomesh::state::PatternChannel::getPatternByTagMap () const
Definition at line 462 of file PatternChannel.cpp.
References patternByTagMap.
const boost::shared_ptr< Pattern > cryomesh::state::PatternChannel::getPatternByUUID (const boost::uuids::uuid &id) const
Definition at line 512 of file PatternChannel.cpp.
References patternMap.
Referenced by printFormattedPatternList(), and printPatternList().
const std::list< boost::uuids::uuid > & cryomesh::state::PatternChannel::getPatternList () const
Definition at line 466 of file PatternChannel.cpp.
References patternList.
Referenced by matchGlobally(), and matchSequentially().
std::list< boost::uuids::uuid >::iterator cryomesh::state::PatternChannel::getPatternListIterator () const
Definition at line 470 of file PatternChannel.cpp.
References patternListIterator.
const std::map< boost::uuids::uuid, boost::shared_ptr< Pattern > > & cryomesh::state::PatternChannel::getPatternMap () const
Definition at line 474 of file PatternChannel.cpp.
References patternMap.
Referenced by matchGlobally(), and matchSequentially().
int cryomesh::state::PatternChannel::getPatternPosition () const
Definition at line 478 of file PatternChannel.cpp.
References patternPosition.
int cryomesh::state::PatternChannel::getRefID () const
Definition at line 490 of file PatternChannel.cpp.
References refID.
unsigned int cryomesh::state::PatternChannel::getRefIDS () [static]
Definition at line 20 of file PatternChannel.cpp.
References refIDS.
Referenced by PatternChannel().
int cryomesh::state::PatternChannel::getWidth () const
Definition at line 482 of file PatternChannel.cpp.
References width.
Referenced by addPatterns().
double cryomesh::state::PatternChannel::matchGlobally (const PatternChannel &obj)
Definition at line 309 of file PatternChannel.cpp.
References getPatternList(), and getPatternMap().
double cryomesh::state::PatternChannel::matchSequentially (const PatternChannel &obj)
Definition at line 395 of file PatternChannel.cpp.
References getPatternList(), and getPatternMap().
const boost::shared_ptr< Pattern > cryomesh::state::PatternChannel::nextPattern ()
Definition at line 278 of file PatternChannel.cpp.
References getCurrentPattern(), getLength(), patternList, patternListIterator, and patternPosition.
PatternChannel & cryomesh::state::PatternChannel::operator= (const PatternChannel &obj)
Assignment operator. Parameters:
const PatternChannel & obj RHS assignment
Returns:
PatternChannel & This object after assignment
Definition at line 81 of file PatternChannel.cpp.
References channelDataType, length, maxPatternListSize, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, refID, and width.
const boost::shared_ptr< Pattern > cryomesh::state::PatternChannel::previousPattern ()
Definition at line 298 of file PatternChannel.cpp.
References getCurrentPattern(), patternList, patternListIterator, and patternPosition.
std::ostream & cryomesh::state::PatternChannel::printBinaryFormattedPatternList (std::ostream &os, boolreversed) const
Definition at line 576 of file PatternChannel.cpp.
References BINARY, and printFormattedPatternList().
Referenced by cryomesh::state::operator<<().
std::ostream & cryomesh::state::PatternChannel::printFormattedPatternList (std::ostream &os, const PrintFormat &pf, boolreversed) const
Definition at line 579 of file PatternChannel.cpp.
References BINARY, getPatternByUUID(), INTEGER, patternList, and TEXT.
Referenced by printBinaryFormattedPatternList(), printIntegerFormattedPatternList(), and printTextFormattedPatternList().
std::ostream & cryomesh::state::PatternChannel::printIntegerFormattedPatternList (std::ostream &os, boolreversed) const
Definition at line 573 of file PatternChannel.cpp.
References INTEGER, and printFormattedPatternList().
std::ostream & cryomesh::state::PatternChannel::printPatternList (std::ostream &os, boolreversed = false) const
Definition at line 540 of file PatternChannel.cpp.
References getPatternByUUID(), and patternList.
std::ostream & cryomesh::state::PatternChannel::printTextFormattedPatternList (std::ostream &os, boolreversed = false) const
Definition at line 569 of file PatternChannel.cpp.
References printFormattedPatternList(), and TEXT.
std::list< boost::shared_ptr< Pattern > > cryomesh::state::PatternChannel::removePatterns (const std::list< boost::shared_ptr< Pattern > > &pats)
Definition at line 156 of file PatternChannel.cpp.
Referenced by forcePatternListSize().
std::list< boost::shared_ptr< Pattern > > cryomesh::state::PatternChannel::removePatterns (const std::list< boost::uuids::uuid > &uuids)
Definition at line 175 of file PatternChannel.cpp.
References length, patternByTagMap, patternList, patternListIterator, patternMap, and patternPosition.
void cryomesh::state::PatternChannel::setMaxPatternListSize (intsz)
Definition at line 505 of file PatternChannel.cpp.
References forcePatternListSize(), and maxPatternListSize.
void cryomesh::state::PatternChannel::setRefID (intr)
Definition at line 493 of file PatternChannel.cpp.
References refID.
void cryomesh::state::PatternChannel::setWidth (intw)
Definition at line 485 of file PatternChannel.cpp.
References width.
Referenced by addPatterns().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const PatternChannel &obj) [friend]
Definition at line 639 of file PatternChannel.cpp.
Member Data Documentation
ChannelDataType cryomesh::state::PatternChannel::channelDataType [private]
Definition at line 169 of file PatternChannel.h.
Referenced by getChannelDataType(), operator=(), and PatternChannel().
const int cryomesh::state::PatternChannel::DEFAULT_MAX_PATTERN_LIST_SIZE = -1 [static]
Definition at line 161 of file PatternChannel.h.
Referenced by PatternChannel().
int cryomesh::state::PatternChannel::length [private]
Definition at line 171 of file PatternChannel.h.
Referenced by addPatterns(), clearPatternList(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and removePatterns().
int cryomesh::state::PatternChannel::maxPatternListSize [private]
Definition at line 172 of file PatternChannel.h.
Referenced by getMaxPatternListSize(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and setMaxPatternListSize().
std::map<boost::shared_ptr<PatternTag>, boost::uuids::uuid> cryomesh::state::PatternChannel::patternByTagMap [private]
Definition at line 174 of file PatternChannel.h.
Referenced by addPatterns(), clearPatternList(), getPatternByTag(), getPatternByTagMap(), operator=(), PatternChannel(), and removePatterns().
std::list<boost::uuids::uuid> cryomesh::state::PatternChannel::patternList [private]
Definition at line 176 of file PatternChannel.h.
Referenced by addPatterns(), clearPatternList(), forcePatternListSize(), getLength(), getPatternByCycle(), getPatternList(), nextPattern(), operator=(), PatternChannel(), previousPattern(), printFormattedPatternList(), printPatternList(), and removePatterns().
std::list<boost::uuids::uuid>::iterator cryomesh::state::PatternChannel::patternListIterator [private]
Definition at line 178 of file PatternChannel.h.
Referenced by addPatterns(), clearPatternList(), getPatternListIterator(), nextPattern(), operator=(), PatternChannel(), previousPattern(), and removePatterns().
std::map<boost::uuids::uuid, boost::shared_ptr<Pattern> > cryomesh::state::PatternChannel::patternMap [private]
Definition at line 180 of file PatternChannel.h.
Referenced by addPatterns(), clearPatternList(), getCurrentPattern(), getMutablePatternByUUID(), getPatternByCycle(), getPatternByTag(), getPatternByUUID(), getPatternMap(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and removePatterns().
int cryomesh::state::PatternChannel::patternPosition [private]
Definition at line 182 of file PatternChannel.h.
Referenced by addPatterns(), clearPatternList(), getPatternPosition(), nextPattern(), cryomesh::state::operator<<(), operator=(), PatternChannel(), previousPattern(), and removePatterns().
int cryomesh::state::PatternChannel::refID [private]
Definition at line 184 of file PatternChannel.h.
Referenced by getRefID(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and setRefID().
const unsigned int cryomesh::state::PatternChannel::REFID_CREATE_START = 100000 [static]
Definition at line 163 of file PatternChannel.h.
unsigned int cryomesh::state::PatternChannel::refIDS = PatternChannel::REFID_CREATE_START [static]
Definition at line 164 of file PatternChannel.h.
Referenced by getRefIDS().
int cryomesh::state::PatternChannel::width [private]
Definition at line 186 of file PatternChannel.h.
Referenced by clearPatternList(), getWidth(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and setWidth().
Author
Generated automatically by Doxygen for cryomesh from the source code.