cryomesh::spacial::SphericalPoint
NAME
cryomesh::spacial::SphericalPoint -
SYNOPSIS
#include <SphericalPoint.h>
Public Member Functions
SphericalPoint ()
SphericalPoint (double r, Radian th, Radian ph)
SphericalPoint (double r, Degree th, Degree ph)
SphericalPoint (const Point &p)
SphericalPoint (const SphericalPoint &p)
virtual ~SphericalPoint ()
double getArcLength (const SphericalPoint &start) const
double getArcLengthBasic (const SphericalPoint &start) const
double getArcLengthHaversine (const SphericalPoint &start) const
SphericalPoint getOpposite () const
double getRadius () const
Radian getTheta () const
Radian getPhi () const
void setRadius (double r)
void setTheta (Radian th)
void setPhi (Radian ph)
bool equals (const SphericalPoint &obj) const
bool operator== (const SphericalPoint &obj) const
SphericalPoint & operator= (const SphericalPoint &obj)
SphericalPoint operator+ (const SphericalPoint &obj) const
SphericalPoint operator- (const SphericalPoint &obj) const
Static Public Attributes
static const double PI = 3.14159265
static const double MIN_ALLOWED_X = 0.00000000001
Private Attributes
double radius
Radian theta
Radian phi
Friends
std::ostream & operator<< (std::ostream &os, const SphericalPoint &obj)
Detailed Description
Definition at line 19 of file SphericalPoint.h.
Constructor & Destructor Documentation
cryomesh::spacial::SphericalPoint::SphericalPoint ()
Definition at line 20 of file SphericalPoint.cpp.
Referenced by getOpposite(), operator+(), and operator-().
cryomesh::spacial::SphericalPoint::SphericalPoint (doubler, Radianth, Radianph)
Definition at line 23 of file SphericalPoint.cpp.
cryomesh::spacial::SphericalPoint::SphericalPoint (doubler, Degreeth, Degreeph)
Definition at line 26 of file SphericalPoint.cpp.
cryomesh::spacial::SphericalPoint::SphericalPoint (const Point &p)
Definition at line 33 of file SphericalPoint.cpp.
References cryomesh::spacial::Point::getX(), cryomesh::spacial::Point::getY(), cryomesh::spacial::Point::getZ(), MIN_ALLOWED_X, radius, setPhi(), setRadius(), and setTheta().
cryomesh::spacial::SphericalPoint::SphericalPoint (const SphericalPoint &p)
Definition at line 30 of file SphericalPoint.cpp.
cryomesh::spacial::SphericalPoint::~SphericalPoint () [virtual]
Definition at line 48 of file SphericalPoint.cpp.
Member Function Documentation
bool cryomesh::spacial::SphericalPoint::equals (const SphericalPoint &obj) const
Definition at line 124 of file SphericalPoint.cpp.
References getPhi(), getRadius(), getTheta(), and cryomesh::spacial::Radian::getValue().
Referenced by getArcLengthHaversine().
double cryomesh::spacial::SphericalPoint::getArcLength (const SphericalPoint &start) const
Definition at line 51 of file SphericalPoint.cpp.
References getArcLengthHaversine().
double cryomesh::spacial::SphericalPoint::getArcLengthBasic (const SphericalPoint &start) const
Definition at line 54 of file SphericalPoint.cpp.
References getPhi(), getRadius(), getTheta(), cryomesh::spacial::Radian::getValue(), and cryomesh::spacial::Radian::toDegrees().
double cryomesh::spacial::SphericalPoint::getArcLengthHaversine (const SphericalPoint &start) const
Definition at line 67 of file SphericalPoint.cpp.
References equals(), getPhi(), getRadius(), getTheta(), cryomesh::spacial::Radian::getValue(), PI, and cryomesh::spacial::Radian::toDegrees().
Referenced by getArcLength().
SphericalPoint cryomesh::spacial::SphericalPoint::getOpposite () const
Definition at line 102 of file SphericalPoint.cpp.
References SphericalPoint().
Radian cryomesh::spacial::SphericalPoint::getPhi () const
Definition at line 112 of file SphericalPoint.cpp.
References phi.
Referenced by equals(), getArcLengthBasic(), getArcLengthHaversine(), cryomesh::spacial::operator<<(), operator=(), and operator==().
double cryomesh::spacial::SphericalPoint::getRadius () const
Definition at line 106 of file SphericalPoint.cpp.
References radius.
Referenced by equals(), getArcLengthBasic(), getArcLengthHaversine(), cryomesh::spacial::operator<<(), operator=(), and operator==().
Radian cryomesh::spacial::SphericalPoint::getTheta () const
Definition at line 109 of file SphericalPoint.cpp.
References theta.
Referenced by equals(), getArcLengthBasic(), getArcLengthHaversine(), cryomesh::spacial::operator<<(), operator=(), and operator==().
SphericalPoint cryomesh::spacial::SphericalPoint::operator+ (const SphericalPoint &obj) const
Definition at line 148 of file SphericalPoint.cpp.
References SphericalPoint().
SphericalPoint cryomesh::spacial::SphericalPoint::operator- (const SphericalPoint &obj) const
Definition at line 153 of file SphericalPoint.cpp.
References SphericalPoint().
SphericalPoint & cryomesh::spacial::SphericalPoint::operator= (const SphericalPoint &obj)
Definition at line 140 of file SphericalPoint.cpp.
References getPhi(), getRadius(), getTheta(), setPhi(), setRadius(), and setTheta().
bool cryomesh::spacial::SphericalPoint::operator== (const SphericalPoint &obj) const
Definition at line 136 of file SphericalPoint.cpp.
References getPhi(), getRadius(), and getTheta().
void cryomesh::spacial::SphericalPoint::setPhi (Radianph)
Definition at line 121 of file SphericalPoint.cpp.
References phi.
Referenced by operator=(), and SphericalPoint().
void cryomesh::spacial::SphericalPoint::setRadius (doubler)
Definition at line 115 of file SphericalPoint.cpp.
References radius.
Referenced by operator=(), and SphericalPoint().
void cryomesh::spacial::SphericalPoint::setTheta (Radianth)
Definition at line 118 of file SphericalPoint.cpp.
References theta.
Referenced by operator=(), and SphericalPoint().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const SphericalPoint &obj) [friend]
Definition at line 159 of file SphericalPoint.cpp.
Member Data Documentation
const double cryomesh::spacial::SphericalPoint::MIN_ALLOWED_X = 0.00000000001 [static]
Definition at line 51 of file SphericalPoint.h.
Referenced by SphericalPoint().
Radian cryomesh::spacial::SphericalPoint::phi [private]
Definition at line 59 of file SphericalPoint.h.
Referenced by getPhi(), and setPhi().
const double cryomesh::spacial::SphericalPoint::PI = 3.14159265 [static]
Definition at line 50 of file SphericalPoint.h.
Referenced by getArcLengthHaversine().
double cryomesh::spacial::SphericalPoint::radius [private]
Definition at line 55 of file SphericalPoint.h.
Referenced by getRadius(), setRadius(), and SphericalPoint().
Radian cryomesh::spacial::SphericalPoint::theta [private]
Definition at line 57 of file SphericalPoint.h.
Referenced by getTheta(), and setTheta().
Author
Generated automatically by Doxygen for cryomesh from the source code.