.TH "cryomesh" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh \- 
.PP
\fBConnector.h\fP.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcommon\fP"
.br
.ti -1c
.RI "namespace \fBcomponents\fP"
.br
.ti -1c
.RI "namespace \fBdataobjects\fP"
.br
.ti -1c
.RI "namespace \fBmanager\fP"
.br
.ti -1c
.RI "namespace \fBstate\fP"
.br
.ti -1c
.RI "namespace \fBstructures\fP"
.br
.ti -1c
.RI "namespace \fButilities\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPointer\fP"
.br
.RI "\fI\fBPointer\fP struct to allow typdef of templated smart pointers. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBConnector.h\fP. 

\fBMesh.h\fP.
.PP
\fBNode.h\fP.
.PP
\fBImpulseCollection.h\fP.
.PP
\fBImpulseCollection.cpp\fP.
.PP
\fBImpulse.h\fP.
.PP
\fBConnection.h\fP.
.PP
\fBCycle.h\fP.
.PP
\fBCycle.cpp\fP.
.PP
Created on: 19 Jan 2011 Author: SevenMachines<SevenMachines@yahoo.co.uk>
.PP
Created on: 1 Feb 2011 Author: SevenMachines<SevenMachines@yahoo.co.uk>
.PP
Created on: 1 Feb 2011 Author: SevenMachines<SevenMachines@yahoo.co.uk> Wrapper class around implementation of a cycle
.PP
Created on: 3 Jan 2011 Author: SevenMachines<SevenMachines@yahoo.co.uk>
.PP
Created on: 20 Jan 2011 Author: SevenMachines<SevenMachines@yahoo.co.uk>
.PP
Created on: 20 Jan 2011 Author: SevenMachines<SevenMachines@yahoo.co.uk>
.PP
A collection of Impulses that allows for Impulses to be held, 'moved forward' in time, and summated in some way 
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
