cryomesh::manipulators::ClusterAnalyserBasic
NAME
cryomesh::manipulators::ClusterAnalyserBasic -
SYNOPSIS
#include <ClusterAnalyserBasic.h>
Inherits cryomesh::manipulators::IClusterAnalyser.
Public Types
enum EnergyVariation { NONE = 2048, OUT_OF_RANGE_POSITIVE = 1024, HIGH_POSITIVE = 512, MEDIUM_POSITIVE = 256, SMALL_POSITIVE = 128, STAGNANT_POSITIVE = 64, ZERO = 32, STAGNANT_NEGATIVE = 16, SMALL_NEGATIVE = 8, MEDIUM_NEGATIVE = 4, HIGH_NEGATIVE = 2, OUT_OF_RANGE_NEGATIVE = 1 }
Public Member Functions
ClusterAnalyserBasic (const ClusterArchitect &ca)
virtual ~ClusterAnalyserBasic ()
virtual ClusterAnalysisData analyseCluster (const structures::Cluster &cluster, const std::map< int, std::list< ClusterAnalysisData > > &histories)
Run an analysis on the cluster to decide what action to take on nodes and connections.
virtual ClusterAnalysisData calculateRangeEnergies (const std::list< ClusterAnalysisData > &history) const
Calculate the range energies stats.
int getConnectionCreationEnabledCountdown () const
int getConnectionDestructionEnabledCountdown () const
int getNodeCreationEnabledCountdown () const
int getNodeDestructionEnabledCountdown () const
void setConnectionDestructionEnabledCountdown (int connectionDestructionEnabledCountdown)
const RestructuringCountdown & getConnectionRestructuring () const
const RestructuringCountdown & getNodeRestructuring () const
Protected Member Functions
virtual EnergyVariationWeightingMap getEnergyVariationMap (const double energy_input, double range) const
Protected Attributes
RestructuringCountdown nodeRestructuring
RestructuringCountdown connectionRestructuring
Private Attributes
const ClusterArchitect & clusterArchitect
Detailed Description
Definition at line 18 of file ClusterAnalyserBasic.h.
Member Enumeration Documentation
enum cryomesh::manipulators::IClusterAnalyser::EnergyVariation [inherited]
Enumerator:
NONE
OUT_OF_RANGE_POSITIVE
HIGH_POSITIVE
MEDIUM_POSITIVE
SMALL_POSITIVE
STAGNANT_POSITIVE
ZERO
STAGNANT_NEGATIVE
SMALL_NEGATIVE
MEDIUM_NEGATIVE
HIGH_NEGATIVE
OUT_OF_RANGE_NEGATIVE
Definition at line 136 of file IClusterAnalyser.h.
Constructor & Destructor Documentation
cryomesh::manipulators::ClusterAnalyserBasic::ClusterAnalyserBasic (const ClusterArchitect &ca)
Definition at line 16 of file ClusterAnalyserBasic.cpp.
cryomesh::manipulators::ClusterAnalyserBasic::~ClusterAnalyserBasic () [virtual]
Definition at line 20 of file ClusterAnalyserBasic.cpp.
Member Function Documentation
ClusterAnalysisData cryomesh::manipulators::ClusterAnalyserBasic::analyseCluster (const structures::Cluster &cluster, const std::map< int, std::list< ClusterAnalysisData > > &histories) [virtual]
Run an analysis on the cluster to decide what action to take on nodes and connections. Parameters:
const structures::Cluster & The cluster to analyse
const std::list<ClusterAnalysisData> The historical analysis data to use
Returns:
ClusterAnalysisData The reulting analytical data
Implements cryomesh::manipulators::IClusterAnalyser.
Definition at line 23 of file ClusterAnalyserBasic.cpp.
References calculateRangeEnergies(), clusterArchitect, cryomesh::manipulators::IClusterAnalyser::connectionRestructuring, cryomesh::manipulators::ClusterAnalysisData::RangeEnergy::energyFraction, cryomesh::manipulators::ClusterAnalysisData::getClusterRangeEnergy(), cryomesh::structures::Cluster::getConnectionMap(), cryomesh::structures::Cluster::getEnergy(), getEnergyVariationMap(), cryomesh::manipulators::ClusterArchitect::getHistorySteppingFactor(), cryomesh::structures::Cluster::getMaxEnergyFraction(), cryomesh::manipulators::ClusterArchitect::getMaxHistorySize(), cryomesh::structures::Cluster::getNodeMap(), cryomesh::manipulators::IClusterAnalyser::HIGH_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAnyLongRestructuringEnabled(), cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAnyMediumRestructuringEnabled(), cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::isAnyRestructuringEnabled(), cryomesh::manipulators::IClusterAnalyser::MEDIUM_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::MEDIUM_POSITIVE, cryomesh::manipulators::IClusterAnalyser::nodeRestructuring, cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::setLongCountdown(), cryomesh::manipulators::IClusterAnalyser::RestructuringCountdown::setMediumCountdown(), cryomesh::manipulators::IClusterAnalyser::SMALL_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::SMALL_POSITIVE, cryomesh::manipulators::IClusterAnalyser::STAGNANT_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::STAGNANT_POSITIVE, and cryomesh::manipulators::IClusterAnalyser::EnergyVariationWeightingMap::variationMap.
ClusterAnalysisData cryomesh::manipulators::ClusterAnalyserBasic::calculateRangeEnergies (const std::list< ClusterAnalysisData > &history) const [virtual]
Calculate the range energies stats. Parameters:
const std::list<ClusterAnalysisData> & The history range to work with
Returns:
ClusterAnalysisData The resulting cluster analysis data
Implements cryomesh::manipulators::IClusterAnalyser.
Definition at line 252 of file ClusterAnalyserBasic.cpp.
References cryomesh::manipulators::ClusterAnalysisData::getClusterRangeEnergy(), cryomesh::manipulators::ClusterAnalysisData::getConnectionCreationWeight(), cryomesh::manipulators::ClusterAnalysisData::getConnectionDestructionWeight(), cryomesh::manipulators::ClusterAnalysisData::getConnectionsToCreate(), cryomesh::manipulators::ClusterAnalysisData::getConnectionsToDestroy(), cryomesh::manipulators::ClusterAnalysisData::getNodeCreationWeight(), cryomesh::manipulators::ClusterAnalysisData::getNodeDestructionWeight(), cryomesh::manipulators::ClusterAnalysisData::getNodesToCreate(), and cryomesh::manipulators::ClusterAnalysisData::getNodesToDestroy().
Referenced by analyseCluster().
int cryomesh::manipulators::ClusterAnalyserBasic::getConnectionCreationEnabledCountdown () const
int cryomesh::manipulators::ClusterAnalyserBasic::getConnectionDestructionEnabledCountdown () const
const RestructuringCountdown& cryomesh::manipulators::IClusterAnalyser::getConnectionRestructuring () const [inline, inherited]
Definition at line 198 of file IClusterAnalyser.h.
References cryomesh::manipulators::IClusterAnalyser::connectionRestructuring.
ClusterAnalyserBasic::EnergyVariationWeightingMap cryomesh::manipulators::ClusterAnalyserBasic::getEnergyVariationMap (const doubleenergy_input, doublerange) const [protected, virtual]
Implements cryomesh::manipulators::IClusterAnalyser.
Definition at line 307 of file ClusterAnalyserBasic.cpp.
References cryomesh::manipulators::IClusterAnalyser::HIGH_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::HIGH_POSITIVE, cryomesh::manipulators::IClusterAnalyser::MEDIUM_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::MEDIUM_POSITIVE, cryomesh::manipulators::IClusterAnalyser::OUT_OF_RANGE_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::OUT_OF_RANGE_POSITIVE, cryomesh::manipulators::IClusterAnalyser::SMALL_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::SMALL_POSITIVE, cryomesh::manipulators::IClusterAnalyser::STAGNANT_NEGATIVE, cryomesh::manipulators::IClusterAnalyser::STAGNANT_POSITIVE, cryomesh::manipulators::IClusterAnalyser::EnergyVariationWeightingMap::variationMap, and cryomesh::manipulators::IClusterAnalyser::ZERO.
Referenced by analyseCluster().
int cryomesh::manipulators::ClusterAnalyserBasic::getNodeCreationEnabledCountdown () const
int cryomesh::manipulators::ClusterAnalyserBasic::getNodeDestructionEnabledCountdown () const
const RestructuringCountdown& cryomesh::manipulators::IClusterAnalyser::getNodeRestructuring () const [inline, inherited]
Definition at line 201 of file IClusterAnalyser.h.
References cryomesh::manipulators::IClusterAnalyser::nodeRestructuring.
void cryomesh::manipulators::ClusterAnalyserBasic::setConnectionDestructionEnabledCountdown (intconnectionDestructionEnabledCountdown)
Member Data Documentation
const ClusterArchitect& cryomesh::manipulators::ClusterAnalyserBasic::clusterArchitect [private]
Definition at line 36 of file ClusterAnalyserBasic.h.
Referenced by analyseCluster().
RestructuringCountdown cryomesh::manipulators::IClusterAnalyser::connectionRestructuring [protected, inherited]
Definition at line 206 of file IClusterAnalyser.h.
Referenced by analyseCluster(), and cryomesh::manipulators::IClusterAnalyser::getConnectionRestructuring().
RestructuringCountdown cryomesh::manipulators::IClusterAnalyser::nodeRestructuring [protected, inherited]
Definition at line 205 of file IClusterAnalyser.h.
Referenced by analyseCluster(), and cryomesh::manipulators::IClusterAnalyser::getNodeRestructuring().
Author
Generated automatically by Doxygen for cryomesh from the source code.