cryomesh::components
NAME
cryomesh::components -
SYNOPSIS
Classes
class ActivityTimer
Simple interface class for activity timers.
class ActivityTimerDistance
class Connection
Connection class to manage the transfer of Impulses between Nodes.
class ConnectionMap
Helper class for ConnectionMap to KeyMappedCollection mapping.
class Impulse
Impulse is a mobile information packet to be passed between Nodes.
class ImpulseCollection
ImpulseCollection represents a collection of Impulse objects.
class Node
Node is an accumulation and computational nodal point of impulses.
class NodeMap
Helper class for NodeMap to KeyMappedCollection mapping.
Functions
std::ostream & operator<< (std::ostream &os, const Connection &obj)
std::ostream & operator<< (std::ostream &os, const Impulse &obj)
std::ostream & operator<< (std::ostream &os, const ImpulseCollection &obj)
std::ostream & operator<< (std::ostream &os, const Node &obj)
Function Documentation
std::ostream& cryomesh::components::operator<< (std::ostream &os, const Connection &obj)"Parameters:
std::ostream & os The output stream
const Connection & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 245 of file Connection.cpp.
References cryomesh::components::Connection::getConnector(), cryomesh::components::Connection::getImpulses(), cryomesh::components::Connection::isPrimaryInputConnection(), and cryomesh::components::Connection::isPrimaryOutputConnection().
std::ostream& cryomesh::components::operator<< (std::ostream &os, const Impulse &obj)"Parameters:
std::ostream & os The output stream
const Impulse & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 339 of file Impulse.cpp.
References cryomesh::components::Impulse::getActivityDelay(), cryomesh::components::Impulse::getActivityTimer(), cryomesh::components::Impulse::getFirstActiveCycle(), and cryomesh::components::Impulse::getLastActiveCycle().
std::ostream& cryomesh::components::operator<< (std::ostream &os, const ImpulseCollection &obj)"Parameters:
std::ostream & os The output stream
const ImpulseCollection & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 375 of file ImpulseCollection.cpp.
std::ostream& cryomesh::components::operator<< (std::ostream &os, const Node &obj)"Parameters:
std::ostream & os The output stream
const Node & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 548 of file Node.cpp.
References cryomesh::components::Node::getActivityThreshold(), cryomesh::components::Node::getConnector(), cryomesh::components::Node::getImpulses(), cryomesh::components::Node::isPrimaryInputAttachedNode(), cryomesh::components::Node::isPrimaryOutputAttachedNode(), and cryomesh::components::Node::printConnections().
Author
Generated automatically by Doxygen for cryomesh from the source code.