cryomesh::components::ConnectionMap
NAME
cryomesh::components::ConnectionMap -
Helper class for ConnectionMap to KeyMappedCollection mapping.
SYNOPSIS
#include <ConnectionMap.h>
Inherits KeyMappedCollection< boost::uuids::uuid, components::Connection >.
Public Member Functions
ConnectionMap ()
virtual ~ConnectionMap ()
virtual void update ()
boost::shared_ptr< state::ActivityPattern > getActivityPattern () const
Get activity pattern on current cycle.
boost::shared_ptr< state::ActivityPattern > getActivityPattern (const common::Cycle &cycle) const
Get activity pattern on cycle.
void clear ()
Clear all objects from collection.
boost::shared_ptr< components::Connection > add (boost::shared_ptr< components::Connection > obj)
Add object to collection.
virtual void add (const std::initializer_list< boost::shared_ptr< components::Connection > > &list)
Add object to collection by initialiser list.
virtual void add (const std::list< boost::shared_ptr< components::Connection > > &list)
Add object to collection by list.
virtual void remove (const std::initializer_list< boost::shared_ptr< components::Connection > > &list)
Remove objects from collection by initialiser list.
virtual void remove (const std::list< boost::shared_ptr< components::Connection > > &list)
Remove objects from collection by list.
boost::shared_ptr< components::Connection > remove (boost::shared_ptr< components::Connection > obj)
Add object to collection.
boost::shared_ptr< components::Connection > remove (components::Connection &obj)
Remove object from collection.
boost::shared_ptr< components::Connection > remove (boost::uuids::uuidkey)
Remove object from collection bt key.
std::list< boost::uuids::uuid > getKeyList () const
Get keys for underlying connection.
std::vector< boost::shared_ptr< components::Connection > > getObjectList () const
Get object list for underlying connection.
boost::shared_ptr< components::Connection > getObjectByKey (const boost::uuids::uuid &key)
Get object using key.
std::vector< boost::shared_ptr< components::Connection > > getRandomRange (int number) const
const std::map< boost::uuids::uuid, boost::shared_ptr< components::Connection > > & getCollection () const
Get maximum value.
std::map< boost::uuids::uuid, boost::shared_ptr< components::Connection > > & getMutableCollection ()
Get mutable underlying collection.
int getSize () const
Get underlying collections size.
Protected Attributes
std::map< boost::uuids::uuid, boost::shared_ptr< components::Connection > > objects
Friends
std::ostream & operator<< (std::ostream &os, const ConnectionMap &obj)
To stream operator.
Detailed Description
Helper class for ConnectionMap to KeyMappedCollection mapping.
Definition at line 26 of file ConnectionMap.h.
Constructor & Destructor Documentation
cryomesh::components::ConnectionMap::ConnectionMap () [inline]
Definition at line 28 of file ConnectionMap.h.
virtual cryomesh::components::ConnectionMap::~ConnectionMap () [inline, virtual]
Definition at line 30 of file ConnectionMap.h.
Member Function Documentation
boost::shared_ptr<components::Connection > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::add (boost::shared_ptr< components::Connection >obj) [inline, inherited]
Add object to collection. Parameters:
boost::shared_ptr<T> obj The object to be added to the collection
Returns:
boost::shared_ptr<T> The object added to the collection
Definition at line 59 of file KeyMappedCollection.h.
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::add (const std::initializer_list< boost::shared_ptr< components::Connection > > &list) [inline, virtual, inherited]
Add object to collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be added to the collection
Definition at line 70 of file KeyMappedCollection.h.
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::add (const std::list< boost::shared_ptr< components::Connection > > &list) [inline, virtual, inherited]
Add object to collection by list. Parameters:
std::list<T> list The list values to be added to the collection
Definition at line 88 of file KeyMappedCollection.h.
void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::clear () [inline, inherited]
Clear all objects from collection.
Definition at line 45 of file KeyMappedCollection.h.
boost::shared_ptr<state::ActivityPattern> cryomesh::components::ConnectionMap::getActivityPattern () const [inline]
Get activity pattern on current cycle. @ param const Cycle & cycle Cycle to get activity on
Definition at line 55 of file ConnectionMap.h.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by cryomesh::structures::operator<<().
boost::shared_ptr<state::ActivityPattern> cryomesh::components::ConnectionMap::getActivityPattern (const common::Cycle &cycle) const [inline]
Get activity pattern on cycle. @ param const Cycle & cycle Cycle to get activity on
Definition at line 65 of file ConnectionMap.h.
References cryomesh::common::KeyMappedCollection< boost::uuids::uuid, components::Connection >::getCollection().
const std::map<boost::uuids::uuid , boost::shared_ptr<components::Connection > >& cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::getCollection () const [inline, inherited]
Get maximum value. Returns:
T The maximum value Get underlying collection
const std::map<U, boost::shared_ptr<T> > & The collection
Definition at line 309 of file KeyMappedCollection.h.
Referenced by getActivityPattern().
std::list<boost::uuids::uuid > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::getKeyList () const [inline, inherited]
Get keys for underlying connection. Returns:
std::list<U> The list of keys
Definition at line 208 of file KeyMappedCollection.h.
std::map<boost::uuids::uuid , boost::shared_ptr<components::Connection > >& cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::getMutableCollection () [inline, inherited]
Get mutable underlying collection. Returns:
const std::map<U, boost::shared_ptr<T> > & The mutable collection
Definition at line 319 of file KeyMappedCollection.h.
boost::shared_ptr<components::Connection > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::getObjectByKey (const boost::uuids::uuid &key) [inline, inherited]
Get object using key. Parameters:
U key Key to search for
Returns:
boost::shared_ptr<T> The found object
Definition at line 250 of file KeyMappedCollection.h.
std::vector<boost::shared_ptr<components::Connection > > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::getObjectList () const [inline, inherited]
Get object list for underlying connection. Returns:
std::list<U> The list of object values
Definition at line 228 of file KeyMappedCollection.h.
std::vector<boost::shared_ptr<components::Connection > > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::getRandomRange (intnumber) const [inline, inherited]
Definition at line 261 of file KeyMappedCollection.h.
int cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::getSize () const [inline, inherited]
Get underlying collections size. Returns:
int The collections size
Definition at line 329 of file KeyMappedCollection.h.
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::remove (const std::list< boost::shared_ptr< components::Connection > > &list) [inline, virtual, inherited]
Remove objects from collection by list. Parameters:
std::list<T> list The list values to be removed to the collection
Definition at line 124 of file KeyMappedCollection.h.
boost::shared_ptr<components::Connection > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::remove (boost::shared_ptr< components::Connection >obj) [inline, inherited]
Add object to collection. Parameters:
T & refobj The object to be added to the collection
Returns:
boost::shared_ptr<T> The object added to the collection
boost::shared_ptr<T> add(T & refobj) { boost::shared_ptr<T> obj = boost::shared_ptr<T>(&refobj); objects[obj->getKey()] = obj; return objects.find(obj->getKey())->second; } Remove object from collection
Parameters:
boost::shared_ptr<T> obj The object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 163 of file KeyMappedCollection.h.
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::remove (const std::initializer_list< boost::shared_ptr< components::Connection > > &list) [inline, virtual, inherited]
Remove objects from collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be removed from the collection
Definition at line 106 of file KeyMappedCollection.h.
boost::shared_ptr<components::Connection > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::remove (boost::uuids::uuidkey) [inline, inherited]
Remove object from collection bt key. Parameters:
U key The ey of the object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 191 of file KeyMappedCollection.h.
boost::shared_ptr<components::Connection > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::remove (components::Connection &obj) [inline, inherited]
Remove object from collection. Parameters:
T & obj The object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 177 of file KeyMappedCollection.h.
virtual void cryomesh::components::ConnectionMap::update () [inline, virtual]
Definition at line 33 of file ConnectionMap.h.
References cryomesh::common::KeyMappedCollection< boost::uuids::uuid, components::Connection >::objects.
Referenced by cryomesh::structures::Fibre::update(), and cryomesh::structures::Cluster::update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const ConnectionMap &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const ConnectionMap & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 98 of file ConnectionMap.h.
Member Data Documentation
std::map<boost::uuids::uuid , boost::shared_ptr<components::Connection > > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , components::Connection >::objects [protected, inherited]
Definition at line 339 of file KeyMappedCollection.h.
Referenced by update().
Author
Generated automatically by Doxygen for cryomesh from the source code.