cryomesh::state::Sequence
NAME
cryomesh::state::Sequence -
SYNOPSIS
#include <Sequence.h>
Public Member Functions
Sequence ()
virtual ~Sequence ()
Sequence (const Sequence &seq)
Sequence (const std::vector< Pattern > &input_pats, const std::vector< Pattern > &output_pats)
Sequence (std::ifstream &ifs)
Sequence & operator= (const Sequence &seq)
const Pattern & getCurrentInputPattern () const
const Pattern & getCurrentOutputPattern () const
const Pattern & getAndAdvanceCurrentInputPattern ()
const Pattern & getAndAdvanceCurrentOutputPattern ()
int getCurrentInputPatternId () const
int getCurrentOutputPatternId () const
std::list< std::pair< Pattern,
Pattern > >::const_iterator getCurrentIterator () const "
void setCurrentIterator (std::list< std::pair< Pattern, Pattern > >::const_iterator)
const Pattern & getNextInputPattern ()
const std::list< std::pair
< Pattern, Pattern > > & getPatterns () const "
void setPatterns (const std::list< std::pair< Pattern, Pattern > > &pats)
void saveToFile (std::ofstream &ofs) const
void loadFromFile (std::ifstream &ifs)
void addEntry (Pattern new_in_pat, Pattern new_out_pat)
void clear ()
double compareOutput (const Sequence &seq) const
double compareInput (const Sequence &seq) const
double compare (const Sequence &seq) const
double compare (int id, const Pattern &pat) const
bool operator== (const Sequence &obj) const
bool isAllZeroes () const
bool isInputAllZeroes () const
bool isOutputAllZeroes () const
Static Public Attributes
static const std::string INPUT_TAG = '<input>'
static const std::string OUTPUT_TAG = '<output>'
Private Member Functions
template<class Archive > void serialize (Archive &ar, const unsigned int version)
void initialise ()
Private Attributes
std::list< std::pair< Pattern,
Pattern > > patterns"
std::list< std::pair< Pattern,
Pattern > >::const_iterator it_patterns"
Friends
class boost::serialization::access
std::ostream & operator<< (std::ostream &os, const Sequence &obj)
Detailed Description
Definition at line 26 of file Sequence.h.
Constructor & Destructor Documentation
cryomesh::state::Sequence::Sequence ()
Definition at line 17 of file Sequence.cpp.
References initialise().
cryomesh::state::Sequence::~Sequence () [virtual]
Definition at line 20 of file Sequence.cpp.
cryomesh::state::Sequence::Sequence (const Sequence &seq)
Definition at line 22 of file Sequence.cpp.
References initialise().
cryomesh::state::Sequence::Sequence (const std::vector< Pattern > &input_pats, const std::vector< Pattern > &output_pats)
Definition at line 25 of file Sequence.cpp.
References initialise(), and patterns.
cryomesh::state::Sequence::Sequence (std::ifstream &ifs)
Definition at line 44 of file Sequence.cpp.
References initialise(), and loadFromFile().
Member Function Documentation
void cryomesh::state::Sequence::addEntry (Patternnew_in_pat, Patternnew_out_pat)
Definition at line 150 of file Sequence.cpp.
References patterns.
void cryomesh::state::Sequence::clear ()
Definition at line 156 of file Sequence.cpp.
References it_patterns, and patterns.
double cryomesh::state::Sequence::compare (const Sequence &seq) const
Definition at line 253 of file Sequence.cpp.
References getPatterns().
double cryomesh::state::Sequence::compare (intid, const Pattern &pat) const
Definition at line 331 of file Sequence.cpp.
References getPatterns().
double cryomesh::state::Sequence::compareInput (const Sequence &seq) const
Definition at line 209 of file Sequence.cpp.
References getPatterns().
double cryomesh::state::Sequence::compareOutput (const Sequence &seq) const
Definition at line 163 of file Sequence.cpp.
References getPatterns().
const Pattern & cryomesh::state::Sequence::getAndAdvanceCurrentInputPattern ()
Definition at line 62 of file Sequence.cpp.
References getCurrentIterator(), and it_patterns.
const Pattern & cryomesh::state::Sequence::getAndAdvanceCurrentOutputPattern ()
Definition at line 70 of file Sequence.cpp.
References getCurrentIterator(), and it_patterns.
const Pattern & cryomesh::state::Sequence::getCurrentInputPattern () const
Definition at line 59 of file Sequence.cpp.
References getCurrentIterator().
Referenced by getNextInputPattern().
int cryomesh::state::Sequence::getCurrentInputPatternId () const
Definition at line 75 of file Sequence.cpp.
References getCurrentIterator().
std::list< std::pair< Pattern, Pattern > >::const_iterator cryomesh::state::Sequence::getCurrentIterator () const
Definition at line 83 of file Sequence.cpp.
References it_patterns.
Referenced by getAndAdvanceCurrentInputPattern(), getAndAdvanceCurrentOutputPattern(), getCurrentInputPattern(), getCurrentInputPatternId(), getCurrentOutputPattern(), getCurrentOutputPatternId(), and getNextInputPattern().
const Pattern & cryomesh::state::Sequence::getCurrentOutputPattern () const
Definition at line 67 of file Sequence.cpp.
References getCurrentIterator().
int cryomesh::state::Sequence::getCurrentOutputPatternId () const
Definition at line 79 of file Sequence.cpp.
References getCurrentIterator().
const Pattern & cryomesh::state::Sequence::getNextInputPattern ()
Definition at line 86 of file Sequence.cpp.
References getCurrentInputPattern(), getCurrentIterator(), getPatterns(), it_patterns, patterns, and setCurrentIterator().
const std::list< std::pair< Pattern, Pattern > > & cryomesh::state::Sequence::getPatterns () const
Definition at line 93 of file Sequence.cpp.
References patterns.
Referenced by compare(), compareInput(), compareOutput(), getNextInputPattern(), cryomesh::state::operator<<(), operator=(), operator==(), and saveToFile().
void cryomesh::state::Sequence::initialise () [private]
Definition at line 437 of file Sequence.cpp.
References it_patterns, and patterns.
Referenced by loadFromFile(), operator=(), Sequence(), and setPatterns().
bool cryomesh::state::Sequence::isAllZeroes () const
Definition at line 392 of file Sequence.cpp.
References it_patterns, and patterns.
bool cryomesh::state::Sequence::isInputAllZeroes () const
Definition at line 407 of file Sequence.cpp.
References it_patterns, and patterns.
bool cryomesh::state::Sequence::isOutputAllZeroes () const
Definition at line 422 of file Sequence.cpp.
References it_patterns, and patterns.
void cryomesh::state::Sequence::loadFromFile (std::ifstream &ifs)
Definition at line 116 of file Sequence.cpp.
References initialise(), and patterns.
Referenced by Sequence().
Sequence & cryomesh::state::Sequence::operator= (const Sequence &seq)
Definition at line 50 of file Sequence.cpp.
References getPatterns(), initialise(), and patterns.
bool cryomesh::state::Sequence::operator== (const Sequence &obj) const
Definition at line 349 of file Sequence.cpp.
References getPatterns().
void cryomesh::state::Sequence::saveToFile (std::ofstream &ofs) const
Definition at line 100 of file Sequence.cpp.
References getPatterns().
template<class Archive > void cryomesh::state::Sequence::serialize (Archive &ar, const unsigned intversion) [inline, private]
Definition at line 29 of file Sequence.h.
References patterns.
void cryomesh::state::Sequence::setCurrentIterator (std::list< std::pair< Pattern, Pattern > >::const_iteratorit)
Definition at line 447 of file Sequence.cpp.
References it_patterns.
Referenced by getNextInputPattern().
void cryomesh::state::Sequence::setPatterns (const std::list< std::pair< Pattern, Pattern > > &pats)
Definition at line 96 of file Sequence.cpp.
References initialise(), and patterns.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 27 of file Sequence.h.
std::ostream& operator<< (std::ostream &os, const Sequence &obj) [friend]
Definition at line 380 of file Sequence.cpp.
Member Data Documentation
const std::string cryomesh::state::Sequence::INPUT_TAG = '<input>' [static]
Definition at line 122 of file Sequence.h.
std::list<std::pair<Pattern, Pattern> >::const_iterator cryomesh::state::Sequence::it_patterns [private]
Definition at line 134 of file Sequence.h.
Referenced by clear(), getAndAdvanceCurrentInputPattern(), getAndAdvanceCurrentOutputPattern(), getCurrentIterator(), getNextInputPattern(), initialise(), isAllZeroes(), isInputAllZeroes(), isOutputAllZeroes(), and setCurrentIterator().
const std::string cryomesh::state::Sequence::OUTPUT_TAG = '<output>' [static]
Definition at line 123 of file Sequence.h.
std::list<std::pair<Pattern, Pattern> > cryomesh::state::Sequence::patterns [private]
Definition at line 130 of file Sequence.h.
Referenced by addEntry(), clear(), getNextInputPattern(), getPatterns(), initialise(), isAllZeroes(), isInputAllZeroes(), isOutputAllZeroes(), loadFromFile(), operator=(), Sequence(), serialize(), and setPatterns().
Author
Generated automatically by Doxygen for cryomesh from the source code.