.TH "cryomesh::common::Comparators< T >" 3 "Fri Jan 28 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::common::Comparators< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Comparators.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComparators\fP ()"
.br
.ti -1c
.RI "virtual \fB~Comparators\fP ()"
.br
.ti -1c
.RI "bool \fBisEqual\fP (const T &obj) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Comparators.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::common::Comparators< T >::Comparators ()"
.SS "virtual cryomesh::common::Comparators< T >::~Comparators ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "bool cryomesh::common::Comparators< T >::isEqual (const T &obj) const\fC [pure virtual]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
