cryomesh::common::TimeKeeper
NAME
cryomesh::common::TimeKeeper -
TimeKeeper is a class keep track of the cycle state and timing.
SYNOPSIS
#include <TimeKeeper.h>
Public Member Functions
void reset ()
Destructor.
virtual ~TimeKeeper ()
bool operator== (const TimeKeeper &)
Equality test override for object.
void update ()
Move the timing on one cycle.
Cycle getCycle () const
Get the current cycle we're on as an Cycle.
std::time_t getStartTime () const
Get the time we started cycling.
double getTiming () const
Difference between the last time and now.
const boost::timer & getTimer () const
Get the Timer.
Static Public Member Functions
static TimeKeeper & getTimeKeeper ()
Protected Member Functions
TimeKeeper ()
Constructor.
TimeKeeper (const TimeKeeper &)
Copy Constructor.
TimeKeeper & operator= (const TimeKeeper &)
Assignment Operator.
Private Attributes
Cycle cycle
std::time_t start_time
boost::timer timer
double this_timing
double last_timing
Static Private Attributes
static boost::shared_ptr
< TimeKeeper > timekeeper"
Detailed Description
TimeKeeper is a class keep track of the cycle state and timing.
TimeKeeper manages the 'tick' cycle and provides the means by which classes throughout the system can keep track of the cycle
Definition at line 31 of file TimeKeeper.h.
Constructor & Destructor Documentation
cryomesh::common::TimeKeeper::~TimeKeeper () [virtual]
Definition at line 37 of file TimeKeeper.cpp.
cryomesh::common::TimeKeeper::TimeKeeper () [protected]
Constructor. Constructor for TimeKeeper. Inaccessible to force singleton class
Definition at line 34 of file TimeKeeper.cpp.
References reset().
Referenced by getTimeKeeper().
cryomesh::common::TimeKeeper::TimeKeeper (const TimeKeeper &) [protected]
Copy Constructor. Overridden Copy Contructor for TimeKeeper. Inaccessible to force singleton class
Parameters:
TimeKeeper Object to Copy Construct from
Member Function Documentation
Cycle cryomesh::common::TimeKeeper::getCycle () const
Get the current cycle we're on as an Cycle. Returns:
Cycle The cycle we're currently on
Definition at line 76 of file TimeKeeper.cpp.
References cycle.
Referenced by cryomesh::manager::DatabaseManager::addHistoryEntry(), cryomesh::components::ImpulseCollection::clearActiveImpulses(), cryomesh::components::ImpulseCollection::clearImpulses(), cryomesh::components::ImpulseCollection::getActivity(), cryomesh::state::Pattern::getDatabaseObject(), cryomesh::components::Connection::getDatabaseObject(), cryomesh::components::Node::getDatabaseObject(), cryomesh::state::PatternChannel::getPatternByCycle(), cryomesh::utilities::operator<<(), cryomesh::structures::Bundle::print(), cryomesh::manager::DatabaseManager::printHistory(), and cryomesh::components::ImpulseCollection::refreshDataObject().
std::time_t cryomesh::common::TimeKeeper::getStartTime () const
Get the time we started cycling. Returns:
time_t The start time
Definition at line 83 of file TimeKeeper.cpp.
References start_time.
TimeKeeper & cryomesh::common::TimeKeeper::getTimeKeeper () [static]
Definition at line 19 of file TimeKeeper.cpp.
References TimeKeeper(), and timekeeper.
Referenced by cryomesh::manager::DatabaseManager::addHistoryEntry(), cryomesh::components::Node::addImpulse(), cryomesh::components::ImpulseCollection::clearActiveImpulses(), cryomesh::components::ImpulseCollection::clearImpulses(), cryomesh::components::Node::enterRecovery(), cryomesh::components::ImpulseCollection::getActivity(), cryomesh::components::Impulse::getActivity(), cryomesh::components::Node::getActivity(), cryomesh::components::ConnectionMap::getActivityPattern(), cryomesh::state::Pattern::getDatabaseObject(), cryomesh::components::Connection::getDatabaseObject(), cryomesh::components::Node::getDatabaseObject(), cryomesh::state::PatternChannel::getPatternByCycle(), cryomesh::components::Impulse::isActive(), cryomesh::utilities::operator<<(), cryomesh::structures::Bundle::print(), cryomesh::manager::DatabaseManager::printHistory(), cryomesh::components::ImpulseCollection::refreshDataObject(), cryomesh::components::Node::setActivity(), and cryomesh::structures::Bundle::update().
const boost::timer & cryomesh::common::TimeKeeper::getTimer () const
Get the Timer. Returns:
boost::Timer
Definition at line 87 of file TimeKeeper.cpp.
References timer.
double cryomesh::common::TimeKeeper::getTiming () const
Difference between the last time and now. Returns:
double The difference between the clock now and the last clock
Definition at line 80 of file TimeKeeper.cpp.
References last_timing, and this_timing.
TimeKeeper& cryomesh::common::TimeKeeper::operator= (const TimeKeeper &) [protected]
Assignment Operator. Overridden Assignment Operator for TimeKeeper. Inaccessible to force singleton class
Parameters:
TimeKeeper Object to Assign this to
bool cryomesh::common::TimeKeeper::operator== (const TimeKeeper &obj)
Equality test override for object. Parameters:
TimeKeeper obj Object to compare this with
Returns:
bool True if equal, false otherwise
Definition at line 40 of file TimeKeeper.cpp.
References cycle, last_timing, start_time, and this_timing.
void cryomesh::common::TimeKeeper::reset ()
Destructor. Destructor for TimeKeeper Reset the timekeeper
Definition at line 26 of file TimeKeeper.cpp.
References cycle, last_timing, start_time, this_timing, and timer.
Referenced by TimeKeeper().
void cryomesh::common::TimeKeeper::update ()
Move the timing on one cycle.
Definition at line 66 of file TimeKeeper.cpp.
References cycle, last_timing, this_timing, and timer.
Referenced by cryomesh::structures::Bundle::update().
Member Data Documentation
Cycle cryomesh::common::TimeKeeper::cycle [private]
Definition at line 159 of file TimeKeeper.h.
Referenced by getCycle(), operator==(), reset(), and update().
double cryomesh::common::TimeKeeper::last_timing [private]
Definition at line 187 of file TimeKeeper.h.
Referenced by getTiming(), operator==(), reset(), and update().
std::time_t cryomesh::common::TimeKeeper::start_time [private]
Definition at line 166 of file TimeKeeper.h.
Referenced by getStartTime(), operator==(), and reset().
double cryomesh::common::TimeKeeper::this_timing [private]
Definition at line 180 of file TimeKeeper.h.
Referenced by getTiming(), operator==(), reset(), and update().
boost::shared_ptr< TimeKeeper > cryomesh::common::TimeKeeper::timekeeper [static, private]
Definition at line 151 of file TimeKeeper.h.
Referenced by getTimeKeeper().
boost::timer cryomesh::common::TimeKeeper::timer [private]
Definition at line 173 of file TimeKeeper.h.
Referenced by getTimer(), reset(), and update().
Author
Generated automatically by Doxygen for cryomesh from the source code.