cryomesh::dataobjects::DataObject
NAME
cryomesh::dataobjects::DataObject -
Class to contain all the useful data about an object.
SYNOPSIS
#include <DataObject.h>
Public Types
enum ComparisonType { MaximumValue, MinimumValue, EqualityValue, AverageValue }
Enum to signal the type of comparison to make.
Public Member Functions
DataObject ()
Default contructor.
DataObject (unsigned int sz)
Contructor with max size.
virtual ~DataObject ()
Default destructor.
void enableLogging (bool enable)
Whether logging is enabled or not.
bool isLoggingEnabled ()
Check logging is enabled or not.
const std::map< U, T > & getMap () const
Get all cycle values.
std::map< U, T > & getMutableMap ()
Get all mutable cycle values.
const std::map< U, T > getMap (U start, U end) const
Get all values within a range [start, end].
const std::map< U, T > getMap (U start) const
Get all values within a range [start, ].
const T getByKey (U key) const
Get value from key.
void clear ()
Clear all data.
void insert (U key, T object)
Add entry.
unsigned int getDatasetMaximumSize () const
void setDatasetMaximumSize (unsigned int sz)
T getValueComparison (ComparisonType type) const
Get comparison values.
T getMaximumValue () const
Get maximum value.
T getMinimumValue () const
Get minimum value.
T getAverageValue () const
Get average value value.
Protected Attributes
std::map< U, T > valueMap
bool loggingEnabled
unsigned int datasetMaximumSize
Static Protected Attributes
static const unsigned int DEFAULT_DATASET_SIZE = 100
Friends
std::ostream & operator<< (std::ostream &os, const DataObject &obj)
To stream operator.
Detailed Description
template<class U, class T> class cryomesh::dataobjects::DataObject< U, T >
Class to contain all the useful data about an object.
Useful for output and plotting
Definition at line 22 of file DataObject.h.
Member Enumeration Documentation
template<class U, class T> enum cryomesh::dataobjects::DataObject< U, T >::ComparisonType
Enum to signal the type of comparison to make.
Enumerator:
MaximumValue
MinimumValue
EqualityValue
AverageValue
Definition at line 29 of file DataObject.h.
Constructor & Destructor Documentation
template<class U, class T> cryomesh::dataobjects::DataObject< U, T >::DataObject () [inline]
Default contructor.
Definition at line 36 of file DataObject.h.
template<class U, class T> cryomesh::dataobjects::DataObject< U, T >::DataObject (unsigned intsz) [inline]
Contructor with max size. Parameters:
unsigned int The maximum size of the data set
Definition at line 46 of file DataObject.h.
template<class U, class T> virtual cryomesh::dataobjects::DataObject< U, T >::~DataObject () [inline, virtual]
Default destructor.
Definition at line 53 of file DataObject.h.
Member Function Documentation
template<class U, class T> void cryomesh::dataobjects::DataObject< U, T >::clear () [inline]
Clear all data.
Definition at line 178 of file DataObject.h.
Referenced by cryomesh::components::ImpulseCollection::refreshDataObject().
template<class U, class T> void cryomesh::dataobjects::DataObject< U, T >::enableLogging (boolenable) [inline]
Whether logging is enabled or not. Parameters:
bool enable True to enable logging, false otherwise
Definition at line 62 of file DataObject.h.
template<class U, class T> T cryomesh::dataobjects::DataObject< U, T >::getAverageValue () const [inline]
Get average value value. Returns:
T The resultant value
Definition at line 284 of file DataObject.h.
template<class U, class T> const T cryomesh::dataobjects::DataObject< U, T >::getByKey (Ukey) const [inline]
Get value from key. Parameters:
U key The key to find
Returns:
T The value found
Definition at line 138 of file DataObject.h.
Referenced by cryomesh::components::Node::getActivity().
template<class U, class T> unsigned int cryomesh::dataobjects::DataObject< U, T >::getDatasetMaximumSize () const [inline]
Definition at line 213 of file DataObject.h.
Referenced by cryomesh::dataobjects::DataObject< common::Cycle, double >::insert(), and cryomesh::components::ImpulseCollection::refreshDataObject().
template<class U, class T> const std::map<U, T> cryomesh::dataobjects::DataObject< U, T >::getMap (Ustart, Uend) const [inline]
Get all values within a range [start, end]. Parameters:
U start The start cycle of the range
U end The end cycle of the range
Returns:
std::map<unsigned long int, double> The cycle values
Definition at line 106 of file DataObject.h.
template<class U, class T> const std::map<U, T>& cryomesh::dataobjects::DataObject< U, T >::getMap () const [inline]
Get all cycle values. Returns:
std::map<unsigned long int, double> & The cycle values
Definition at line 81 of file DataObject.h.
Referenced by cryomesh::components::Node::getActivities().
template<class U, class T> const std::map<U, T> cryomesh::dataobjects::DataObject< U, T >::getMap (Ustart) const [inline]
Get all values within a range [start, ]. Parameters:
U start The start cycle of the range
Returns:
std::map<unsigned long int, double> The cycle values
Definition at line 122 of file DataObject.h.
template<class U, class T> T cryomesh::dataobjects::DataObject< U, T >::getMaximumValue () const [inline]
Get maximum value. Returns:
T The resultant value
Definition at line 264 of file DataObject.h.
template<class U, class T> T cryomesh::dataobjects::DataObject< U, T >::getMinimumValue () const [inline]
Get minimum value. Returns:
T The resultant value
Definition at line 274 of file DataObject.h.
template<class U, class T> std::map<U, T>& cryomesh::dataobjects::DataObject< U, T >::getMutableMap () [inline]
Get all mutable cycle values. Returns:
std::map<U, T> & The mutable cycle values
Definition at line 91 of file DataObject.h.
template<class U, class T> T cryomesh::dataobjects::DataObject< U, T >::getValueComparison (ComparisonTypetype) const [inline]
Get comparison values. Parameters:
ComparisonType type The type of comparison to make
Returns:
T The result of the comparison
Definition at line 230 of file DataObject.h.
Referenced by cryomesh::dataobjects::DataObject< common::Cycle, double >::getAverageValue(), cryomesh::dataobjects::DataObject< common::Cycle, double >::getMaximumValue(), and cryomesh::dataobjects::DataObject< common::Cycle, double >::getMinimumValue().
template<class U, class T> void cryomesh::dataobjects::DataObject< U, T >::insert (Ukey, Tobject) [inline]
Add entry. Parameters:
unsigned int cycle The cycle the value is on
double The value
Definition at line 191 of file DataObject.h.
Referenced by cryomesh::components::Node::addActivity(), cryomesh::components::ImpulseCollection::refreshDataObject(), and cryomesh::components::Node::update().
template<class U, class T> bool cryomesh::dataobjects::DataObject< U, T >::isLoggingEnabled () [inline]
Check logging is enabled or not. Returns:
bool enable Trueif logging enabled, flase otherwise
Definition at line 71 of file DataObject.h.
Referenced by cryomesh::components::ImpulseCollection::refreshDataObject(), and cryomesh::components::Node::update().
template<class U, class T> void cryomesh::dataobjects::DataObject< U, T >::setDatasetMaximumSize (unsigned intsz) [inline]
Definition at line 217 of file DataObject.h.
Referenced by cryomesh::components::Node::Node().
Friends And Related Function Documentation
template<class U, class T> std::ostream& operator<< (std::ostream &os, const DataObject< U, T > &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const DataObject & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 159 of file DataObject.h.
Member Data Documentation
template<class U, class T> unsigned int cryomesh::dataobjects::DataObject< U, T >::datasetMaximumSize [protected]
Definition at line 307 of file DataObject.h.
Referenced by cryomesh::dataobjects::DataObject< common::Cycle, double >::getDatasetMaximumSize(), and cryomesh::dataobjects::DataObject< common::Cycle, double >::setDatasetMaximumSize().
template<class U, class T> const unsigned int cryomesh::dataobjects::DataObject< U, T >::DEFAULT_DATASET_SIZE = 100 [static, protected]
Definition at line 314 of file DataObject.h.
template<class U, class T> bool cryomesh::dataobjects::DataObject< U, T >::loggingEnabled [protected]
Definition at line 300 of file DataObject.h.
Referenced by cryomesh::dataobjects::DataObject< common::Cycle, double >::enableLogging(), and cryomesh::dataobjects::DataObject< common::Cycle, double >::isLoggingEnabled().
template<class U, class T> std::map<U, T> cryomesh::dataobjects::DataObject< U, T >::valueMap [protected]
Definition at line 293 of file DataObject.h.
Referenced by cryomesh::dataobjects::DataObject< common::Cycle, double >::clear(), cryomesh::dataobjects::DataObject< common::Cycle, double >::getByKey(), cryomesh::dataobjects::DataObject< common::Cycle, double >::getMap(), cryomesh::dataobjects::DataObject< common::Cycle, double >::getMutableMap(), cryomesh::dataobjects::DataObject< common::Cycle, double >::getValueComparison(), and cryomesh::dataobjects::DataObject< common::Cycle, double >::insert().
Author
Generated automatically by Doxygen for cryomesh from the source code.