cryomesh::common::Maths
NAME
cryomesh::common::Maths -
Maths contains some useful maths functions and algorithmns.
SYNOPSIS
#include <Maths.h>
Public Member Functions
Maths ()
virtual ~Maths ()
Static Public Member Functions
static bool compareDoubles (const double lhs, const double rhs, const double delta=0.00001)
Compare doubles using delta.
static int getRandomInteger (int low, int high)
static double getRandomDouble (double low, double high)
static bool getRandomBool (double fraction=0.5)
Detailed Description
Maths contains some useful maths functions and algorithmns.
Definition at line 18 of file Maths.h.
Constructor & Destructor Documentation
cryomesh::common::Maths::Maths ()
virtual cryomesh::common::Maths::~Maths () [virtual]
Member Function Documentation
static bool cryomesh::common::Maths::compareDoubles (const doublelhs, const doublerhs, const doubledelta = 0.00001) [inline, static]
Compare doubles using delta. Parameters:
const double lhs lhs comparator
const double rhs rhs comparator
const double delta comparison delta
Returns:
bool True if lhs and rhs compare within delta margin, false otherwise
Definition at line 36 of file Maths.h.
Referenced by cryomesh::components::ImpulseCollection::getByActivityTimerValue(), and cryomesh::components::Impulse::operator==().
static bool cryomesh::common::Maths::getRandomBool (doublefraction = 0.5) [inline, static]
Definition at line 66 of file Maths.h.
References getRandomDouble().
Referenced by cryomesh::state::Pattern::getRandom().
static double cryomesh::common::Maths::getRandomDouble (doublelow, doublehigh) [inline, static]
Definition at line 54 of file Maths.h.
Referenced by cryomesh::components::Node::getRandom(), getRandomBool(), and cryomesh::components::Impulse::randomise().
static int cryomesh::common::Maths::getRandomInteger (intlow, inthigh) [inline, static]
Definition at line 43 of file Maths.h.
Referenced by cryomesh::components::Impulse::randomise().
Author
Generated automatically by Doxygen for cryomesh from the source code.