.TH "cryomesh::components::ActivityTimerDistance" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::ActivityTimerDistance \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ActivityTimerDistance\&.h>\fP
.PP
Inherits \fBcryomesh::components::ActivityTimer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActivityTimerDistance\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBActivityTimerDistance\fP (double dist, double dec)"
.br
.RI "\fIConstruct from an initial distance, and a rate of decrement\&. \fP"
.ti -1c
.RI "virtual \fB~ActivityTimerDistance\fP ()"
.br
.ti -1c
.RI "\fBActivityTimerDistance\fP & \fBoperator=\fP (const \fBActivityTimerDistance\fP &obj)"
.br
.RI "\fIAssignment operator\&. \fP"
.ti -1c
.RI "bool \fBoperator<\fP (const \fBActivityTimerDistance\fP &obj) const "
.br
.RI "\fILess than operator\&. \fP"
.ti -1c
.RI "bool \fBoperator>\fP (const \fBActivityTimerDistance\fP &obj) const "
.br
.RI "\fIGreater than operator\&. \fP"
.ti -1c
.RI "\fBActivityTimerDistance\fP & \fBoperator--\fP ()"
.br
.RI "\fIPrefix increment operator\&. \fP"
.ti -1c
.RI "\fBActivityTimerDistance\fP \fBoperator--\fP (int)"
.br
.RI "\fIPostfix decrement operator\&. \fP"
.ti -1c
.RI "const \fBActivityTimerDistance\fP \fBoperator+\fP (const \fBActivityTimerDistance\fP &obj) const "
.br
.RI "\fINon-destructive addition operator\&. \fP"
.ti -1c
.RI "\fBActivityTimerDistance\fP & \fBoperator+=\fP (const \fBActivityTimerDistance\fP &obj)"
.br
.RI "\fIDestructive addition and assignment operator\&. \fP"
.ti -1c
.RI "double \fBgetDelay\fP () const "
.br
.RI "\fIGet the delay\&. \fP"
.ti -1c
.RI "double \fBgetStartingDelay\fP () const "
.br
.RI "\fIGet the starting delay\&. \fP"
.ti -1c
.RI "double \fBgetDecrement\fP () const "
.br
.RI "\fIGet the decrement\&. \fP"
.ti -1c
.RI "void \fBreset\fP ()"
.br
.RI "\fIReset the countdown\&. \fP"
.ti -1c
.RI "virtual bool \fBcheckConstraints\fP () const "
.br
.ti -1c
.RI "virtual void \fBenableDebug\fP (bool b)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boost::shared_ptr
.br
< \fBActivityTimerDistance\fP > \fBgetRandom\fP ()"
.br
.RI "\fIGet a random object\&. \fP"
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const double \fBMIN_DECREMENT_FRACTION\fP = 0\&.1"
.br
.ti -1c
.RI "static const double \fBMAX_DECREMENT_FRACTION\fP = 1"
.br
.ti -1c
.RI "static const double \fBMIN_DISTANCE\fP = 1\&.0"
.br
.ti -1c
.RI "static const double \fBMAX_DISTANCE\fP = 100\&.0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual std::ostream & \fBprint\fP (std::ostream &os) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBdistance\fP"
.br
.ti -1c
.RI "double \fBdistance_remaining\fP"
.br
.ti -1c
.RI "double \fBdecrement\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBActivityTimer\fP &obj)"
.br
.RI "\fITo stream operator\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file ActivityTimerDistance\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::components::ActivityTimerDistance::ActivityTimerDistance\fP ()"
.PP
Constructor\&. 
.PP
Definition at line 36 of file ActivityTimerDistance\&.cpp\&.
.PP
Referenced by getRandom()\&.
.SS "\fBcryomesh::components::ActivityTimerDistance::ActivityTimerDistance\fP (doubledist, doubledec)"
.PP
Construct from an initial distance, and a rate of decrement\&. 
.PP
Definition at line 40 of file ActivityTimerDistance\&.cpp\&.
.SS "\fBcryomesh::components::ActivityTimerDistance::~ActivityTimerDistance\fP ()\fC [virtual]\fP"
.PP
Definition at line 44 of file ActivityTimerDistance\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool \fBcryomesh::components::ActivityTimerDistance::checkConstraints\fP () const\fC [virtual]\fP"
.PP
Definition at line 113 of file ActivityTimerDistance\&.cpp\&.
.PP
References getDecrement(), getStartingDelay(), and MIN_DISTANCE\&.
.SS "void \fBcryomesh::components::ActivityTimerDistance::enableDebug\fP (boolb)\fC [virtual]\fP"
.PP
Definition at line 101 of file ActivityTimerDistance\&.cpp\&.
.SS "double \fBcryomesh::components::ActivityTimerDistance::getDecrement\fP () const"
.PP
Get the decrement\&. \fBReturns:\fP
.RS 4
double The decrement of the timer 
.RE
.PP

.PP
Definition at line 98 of file ActivityTimerDistance\&.cpp\&.
.PP
References decrement\&.
.PP
Referenced by checkConstraints(), and print()\&.
.SS "double \fBcryomesh::components::ActivityTimerDistance::getDelay\fP () const"
.PP
Get the delay\&. \fBReturns:\fP
.RS 4
double The distance delay 
.RE
.PP

.PP
Definition at line 90 of file ActivityTimerDistance\&.cpp\&.
.PP
References distance_remaining\&.
.PP
Referenced by print()\&.
.SS "boost::shared_ptr< \fBActivityTimerDistance\fP > \fBcryomesh::components::ActivityTimerDistance::getRandom\fP ()\fC [static]\fP"
.PP
Get a random object\&. \fBReturns:\fP
.RS 4
boost::shared_ptr<ActivityTimerDistance> The random object 
.RE
.PP

.PP
Definition at line 22 of file ActivityTimerDistance\&.cpp\&.
.PP
References ActivityTimerDistance(), MAX_DECREMENT_FRACTION, MAX_DISTANCE, MIN_DECREMENT_FRACTION, and MIN_DISTANCE\&.
.SS "double \fBcryomesh::components::ActivityTimerDistance::getStartingDelay\fP () const"
.PP
Get the starting delay\&. \fBReturns:\fP
.RS 4
double The starting distance delay 
.RE
.PP

.PP
Definition at line 94 of file ActivityTimerDistance\&.cpp\&.
.PP
References distance\&.
.PP
Referenced by checkConstraints(), and print()\&.
.SS "const \fBActivityTimerDistance\fP cryomesh::components::ActivityTimerDistance::operator+ (const \fBActivityTimerDistance\fP &obj) const"
.PP
Non-destructive addition operator\&. \fBParameters:\fP
.RS 4
\fIconst\fP \fBActivityTimerDistance\fP & obj RHS addition
.RE
.PP
\fBReturns:\fP
.RS 4
\fBActivityTimerDistance\fP New object after addition 
.RE
.PP

.PP
Definition at line 76 of file ActivityTimerDistance\&.cpp\&.
.SS "\fBActivityTimerDistance\fP & cryomesh::components::ActivityTimerDistance::operator+= (const \fBActivityTimerDistance\fP &obj)"
.PP
Destructive addition and assignment operator\&. \fBParameters:\fP
.RS 4
\fIconst\fP \fBActivityTimerDistance\fP & obj RHS addition
.RE
.PP
\fBReturns:\fP
.RS 4
\fBActivityTimerDistance\fP & This object after addition and assignment 
.RE
.PP

.PP
Definition at line 82 of file ActivityTimerDistance\&.cpp\&.
.PP
References decrement, distance, and distance_remaining\&.
.SS "\fBActivityTimerDistance\fP & cryomesh::components::ActivityTimerDistance::operator-- ()"
.PP
Prefix increment operator\&. \fBReturns:\fP
.RS 4
\fBActivityTimerDistance\fP & Return this 
.RE
.PP

.PP
Definition at line 62 of file ActivityTimerDistance\&.cpp\&.
.PP
References decrement, and distance_remaining\&.
.SS "\fBActivityTimerDistance\fP cryomesh::components::ActivityTimerDistance::operator-- (int)"
.PP
Postfix decrement operator\&. \fBReturns:\fP
.RS 4
\fBActivityTimerDistance\fP & Return this 
.RE
.PP

.PP
Definition at line 70 of file ActivityTimerDistance\&.cpp\&.
.SS "bool cryomesh::components::ActivityTimerDistance::operator< (const \fBActivityTimerDistance\fP &obj) const"
.PP
Less than operator\&. \fBParameters:\fP
.RS 4
\fIconst\fP \fBActivityTimerDistance\fP & obj RHS
.RE
.PP
\fBReturns:\fP
.RS 4
bool True if < than obj, false otherwise 
.RE
.PP

.PP
Definition at line 54 of file ActivityTimerDistance\&.cpp\&.
.PP
References distance\&.
.SS "\fBActivityTimerDistance\fP & cryomesh::components::ActivityTimerDistance::operator= (const \fBActivityTimerDistance\fP &obj)"
.PP
Assignment operator\&. \fBParameters:\fP
.RS 4
\fIconst\fP \fBActivityTimerDistance\fP & obj RHS assignment
.RE
.PP
\fBReturns:\fP
.RS 4
\fBActivityTimerDistance\fP & This object after assignment 
.RE
.PP

.PP
Definition at line 47 of file ActivityTimerDistance\&.cpp\&.
.PP
References decrement, distance, and distance_remaining\&.
.SS "bool cryomesh::components::ActivityTimerDistance::operator> (const \fBActivityTimerDistance\fP &obj) const"
.PP
Greater than operator\&. \fBParameters:\fP
.RS 4
\fIconst\fP \fBActivityTimerDistance\fP & obj RHS
.RE
.PP
\fBReturns:\fP
.RS 4
bool True if > than obj, false otherwise 
.RE
.PP

.PP
Definition at line 58 of file ActivityTimerDistance\&.cpp\&.
.PP
References distance_remaining\&.
.SS "std::ostream & \fBcryomesh::components::ActivityTimerDistance::print\fP (std::ostream &os) const\fC [protected, virtual]\fP"
.PP
Implements \fBcryomesh::components::ActivityTimer\fP\&.
.PP
Definition at line 107 of file ActivityTimerDistance\&.cpp\&.
.PP
References getDecrement(), getDelay(), and getStartingDelay()\&.
.SS "void \fBcryomesh::components::ActivityTimerDistance::reset\fP ()\fC [virtual]\fP"
.PP
Reset the countdown\&. 
.PP
Implements \fBcryomesh::components::ActivityTimer\fP\&.
.PP
Definition at line 104 of file ActivityTimerDistance\&.cpp\&.
.PP
References distance, and distance_remaining\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBActivityTimer\fP &obj)\fC [friend, inherited]\fP"
.PP
To stream operator\&. \fBParameters:\fP
.RS 4
\fIstd::ostream\fP & os The output stream 
.br
\fIconst\fP \fBActivityTimer\fP & obj The object to stream
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream & The output stream 
.RE
.PP

.PP
Definition at line 47 of file ActivityTimer\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBcryomesh::components::ActivityTimerDistance::decrement\fP\fC [private]\fP"
.PP
Definition at line 196 of file ActivityTimerDistance\&.h\&.
.PP
Referenced by getDecrement(), operator+=(), operator--(), and operator=()\&.
.SS "double \fBcryomesh::components::ActivityTimerDistance::distance\fP\fC [private]\fP"
.PP
Definition at line 181 of file ActivityTimerDistance\&.h\&.
.PP
Referenced by getStartingDelay(), operator+=(), operator<(), operator=(), and reset()\&.
.SS "double \fBcryomesh::components::ActivityTimerDistance::distance_remaining\fP\fC [private]\fP"
.PP
Definition at line 188 of file ActivityTimerDistance\&.h\&.
.PP
Referenced by getDelay(), operator+=(), operator--(), operator=(), operator>(), and reset()\&.
.SS "const double \fBcryomesh::components::ActivityTimerDistance::MAX_DECREMENT_FRACTION\fP = 1\fC [static]\fP"
.PP
Definition at line 156 of file ActivityTimerDistance\&.h\&.
.PP
Referenced by getRandom()\&.
.SS "const double \fBcryomesh::components::ActivityTimerDistance::MAX_DISTANCE\fP = 100\&.0\fC [static]\fP"
.PP
Definition at line 170 of file ActivityTimerDistance\&.h\&.
.PP
Referenced by getRandom()\&.
.SS "const double \fBcryomesh::components::ActivityTimerDistance::MIN_DECREMENT_FRACTION\fP = 0\&.1\fC [static]\fP"
.PP
Definition at line 149 of file ActivityTimerDistance\&.h\&.
.PP
Referenced by getRandom()\&.
.SS "const double \fBcryomesh::components::ActivityTimerDistance::MIN_DISTANCE\fP = 1\&.0\fC [static]\fP"
.PP
Definition at line 163 of file ActivityTimerDistance\&.h\&.
.PP
Referenced by checkConstraints(), getRandom(), and cryomesh::components::Connection::updatePosition()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
