cryomesh::common::Tagged
NAME
cryomesh::common::Tagged -
Tagged class implements uuid tagging of classes.
SYNOPSIS
#include <Tagged.h>
Inherited by cryomesh::components::Connection, cryomesh::components::Impulse, cryomesh::components::Node, cryomesh::structures::Cluster, and cryomesh::structures::Fibre.
Public Member Functions
Tagged ()
Constructor.
virtual ~Tagged ()
Destructor.
boost::uuids::uuid getUUID () const
Get the uuid of object.
boost::uuids::uuid getKey () const
Get the key of object.
boost::uuids::uuid getTag () const
Get the tag of object.
Private Attributes
boost::uuids::uuid uuid
Detailed Description
Tagged class implements uuid tagging of classes.
Tagged class should be inherited by functions who want to be uuid tagged and have the related functionality.
Definition at line 24 of file Tagged.h.
Constructor & Destructor Documentation
cryomesh::common::Tagged::Tagged () [inline]
Constructor. Constructor for Tagged
Definition at line 31 of file Tagged.h.
References uuid.
virtual cryomesh::common::Tagged::~Tagged () [inline, virtual]
Destructor. Destructor for Tagged
Definition at line 41 of file Tagged.h.
Member Function Documentation
boost::uuids::uuid cryomesh::common::Tagged::getKey () const [inline]
Get the key of object. Returns:
boost::uuids::uuid The unique uuid tag of this object
Definition at line 61 of file Tagged.h.
References getUUID().
boost::uuids::uuid cryomesh::common::Tagged::getTag () const [inline]
Get the tag of object. Returns:
boost::uuids::uuid The unique uuid tag of this object
Definition at line 71 of file Tagged.h.
References getUUID().
boost::uuids::uuid cryomesh::common::Tagged::getUUID () const [inline]
Get the uuid of object. Returns:
boost::uuids::uuid The unique uuid tag of this object
Definition at line 51 of file Tagged.h.
References uuid.
Referenced by getKey(), and getTag().
Member Data Documentation
boost::uuids::uuid cryomesh::common::Tagged::uuid [private]
Definition at line 81 of file Tagged.h.
Referenced by getUUID(), and Tagged().
Author
Generated automatically by Doxygen for cryomesh from the source code.