cryomesh::spacial::Radian
NAME
cryomesh::spacial::Radian -
SYNOPSIS
#include <Radian.h>
Public Member Functions
Radian (double d)
virtual ~Radian ()
double getValue () const
double toDegrees () const
bool operator== (const Radian &obj) const
Radian & operator= (const Radian &obj)
Radian operator+ (const Radian &obj) const
Radian operator- (const Radian &obj) const
Static Public Attributes
static const double PI = 3.14159265
Private Attributes
double value
Detailed Description
Definition at line 15 of file Radian.h.
Constructor & Destructor Documentation
cryomesh::spacial::Radian::Radian (doubled)
Definition at line 16 of file Radian.cpp.
Referenced by operator+(), and operator-().
cryomesh::spacial::Radian::~Radian () [virtual]
Definition at line 22 of file Radian.cpp.
Member Function Documentation
double cryomesh::spacial::Radian::getValue () const
Definition at line 25 of file Radian.cpp.
References value.
Referenced by cryomesh::spacial::SphericalPoint::equals(), cryomesh::spacial::SphericalPoint::getArcLengthBasic(), and cryomesh::spacial::SphericalPoint::getArcLengthHaversine().
Radian cryomesh::spacial::Radian::operator+ (const Radian &obj) const
Definition at line 39 of file Radian.cpp.
References Radian(), and value.
Radian cryomesh::spacial::Radian::operator- (const Radian &obj) const
Definition at line 42 of file Radian.cpp.
References Radian(), and value.
Radian & cryomesh::spacial::Radian::operator= (const Radian &obj)
Definition at line 35 of file Radian.cpp.
References value.
bool cryomesh::spacial::Radian::operator== (const Radian &obj) const
Definition at line 32 of file Radian.cpp.
References value.
double cryomesh::spacial::Radian::toDegrees () const
Definition at line 28 of file Radian.cpp.
References PI, and value.
Referenced by cryomesh::spacial::SphericalPoint::getArcLengthBasic(), cryomesh::spacial::SphericalPoint::getArcLengthHaversine(), and cryomesh::spacial::operator<<().
Member Data Documentation
const double cryomesh::spacial::Radian::PI = 3.14159265 [static]
Definition at line 27 of file Radian.h.
Referenced by toDegrees().
double cryomesh::spacial::Radian::value [private]
Definition at line 29 of file Radian.h.
Referenced by getValue(), operator+(), operator-(), operator=(), operator==(), and toDegrees().
Author
Generated automatically by Doxygen for cryomesh from the source code.