cryomesh::utilities::Statistician
NAME
cryomesh::utilities::Statistician -
Class to draw together lots of useful statistics and monitoring data for a Bundle and its components.
SYNOPSIS
#include <Statistician.h>
Public Member Functions
Statistician (const structures::Bundle &bun)
Contruct a statistician with a build in Bundle reference.
virtual ~Statistician ()
Default destructor.
void update ()
const structures::Bundle & getBundle () const
int getClusterCount () const
int getInputFibresCount () const
int getOutputFibresCount () const
int getNormalFibresCount () const
int getInputChannelsCount () const
int getOutputChannelsCount () const
std::string getBundleUUID () const
std::map< std::string, int > getTriggeredNodesPerCluster () const
std::map< std::string, int > getActiveNodesPerCluster () const
int getTriggeredNodesTotal () const
int getActiveNodesTotal () const
Private Attributes
const structures::Bundle & bundle
int clusterCount
int inputFibresCount
int outputFibresCount
int normalFibresCount
int inputChannelsCount
int outputChannelsCount
std::string bundleuuid
int nodesTotal
int nodesTriggered
int nodesActive
Friends
std::ostream & operator<< (std::ostream &os, const Statistician &obj)
To stream operator.
Detailed Description
Class to draw together lots of useful statistics and monitoring data for a Bundle and its components.
Definition at line 28 of file Statistician.h.
Constructor & Destructor Documentation
cryomesh::utilities::Statistician::Statistician (const structures::Bundle &bun)
Contruct a statistician with a build in Bundle reference.
Definition at line 15 of file Statistician.cpp.
References update().
cryomesh::utilities::Statistician::~Statistician () [virtual]
Default destructor.
Definition at line 21 of file Statistician.cpp.
Member Function Documentation
std::map< std::string, int > cryomesh::utilities::Statistician::getActiveNodesPerCluster () const
Definition at line 76 of file Statistician.cpp.
References bundle, and cryomesh::structures::Bundle::getClusters().
Referenced by getActiveNodesTotal(), and cryomesh::utilities::operator<<().
int cryomesh::utilities::Statistician::getActiveNodesTotal () const
Definition at line 110 of file Statistician.cpp.
References getActiveNodesPerCluster().
Referenced by cryomesh::utilities::operator<<().
const structures::Bundle & cryomesh::utilities::Statistician::getBundle () const
Definition at line 127 of file Statistician.cpp.
References bundle.
std::string cryomesh::utilities::Statistician::getBundleUUID () const
Definition at line 53 of file Statistician.cpp.
References bundleuuid.
Referenced by cryomesh::utilities::operator<<().
int cryomesh::utilities::Statistician::getClusterCount () const
Definition at line 35 of file Statistician.cpp.
References clusterCount.
Referenced by cryomesh::utilities::operator<<().
int cryomesh::utilities::Statistician::getInputChannelsCount () const
Definition at line 47 of file Statistician.cpp.
References inputChannelsCount.
int cryomesh::utilities::Statistician::getInputFibresCount () const
Definition at line 38 of file Statistician.cpp.
References inputFibresCount.
int cryomesh::utilities::Statistician::getNormalFibresCount () const
Definition at line 44 of file Statistician.cpp.
References normalFibresCount.
int cryomesh::utilities::Statistician::getOutputChannelsCount () const
Definition at line 50 of file Statistician.cpp.
References outputChannelsCount.
int cryomesh::utilities::Statistician::getOutputFibresCount () const
Definition at line 41 of file Statistician.cpp.
References outputFibresCount.
std::map< std::string, int > cryomesh::utilities::Statistician::getTriggeredNodesPerCluster () const
Definition at line 57 of file Statistician.cpp.
References bundle, and cryomesh::structures::Bundle::getClusters().
Referenced by getTriggeredNodesTotal().
int cryomesh::utilities::Statistician::getTriggeredNodesTotal () const
Definition at line 95 of file Statistician.cpp.
References getTriggeredNodesPerCluster().
Referenced by cryomesh::utilities::operator<<().
void cryomesh::utilities::Statistician::update ()
Definition at line 24 of file Statistician.cpp.
References bundle, clusterCount, cryomesh::structures::Bundle::getClusters(), cryomesh::structures::Bundle::getFibres(), cryomesh::structures::Bundle::getInputFibres(), cryomesh::structures::Bundle::getOutputFibres(), cryomesh::structures::Bundle::getRealInputChannelsMap(), cryomesh::structures::Bundle::getRealOutputChannelsMap(), inputChannelsCount, inputFibresCount, normalFibresCount, outputChannelsCount, and outputFibresCount.
Referenced by Statistician().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Statistician &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Statistician & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 131 of file Statistician.cpp.
Member Data Documentation
const structures::Bundle& cryomesh::utilities::Statistician::bundle [private]
Definition at line 74 of file Statistician.h.
Referenced by getActiveNodesPerCluster(), getBundle(), getTriggeredNodesPerCluster(), and update().
std::string cryomesh::utilities::Statistician::bundleuuid [private]
Definition at line 82 of file Statistician.h.
Referenced by getBundleUUID().
int cryomesh::utilities::Statistician::clusterCount [private]
Definition at line 76 of file Statistician.h.
Referenced by getClusterCount(), and update().
int cryomesh::utilities::Statistician::inputChannelsCount [private]
Definition at line 80 of file Statistician.h.
Referenced by getInputChannelsCount(), cryomesh::utilities::operator<<(), and update().
int cryomesh::utilities::Statistician::inputFibresCount [private]
Definition at line 77 of file Statistician.h.
Referenced by getInputFibresCount(), cryomesh::utilities::operator<<(), and update().
int cryomesh::utilities::Statistician::nodesActive [private]
Definition at line 85 of file Statistician.h.
int cryomesh::utilities::Statistician::nodesTotal [private]
Definition at line 83 of file Statistician.h.
int cryomesh::utilities::Statistician::nodesTriggered [private]
Definition at line 84 of file Statistician.h.
int cryomesh::utilities::Statistician::normalFibresCount [private]
Definition at line 79 of file Statistician.h.
Referenced by getNormalFibresCount(), cryomesh::utilities::operator<<(), and update().
int cryomesh::utilities::Statistician::outputChannelsCount [private]
Definition at line 81 of file Statistician.h.
Referenced by getOutputChannelsCount(), cryomesh::utilities::operator<<(), and update().
int cryomesh::utilities::Statistician::outputFibresCount [private]
Definition at line 78 of file Statistician.h.
Referenced by getOutputFibresCount(), cryomesh::utilities::operator<<(), and update().
Author
Generated automatically by Doxygen for cryomesh from the source code.