cryomesh::structures::Mesh
NAME
cryomesh::structures::Mesh -
Mesh is the fabric of connection space and warps and is warped by it.
SYNOPSIS
#include <Mesh.h>
Public Types
enum BlendingMethod { BLEND_LINEAR }
Public Member Functions
Mesh (Cluster &clus)
Constructor.
Mesh (const Mesh &)
Copy Constructor.
virtual ~Mesh ()
Destructor.
void update ()
Update mesh from cluster.
components::Node & warp (components::Node &node)
Assignment Operator.
components::ImpulseCollection & warp (components::ImpulseCollection &impulseCollection)
Warp an ImpulseCollection using the mesh.
cryomesh::components::Impulse & warp (cryomesh::components::Impulse &impulse)
Warp an Impulse using the mesh.
const Cluster & getCluster () const
const boost::shared_ptr< spacial::ActivityGrid > getActivityGrid () const
Protected Member Functions
double getBlendedActivity (const double first_activity, const double second_activity, const BlendingMethod blending_method=BLEND_LINEAR, double force=0.5)
Private Attributes
Cluster & cluster
boost::shared_ptr< spacial::ActivityGrid > grid
const int DEFAULT_MESH_GRANULARITY
const int DEFAULT_BLEND_FORCE
Detailed Description
Mesh is the fabric of connection space and warps and is warped by it.
The Mesh is an overlying structure on top of Connections space that can be used to warp the underlying space, Impulses, Connections, Nodes, etc based on spacial criteria on any other criteria that can be applied to the underlying data objects
Definition at line 33 of file Mesh.h.
Member Enumeration Documentation
enum cryomesh::structures::Mesh::BlendingMethod
Enumerator:
BLEND_LINEAR
Definition at line 36 of file Mesh.h.
Constructor & Destructor Documentation
cryomesh::structures::Mesh::Mesh (Cluster &clus)
Constructor. Constructor for Mesh. Inaccessible to force singleton class
Definition at line 32 of file Mesh.cpp.
References cluster, DEFAULT_MESH_GRANULARITY, grid, and update().
cryomesh::structures::Mesh::Mesh (const Mesh &)
Copy Constructor. Overridden Copy Contructor for Mesh. Inaccessible to force singleton class
Parameters:
Mesh Object to Copy Construct from
cryomesh::structures::Mesh::~Mesh () [virtual]
Destructor.
Definition at line 41 of file Mesh.cpp.
Member Function Documentation
const boost::shared_ptr< spacial::ActivityGrid > cryomesh::structures::Mesh::getActivityGrid () const
Definition at line 107 of file Mesh.cpp.
References grid.
double cryomesh::structures::Mesh::getBlendedActivity (const doublefirst_activity, const doublesecond_activity, const BlendingMethodblending_method = BLEND_LINEAR, doubleforce = 0.5) [protected]
Definition at line 91 of file Mesh.cpp.
References BLEND_LINEAR.
Referenced by warp().
const Cluster & cryomesh::structures::Mesh::getCluster () const
Definition at line 103 of file Mesh.cpp.
References cluster.
void cryomesh::structures::Mesh::update ()
Update mesh from cluster.
Definition at line 44 of file Mesh.cpp.
References cluster, cryomesh::components::Node::getActivity(), cryomesh::structures::Cluster::getNodes(), cryomesh::components::Node::getPosition(), and grid.
Referenced by Mesh().
Impulse & cryomesh::structures::Mesh::warp (cryomesh::components::Impulse &impulse)
Warp an Impulse using the mesh. Parameters:
Impulse & Impulse
Returns:
Impulse & The warped Impulse
Definition at line 85 of file Mesh.cpp.
ImpulseCollection & cryomesh::structures::Mesh::warp (components::ImpulseCollection &impulseCollection)
Warp an ImpulseCollection using the mesh. Parameters:
ImpulseCollection & ImpulseCollection
Returns:
ImpulseCollection & The warped collection
Definition at line 79 of file Mesh.cpp.
Node & cryomesh::structures::Mesh::warp (components::Node &node)
Assignment Operator. Overridden Assignment Operator for Mesh. Inaccessible to force singleton class
Parameters:
Mesh Object to Assign this to
Mesh & operator=(const Mesh &); /** Singleton accessor for object
Returns the single instance of a mesh, creating it if it doesn't exist yet
Returns:
boost::shared_ptr<Mesh> The singleton instance of the mesh
static boost::shared_ptr< Mesh > getMesh(); Warp the a Node using the mesh
This function will use any values of the node, such as position in space for example, to apply a warp to the node. In practice this might be to suppress or increase the activity threshold, or to scale the activites at that node in some way. Note that this is an permanent change, ie, the node is warped 'in place'
Parameters:
Node & node The node to be warped
Returns:
Node & The warped node
Definition at line 69 of file Mesh.cpp.
References BLEND_LINEAR, DEFAULT_BLEND_FORCE, cryomesh::components::Node::getActivity(), getBlendedActivity(), cryomesh::components::Node::getPosition(), grid, and cryomesh::components::Node::setActivity().
Member Data Documentation
Cluster& cryomesh::structures::Mesh::cluster [private]
Definition at line 131 of file Mesh.h.
Referenced by getCluster(), Mesh(), and update().
const int cryomesh::structures::Mesh::DEFAULT_BLEND_FORCE [private]
Definition at line 134 of file Mesh.h.
Referenced by warp().
const int cryomesh::structures::Mesh::DEFAULT_MESH_GRANULARITY [private]
Definition at line 133 of file Mesh.h.
Referenced by Mesh().
boost::shared_ptr<spacial::ActivityGrid> cryomesh::structures::Mesh::grid [private]
Definition at line 132 of file Mesh.h.
Referenced by getActivityGrid(), Mesh(), update(), and warp().
Author
Generated automatically by Doxygen for cryomesh from the source code.