.TH "cryomesh::state::PatternChannel" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::state::PatternChannel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PatternChannel\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPrintFormat\fP { \fBBINARY\fP, \fBTEXT\fP, \fBINTEGER\fP }"
.br
.ti -1c
.RI "enum \fBChannelDataType\fP { \fBInput\fP, \fBOutput\fP, \fBTransitional\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPatternChannel\fP (\fBChannelDataType\fP dt)"
.br
.ti -1c
.RI "\fBPatternChannel\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats, \fBChannelDataType\fP dt)"
.br
.ti -1c
.RI "virtual \fB~PatternChannel\fP ()"
.br
.ti -1c
.RI "\fBPatternChannel\fP (const \fBPatternChannel\fP &obj)"
.br
.ti -1c
.RI "\fBPatternChannel\fP & \fBoperator=\fP (const \fBPatternChannel\fP &obj)"
.br
.RI "\fIAssignment operator\&. \fP"
.ti -1c
.RI "void \fBaddPattern\fP (boost::shared_ptr< \fBPattern\fP > pat)"
.br
.ti -1c
.RI "void \fBaddPatterns\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats)"
.br
.ti -1c
.RI "void \fBaddPatterns\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats, int position)"
.br
.ti -1c
.RI "std::list< boost::shared_ptr
.br
< \fBPattern\fP > > \fBremovePatterns\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats)"
.br
.ti -1c
.RI "std::list< boost::shared_ptr
.br
< \fBPattern\fP > > \fBremovePatterns\fP (const std::list< boost::uuids::uuid > &uuids)"
.br
.ti -1c
.RI "void \fBclearPatternList\fP ()"
.br
.ti -1c
.RI "std::list< boost::shared_ptr
.br
< \fBPattern\fP > > \fBforcePatternListSize\fP (int sz)"
.br
.ti -1c
.RI "std::list< boost::shared_ptr
.br
< \fBPattern\fP > > \fBforcePatternListSize\fP ()"
.br
.ti -1c
.RI "const boost::shared_ptr< \fBPattern\fP > \fBgetCurrentPattern\fP ()"
.br
.ti -1c
.RI "const boost::shared_ptr< \fBPattern\fP > \fBgetPatternByCycle\fP (const \fBcommon::Cycle\fP &cycle)"
.br
.ti -1c
.RI "const boost::shared_ptr< \fBPattern\fP > \fBgetPatternByTag\fP (const boost::shared_ptr< \fBPatternTag\fP > tg) const "
.br
.ti -1c
.RI "const boost::shared_ptr< \fBPattern\fP > \fBnextPattern\fP ()"
.br
.ti -1c
.RI "const boost::shared_ptr< \fBPattern\fP > \fBpreviousPattern\fP ()"
.br
.ti -1c
.RI "double \fBmatchGlobally\fP (const \fBPatternChannel\fP &)"
.br
.ti -1c
.RI "double \fBmatchSequentially\fP (const \fBPatternChannel\fP &)"
.br
.ti -1c
.RI "virtual void \fBenableDebug\fP (bool b)"
.br
.ti -1c
.RI "\fBChannelDataType\fP \fBgetChannelDataType\fP () const "
.br
.ti -1c
.RI "int \fBgetLength\fP () const "
.br
.ti -1c
.RI "const std::map
.br
< boost::shared_ptr
.br
< \fBPatternTag\fP >
.br
, boost::uuids::uuid > & \fBgetPatternByTagMap\fP () const "
.br
.ti -1c
.RI "const boost::shared_ptr< \fBPattern\fP > \fBgetPatternByUUID\fP (const boost::uuids::uuid &id) const "
.br
.ti -1c
.RI "boost::shared_ptr< \fBPattern\fP > \fBgetMutablePatternByUUID\fP (const boost::uuids::uuid &id)"
.br
.ti -1c
.RI "const std::list
.br
< boost::uuids::uuid > & \fBgetPatternList\fP () const "
.br
.ti -1c
.RI "std::list< boost::uuids::uuid >
.br
::iterator \fBgetPatternListIterator\fP () const "
.br
.ti -1c
.RI "const std::map
.br
< boost::uuids::uuid, 
.br
boost::shared_ptr< \fBPattern\fP > > & \fBgetPatternMap\fP () const "
.br
.ti -1c
.RI "int \fBgetPatternPosition\fP () const "
.br
.ti -1c
.RI "int \fBgetWidth\fP () const "
.br
.ti -1c
.RI "void \fBsetWidth\fP (int w)"
.br
.ti -1c
.RI "int \fBgetRefID\fP () const "
.br
.ti -1c
.RI "void \fBsetRefID\fP (int r)"
.br
.ti -1c
.RI "int \fBgetMaxPatternListSize\fP () const "
.br
.ti -1c
.RI "void \fBsetMaxPatternListSize\fP (int sz)"
.br
.ti -1c
.RI "std::ostream & \fBprintPatternList\fP (std::ostream &os, bool reversed=false) const "
.br
.ti -1c
.RI "std::ostream & \fBprintTextFormattedPatternList\fP (std::ostream &os, bool reversed=false) const "
.br
.ti -1c
.RI "std::ostream & \fBprintIntegerFormattedPatternList\fP (std::ostream &os, bool reversed) const "
.br
.ti -1c
.RI "std::ostream & \fBprintBinaryFormattedPatternList\fP (std::ostream &os, bool reversed) const "
.br
.ti -1c
.RI "std::ostream & \fBprintFormattedPatternList\fP (std::ostream &os, const \fBPrintFormat\fP &pf, bool reversed) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBgetRefIDS\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBDEFAULT_MAX_PATTERN_LIST_SIZE\fP = -1"
.br
.ti -1c
.RI "static const unsigned int \fBREFID_CREATE_START\fP = 100000"
.br
.ti -1c
.RI "static unsigned int \fBrefIDS\fP = \fBPatternChannel::REFID_CREATE_START\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBChannelDataType\fP \fBchannelDataType\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBmaxPatternListSize\fP"
.br
.ti -1c
.RI "std::map< boost::shared_ptr
.br
< \fBPatternTag\fP >
.br
, boost::uuids::uuid > \fBpatternByTagMap\fP"
.br
.ti -1c
.RI "std::list< boost::uuids::uuid > \fBpatternList\fP"
.br
.ti -1c
.RI "std::list< boost::uuids::uuid >
.br
::iterator \fBpatternListIterator\fP"
.br
.ti -1c
.RI "std::map< boost::uuids::uuid, 
.br
boost::shared_ptr< \fBPattern\fP > > \fBpatternMap\fP"
.br
.ti -1c
.RI "int \fBpatternPosition\fP"
.br
.ti -1c
.RI "int \fBrefID\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBPatternChannel\fP &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file PatternChannel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBcryomesh::state::PatternChannel::ChannelDataType\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIInput \fP\fP
.TP
\fB\fIOutput \fP\fP
.TP
\fB\fITransitional \fP\fP

.PP
Definition at line 30 of file PatternChannel\&.h\&.
.SS "enum \fBcryomesh::state::PatternChannel::PrintFormat\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIBINARY \fP\fP
.TP
\fB\fITEXT \fP\fP
.TP
\fB\fIINTEGER \fP\fP

.PP
Definition at line 27 of file PatternChannel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::state::PatternChannel::PatternChannel\fP (\fBChannelDataType\fPdt)"
.PP
Definition at line 24 of file PatternChannel\&.cpp\&.
.PP
References channelDataType, and Input\&.
.SS "\fBcryomesh::state::PatternChannel::PatternChannel\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats, \fBChannelDataType\fPdt)"
.PP
Definition at line 37 of file PatternChannel\&.cpp\&.
.PP
References addPatterns(), channelDataType, DEFAULT_MAX_PATTERN_LIST_SIZE, getRefIDS(), Input, maxPatternListSize, Output, patternList, patternListIterator, and refID\&.
.SS "\fBcryomesh::state::PatternChannel::~PatternChannel\fP ()\fC [virtual]\fP"
.PP
Definition at line 59 of file PatternChannel\&.cpp\&.
.SS "\fBcryomesh::state::PatternChannel::PatternChannel\fP (const \fBPatternChannel\fP &obj)"
.PP
Definition at line 65 of file PatternChannel\&.cpp\&.
.PP
References channelDataType, length, maxPatternListSize, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, refID, and width\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBcryomesh::state::PatternChannel::addPattern\fP (boost::shared_ptr< \fBPattern\fP >pat)"
.PP
Definition at line 98 of file PatternChannel\&.cpp\&.
.PP
References addPatterns(), and getLength()\&.
.SS "void \fBcryomesh::state::PatternChannel::addPatterns\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats)"
.PP
Definition at line 103 of file PatternChannel\&.cpp\&.
.PP
References getLength()\&.
.PP
Referenced by addPattern(), and PatternChannel()\&.
.SS "void \fBcryomesh::state::PatternChannel::addPatterns\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats, intposition)"
.PP
Definition at line 107 of file PatternChannel\&.cpp\&.
.PP
References forcePatternListSize(), getLength(), getWidth(), length, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, and setWidth()\&.
.SS "void \fBcryomesh::state::PatternChannel::clearPatternList\fP ()"
.PP
Definition at line 200 of file PatternChannel\&.cpp\&.
.PP
References length, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, and width\&.
.SS "void \fBcryomesh::state::PatternChannel::enableDebug\fP (boolb)\fC [virtual]\fP"
.PP
Definition at line 536 of file PatternChannel\&.cpp\&.
.SS "std::list< boost::shared_ptr< \fBPattern\fP > > \fBcryomesh::state::PatternChannel::forcePatternListSize\fP (intsz)"
.PP
Definition at line 209 of file PatternChannel\&.cpp\&.
.PP
References patternList, and removePatterns()\&.
.SS "std::list< boost::shared_ptr< \fBPattern\fP > > \fBcryomesh::state::PatternChannel::forcePatternListSize\fP ()"
.PP
Definition at line 233 of file PatternChannel\&.cpp\&.
.PP
References getMaxPatternListSize()\&.
.PP
Referenced by addPatterns(), and setMaxPatternListSize()\&.
.SS "\fBPatternChannel::ChannelDataType\fP \fBcryomesh::state::PatternChannel::getChannelDataType\fP () const"
.PP
Definition at line 498 of file PatternChannel\&.cpp\&.
.PP
References channelDataType\&.
.SS "const boost::shared_ptr< \fBPattern\fP > \fBcryomesh::state::PatternChannel::getCurrentPattern\fP ()"
.PP
Definition at line 241 of file PatternChannel\&.cpp\&.
.PP
References patternMap\&.
.PP
Referenced by nextPattern(), and previousPattern()\&.
.SS "int \fBcryomesh::state::PatternChannel::getLength\fP () const"
.PP
Definition at line 458 of file PatternChannel\&.cpp\&.
.PP
References patternList\&.
.PP
Referenced by addPattern(), addPatterns(), and nextPattern()\&.
.SS "int \fBcryomesh::state::PatternChannel::getMaxPatternListSize\fP () const"
.PP
Definition at line 502 of file PatternChannel\&.cpp\&.
.PP
References maxPatternListSize\&.
.PP
Referenced by forcePatternListSize()\&.
.SS "boost::shared_ptr< \fBPattern\fP > \fBcryomesh::state::PatternChannel::getMutablePatternByUUID\fP (const boost::uuids::uuid &id)"
.PP
Definition at line 524 of file PatternChannel\&.cpp\&.
.PP
References patternMap\&.
.SS "const boost::shared_ptr< \fBPattern\fP > \fBcryomesh::state::PatternChannel::getPatternByCycle\fP (const \fBcommon::Cycle\fP &cycle)"
.PP
Definition at line 245 of file PatternChannel\&.cpp\&.
.PP
References cryomesh::common::TimeKeeper::getCycle(), cryomesh::common::TimeKeeper::getTimeKeeper(), patternList, and patternMap\&.
.SS "const boost::shared_ptr< \fBPattern\fP > \fBcryomesh::state::PatternChannel::getPatternByTag\fP (const boost::shared_ptr< \fBPatternTag\fP >tg) const"
.PP
Definition at line 269 of file PatternChannel\&.cpp\&.
.PP
References patternByTagMap, and patternMap\&.
.SS "const std::map< boost::shared_ptr< \fBPatternTag\fP >, boost::uuids::uuid > & \fBcryomesh::state::PatternChannel::getPatternByTagMap\fP () const"
.PP
Definition at line 462 of file PatternChannel\&.cpp\&.
.PP
References patternByTagMap\&.
.SS "const boost::shared_ptr< \fBPattern\fP > \fBcryomesh::state::PatternChannel::getPatternByUUID\fP (const boost::uuids::uuid &id) const"
.PP
Definition at line 512 of file PatternChannel\&.cpp\&.
.PP
References patternMap\&.
.PP
Referenced by printFormattedPatternList(), and printPatternList()\&.
.SS "const std::list< boost::uuids::uuid > & \fBcryomesh::state::PatternChannel::getPatternList\fP () const"
.PP
Definition at line 466 of file PatternChannel\&.cpp\&.
.PP
References patternList\&.
.PP
Referenced by matchGlobally(), and matchSequentially()\&.
.SS "std::list< boost::uuids::uuid >::iterator \fBcryomesh::state::PatternChannel::getPatternListIterator\fP () const"
.PP
Definition at line 470 of file PatternChannel\&.cpp\&.
.PP
References patternListIterator\&.
.SS "const std::map< boost::uuids::uuid, boost::shared_ptr< \fBPattern\fP > > & \fBcryomesh::state::PatternChannel::getPatternMap\fP () const"
.PP
Definition at line 474 of file PatternChannel\&.cpp\&.
.PP
References patternMap\&.
.PP
Referenced by matchGlobally(), and matchSequentially()\&.
.SS "int \fBcryomesh::state::PatternChannel::getPatternPosition\fP () const"
.PP
Definition at line 478 of file PatternChannel\&.cpp\&.
.PP
References patternPosition\&.
.SS "int \fBcryomesh::state::PatternChannel::getRefID\fP () const"
.PP
Definition at line 490 of file PatternChannel\&.cpp\&.
.PP
References refID\&.
.SS "unsigned int \fBcryomesh::state::PatternChannel::getRefIDS\fP ()\fC [static]\fP"
.PP
Definition at line 20 of file PatternChannel\&.cpp\&.
.PP
References refIDS\&.
.PP
Referenced by PatternChannel()\&.
.SS "int \fBcryomesh::state::PatternChannel::getWidth\fP () const"
.PP
Definition at line 482 of file PatternChannel\&.cpp\&.
.PP
References width\&.
.PP
Referenced by addPatterns()\&.
.SS "double \fBcryomesh::state::PatternChannel::matchGlobally\fP (const \fBPatternChannel\fP &obj)"
.PP
Definition at line 309 of file PatternChannel\&.cpp\&.
.PP
References getPatternList(), and getPatternMap()\&.
.SS "double \fBcryomesh::state::PatternChannel::matchSequentially\fP (const \fBPatternChannel\fP &obj)"
.PP
Definition at line 395 of file PatternChannel\&.cpp\&.
.PP
References getPatternList(), and getPatternMap()\&.
.SS "const boost::shared_ptr< \fBPattern\fP > \fBcryomesh::state::PatternChannel::nextPattern\fP ()"
.PP
Definition at line 278 of file PatternChannel\&.cpp\&.
.PP
References getCurrentPattern(), getLength(), patternList, patternListIterator, and patternPosition\&.
.SS "\fBPatternChannel\fP & cryomesh::state::PatternChannel::operator= (const \fBPatternChannel\fP &obj)"
.PP
Assignment operator\&. \fBParameters:\fP
.RS 4
\fIconst\fP \fBPatternChannel\fP & obj RHS assignment
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPatternChannel\fP & This object after assignment 
.RE
.PP

.PP
Definition at line 81 of file PatternChannel\&.cpp\&.
.PP
References channelDataType, length, maxPatternListSize, patternByTagMap, patternList, patternListIterator, patternMap, patternPosition, refID, and width\&.
.SS "const boost::shared_ptr< \fBPattern\fP > \fBcryomesh::state::PatternChannel::previousPattern\fP ()"
.PP
Definition at line 298 of file PatternChannel\&.cpp\&.
.PP
References getCurrentPattern(), patternList, patternListIterator, and patternPosition\&.
.SS "std::ostream & \fBcryomesh::state::PatternChannel::printBinaryFormattedPatternList\fP (std::ostream &os, boolreversed) const"
.PP
Definition at line 576 of file PatternChannel\&.cpp\&.
.PP
References BINARY, and printFormattedPatternList()\&.
.PP
Referenced by cryomesh::state::operator<<()\&.
.SS "std::ostream & \fBcryomesh::state::PatternChannel::printFormattedPatternList\fP (std::ostream &os, const \fBPrintFormat\fP &pf, boolreversed) const"
.PP
Definition at line 579 of file PatternChannel\&.cpp\&.
.PP
References BINARY, getPatternByUUID(), INTEGER, patternList, and TEXT\&.
.PP
Referenced by printBinaryFormattedPatternList(), printIntegerFormattedPatternList(), and printTextFormattedPatternList()\&.
.SS "std::ostream & \fBcryomesh::state::PatternChannel::printIntegerFormattedPatternList\fP (std::ostream &os, boolreversed) const"
.PP
Definition at line 573 of file PatternChannel\&.cpp\&.
.PP
References INTEGER, and printFormattedPatternList()\&.
.SS "std::ostream & \fBcryomesh::state::PatternChannel::printPatternList\fP (std::ostream &os, boolreversed = \fCfalse\fP) const"
.PP
Definition at line 540 of file PatternChannel\&.cpp\&.
.PP
References getPatternByUUID(), and patternList\&.
.SS "std::ostream & \fBcryomesh::state::PatternChannel::printTextFormattedPatternList\fP (std::ostream &os, boolreversed = \fCfalse\fP) const"
.PP
Definition at line 569 of file PatternChannel\&.cpp\&.
.PP
References printFormattedPatternList(), and TEXT\&.
.SS "std::list< boost::shared_ptr< \fBPattern\fP > > \fBcryomesh::state::PatternChannel::removePatterns\fP (const std::list< boost::shared_ptr< \fBPattern\fP > > &pats)"
.PP
Definition at line 156 of file PatternChannel\&.cpp\&.
.PP
Referenced by forcePatternListSize()\&.
.SS "std::list< boost::shared_ptr< \fBPattern\fP > > \fBcryomesh::state::PatternChannel::removePatterns\fP (const std::list< boost::uuids::uuid > &uuids)"
.PP
Definition at line 175 of file PatternChannel\&.cpp\&.
.PP
References length, patternByTagMap, patternList, patternListIterator, patternMap, and patternPosition\&.
.SS "void \fBcryomesh::state::PatternChannel::setMaxPatternListSize\fP (intsz)"
.PP
Definition at line 505 of file PatternChannel\&.cpp\&.
.PP
References forcePatternListSize(), and maxPatternListSize\&.
.SS "void \fBcryomesh::state::PatternChannel::setRefID\fP (intr)"
.PP
Definition at line 493 of file PatternChannel\&.cpp\&.
.PP
References refID\&.
.SS "void \fBcryomesh::state::PatternChannel::setWidth\fP (intw)"
.PP
Definition at line 485 of file PatternChannel\&.cpp\&.
.PP
References width\&.
.PP
Referenced by addPatterns()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBPatternChannel\fP &obj)\fC [friend]\fP"
.PP
Definition at line 639 of file PatternChannel\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBChannelDataType\fP \fBcryomesh::state::PatternChannel::channelDataType\fP\fC [private]\fP"
.PP
Definition at line 169 of file PatternChannel\&.h\&.
.PP
Referenced by getChannelDataType(), operator=(), and PatternChannel()\&.
.SS "const int \fBcryomesh::state::PatternChannel::DEFAULT_MAX_PATTERN_LIST_SIZE\fP = -1\fC [static]\fP"
.PP
Definition at line 161 of file PatternChannel\&.h\&.
.PP
Referenced by PatternChannel()\&.
.SS "int \fBcryomesh::state::PatternChannel::length\fP\fC [private]\fP"
.PP
Definition at line 171 of file PatternChannel\&.h\&.
.PP
Referenced by addPatterns(), clearPatternList(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and removePatterns()\&.
.SS "int \fBcryomesh::state::PatternChannel::maxPatternListSize\fP\fC [private]\fP"
.PP
Definition at line 172 of file PatternChannel\&.h\&.
.PP
Referenced by getMaxPatternListSize(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and setMaxPatternListSize()\&.
.SS "std::map<boost::shared_ptr<\fBPatternTag\fP>, boost::uuids::uuid> \fBcryomesh::state::PatternChannel::patternByTagMap\fP\fC [private]\fP"
.PP
Definition at line 174 of file PatternChannel\&.h\&.
.PP
Referenced by addPatterns(), clearPatternList(), getPatternByTag(), getPatternByTagMap(), operator=(), PatternChannel(), and removePatterns()\&.
.SS "std::list<boost::uuids::uuid> \fBcryomesh::state::PatternChannel::patternList\fP\fC [private]\fP"
.PP
Definition at line 176 of file PatternChannel\&.h\&.
.PP
Referenced by addPatterns(), clearPatternList(), forcePatternListSize(), getLength(), getPatternByCycle(), getPatternList(), nextPattern(), operator=(), PatternChannel(), previousPattern(), printFormattedPatternList(), printPatternList(), and removePatterns()\&.
.SS "std::list<boost::uuids::uuid>::iterator \fBcryomesh::state::PatternChannel::patternListIterator\fP\fC [private]\fP"
.PP
Definition at line 178 of file PatternChannel\&.h\&.
.PP
Referenced by addPatterns(), clearPatternList(), getPatternListIterator(), nextPattern(), operator=(), PatternChannel(), previousPattern(), and removePatterns()\&.
.SS "std::map<boost::uuids::uuid, boost::shared_ptr<\fBPattern\fP> > \fBcryomesh::state::PatternChannel::patternMap\fP\fC [private]\fP"
.PP
Definition at line 180 of file PatternChannel\&.h\&.
.PP
Referenced by addPatterns(), clearPatternList(), getCurrentPattern(), getMutablePatternByUUID(), getPatternByCycle(), getPatternByTag(), getPatternByUUID(), getPatternMap(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and removePatterns()\&.
.SS "int \fBcryomesh::state::PatternChannel::patternPosition\fP\fC [private]\fP"
.PP
Definition at line 182 of file PatternChannel\&.h\&.
.PP
Referenced by addPatterns(), clearPatternList(), getPatternPosition(), nextPattern(), cryomesh::state::operator<<(), operator=(), PatternChannel(), previousPattern(), and removePatterns()\&.
.SS "int \fBcryomesh::state::PatternChannel::refID\fP\fC [private]\fP"
.PP
Definition at line 184 of file PatternChannel\&.h\&.
.PP
Referenced by getRefID(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and setRefID()\&.
.SS "const unsigned int \fBcryomesh::state::PatternChannel::REFID_CREATE_START\fP = 100000\fC [static]\fP"
.PP
Definition at line 163 of file PatternChannel\&.h\&.
.SS "unsigned int \fBcryomesh::state::PatternChannel::refIDS\fP = \fBPatternChannel::REFID_CREATE_START\fP\fC [static]\fP"
.PP
Definition at line 164 of file PatternChannel\&.h\&.
.PP
Referenced by getRefIDS()\&.
.SS "int \fBcryomesh::state::PatternChannel::width\fP\fC [private]\fP"
.PP
Definition at line 186 of file PatternChannel\&.h\&.
.PP
Referenced by clearPatternList(), getWidth(), cryomesh::state::operator<<(), operator=(), PatternChannel(), and setWidth()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
