cryomesh::components::ImpulseCollection
NAME
cryomesh::components::ImpulseCollection -
ImpulseCollection represents a collection of Impulse objects.
SYNOPSIS
#include <ImpulseCollection.h>
Inherits KeyMappedCollection< boost::uuids::uuid, Impulse >, and DataObjectController< unsigned long int, double >.
Public Types
enum Comparison { GreaterThan, LessThan, EqualTo, NotEqualTo }
Public Member Functions
ImpulseCollection ()
Contructor for ImpulseCollection.
virtual ~ImpulseCollection ()
Destructor for ImpulseCollection.
double getActivity (common::Cycle cycle) const
Get activity at cycle.
double getActivity () const
Get activity at current cycle.
void clearImpulses ()
Clear collection up to present cycle.
void clearImpulses (common::Cycle cycle)
Clear collection up to specified cycle.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > clearImpulses (common::Cycle cycleStart, common::Cycle cycleEnd)
Clear the Impulses that start on or after cycle start parameter and finish before cycle end parameter.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > clearActiveImpulses ()
Clear cycles that are active on this cycle.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > clearActiveImpulses (common::Cycle cycle)
Clear cycles that are active on cycle.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > clearActiveImpulses (common::Cycle cycleStart, common::Cycle cycleEnd)
Clear cycles that are active on cycle range.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > clearActivitiesByMinimum (double activity)
Clear the Impulses that have activities less than parameter.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > clearActivitiesByMaximum (double activity)
Clear the Impulses that have activities greater than parameter.
void decrementActivityTimers ()
Decrement the activity timers of all impulses.
std::list< boost::shared_ptr< Impulse > > getByActivityTimerValue (double value, Comparison comp)
Get impulse list by activity timer value.
std::list< boost::shared_ptr< Impulse > > removeByActivityTimerValue (double value=0, Comparison comp=LessThan)
remove impulses by activity timer value
virtual void refreshDataObject ()
Inherited from DataObjectController.
ImpulseCollection & operator= (const ImpulseCollection &obj)
Assignment operator.
ImpulseCollection & operator+= (const ImpulseCollection &obj)
Destructive addition and assignment operator.
const ImpulseCollection operator+ (const ImpulseCollection &obj) const
Non-destructive addition operator.
bool operator== (const ImpulseCollection &obj) const
Comparator operator.
bool operator!= (const ImpulseCollection &obj) const
Not comparator operator.
void clear ()
Clear all objects from collection.
boost::shared_ptr< Impulse > add (boost::shared_ptr< Impulse > obj)
Add object to collection.
virtual void add (const std::initializer_list< boost::shared_ptr< Impulse > > &list)
Add object to collection by initialiser list.
virtual void add (const std::list< boost::shared_ptr< Impulse > > &list)
Add object to collection by list.
virtual void remove (const std::initializer_list< boost::shared_ptr< Impulse > > &list)
Remove objects from collection by initialiser list.
virtual void remove (const std::list< boost::shared_ptr< Impulse > > &list)
Remove objects from collection by list.
boost::shared_ptr< Impulse > remove (boost::shared_ptr< Impulse > obj)
Add object to collection.
boost::shared_ptr< Impulse > remove (Impulse &obj)
Remove object from collection.
boost::shared_ptr< Impulse > remove (boost::uuids::uuidkey)
Remove object from collection bt key.
std::list< boost::uuids::uuid > getKeyList () const
Get keys for underlying connection.
std::vector< boost::shared_ptr< Impulse > > getObjectList () const
Get object list for underlying connection.
boost::shared_ptr< Impulse > getObjectByKey (const boost::uuids::uuid &key)
Get object using key.
std::vector< boost::shared_ptr< Impulse > > getRandomRange (int number) const
const std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > & getCollection () const
Get maximum value.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > & getMutableCollection ()
Get mutable underlying collection.
int getSize () const
Get underlying collections size.
virtual void enableLogging (bool enable)
Whether logging is enabled or not.
virtual const std::map< unsigned long int, double > & getMap ()
Get all cycle values.
virtual const dataobjects::DataObject< unsigned long int, double > & getDataObject ()
Get data object.
Protected Member Functions
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > clearActivitiesByValue (double activity, bool greater)
Get the associated Mesh.
Protected Attributes
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > objects
dataobjects::DataObject< unsigned long int, double > dataObject
Friends
std::ostream & operator<< (std::ostream &os, const ImpulseCollection &obj)
To stream operator.
Detailed Description
ImpulseCollection represents a collection of Impulse objects.
A collection of Impulses that allows for Impulses to be held, 'moved forward' in time, and summated in some way
Definition at line 35 of file ImpulseCollection.h.
Member Enumeration Documentation
enum cryomesh::components::ImpulseCollection::Comparison
Enumerator:
GreaterThan
LessThan
EqualTo
NotEqualTo
Definition at line 38 of file ImpulseCollection.h.
Constructor & Destructor Documentation
cryomesh::components::ImpulseCollection::ImpulseCollection ()
Contructor for ImpulseCollection. Contruct using default Mesh
Definition at line 16 of file ImpulseCollection.cpp.
cryomesh::components::ImpulseCollection::~ImpulseCollection () [virtual]
Destructor for ImpulseCollection. Destructor
Definition at line 20 of file ImpulseCollection.cpp.
Member Function Documentation
boost::shared_ptr<Impulse > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::add (boost::shared_ptr< Impulse >obj) [inline, inherited]
Add object to collection. Parameters:
boost::shared_ptr<T> obj The object to be added to the collection
Returns:
boost::shared_ptr<T> The object added to the collection
Definition at line 59 of file KeyMappedCollection.h.
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::add (const std::initializer_list< boost::shared_ptr< Impulse > > &list) [inline, virtual, inherited]
Add object to collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be added to the collection
Definition at line 70 of file KeyMappedCollection.h.
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::add (const std::list< boost::shared_ptr< Impulse > > &list) [inline, virtual, inherited]
Add object to collection by list. Parameters:
std::list<T> list The list values to be added to the collection
Definition at line 88 of file KeyMappedCollection.h.
void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::clear () [inline, inherited]
Clear all objects from collection.
Definition at line 45 of file KeyMappedCollection.h.
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::clearActiveImpulses ()
Clear cycles that are active on this cycle. Update the collection to by dropping all impulses that are active on this cycle
Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<Impulse> > The collection of deleted impulses
Definition at line 100 of file ImpulseCollection.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by clearActiveImpulses(), and cryomesh::components::Node::update().
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::clearActiveImpulses (common::CyclecycleStart, common::CyclecycleEnd)
Clear cycles that are active on cycle range. Interval is [cycle_start,cycle_end)
Update the collection to by dropping all impulses that are active on cycle range
Parameters:
common::Cycle cycleStart The start cycle to drop inclusive impulses from
common::Cycle cycleEnd The end cycle to drop inclusive impulses from excluded
Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<Impulse> > The collection of deleted impulses
Definition at line 109 of file ImpulseCollection.cpp.
References cryomesh::components::Impulse::getFirstActiveCycle(), cryomesh::components::Impulse::getLastActiveCycle(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::getMutableCollection(), and cryomesh::components::Impulse::isActive().
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::clearActiveImpulses (common::Cyclecycle)
Clear cycles that are active on cycle. Update the collection to by dropping all impulses that are active on cycle
Parameters:
common::Cycle cycle The cycle to drop inclusive impulses from
Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<Impulse> > The collection of deleted impulses
Definition at line 105 of file ImpulseCollection.cpp.
References clearActiveImpulses().
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::clearActivitiesByMaximum (doubleactivity)
Clear the Impulses that have activities greater than parameter. Parameters:
double activity The maximum activity impulses must have to avoid deleteion
Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<Impulse> > The deleted collection of impulses
Definition at line 159 of file ImpulseCollection.cpp.
References clearActivitiesByValue().
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::clearActivitiesByMinimum (doubleactivity)
Clear the Impulses that have activities less than parameter. Parameters:
double activity The minimum activity impulses must have to avoid deleteion
Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<Impulse> > The deleted collection of impulses
Definition at line 155 of file ImpulseCollection.cpp.
References clearActivitiesByValue().
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::clearActivitiesByValue (doubleactivity, boolgreater) [protected]
Get the associated Mesh. Returns:
Mesh
const boost::shared_ptr<Mesh> getMesh() const; Clear the Impulses that have activities greater or less than parameter
Parameters:
double activity The maximum or minimum activity impulses must have to avoid deleteion
bool True is first parameter is maximum allowed value, false if its the minimum
Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<Impulse> > The deleted collection of impulses
Definition at line 342 of file ImpulseCollection.cpp.
References cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::getMutableCollection().
Referenced by clearActivitiesByMaximum(), and clearActivitiesByMinimum().
void cryomesh::components::ImpulseCollection::clearImpulses (common::Cyclecycle)
Clear collection up to specified cycle. Update the collection to specified cycle (non-inclusive) by dropping all impulses that are 'in the past' relative to that cycle. Interval is [0,cycle)
Parameters:
common::Cycle cycle The cycle that is the cutoff point for the collection
Definition at line 50 of file ImpulseCollection.cpp.
References clearImpulses().
std::map< boost::uuids::uuid, boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::clearImpulses (common::CyclecycleStart, common::CyclecycleEnd)
Clear the Impulses that start on or after cycle start parameter and finish before cycle end parameter. Interval is [cycle_start,cycle_end)
Parameters:
Cycle cycleStart Cycle parameter that marks the start of the cleared area
Cycle cycleEnd Cycle parameter that marks the end of the cleared area (non-inclusive)
Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<Impulse> > The deleted collection of impulses
Definition at line 54 of file ImpulseCollection.cpp.
References cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::getMutableCollection().
void cryomesh::components::ImpulseCollection::clearImpulses ()
Clear collection up to present cycle. Update the collection to present cycle (non-inclusive) by dropping all impulses that are 'in the past' relative to that cycle. Interval is [0,present_cycle)
Definition at line 46 of file ImpulseCollection.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by clearImpulses(), and cryomesh::components::Node::updateImpulses().
void cryomesh::components::ImpulseCollection::decrementActivityTimers ()
Decrement the activity timers of all impulses.
Definition at line 163 of file ImpulseCollection.cpp.
References cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::getMutableCollection().
virtual void cryomesh::dataobjects::DataObjectController< unsigned long int , double >::enableLogging (boolenable) [inline, virtual, inherited]
Whether logging is enabled or not. Parameters:
bool enable True to enable logging, false otherwise
Definition at line 41 of file DataObjectController.h.
double cryomesh::components::ImpulseCollection::getActivity () const
Get activity at current cycle. Sum all the Impulses in the collection on the current cycle and return activity
Returns:
double The activity on specified cycle
Definition at line 41 of file ImpulseCollection.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by refreshDataObject().
double cryomesh::components::ImpulseCollection::getActivity (common::Cyclecycle) const
Get activity at cycle. Sum all the Impulses in the collection on specified cycle and return activity
Parameters:
Cycle cycle The cycle to calculate the activity on
Returns:
double The activity on specified cycle
Definition at line 23 of file ImpulseCollection.cpp.
References cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::getCollection(), and cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::objects.
std::list< boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::getByActivityTimerValue (doublevalue, ImpulseCollection::Comparisoncomp)
Get impulse list by activity timer value. Parameters:
double value activity timer value
Comparison comp What comparison to make with the value
Returns:
std::list<boost::shared_ptr< Impulse> > The list of impulses that meet the comparison
Definition at line 179 of file ImpulseCollection.cpp.
References cryomesh::common::Maths::compareDoubles(), EqualTo, cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::getMutableCollection(), GreaterThan, and LessThan.
Referenced by removeByActivityTimerValue().
const std::map<boost::uuids::uuid , boost::shared_ptr<Impulse > >& cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::getCollection () const [inline, inherited]
Get maximum value. Returns:
T The maximum value Get underlying collection
const std::map<U, boost::shared_ptr<T> > & The collection
Definition at line 309 of file KeyMappedCollection.h.
Referenced by getActivity(), and operator==().
virtual const dataobjects::DataObject<unsigned long int , double >& cryomesh::dataobjects::DataObjectController< unsigned long int , double >::getDataObject () [inline, virtual, inherited]
Get data object. Returns:
dataobjects::DataObject<U,T> & The data object
Definition at line 62 of file DataObjectController.h.
std::list<boost::uuids::uuid > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::getKeyList () const [inline, inherited]
Get keys for underlying connection. Returns:
std::list<U> The list of keys
Definition at line 208 of file KeyMappedCollection.h.
virtual const std::map<unsigned long int , double >& cryomesh::dataobjects::DataObjectController< unsigned long int , double >::getMap () [inline, virtual, inherited]
Get all cycle values. Returns:
std::map<unsigned long int, double> & The cycle values
Definition at line 51 of file DataObjectController.h.
std::map<boost::uuids::uuid , boost::shared_ptr<Impulse > >& cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::getMutableCollection () [inline, inherited]
Get mutable underlying collection. Returns:
const std::map<U, boost::shared_ptr<T> > & The mutable collection
Definition at line 319 of file KeyMappedCollection.h.
Referenced by clearActiveImpulses(), clearActivitiesByValue(), clearImpulses(), decrementActivityTimers(), and getByActivityTimerValue().
boost::shared_ptr<Impulse > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::getObjectByKey (const boost::uuids::uuid &key) [inline, inherited]
Get object using key. Parameters:
U key Key to search for
Returns:
boost::shared_ptr<T> The found object
Definition at line 250 of file KeyMappedCollection.h.
std::vector<boost::shared_ptr<Impulse > > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::getObjectList () const [inline, inherited]
Get object list for underlying connection. Returns:
std::list<U> The list of object values
Definition at line 228 of file KeyMappedCollection.h.
std::vector<boost::shared_ptr<Impulse > > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::getRandomRange (intnumber) const [inline, inherited]
Definition at line 261 of file KeyMappedCollection.h.
int cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::getSize () const [inline, inherited]
Get underlying collections size. Returns:
int The collections size
Definition at line 329 of file KeyMappedCollection.h.
bool cryomesh::components::ImpulseCollection::operator!= (const ImpulseCollection &obj) const
Not comparator operator. Parameters:
const ImpulseCollection & obj RHS object
Returns:
bool True if not equal, false otherwise
Definition at line 313 of file ImpulseCollection.cpp.
const ImpulseCollection cryomesh::components::ImpulseCollection::operator+ (const ImpulseCollection &obj) const
Non-destructive addition operator. Parameters:
const ImpulseCollection & obj RHS addition
Returns:
ImpulseCollection New object after addition
Definition at line 259 of file ImpulseCollection.cpp.
ImpulseCollection & cryomesh::components::ImpulseCollection::operator+= (const ImpulseCollection &obj)
Destructive addition and assignment operator. Parameters:
const ImpulseCollection & obj RHS addition
Returns:
ImpulseCollection & This object after addition and assignment
Definition at line 239 of file ImpulseCollection.cpp.
References cryomesh::common::KeyMappedCollection< U, T >::getCollection(), and cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::objects.
ImpulseCollection & cryomesh::components::ImpulseCollection::operator= (const ImpulseCollection &obj)
Assignment operator. Parameters:
const ImpulseCollection & obj RHS assignment
Returns:
ImpulseCollection & This object after assignment
Definition at line 230 of file ImpulseCollection.cpp.
References cryomesh::common::KeyMappedCollection< U, T >::getCollection(), and cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::objects.
bool cryomesh::components::ImpulseCollection::operator== (const ImpulseCollection &obj) const
Comparator operator. Parameters:
const ImpulseCollection & obj RHS object
Returns:
bool True if equal, false otherwise
Definition at line 265 of file ImpulseCollection.cpp.
References cryomesh::common::KeyMappedCollection< U, T >::getCollection(), and cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Impulse >::getCollection().
void cryomesh::components::ImpulseCollection::refreshDataObject () [virtual]
Inherited from DataObjectController. Overriden to force refresh update on call
Reimplemented from cryomesh::dataobjects::DataObjectController< unsigned long int, double >.
Definition at line 210 of file ImpulseCollection.cpp.
References cryomesh::dataobjects::DataObject< U, T >::clear(), cryomesh::dataobjects::DataObjectController< unsigned long int, double >::dataObject, getActivity(), cryomesh::dataobjects::DataObject< U, T >::getDatasetMaximumSize(), cryomesh::common::TimeKeeper::getTimeKeeper(), cryomesh::dataobjects::DataObject< U, T >::insert(), cryomesh::dataobjects::DataObject< U, T >::isLoggingEnabled(), and cryomesh::common::Cycle::toULInt().
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::remove (const std::list< boost::shared_ptr< Impulse > > &list) [inline, virtual, inherited]
Remove objects from collection by list. Parameters:
std::list<T> list The list values to be removed to the collection
Definition at line 124 of file KeyMappedCollection.h.
boost::shared_ptr<Impulse > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::remove (boost::uuids::uuidkey) [inline, inherited]
Remove object from collection bt key. Parameters:
U key The ey of the object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 191 of file KeyMappedCollection.h.
virtual void cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::remove (const std::initializer_list< boost::shared_ptr< Impulse > > &list) [inline, virtual, inherited]
Remove objects from collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be removed from the collection
Definition at line 106 of file KeyMappedCollection.h.
boost::shared_ptr<Impulse > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::remove (boost::shared_ptr< Impulse >obj) [inline, inherited]
Add object to collection. Parameters:
T & refobj The object to be added to the collection
Returns:
boost::shared_ptr<T> The object added to the collection
boost::shared_ptr<T> add(T & refobj) { boost::shared_ptr<T> obj = boost::shared_ptr<T>(&refobj); objects[obj->getKey()] = obj; return objects.find(obj->getKey())->second; } Remove object from collection
Parameters:
boost::shared_ptr<T> obj The object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 163 of file KeyMappedCollection.h.
boost::shared_ptr<Impulse > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::remove (Impulse &obj) [inline, inherited]
Remove object from collection. Parameters:
T & obj The object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 177 of file KeyMappedCollection.h.
std::list< boost::shared_ptr< Impulse > > cryomesh::components::ImpulseCollection::removeByActivityTimerValue (doublevalue = 0, ImpulseCollection::Comparisoncomp = LessThan)
remove impulses by activity timer value Parameters:
double value activity timer value
Comparison comp What comparison to make with the value
Returns:
std::list<boost::shared_ptr< Impulse> > The that meet the comparison and were removed
Definition at line 203 of file ImpulseCollection.cpp.
References getByActivityTimerValue().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const ImpulseCollection &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const ImpulseCollection & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 317 of file ImpulseCollection.cpp.
Member Data Documentation
dataobjects::DataObject<unsigned long int , double > cryomesh::dataobjects::DataObjectController< unsigned long int , double >::dataObject [protected, inherited]
Definition at line 79 of file DataObjectController.h.
Referenced by refreshDataObject(), and cryomesh::components::Node::update().
std::map<boost::uuids::uuid , boost::shared_ptr<Impulse > > cryomesh::common::KeyMappedCollection< boost::uuids::uuid , Impulse >::objects [protected, inherited]
Definition at line 339 of file KeyMappedCollection.h.
Referenced by getActivity(), operator+=(), and operator=().
Author
Generated automatically by Doxygen for cryomesh from the source code.