cryomesh::manager::PatternDatabaseObject
NAME
cryomesh::manager::PatternDatabaseObject -
SYNOPSIS
#include <PatternDatabaseObject.h>
Inherits cryomesh::manager::DatabaseObject.
Public Member Functions
PatternDatabaseObject (const std::string uuid_str, const common::Cycle &cyc, const state::Pattern &pat)
Create database object using pattern and a cycle.
PatternDatabaseObject (const std::string &node_table_entry)
Create object from the string of entries in the database output table.
virtual ~PatternDatabaseObject ()
Default destructor.
virtual std::string getInsert (const std::string &table) const
Get the string that can be used to insert the sql data.
std::string getUUID () const
Get uuid variable.
const common::Cycle & getCycle () const
Get cycle variable.
const state::Pattern & getPattern () const
Get pattern variable.
std::string getKey (const std::string &key) const
Return the string object associated with a key.
Static Public Member Functions
static std::string findValue (const std::string &entry, const std::map< std::string, std::string > &map)
Find entries value in map or return null.
static std::map< std::string,
std::string > getColumnMapFromEntry (const std::string &entry)"
Parse a string database entry, extract columns and values and return a map.
template<class T > static std::string toString (T obj)
Convert an templated object that can be piped to a stream to a string.
Static Public Attributes
static const std::string ID_TAG = 'id'
static const std::string CYCLE_TAG = 'cycle'
static const std::string PATTERN_TAG = 'pattern'
Protected Attributes
std::map< std::string,
std::string > columns"
Private Attributes
std::string uuid
common::Cycle cycle
boost::shared_ptr< state::Pattern > pattern
Detailed Description
Definition at line 22 of file PatternDatabaseObject.h.
Constructor & Destructor Documentation
cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject (const std::stringuuid_str, const common::Cycle &cyc, const state::Pattern &pat)
Create database object using pattern and a cycle.
Definition at line 19 of file PatternDatabaseObject.cpp.
References cryomesh::manager::DatabaseObject::columns, cycle, CYCLE_TAG, ID_TAG, pattern, PATTERN_TAG, cryomesh::common::Cycle::toULInt(), and uuid.
cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject (const std::string &node_table_entry)
Create object from the string of entries in the database output table. Parameters:
std::string The string of data taken from a output entry in the database node table
Definition at line 26 of file PatternDatabaseObject.cpp.
References cycle, CYCLE_TAG, cryomesh::manager::DatabaseObject::findValue(), cryomesh::manager::DatabaseObject::getColumnMapFromEntry(), ID_TAG, pattern, PATTERN_TAG, and uuid.
cryomesh::manager::PatternDatabaseObject::~PatternDatabaseObject () [virtual]
Default destructor.
Definition at line 38 of file PatternDatabaseObject.cpp.
Member Function Documentation
static std::string cryomesh::manager::DatabaseObject::findValue (const std::string &entry, const std::map< std::string, std::string > &map) [inline, static, inherited]
Find entries value in map or return null. Parameters:
std::string Entry to find
std::map<std::string,std::string map to search
Returns:
Value of entry
Definition at line 59 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and PatternDatabaseObject().
static std::map<std::string, std::string> cryomesh::manager::DatabaseObject::getColumnMapFromEntry (const std::string &entry) [inline, static, inherited]
Parse a string database entry, extract columns and values and return a map.
Definition at line 72 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and PatternDatabaseObject().
const common::Cycle & cryomesh::manager::PatternDatabaseObject::getCycle () const
Get cycle variable. Returns:
common::Cycle The cycle variable
Definition at line 55 of file PatternDatabaseObject.cpp.
References cycle.
std::string cryomesh::manager::PatternDatabaseObject::getInsert (const std::string &table) const [virtual]
Get the string that can be used to insert the sql data. Returns:
the sql command string to insert into this table
Implements cryomesh::manager::DatabaseObject.
Definition at line 42 of file PatternDatabaseObject.cpp.
References CYCLE_TAG, cryomesh::manager::DatabaseObject::getKey(), ID_TAG, and PATTERN_TAG.
std::string cryomesh::manager::DatabaseObject::getKey (const std::string &key) const [inline, inherited]
Return the string object associated with a key. ::string The key to search for
Returns:
std::string The object associated with the search key, '' if not found
Definition at line 37 of file DatabaseObject.h.
References cryomesh::manager::DatabaseObject::columns.
Referenced by getInsert(), cryomesh::manager::NodeDatabaseObject::getInsert(), and cryomesh::manager::ConnectionDatabaseObject::getInsert().
const state::Pattern & cryomesh::manager::PatternDatabaseObject::getPattern () const
Get pattern variable. Returns:
Pattern The pattern variable
Definition at line 59 of file PatternDatabaseObject.cpp.
References pattern.
std::string cryomesh::manager::PatternDatabaseObject::getUUID () const
Get uuid variable. Returns:
std::string The uuid variable
Definition at line 52 of file PatternDatabaseObject.cpp.
References uuid.
template<class T > static std::string cryomesh::manager::DatabaseObject::toString (Tobj) [inline, static, inherited]
Convert an templated object that can be piped to a stream to a string. Parameters:
T The object to get a string for
Definition at line 108 of file DatabaseObject.h.
Member Data Documentation
std::map<std::string, std::string> cryomesh::manager::DatabaseObject::columns [protected, inherited]
Definition at line 119 of file DatabaseObject.h.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::manager::DatabaseObject::getKey(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and PatternDatabaseObject().
common::Cycle cryomesh::manager::PatternDatabaseObject::cycle [private]
Definition at line 106 of file PatternDatabaseObject.h.
Referenced by getCycle(), and PatternDatabaseObject().
const std::string cryomesh::manager::PatternDatabaseObject::CYCLE_TAG = 'cycle' [static]
Definition at line 85 of file PatternDatabaseObject.h.
Referenced by getInsert(), and PatternDatabaseObject().
const std::string cryomesh::manager::PatternDatabaseObject::ID_TAG = 'id' [static]
Definition at line 79 of file PatternDatabaseObject.h.
Referenced by getInsert(), and PatternDatabaseObject().
boost::shared_ptr< state::Pattern > cryomesh::manager::PatternDatabaseObject::pattern [private]
Definition at line 113 of file PatternDatabaseObject.h.
Referenced by getPattern(), and PatternDatabaseObject().
const std::string cryomesh::manager::PatternDatabaseObject::PATTERN_TAG = 'pattern' [static]
Definition at line 92 of file PatternDatabaseObject.h.
Referenced by getInsert(), and PatternDatabaseObject().
std::string cryomesh::manager::PatternDatabaseObject::uuid [private]
Definition at line 99 of file PatternDatabaseObject.h.
Referenced by getUUID(), and PatternDatabaseObject().
Author
Generated automatically by Doxygen for cryomesh from the source code.