.TH "cryomesh::structures::FibreMap" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::structures::FibreMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FibreMap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFibreMap\fP ()"
.br
.ti -1c
.RI "virtual \fB~FibreMap\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBFibreMap\fP &objs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file FibreMap\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::structures::FibreMap::FibreMap\fP ()\fC [inline]\fP"
.PP
Definition at line 20 of file FibreMap\&.h\&.
.SS "virtual \fBcryomesh::structures::FibreMap::~FibreMap\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 22 of file FibreMap\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void \fBcryomesh::structures::FibreMap::update\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 24 of file FibreMap\&.h\&.
.PP
Referenced by cryomesh::structures::Bundle::update(), cryomesh::structures::Bundle::updatePrimaryInputFibres(), and cryomesh::structures::Bundle::updatePrimaryOutputFibres()\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBFibreMap\fP &objs)\fC [friend]\fP"
.PP
Definition at line 40 of file FibreMap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
