cryomesh::common::Cycle
NAME
cryomesh::common::Cycle -
SYNOPSIS
#include <Cycle.h>
Public Member Functions
Cycle ()
Default Constructor.
Cycle (const long int it)
Construct from unsigned long int.
Cycle (mpz_class mp)
Construct from mpz.
Cycle & operator= (const Cycle &obj)
Assignment operator.
const Cycle operator+ (const Cycle &obj) const
Non-destructive addition operator.
bool operator> (const Cycle &obj) const
Greater than operator.
bool operator< (const Cycle &obj) const
Less than operator.
bool operator>= (const Cycle &obj) const
>= than operator
bool operator<= (const Cycle &obj) const
<= than operator
Cycle & operator+= (const Cycle &obj)
Destructive addition and assignment operator.
const Cycle operator- (const Cycle &obj) const
Non-destructive addition operator.
Cycle & operator-= (const Cycle &obj)
Destructive addition and assignment operator.
bool operator== (const Cycle &obj) const
Comparator operator.
bool operator!= (const Cycle &obj) const
Not comparator operator.
Cycle & operator++ ()
Prefix increment operator.
Cycle operator++ (int)
Postfix increment operator.
Cycle operator-- (int)
Postfix decrement operator.
Cycle & operator-- ()
Prefix increment operator.
unsigned long int toULInt () const
Return as an unsigned integer.
long int toLInt () const
Return as an signed integer.
const mpz_class & getMP () const
Get multiprecision value.
Private Attributes
mpz_class cycle
Friends
std::ostream & operator<< (std::ostream &os, const Cycle &obj)
To stream operator.
Detailed Description
Definition at line 20 of file Cycle.h.
Constructor & Destructor Documentation
cryomesh::common::Cycle::Cycle ()
Default Constructor.
Definition at line 16 of file Cycle.cpp.
cryomesh::common::Cycle::Cycle (const long intit)
Construct from unsigned long int. Parameters:
const unsigned long int The ulong int to contruct from
Definition at line 19 of file Cycle.cpp.
cryomesh::common::Cycle::Cycle (mpz_classmp)
Construct from mpz. Parameters:
mpz_class mp The multi-precision integer to contruct from
Definition at line 23 of file Cycle.cpp.
Member Function Documentation
const mpz_class & cryomesh::common::Cycle::getMP () const
Get multiprecision value. Returns:
mpz_class
Definition at line 115 of file Cycle.cpp.
bool cryomesh::common::Cycle::operator!= (const Cycle &obj) const
Not comparator operator. Parameters:
const Cycle & obj RHS object
Returns:
bool True if not equal, false otherwise
Definition at line 68 of file Cycle.cpp.
const Cycle cryomesh::common::Cycle::operator+ (const Cycle &obj) const
Non-destructive addition operator. Parameters:
const Cycle & obj RHS addition
Returns:
Cycle New object after addition
Definition at line 32 of file Cycle.cpp.
Cycle & cryomesh::common::Cycle::operator++ ()
Prefix increment operator. Returns:
Cycle & Return this
Definition at line 88 of file Cycle.cpp.
Cycle cryomesh::common::Cycle::operator++ (int)
Postfix increment operator. Returns:
Cycle & Return this
Definition at line 93 of file Cycle.cpp.
Cycle & cryomesh::common::Cycle::operator+= (const Cycle &obj)
Destructive addition and assignment operator. Parameters:
const Cycle & obj RHS addition
Returns:
Cycle & This object after addition and assignment
Definition at line 38 of file Cycle.cpp.
const Cycle cryomesh::common::Cycle::operator- (const Cycle &obj) const
Non-destructive addition operator. Parameters:
const Cycle & obj RHS addition
Returns:
Cycle New object after addition
Definition at line 43 of file Cycle.cpp.
Cycle & cryomesh::common::Cycle::operator-- ()
Prefix increment operator. Returns:
Cycle & Return this
Definition at line 105 of file Cycle.cpp.
Cycle cryomesh::common::Cycle::operator-- (int)
Postfix decrement operator. Returns:
Cycle & Return this
Definition at line 99 of file Cycle.cpp.
Cycle & cryomesh::common::Cycle::operator-= (const Cycle &obj)
Destructive addition and assignment operator. Parameters:
const Cycle & obj RHS addition
Returns:
Cycle & This object after addition and assignment
Definition at line 51 of file Cycle.cpp.
bool cryomesh::common::Cycle::operator< (const Cycle &obj) const
Less than operator. Parameters:
const Cycle & obj RHS addition
Returns:
bool True if less than obj, false otherwise
Definition at line 76 of file Cycle.cpp.
bool cryomesh::common::Cycle::operator<= (const Cycle &obj) const
<= than operator Parameters:
const Cycle & obj RHS addition
Returns:
bool True if less than obj, false otherwise
Definition at line 84 of file Cycle.cpp.
Cycle & cryomesh::common::Cycle::operator= (const Cycle &obj)
Assignment operator. Parameters:
const Cycle & obj RHS assignment
Returns:
Cycle & This object after assignment
Definition at line 27 of file Cycle.cpp.
bool cryomesh::common::Cycle::operator== (const Cycle &obj) const
Comparator operator. Parameters:
const Cycle & obj RHS object
Returns:
bool True if equal, false otherwise
Definition at line 64 of file Cycle.cpp.
bool cryomesh::common::Cycle::operator> (const Cycle &obj) const
Greater than operator. Parameters:
const Cycle & obj RHS addition
Returns:
bool True if > than obj, false otherwise
Definition at line 72 of file Cycle.cpp.
bool cryomesh::common::Cycle::operator>= (const Cycle &obj) const
>= than operator Parameters:
const Cycle & obj RHS addition
Returns:
bool True if > than obj, false otherwise
Definition at line 80 of file Cycle.cpp.
long int cryomesh::common::Cycle::toLInt () const
Return as an signed integer. Returns:
signed int The cycle as an int
Definition at line 60 of file Cycle.cpp.
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::components::Impulse::getActivity(), and cryomesh::manager::DatabaseManager::updateByUUID().
unsigned long int cryomesh::common::Cycle::toULInt () const
Return as an unsigned integer. Returns:
unsigned int The cycle as an int
Definition at line 56 of file Cycle.cpp.
Referenced by cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), cryomesh::components::Impulse::operator+=(), and cryomesh::components::ImpulseCollection::refreshDataObject().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Cycle &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Cycle & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 110 of file Cycle.cpp.
Member Data Documentation
mpz_class cryomesh::common::Cycle::cycle [private]
Definition at line 240 of file Cycle.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.