.TH "cryomesh::common" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::common \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnector\fP"
.br
.RI "\fI\fBConnector\fP is a template to add connectable functionality between two classes. \fP"
.ti -1c
.RI "class \fBCycle\fP"
.br
.ti -1c
.RI "class \fBLoggable\fP"
.br
.ti -1c
.RI "class \fBTimeKeeper\fP"
.br
.RI "\fI\fBTimeKeeper\fP is a class keep track of the cycle state and timing. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBCycle\fP &obj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& cryomesh::common::operator<< (std::ostream &os, const Cycle &obj)"\fBParameters:\fP
.RS 4
\fIstd::ostream\fP & os The output stream 
.br
\fIconst\fP \fBCycle\fP & obj The object to stream
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream & The output stream 
.RE
.PP

.PP
Definition at line 110 of file Cycle.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
