cryomesh::manager::ConnectionDatabaseObject
NAME
cryomesh::manager::ConnectionDatabaseObject -
SYNOPSIS
#include <ConnectionDatabaseObject.h>
Inherits cryomesh::manager::DatabaseObject.
Public Member Functions
ConnectionDatabaseObject (const std::string &uuid_str, const std::string &innode_uuid_str, const std::string &outnode_uuid_str, const common::Cycle &cycle, const int impulse_count)
Create database object from connection information.
ConnectionDatabaseObject (const std::string &connection_table_entry)
Create database object from a string database entry for a connection.
virtual ~ConnectionDatabaseObject ()
Default Destructor.
virtual std::string getInsert (const std::string &table) const
Get the string that can be used to insert the sql data.
const std::string & getUUID () const
Get uuid variable of this object.
const std::string & getInputNodeUUID () const
Get inputNodeUUID variable of this object.
const std::string & getOutputNodeUUID () const
Get outputNodeUUID variable of this object.
const common::Cycle & getCycle () const
Get cycle variable of this object.
const int & getImpulseCount () const
Get impulseCount variable of this object.
std::string getKey (const std::string &key) const
Return the string object associated with a key.
Static Public Member Functions
static std::string findValue (const std::string &entry, const std::map< std::string, std::string > &map)
Find entries value in map or return null.
static std::map< std::string,
std::string > getColumnMapFromEntry (const std::string &entry)"
Parse a string database entry, extract columns and values and return a map.
template<class T > static std::string toString (T obj)
Convert an templated object that can be piped to a stream to a string.
Static Public Attributes
static const std::string ID_TAG = 'id'
static const std::string INPUT_ID_TAG = 'inputid'
static const std::string OUTPUT_ID_TAG = 'outputid'
static const std::string IMPULSE_COUNT_TAG = 'impulses'
static const std::string CYCLE_TAG = 'cycle'
Protected Attributes
std::map< std::string,
std::string > columns"
Private Attributes
std::string uuid
std::string inputNodeUUID
std::string outputNodeUUID
common::Cycle cycle
int impulseCount
Detailed Description
Definition at line 21 of file ConnectionDatabaseObject.h.
Constructor & Destructor Documentation
cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject (const std::string &uuid_str, const std::string &innode_uuid_str, const std::string &outnode_uuid_str, const common::Cycle &cycle, const intimpulse_count)
Create database object from connection information. Parameters:
std::string The uuid of the connection
std::string The uuid of the input node
std::string The uuid of the output node
common::Cycle The cycle of the entry
int The impulse count of the connection on this entry
Definition at line 20 of file ConnectionDatabaseObject.cpp.
References cryomesh::manager::DatabaseObject::columns, cycle, CYCLE_TAG, ID_TAG, IMPULSE_COUNT_TAG, INPUT_ID_TAG, OUTPUT_ID_TAG, and cryomesh::common::Cycle::toLInt().
cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject (const std::string &connection_table_entry)
Create database object from a string database entry for a connection. Parameters:
std::string The database entry of the connection
Definition at line 31 of file ConnectionDatabaseObject.cpp.
References cycle, cryomesh::manager::DatabaseObject::findValue(), cryomesh::manager::DatabaseObject::getColumnMapFromEntry(), impulseCount, inputNodeUUID, outputNodeUUID, and uuid.
cryomesh::manager::ConnectionDatabaseObject::~ConnectionDatabaseObject () [virtual]
Default Destructor.
Definition at line 66 of file ConnectionDatabaseObject.cpp.
Member Function Documentation
static std::string cryomesh::manager::DatabaseObject::findValue (const std::string &entry, const std::map< std::string, std::string > &map) [inline, static, inherited]
Find entries value in map or return null. Parameters:
std::string Entry to find
std::map<std::string,std::string map to search
Returns:
Value of entry
Definition at line 59 of file DatabaseObject.h.
Referenced by ConnectionDatabaseObject(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
static std::map<std::string, std::string> cryomesh::manager::DatabaseObject::getColumnMapFromEntry (const std::string &entry) [inline, static, inherited]
Parse a string database entry, extract columns and values and return a map.
Definition at line 72 of file DatabaseObject.h.
Referenced by ConnectionDatabaseObject(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
const common::Cycle & cryomesh::manager::ConnectionDatabaseObject::getCycle () const
Get cycle variable of this object. Returns:
std::string The cycle variable
Definition at line 92 of file ConnectionDatabaseObject.cpp.
References cycle.
const int & cryomesh::manager::ConnectionDatabaseObject::getImpulseCount () const
Get impulseCount variable of this object. Returns:
std::string The impulseCount variable
Definition at line 96 of file ConnectionDatabaseObject.cpp.
References impulseCount.
const std::string & cryomesh::manager::ConnectionDatabaseObject::getInputNodeUUID () const
Get inputNodeUUID variable of this object. Returns:
std::string The inputNodeUUID variable
Definition at line 84 of file ConnectionDatabaseObject.cpp.
References inputNodeUUID.
std::string cryomesh::manager::ConnectionDatabaseObject::getInsert (const std::string &table) const [virtual]
Get the string that can be used to insert the sql data. Returns:
the sql command string to insert into this table
Implements cryomesh::manager::DatabaseObject.
Definition at line 69 of file ConnectionDatabaseObject.cpp.
References CYCLE_TAG, cryomesh::manager::DatabaseObject::getKey(), ID_TAG, IMPULSE_COUNT_TAG, INPUT_ID_TAG, and OUTPUT_ID_TAG.
std::string cryomesh::manager::DatabaseObject::getKey (const std::string &key) const [inline, inherited]
Return the string object associated with a key. ::string The key to search for
Returns:
std::string The object associated with the search key, '' if not found
Definition at line 37 of file DatabaseObject.h.
References cryomesh::manager::DatabaseObject::columns.
Referenced by cryomesh::manager::PatternDatabaseObject::getInsert(), cryomesh::manager::NodeDatabaseObject::getInsert(), and getInsert().
const std::string & cryomesh::manager::ConnectionDatabaseObject::getOutputNodeUUID () const
Get outputNodeUUID variable of this object. Returns:
std::string The outputNodeUUID variable
Definition at line 88 of file ConnectionDatabaseObject.cpp.
References outputNodeUUID.
const std::string & cryomesh::manager::ConnectionDatabaseObject::getUUID () const
Get uuid variable of this object. Returns:
std::string The uuid variable
Definition at line 80 of file ConnectionDatabaseObject.cpp.
References uuid.
template<class T > static std::string cryomesh::manager::DatabaseObject::toString (Tobj) [inline, static, inherited]
Convert an templated object that can be piped to a stream to a string. Parameters:
T The object to get a string for
Definition at line 108 of file DatabaseObject.h.
Member Data Documentation
std::map<std::string, std::string> cryomesh::manager::DatabaseObject::columns [protected, inherited]
Definition at line 119 of file DatabaseObject.h.
Referenced by ConnectionDatabaseObject(), cryomesh::manager::DatabaseObject::getKey(), cryomesh::manager::NodeDatabaseObject::NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject().
common::Cycle cryomesh::manager::ConnectionDatabaseObject::cycle [private]
Definition at line 162 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getCycle().
const std::string cryomesh::manager::ConnectionDatabaseObject::CYCLE_TAG = 'cycle' [static]
Definition at line 133 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getInsert().
const std::string cryomesh::manager::ConnectionDatabaseObject::ID_TAG = 'id' [static]
Definition at line 106 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getInsert().
const std::string cryomesh::manager::ConnectionDatabaseObject::IMPULSE_COUNT_TAG = 'impulses' [static]
Definition at line 127 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getInsert().
int cryomesh::manager::ConnectionDatabaseObject::impulseCount [private]
Definition at line 169 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getImpulseCount().
const std::string cryomesh::manager::ConnectionDatabaseObject::INPUT_ID_TAG = 'inputid' [static]
Definition at line 113 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getInsert().
std::string cryomesh::manager::ConnectionDatabaseObject::inputNodeUUID [private]
Definition at line 148 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getInputNodeUUID().
const std::string cryomesh::manager::ConnectionDatabaseObject::OUTPUT_ID_TAG = 'outputid' [static]
Definition at line 120 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getInsert().
std::string cryomesh::manager::ConnectionDatabaseObject::outputNodeUUID [private]
Definition at line 155 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getOutputNodeUUID().
std::string cryomesh::manager::ConnectionDatabaseObject::uuid [private]
Definition at line 141 of file ConnectionDatabaseObject.h.
Referenced by ConnectionDatabaseObject(), and getUUID().
Author
Generated automatically by Doxygen for cryomesh from the source code.