cryomesh::components::Impulse
NAME
cryomesh::components::Impulse -
Impulse is a mobile information packet to be passed between Nodes.
SYNOPSIS
#include <Impulse.h>
Inherits cryomesh::common::Tagged, and SimpleCollection< double >.
Public Member Functions
Impulse ()
Constructor.
Impulse (const double max_y, const int length, const common::Cycle &startCycle=0)
Construct a from a curve with max f(x) and length and set starting cycle to startCycle, which defaults to the present, 'now' cycle.
Impulse (const double max_y, const int length, const common::Cycle &startCycle, boost::shared_ptr< ActivityTimerDistance >)
Construct a from a curve with max f(x) and length and set starting cycle to startCycle, and an activity timer.
virtual ~Impulse ()
Destructor.
void randomise ()
bool isActive () const
Is the Impulse active on current cycle.
bool isActive (const common::Cycle &cycle) const
Is the Impulse active on cycle.
bool isActive (const common::Cycle &startCycle, const common::Cycle &endCycle) const
Is the Impulse active at some point in cycle range.
double getActivity (common::Cycle cycle) const
Get activity at cycle.
double getActivity () const
Get activity at current cycle.
double getActivityMaximum () const
Get maximum activity.
double getActivityMinimum () const
Get minimum activity.
virtual Impulse & invert ()
Invert the impulse.
common::Cycle getFirstActiveCycle () const
Get the first active cycle.
void setFirstActiveCycle (const common::Cycle cycle)
Set the first active cycle.
common::Cycle getLastActiveCycle () const
Get the last active cycle.
const std::list< double > & getActivities () const
Get activities.
const boost::shared_ptr< ActivityTimerDistance > getActivityTimer () const
Get activity timer.
boost::shared_ptr< ActivityTimerDistance > getMutableActivityTimer ()
Get mutable activity timer.
void setActivityTimer (boost::shared_ptr< ActivityTimerDistance > timer)
Set activity timer.
const Impulse operator+ (const Impulse &obj) const
Non-destructive addition operator.
Impulse & operator+= (const Impulse &obj)
Destructive addition and assignment operator.
Impulse & operator= (const Impulse &obj)
Assignment operator.
bool operator== (const Impulse &obj) const
Comparator operator.
bool operator!= (const Impulse &obj) const
Not comparator operator.
boost::uuids::uuid getUUID () const
Get the uuid of object.
boost::uuids::uuid getKey () const
Get the key of object.
boost::uuids::uuid getTag () const
Get the tag of object.
virtual void clear ()
Clear all objects from collection.
virtual void add (doubleobj)
Add object to collection.
virtual void add (const std::initializer_list< double > &list)
Add object to collection by initialiser list.
virtual void add (const std::list< double > &list)
Add object to collection by list.
virtual void remove (doubleobj)
Remove object from collection.
virtual void remove (const std::initializer_list< double > &list)
Remove objects from collection by initialiser list.
virtual void remove (const std::list< double > &list)
Remove objects from collection by list.
virtual double getSum () const
virtual double getMaximum () const
virtual double getMinimum () const
virtual double operator[] (unsigned index) const throw (exceptions::IndexOutOfBoundsException)
Get value at index.
virtual SimpleCollection< double > & reverse ()
Reverse collection.
virtual const std::list< double > & getCollection () const
Get underlying collection.
virtual std::list< double > & getMutableCollection ()
Get mutable underlying collection.
virtual int getSize () const
Get underlying collections size.
virtual const SimpleCollection< double > operator+ (const SimpleCollection< double > &obj) const
Non-destructive addition operator.
virtual SimpleCollection< double > & operator+= (const SimpleCollection< double > &obj)
Destructive addition and assignment operator.
virtual bool operator== (const SimpleCollection< double > &obj) const
Comparator operator.
bool operator!= (const SimpleCollection &obj) const
Not comparator operator.
virtual bool operator!= (const SimpleCollection< double > &obj) const =0
Not comparator operator.
std::list< double > & pad (int front_pad, int back_pad, doublepad_value)
Pad Collection.
Static Public Member Functions
static boost::shared_ptr< Impulse > getTriggerImpulse ()
Get a 'trigger' impulse, a maximum impulse.
static boost::shared_ptr< Impulse > getRandomImpulse ()
Get a randomised impulse.
Static Public Attributes
static const double FORCED_TRIGGER_ACTIVITY = 1000
static const double MAX_ACTIVITY = 1
static const double MIN_ACTIVITY = -1
static const int MAX_ACTIVITY_LENGTH = 10
static const int MIN_ACTIVITY_LENGTH = 1
Protected Member Functions
double getActivityBoundary (bool maximal) const
Get the boundary value of activity.
double getBoundaryValue (bool greater) const
void generateCurve (const double max_y, const unsigned long length)
Generate a curve from boundary value.
Private Attributes
common::Cycle firstActiveCycle
The first cycle that this Impulse has activity.
common::Cycle lastActiveCycle
The lase cycle that this Impulse has activity.
boost::shared_ptr< ActivityTimerDistance > activityTimer
Friends
std::ostream & operator<< (std::ostream &os, const Impulse &obj)
To stream operator.
std::ostream & operator<< (std::ostream &out, const SimpleCollection &obj)
To stream operator.
Detailed Description
Impulse is a mobile information packet to be passed between Nodes.
Impulses represent information generated by a Node firing They are propagated along a connection Can be modified by the overlying Mesh as they propagate
Definition at line 30 of file Impulse.h.
Constructor & Destructor Documentation
cryomesh::components::Impulse::Impulse ()
Constructor. Constructor for Impulse
Parameters:
bool random If true then randomise the impulse on creation
Definition at line 37 of file Impulse.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
cryomesh::components::Impulse::Impulse (const doublemax_y, const intlength, const common::Cycle &startCycle = 0)
Construct a from a curve with max f(x) and length and set starting cycle to startCycle, which defaults to the present, 'now' cycle. Parameters:
const int max_y Boundary value of curve
const int length Length of Impulse
const Cycle startCycle Cycle to start activity on
Definition at line 45 of file Impulse.cpp.
cryomesh::components::Impulse::Impulse (const doublemax_y, const intlength, const common::Cycle &startCycle, boost::shared_ptr< ActivityTimerDistance >timer)
Construct a from a curve with max f(x) and length and set starting cycle to startCycle, and an activity timer. Parameters:
const int max_y Boundary value of curve
const int length Length of Impulse
const Cycle startCycle Cycle to start activity on
boost::shared_ptr<ActivityTimer> timer The activity timer associated with this
Definition at line 54 of file Impulse.cpp.
cryomesh::components::Impulse::~Impulse () [virtual]
Destructor. Destructor for Impulse
Definition at line 62 of file Impulse.cpp.
Member Function Documentation
virtual void cryomesh::common::SimpleCollection< double >::add (doubleobj) [inline, virtual, inherited]
Add object to collection. Parameters:
T obj The value to be added to the collection
Returns:
T The value added to the collection
Definition at line 80 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual void cryomesh::common::SimpleCollection< double >::add (const std::initializer_list< double > &list) [inline, virtual, inherited]
Add object to collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be added to the collection
Definition at line 90 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::add().
virtual void cryomesh::common::SimpleCollection< double >::add (const std::list< double > &list) [inline, virtual, inherited]
Add object to collection by list. Parameters:
std::list<T> list The list values to be added to the collection
Definition at line 108 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::add().
virtual void cryomesh::common::SimpleCollection< double >::clear () [inline, virtual, inherited]
Clear all objects from collection.
Definition at line 66 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
void cryomesh::common::SimpleCollection< double >::generateCurve (const doublemax_y, const unsigned longlength) [inline, protected, inherited]
Generate a curve from boundary value. Parameters:
const int max_y Boundary value of curve
const int length Length of Impulse
Definition at line 537 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
const std::list< double > & cryomesh::components::Impulse::getActivities () const
Get activities. Returns:
const std::list<double> & The activities list
Definition at line 155 of file Impulse.cpp.
double cryomesh::components::Impulse::getActivity () const
Get activity at current cycle. Sum all the Impulses in the collection on the current cycle and return activity
Returns:
double The activity on specified cycle
Definition at line 91 of file Impulse.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
double cryomesh::components::Impulse::getActivity (common::Cyclecycle) const
Get activity at cycle. Sum all the Impulses in the collection on specified cycle and return activity
Parameters:
int cycle The cycle to calculate the activity on
Returns:
double The activity on specified cycle
Definition at line 95 of file Impulse.cpp.
References cryomesh::common::Cycle::toLInt().
double cryomesh::components::Impulse::getActivityBoundary (boolmaximal) const [protected]
Get the boundary value of activity. Parameters:
bool maximal True if maximal boundary, false if minimal
Returns:
double The boundary value of activity
double cryomesh::components::Impulse::getActivityMaximum () const
Get maximum activity. Find the maximum activity between start and end cycles
Returns:
double The maximum activity
Definition at line 120 of file Impulse.cpp.
double cryomesh::components::Impulse::getActivityMinimum () const
Get minimum activity. Find the minimum activity between start and end cycles
Returns:
double The minimum activity
Definition at line 124 of file Impulse.cpp.
const boost::shared_ptr< ActivityTimerDistance > cryomesh::components::Impulse::getActivityTimer () const
Get activity timer. Returns:
boost::shared_ptr< ActivityTimer > activityTimer; The activity timer
Definition at line 159 of file Impulse.cpp.
Referenced by operator=().
double cryomesh::common::SimpleCollection< double >::getBoundaryValue (boolgreater) const [inline, protected, inherited]
Definition at line 500 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual const std::list<double >& cryomesh::common::SimpleCollection< double >::getCollection () const [inline, virtual, inherited]
Get underlying collection. Returns:
const std::list<T> & The collection
Definition at line 298 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
Cycle cryomesh::components::Impulse::getFirstActiveCycle () const
Get the first active cycle. Returns:
Cycle The first active cycle
Definition at line 133 of file Impulse.cpp.
Referenced by cryomesh::components::ImpulseCollection::clearActiveImpulses(), operator+=(), operator=(), and operator==().
boost::uuids::uuid cryomesh::common::Tagged::getKey () const [inline, inherited]
Get the key of object. Returns:
boost::uuids::uuid The unique uuid tag of this object
Definition at line 61 of file Tagged.h.
References cryomesh::common::Tagged::getUUID().
Cycle cryomesh::components::Impulse::getLastActiveCycle () const
Get the last active cycle. Returns:
Cycle The last active cycle
Definition at line 151 of file Impulse.cpp.
Referenced by cryomesh::components::ImpulseCollection::clearActiveImpulses(), operator+=(), and operator==().
virtual double cryomesh::common::SimpleCollection< double >::getMaximum () const [inline, virtual, inherited]
Definition at line 205 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getBoundaryValue().
virtual double cryomesh::common::SimpleCollection< double >::getMinimum () const [inline, virtual, inherited]
Definition at line 215 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getBoundaryValue().
boost::shared_ptr< ActivityTimerDistance > cryomesh::components::Impulse::getMutableActivityTimer ()
Get mutable activity timer. Returns:
boost::shared_ptr< ActivityTimer > activityTimer; The activity timer
Definition at line 163 of file Impulse.cpp.
virtual std::list<double >& cryomesh::common::SimpleCollection< double >::getMutableCollection () [inline, virtual, inherited]
Get mutable underlying collection. Returns:
std::list<T> & The mutable collection
Definition at line 308 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
boost::shared_ptr< Impulse > cryomesh::components::Impulse::getRandomImpulse () [static]
Get a randomised impulse. Returns:
boost::shared_ptr<Impulse> The randomised impulse
Definition at line 31 of file Impulse.cpp.
Referenced by cryomesh::components::Node::randomise().
virtual int cryomesh::common::SimpleCollection< double >::getSize () const [inline, virtual, inherited]
Get underlying collections size. Returns:
int The collections size
Definition at line 318 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual double cryomesh::common::SimpleCollection< double >::getSum () const [inline, virtual, inherited]
Definition at line 185 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
boost::uuids::uuid cryomesh::common::Tagged::getTag () const [inline, inherited]
Get the tag of object. Returns:
boost::uuids::uuid The unique uuid tag of this object
Definition at line 71 of file Tagged.h.
References cryomesh::common::Tagged::getUUID().
boost::shared_ptr< Impulse > cryomesh::components::Impulse::getTriggerImpulse () [static]
Get a 'trigger' impulse, a maximum impulse. Returns:
boost::shared_ptr<Impulse> The trigger impulse
Definition at line 26 of file Impulse.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by cryomesh::structures::Fibre::trigger().
boost::uuids::uuid cryomesh::common::Tagged::getUUID () const [inline, inherited]
Get the uuid of object. Returns:
boost::uuids::uuid The unique uuid tag of this object
Definition at line 51 of file Tagged.h.
References cryomesh::common::Tagged::uuid.
Referenced by cryomesh::common::Tagged::getKey(), and cryomesh::common::Tagged::getTag().
Impulse & cryomesh::components::Impulse::invert () [virtual]
Invert the impulse. @ return Impulse & This object inverted
Reimplemented from cryomesh::common::SimpleCollection< double >.
Definition at line 128 of file Impulse.cpp.
References cryomesh::common::SimpleCollection< T >::invert().
bool cryomesh::components::Impulse::isActive () const
Is the Impulse active on current cycle. Returns:
bool True if active, false otherwise
Definition at line 74 of file Impulse.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by cryomesh::components::ImpulseCollection::clearActiveImpulses().
bool cryomesh::components::Impulse::isActive (const common::Cycle &startCycle, const common::Cycle &endCycle) const
Is the Impulse active at some point in cycle range. Returns:
bool True if active, false otherwise
Definition at line 82 of file Impulse.cpp.
bool cryomesh::components::Impulse::isActive (const common::Cycle &cycle) const
Is the Impulse active on cycle. Returns:
bool True if active, false otherwise
Definition at line 78 of file Impulse.cpp.
bool cryomesh::components::Impulse::operator!= (const Impulse &obj) const
Not comparator operator. Parameters:
const Impulse & obj RHS object
Returns:
bool True if not equal, false otherwise
Definition at line 290 of file Impulse.cpp.
bool cryomesh::common::SimpleCollection< double >::operator!= (const SimpleCollection< double > &obj) const [inline, inherited]
Not comparator operator. Parameters:
const SimpleCollection & obj RHS object
Returns:
bool True if not equal, false otherwise
Definition at line 432 of file SimpleCollection.h.
virtual bool cryomesh::common::ICollection< SimpleCollection< double > >::operator!= (const SimpleCollection< double > &obj) const [pure virtual, inherited]
Not comparator operator. Parameters:
const T & obj RHS object
Returns:
bool True if not equal, false otherwise
virtual const SimpleCollection<double > cryomesh::common::SimpleCollection< double >::operator+ (const SimpleCollection< double > &obj) const [inline, virtual, inherited]
Non-destructive addition operator. Parameters:
const SimpleCollection<T> & obj RHS addition
Returns:
SimpleCollection<T> New object after addition
Implements cryomesh::common::ICollection< SimpleCollection< double > >.
Definition at line 331 of file SimpleCollection.h.
const Impulse cryomesh::components::Impulse::operator+ (const Impulse &obj) const
Non-destructive addition operator. Parameters:
const Impulse & obj RHS addition
Returns:
Impulse New object after addition
Definition at line 171 of file Impulse.cpp.
virtual SimpleCollection<double >& cryomesh::common::SimpleCollection< double >::operator+= (const SimpleCollection< double > &obj) [inline, virtual, inherited]
Destructive addition and assignment operator. Parameters:
const SimpleCollection<T> & obj RHS addition
Returns:
SimpleCollection<T> & This object after addition and assignment
Implements cryomesh::common::ICollection< SimpleCollection< double > >.
Definition at line 346 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getCollection(), and cryomesh::common::SimpleCollection< T >::getMutableCollection().
Impulse & cryomesh::components::Impulse::operator+= (const Impulse &obj)
Destructive addition and assignment operator. Parameters:
const Impulse & obj RHS addition
Returns:
Impulse & This object after addition and assignment
Definition at line 177 of file Impulse.cpp.
References cryomesh::common::SimpleCollection< T >::getCollection(), getFirstActiveCycle(), getLastActiveCycle(), and cryomesh::common::Cycle::toULInt().
Impulse & cryomesh::components::Impulse::operator= (const Impulse &obj)
Assignment operator. Parameters:
const Impulse & obj RHS assignment
Returns:
Impulse & This object after assignment
Definition at line 231 of file Impulse.cpp.
References cryomesh::common::SimpleCollection< T >::clear(), getActivityTimer(), cryomesh::common::SimpleCollection< T >::getCollection(), and getFirstActiveCycle().
virtual bool cryomesh::common::SimpleCollection< double >::operator== (const SimpleCollection< double > &obj) const [inline, virtual, inherited]
Comparator operator. Parameters:
const SimpleCollection<T> & obj RHS object
Returns:
bool True if equal, false otherwise
Implements cryomesh::common::ICollection< SimpleCollection< double > >.
Definition at line 390 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getCollection(), and cryomesh::common::Containers::print().
bool cryomesh::components::Impulse::operator== (const Impulse &obj) const
Comparator operator. Parameters:
const Impulse & obj RHS object
Returns:
bool True if equal, false otherwise
Definition at line 253 of file Impulse.cpp.
References cryomesh::common::Maths::compareDoubles(), cryomesh::common::SimpleCollection< T >::getCollection(), getFirstActiveCycle(), and getLastActiveCycle().
virtual double cryomesh::common::SimpleCollection< double >::operator[] (unsignedindex) const throw (exceptions::IndexOutOfBoundsException) [inline, virtual, inherited]
Get value at index. Parameters:
unsigned index Index to return
Returns:
T Value at index, 0 if out of bounds
Definition at line 228 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::getSize(), and cryomesh::common::SimpleCollection< T >::objects.
std::list<double >& cryomesh::common::SimpleCollection< double >::pad (intfront_pad, intback_pad, doublepad_value) [inline, inherited]
Pad Collection. Parameters:
int front_pad Amount of places to pad to front
int back_pad Amount of places to pad to back
T & obj Object to use for pad
Returns:
T & Return the collection
Definition at line 475 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
void cryomesh::components::Impulse::randomise ()
Definition at line 65 of file Impulse.cpp.
References cryomesh::common::Maths::getRandomDouble(), and cryomesh::common::Maths::getRandomInteger().
virtual void cryomesh::common::SimpleCollection< double >::remove (const std::initializer_list< double > &list) [inline, virtual, inherited]
Remove objects from collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be removed from the collection
Definition at line 149 of file SimpleCollection.h.
virtual void cryomesh::common::SimpleCollection< double >::remove (const std::list< double > &list) [inline, virtual, inherited]
Remove objects from collection by list. Parameters:
std::list<T> list The list values to be removed to the collection
Definition at line 167 of file SimpleCollection.h.
virtual void cryomesh::common::SimpleCollection< double >::remove (doubleobj) [inline, virtual, inherited]
Remove object from collection. Parameters:
T obj The object to be removed from the collection
Definition at line 126 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects.
virtual SimpleCollection<double >& cryomesh::common::SimpleCollection< double >::reverse () [inline, virtual, inherited]
Reverse collection. Reflect the collection in the y axis
Returns:
SimpleCollection<T> & The inverted object
Definition at line 285 of file SimpleCollection.h.
References cryomesh::common::SimpleCollection< T >::objects, and cryomesh::common::SimpleCollection< T >::reverse().
void cryomesh::components::Impulse::setActivityTimer (boost::shared_ptr< ActivityTimerDistance >timer)
Set activity timer. Parameters:
boost::shared_ptr<ActivityTimer> The activity timer to set
Definition at line 167 of file Impulse.cpp.
void cryomesh::components::Impulse::setFirstActiveCycle (const common::Cyclecycle)
Set the first active cycle. Parameters:
const Cycle cycle The first active cycle
Definition at line 137 of file Impulse.cpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Impulse &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Impulse & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 294 of file Impulse.cpp.
std::ostream& operator<< (std::ostream &out, const SimpleCollection< double > &obj) [friend, inherited]
To stream operator. Parameters:
std::ostream & out The output stream
const SimpleCollection & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 447 of file SimpleCollection.h.
Member Data Documentation
boost::shared_ptr<ActivityTimerDistance> cryomesh::components::Impulse::activityTimer [private]
Definition at line 377 of file Impulse.h.
common::Cycle cryomesh::components::Impulse::firstActiveCycle [private]
The first cycle that this Impulse has activity. Returns:
Cycle Return first active cycle
Definition at line 362 of file Impulse.h.
const double cryomesh::components::Impulse::FORCED_TRIGGER_ACTIVITY = 1000 [static]
Definition at line 293 of file Impulse.h.
common::Cycle cryomesh::components::Impulse::lastActiveCycle [private]
The lase cycle that this Impulse has activity. Returns:
Cycle Return last active cycle
Definition at line 370 of file Impulse.h.
const double cryomesh::components::Impulse::MAX_ACTIVITY = 1 [static]
Definition at line 300 of file Impulse.h.
const int cryomesh::components::Impulse::MAX_ACTIVITY_LENGTH = 10 [static]
Definition at line 316 of file Impulse.h.
const double cryomesh::components::Impulse::MIN_ACTIVITY = -1 [static]
Definition at line 308 of file Impulse.h.
const int cryomesh::components::Impulse::MIN_ACTIVITY_LENGTH = 1 [static]
Definition at line 324 of file Impulse.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.