cryomesh::state::BinaryString
NAME
cryomesh::state::BinaryString -
SYNOPSIS
#include <BinaryString.h>
Public Types
enum Type { TXT, BIN }
Public Member Functions
template<class Archive > void serialize (Archive &ar, const unsigned int version)
BinaryString ()
BinaryString (const std::string &str, bool sign_bit=false, Type tp=TXT)
BinaryString (const std::vector< bool > &binvec, bool sign_bit)
BinaryString (const BinaryString &obj)
virtual ~BinaryString ()
void setSignBit (bool b)
bool getSignBit () const
const std::string & getBinaryString () const
const std::vector< bool > getBools () const
void setBinaryString (const std::string &str)
void setBinaryString (const std::vector< bool > &binvec)
bool isValidBinary () const
bool isAllZeroes () const
unsigned int getWidth () const
std::list< int > toInts () const
std::string toText () const
std::string resize (const unsigned int size)
int toInt () const
Static Public Member Functions
static std::list< int > formatTextToInts (const std::string &str)
static std::string formatIntsToText (const std::list< int > &charints)
static std::list< BinaryString > formatTextToBinaryStrings (const std::string &str, std::string &allbins)
static std::string formatBinaryStringsToText (const std::list< std::string > &strs)
Static Public Attributes
static const unsigned int BINARY_CHAR_LENGTH = 8
static const unsigned int MAX_BINARY_INTEGER_SIZE = 32
Static Private Member Functions
static std::string charToBinaryString (const char &ch, bool sign_bit)
Private Attributes
std::string binaryString
bool signBit
Friends
class boost::serialization::access
std::ostream & operator<< (std::ostream &os, const BinaryString &obj)
Detailed Description
Definition at line 21 of file BinaryString.h.
Member Enumeration Documentation
enum cryomesh::state::BinaryString::Type
Enumerator:
TXT
BIN
Definition at line 29 of file BinaryString.h.
Constructor & Destructor Documentation
cryomesh::state::BinaryString::BinaryString ()
Definition at line 21 of file BinaryString.cpp.
cryomesh::state::BinaryString::BinaryString (const std::string &str, boolsign_bit = false, Typetp = TXT)
Definition at line 25 of file BinaryString.cpp.
References BIN, BINARY_CHAR_LENGTH, binaryString, charToBinaryString(), formatTextToInts(), getSignBit(), and resize().
cryomesh::state::BinaryString::BinaryString (const std::vector< bool > &binvec, boolsign_bit)
Definition at line 59 of file BinaryString.cpp.
References binaryString.
cryomesh::state::BinaryString::BinaryString (const BinaryString &obj)
Definition at line 78 of file BinaryString.cpp.
References binaryString, getBinaryString(), getSignBit(), and signBit.
cryomesh::state::BinaryString::~BinaryString () [virtual]
Definition at line 83 of file BinaryString.cpp.
Member Function Documentation
std::string cryomesh::state::BinaryString::charToBinaryString (const char &ch, boolsign_bit) [static, private]
Definition at line 327 of file BinaryString.cpp.
References BIN, BINARY_CHAR_LENGTH, and resize().
Referenced by BinaryString(), and formatTextToBinaryStrings().
static std::string cryomesh::state::BinaryString::formatBinaryStringsToText (const std::list< std::string > &strs) [static]
std::string cryomesh::state::BinaryString::formatIntsToText (const std::list< int > &charints) [static]
Definition at line 290 of file BinaryString.cpp.
std::list< BinaryString > cryomesh::state::BinaryString::formatTextToBinaryStrings (const std::string &str, std::string &allbins) [static]
Definition at line 304 of file BinaryString.cpp.
References BIN, and charToBinaryString().
Referenced by toInts().
std::list< int > cryomesh::state::BinaryString::formatTextToInts (const std::string &str) [static]
Definition at line 277 of file BinaryString.cpp.
Referenced by BinaryString().
const std::string & cryomesh::state::BinaryString::getBinaryString () const
Definition at line 93 of file BinaryString.cpp.
References binaryString.
Referenced by BinaryString(), cryomesh::state::operator<<(), resize(), toInts(), and toText().
const std::vector< bool > cryomesh::state::BinaryString::getBools () const
Definition at line 97 of file BinaryString.cpp.
References binaryString, and isValidBinary().
Referenced by cryomesh::state::Pattern::getPattern().
bool cryomesh::state::BinaryString::getSignBit () const
Definition at line 90 of file BinaryString.cpp.
References signBit.
Referenced by BinaryString(), resize(), toInt(), and toText().
unsigned int cryomesh::state::BinaryString::getWidth () const
Definition at line 177 of file BinaryString.cpp.
References binaryString.
Referenced by cryomesh::state::Pattern::getSize().
bool cryomesh::state::BinaryString::isAllZeroes () const
Definition at line 162 of file BinaryString.cpp.
References binaryString.
Referenced by cryomesh::state::Pattern::isAllZeroes().
bool cryomesh::state::BinaryString::isValidBinary () const
Definition at line 147 of file BinaryString.cpp.
References binaryString.
Referenced by getBools(), and toInt().
std::string cryomesh::state::BinaryString::resize (const unsigned intsize)
Definition at line 374 of file BinaryString.cpp.
References binaryString, getBinaryString(), and getSignBit().
Referenced by BinaryString(), charToBinaryString(), and toText().
template<class Archive > void cryomesh::state::BinaryString::serialize (Archive &ar, const unsigned intversion) [inline]
Definition at line 25 of file BinaryString.h.
References binaryString, and signBit.
void cryomesh::state::BinaryString::setBinaryString (const std::string &str)
Definition at line 125 of file BinaryString.cpp.
References binaryString.
Referenced by cryomesh::state::Pattern::setPattern().
void cryomesh::state::BinaryString::setBinaryString (const std::vector< bool > &binvec)
Definition at line 128 of file BinaryString.cpp.
References binaryString.
void cryomesh::state::BinaryString::setSignBit (boolb)
Definition at line 87 of file BinaryString.cpp.
References signBit.
int cryomesh::state::BinaryString::toInt () const
Definition at line 181 of file BinaryString.cpp.
References binaryString, getSignBit(), isValidBinary(), MAX_BINARY_INTEGER_SIZE, and signBit.
Referenced by toText().
std::list< int > cryomesh::state::BinaryString::toInts () const
Definition at line 227 of file BinaryString.cpp.
References formatTextToBinaryStrings(), and getBinaryString().
std::string cryomesh::state::BinaryString::toText () const
Definition at line 242 of file BinaryString.cpp.
References BIN, BINARY_CHAR_LENGTH, binaryString, getBinaryString(), getSignBit(), resize(), and toInt().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 23 of file BinaryString.h.
std::ostream& operator<< (std::ostream &os, const BinaryString &obj) [friend]
Definition at line 223 of file BinaryString.cpp.
Member Data Documentation
const unsigned int cryomesh::state::BinaryString::BINARY_CHAR_LENGTH = 8 [static]
Definition at line 61 of file BinaryString.h.
Referenced by BinaryString(), charToBinaryString(), and toText().
std::string cryomesh::state::BinaryString::binaryString [private]
Definition at line 64 of file BinaryString.h.
Referenced by BinaryString(), getBinaryString(), getBools(), getWidth(), isAllZeroes(), isValidBinary(), resize(), serialize(), setBinaryString(), toInt(), and toText().
const unsigned int cryomesh::state::BinaryString::MAX_BINARY_INTEGER_SIZE = 32 [static]
Definition at line 62 of file BinaryString.h.
Referenced by toInt().
bool cryomesh::state::BinaryString::signBit [private]
Definition at line 65 of file BinaryString.h.
Referenced by BinaryString(), getSignBit(), serialize(), setSignBit(), and toInt().
Author
Generated automatically by Doxygen for cryomesh from the source code.