cryomesh::state::Pattern
NAME
cryomesh::state::Pattern -
SYNOPSIS
#include <Pattern.h>
Public Member Functions
Pattern ()
Pattern (const Pattern &)
Pattern (const std::string &)
Pattern (const std::vector< bool > &)
Pattern (const BinaryString &obj)
virtual ~Pattern ()
Pattern & operator= (const Pattern &)
double compare (const Pattern &) const
bool isAllZeroes () const
bool operator== (const Pattern &) const
bool operator< (const Pattern &) const
std::vector< bool > getPattern () const
std::string getString () const
void setPattern (const std::vector< bool > &)
int getId () const
void setId (int)
int getWidth () const
int getSize () const
const BinaryString & getBinaryString () const
BinaryString & getMutableBinaryString ()
const boost::shared_ptr
< PatternTag > getPatternTag () const "
void setPatternTag (boost::shared_ptr< PatternTag > pt)
boost::shared_ptr
< manager::DatabaseObject > getDatabaseObject () const "
Static Public Member Functions
static int getIds ()
static int assignIds ()
static void setIds (int)
static std::string patternToString (const std::vector< bool > &vec)
static std::vector< bool > stringToPattern (const std::string &)
static Pattern getRandom (unsigned int width, double fraction=0.5)
Generate a random pattern of width.
Private Member Functions
template<class Archive > void serialize (Archive &ar, const unsigned int version)
void initialise ()
Private Attributes
BinaryString binaryString
int id
boost::shared_ptr< PatternTag > patternTag
Static Private Attributes
static int ids = 1
Friends
class boost::serialization::access
std::ostream & operator<< (std::ostream &os, const Pattern &obj)
Detailed Description
Definition at line 27 of file Pattern.h.
Constructor & Destructor Documentation
cryomesh::state::Pattern::Pattern ()
Definition at line 31 of file Pattern.cpp.
References initialise().
Referenced by getRandom().
cryomesh::state::Pattern::Pattern (const Pattern &pat)
Definition at line 35 of file Pattern.cpp.
References initialise().
cryomesh::state::Pattern::Pattern (const std::string &str)
Definition at line 43 of file Pattern.cpp.
References initialise().
cryomesh::state::Pattern::Pattern (const std::vector< bool > &pat)
Definition at line 39 of file Pattern.cpp.
References initialise().
cryomesh::state::Pattern::Pattern (const BinaryString &obj)
cryomesh::state::Pattern::~Pattern () [virtual]
Definition at line 47 of file Pattern.cpp.
Member Function Documentation
int cryomesh::state::Pattern::assignIds () [static]
Definition at line 212 of file Pattern.cpp.
References ids.
double cryomesh::state::Pattern::compare (const Pattern &obj) const
Definition at line 63 of file Pattern.cpp.
References getPattern().
const BinaryString & cryomesh::state::Pattern::getBinaryString () const
Definition at line 159 of file Pattern.cpp.
References binaryString.
Referenced by operator=().
boost::shared_ptr< manager::DatabaseObject > cryomesh::state::Pattern::getDatabaseObject () const
Definition at line 229 of file Pattern.cpp.
References cryomesh::common::TimeKeeper::getCycle(), getString(), cryomesh::common::TimeKeeper::getTimeKeeper(), and cryomesh::common::Cycle::toULInt().
int cryomesh::state::Pattern::getId () const
Definition at line 142 of file Pattern.cpp.
References id.
Referenced by operator<(), cryomesh::state::operator<<(), and operator=().
int cryomesh::state::Pattern::getIds () [static]
Definition at line 218 of file Pattern.cpp.
References ids.
Referenced by cryomesh::state::PatternTagById::getEndTag().
BinaryString & cryomesh::state::Pattern::getMutableBinaryString ()
Definition at line 162 of file Pattern.cpp.
References binaryString.
std::vector< bool > cryomesh::state::Pattern::getPattern () const
Definition at line 133 of file Pattern.cpp.
References binaryString, and cryomesh::state::BinaryString::getBools().
Referenced by compare(), cryomesh::structures::Fibre::forceFireNodes(), getString(), operator==(), and cryomesh::structures::Fibre::trigger().
const boost::shared_ptr< PatternTag > cryomesh::state::Pattern::getPatternTag () const
Definition at line 205 of file Pattern.cpp.
References patternTag.
Pattern cryomesh::state::Pattern::getRandom (unsigned intwidth, doublefraction = 0.5) [static]
Generate a random pattern of width. Parameters:
unsigned int Width of pattern to generate
double Fraction of pattern to activate, default to 0.5
Returns:
Pattern The random pattern
Definition at line 21 of file Pattern.cpp.
References Pattern().
Referenced by cryomesh::structures::Fibre::trigger().
int cryomesh::state::Pattern::getSize () const
Definition at line 155 of file Pattern.cpp.
References binaryString, and cryomesh::state::BinaryString::getWidth().
Referenced by cryomesh::structures::Fibre::forceFireNodes(), and getWidth().
std::string cryomesh::state::Pattern::getString () const
Definition at line 136 of file Pattern.cpp.
References getPattern(), and patternToString().
Referenced by getDatabaseObject(), and cryomesh::state::operator<<().
int cryomesh::state::Pattern::getWidth () const
Definition at line 151 of file Pattern.cpp.
References getSize().
void cryomesh::state::Pattern::initialise () [private]
Definition at line 237 of file Pattern.cpp.
References patternTag.
Referenced by operator=(), and Pattern().
bool cryomesh::state::Pattern::isAllZeroes () const
Definition at line 60 of file Pattern.cpp.
References binaryString, and cryomesh::state::BinaryString::isAllZeroes().
bool cryomesh::state::Pattern::operator< (const Pattern &obj) const
Definition at line 129 of file Pattern.cpp.
References getId().
Pattern & cryomesh::state::Pattern::operator= (const Pattern &obj)
Definition at line 51 of file Pattern.cpp.
References binaryString, getBinaryString(), getId(), initialise(), and setId().
bool cryomesh::state::Pattern::operator== (const Pattern &obj) const
Definition at line 115 of file Pattern.cpp.
References getPattern().
std::string cryomesh::state::Pattern::patternToString (const std::vector< bool > &vec) [static]
Definition at line 166 of file Pattern.cpp.
Referenced by getString().
template<class Archive > void cryomesh::state::Pattern::serialize (Archive &ar, const unsigned intversion) [inline, private]
Definition at line 30 of file Pattern.h.
References binaryString, id, and ids.
void cryomesh::state::Pattern::setId (intnew_id)
Definition at line 145 of file Pattern.cpp.
Referenced by operator=().
void cryomesh::state::Pattern::setIds (intis) [static]
Definition at line 222 of file Pattern.cpp.
References ids.
void cryomesh::state::Pattern::setPattern (const std::vector< bool > &pat)
Definition at line 139 of file Pattern.cpp.
References binaryString, and cryomesh::state::BinaryString::setBinaryString().
void cryomesh::state::Pattern::setPatternTag (boost::shared_ptr< PatternTag >pt)
Definition at line 208 of file Pattern.cpp.
References patternTag.
std::vector< bool > cryomesh::state::Pattern::stringToPattern (const std::string &str) [static]
Definition at line 184 of file Pattern.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 28 of file Pattern.h.
std::ostream& operator<< (std::ostream &os, const Pattern &obj) [friend]
Definition at line 242 of file Pattern.cpp.
Member Data Documentation
BinaryString cryomesh::state::Pattern::binaryString [private]
Definition at line 115 of file Pattern.h.
Referenced by getBinaryString(), getMutableBinaryString(), getPattern(), getSize(), isAllZeroes(), operator=(), serialize(), and setPattern().
int cryomesh::state::Pattern::id [private]
Definition at line 117 of file Pattern.h.
Referenced by getId(), and serialize().
int cryomesh::state::Pattern::ids = 1 [static, private]
Definition at line 128 of file Pattern.h.
Referenced by assignIds(), getIds(), serialize(), and setIds().
boost::shared_ptr<PatternTag> cryomesh::state::Pattern::patternTag [private]
Definition at line 120 of file Pattern.h.
Referenced by getPatternTag(), initialise(), and setPatternTag().
Author
Generated automatically by Doxygen for cryomesh from the source code.