.TH "cryomesh::spacial::Degree" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::spacial::Degree \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Degree.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDegree\fP (double d)"
.br
.ti -1c
.RI "virtual \fB~Degree\fP ()"
.br
.ti -1c
.RI "double \fBgetValue\fP () const "
.br
.ti -1c
.RI "double \fBtoRadians\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Degree.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::spacial::Degree::Degree (doubled)"
.PP
Definition at line 16 of file Degree.cpp.
.SS "cryomesh::spacial::Degree::~Degree ()\fC [virtual]\fP"
.PP
Definition at line 20 of file Degree.cpp.
.SH "Member Function Documentation"
.PP 
.SS "double cryomesh::spacial::Degree::getValue () const"
.PP
Definition at line 23 of file Degree.cpp.
.SS "double cryomesh::spacial::Degree::toRadians () const"
.PP
Definition at line 26 of file Degree.cpp.
.SH "Member Data Documentation"
.PP 
.SS "double \fBcryomesh::spacial::Degree::value\fP\fC [private]\fP"
.PP
Definition at line 22 of file Degree.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
