cryomesh::manager::Creator
NAME
cryomesh::manager::Creator -
Class to take in a config file of ConfigTranslator form and parse the commands to create a full cryomesh object.
SYNOPSIS
#include <Creator.h>
Public Member Functions
Creator (const std::string &config_filename, const std::string &database_filename=DEFAULT_DATABASE_FILENAME)
Constructor to create a bundle from a config file name with option to specify the database file name that will be used.
Creator (std::istream &config_stream, const std::string &database_filename=DEFAULT_DATABASE_FILENAME)
virtual ~Creator ()
Deffault destructor.
const boost::shared_ptr
< structures::Bundle > getBundle () const "
Get the create bundle.
boost::shared_ptr
< structures::Bundle > getMutableBundle ()"
Get the mutable create bundle.
const std::map< int,
boost::uuids::uuid > & getClusterIDMap () const "
get the clusterIDMap
const std::map< int,
boost::uuids::uuid > & getFibreIDMap () const "
get the fibreIDMap
const std::map< int,
boost::uuids::uuid > & getPatternChannelIDMap () const "
get the patternChannelIDMap
void createCluster (int id, int size, int connectivity)
Translator from config command to actual command.
void connectCluster (int input_cluster_id, int ouput_cluster_id, int width)
Translator from config command to actual command.
void loadData (std::string datafile)
Translator from config command to actual command.
bool runCommand (const config::ConfigEntry &conf_entry)
void connectPrimaryInputChannel (int channel_id, int outputid)
Translator from config command to actual command.
void connectPrimaryOutputChannel (int channel_id, int inputid)
Translator from config command to actual command.
void autoConnectPrimaryInputs (const std::vector< int > &cluster_ids)
auto connect all the primary input channels to the list of clusters
void autoConnectPrimaryOutputs (const std::vector< int > &cluster_ids)
auto connect all the primary output channels to the list of clusters
Static Public Member Functions
static bool analyseConfig (const config::ConfigTranslator &conf_trans)
Analyse the config translator for coherence.
static bool checkConfigEntry (const config::ConfigEntry &conf_entry)
Analyse the config entry for coherence.
static bool checkConfigStructure (const std::list< config::ConfigEntry > &conf_entries)
Analyse the config for structural coherence.
static std::map< std::string,
std::list< std::string > > getAcceptedCommandList ()"
Generate and return the accepted command list.
Static Public Attributes
static const std::string DEFAULT_DATABASE_FILENAME = 'cryomesh_default.db'
static std::map< std::string,
std::list< std::string > > acceptedCommandList = Creator::getAcceptedCommandList()"
Protected Member Functions
void initialise ()
Helper to initialise the creator.
bool createFromConfigFile (const std::string config_filename)
Run through the config file generating all commands.
bool createFromConfigStream (std::istream &is)
Private Member Functions
boost::uuids::uuid getRealID (const int id, const std::map< int, boost::uuids::uuid > &idmap) const
Retreive a uuid from a fake int id inside a map.
boost::uuids::uuid getClusterRealID (const int id) const
Helper to retrieve a uuid from a fake int id for clusters.
boost::uuids::uuid getFibreRealID (const int id) const
Helper to retrieve a uuid from a fake int id for fibres.
boost::uuids::uuid getPatternChannelRealID (const int id) const
Helper to retrieve a uuid from a fake int id for pattern channels.
Private Attributes
std::string databaseFilename
boost::shared_ptr
< structures::Bundle > bundle"
std::map< int, boost::uuids::uuid > clusterIDMap
std::map< int, boost::uuids::uuid > fibreIDMap
std::map< int, boost::uuids::uuid > patternChannelIDMap
Detailed Description
Class to take in a config file of ConfigTranslator form and parse the commands to create a full cryomesh object.
needs to hold a fakeid to realid mapping to facillitate using fake ids in config files before the objects ids are actually known
holds a unique instance of any create cryomeshes
holds other data from the config file or defaults such as database name, filename, data filename, etc
Definition at line 31 of file Creator.h.
Constructor & Destructor Documentation
cryomesh::manager::Creator::Creator (const std::string &config_filename, const std::string &database_filename = DEFAULT_DATABASE_FILENAME)
Constructor to create a bundle from a config file name with option to specify the database file name that will be used. Parameters:
std::string The name with full path of the config file
std::string The name with full path of the database file
Definition at line 47 of file Creator.cpp.
References createFromConfigFile(), and initialise().
cryomesh::manager::Creator::Creator (std::istream &config_stream, const std::string &database_filename = DEFAULT_DATABASE_FILENAME)
Definition at line 61 of file Creator.cpp.
References createFromConfigStream(), and initialise().
cryomesh::manager::Creator::~Creator () [virtual]
Deffault destructor.
Definition at line 71 of file Creator.cpp.
Member Function Documentation
bool cryomesh::manager::Creator::analyseConfig (const config::ConfigTranslator &conf_trans) [static]
Analyse the config translator for coherence. Parameters:
ConfigTranslator The config translator to analyse
Returns:
bool True if the config translator passed all the tests for coherence, false otherwise.
Definition at line 195 of file Creator.cpp.
References checkConfigEntry(), and checkConfigStructure().
Referenced by createFromConfigStream().
void cryomesh::manager::Creator::autoConnectPrimaryInputs (const std::vector< int > &cluster_ids)
auto connect all the primary input channels to the list of clusters Parameters:
std::vector<int> The fake ids of the clusters to connect
Definition at line 356 of file Creator.cpp.
References bundle, and getClusterRealID().
Referenced by runCommand().
void cryomesh::manager::Creator::autoConnectPrimaryOutputs (const std::vector< int > &cluster_ids)
auto connect all the primary output channels to the list of clusters Parameters:
std::vector<int> The fake ids of the clusters to connect
Definition at line 374 of file Creator.cpp.
References bundle, and getClusterRealID().
Referenced by runCommand().
bool cryomesh::manager::Creator::checkConfigEntry (const config::ConfigEntry &conf_entry) [static]
Analyse the config entry for coherence. Parameters:
ConfigEntry The config entry to analyse
Returns:
bool True if the config entry passed all the tests for coherence, false otherwise.
Definition at line 215 of file Creator.cpp.
References acceptedCommandList.
Referenced by analyseConfig().
bool cryomesh::manager::Creator::checkConfigStructure (const std::list< config::ConfigEntry > &conf_entries) [static]
Analyse the config for structural coherence. Parameters:
std::list<config::ConfigEntry> The list of config entries to analyse for structure
Returns:
bool True if the config entries passed all the tests for structural coherence, false otherwise.
Definition at line 245 of file Creator.cpp.
Referenced by analyseConfig().
void cryomesh::manager::Creator::connectCluster (intinput_cluster_id, intouput_cluster_id, intwidth)
Translator from config command to actual command. Connect two clusters using there fake ids
Parameters:
int The fake id of the input cluster
int The fake id of the output cluster
int The width of the new fibre connection
Definition at line 284 of file Creator.cpp.
References bundle, and getClusterRealID().
Referenced by runCommand().
void cryomesh::manager::Creator::connectPrimaryInputChannel (intchannel_id, intoutputid)
Translator from config command to actual command. Create a fibre to connect a primary input pattern channel to a cluster output
Parameters:
int The fake id of the pattern channel
The fake id of the output cluster
Definition at line 342 of file Creator.cpp.
References bundle, getClusterRealID(), and getPatternChannelRealID().
Referenced by runCommand().
void cryomesh::manager::Creator::connectPrimaryOutputChannel (intchannel_id, intinputid)
Translator from config command to actual command. Create a fibre to connect a primary output pattern channel to a cluster output
Parameters:
int The fake id of the pattern channel
The fake id of the input cluster
Definition at line 349 of file Creator.cpp.
References bundle, getClusterRealID(), and getPatternChannelRealID().
Referenced by runCommand().
void cryomesh::manager::Creator::createCluster (intid, intsize, intconnectivity)
Translator from config command to actual command. Create a cluster using a fake id to map to a real one
Parameters:
int The fake id of the cluster
int The size of the cluster
int The connetivity of the cluster
Definition at line 280 of file Creator.cpp.
References bundle, and clusterIDMap.
Referenced by runCommand().
bool cryomesh::manager::Creator::createFromConfigFile (const std::stringconfig_filename) [protected]
Run through the config file generating all commands. Returns:
bool True if running the config file was successful, false otherwise
Definition at line 181 of file Creator.cpp.
References createFromConfigStream().
Referenced by Creator().
bool cryomesh::manager::Creator::createFromConfigStream (std::istream &is) [protected]
Definition at line 156 of file Creator.cpp.
References analyseConfig(), and runCommand().
Referenced by createFromConfigFile(), and Creator().
std::map< std::string, std::list< std::string > > cryomesh::manager::Creator::getAcceptedCommandList () [static]
Generate and return the accepted command list. Returns:
std::map<std::string, std::list<std::string> > The accepted commands mapping
Definition at line 22 of file Creator.cpp.
const boost::shared_ptr< structures::Bundle > cryomesh::manager::Creator::getBundle () const
Get the create bundle. Returns:
boost::shared_ptr<structures::Bundle> The created bundle
Definition at line 74 of file Creator.cpp.
References bundle.
const std::map< int, boost::uuids::uuid > & cryomesh::manager::Creator::getClusterIDMap () const
get the clusterIDMap Returns:
const std::map<int, boost::uuids::uuid> the clusterIDMap
Definition at line 82 of file Creator.cpp.
References clusterIDMap.
boost::uuids::uuid cryomesh::manager::Creator::getClusterRealID (const intid) const [private]
Helper to retrieve a uuid from a fake int id for clusters. Parameters:
int The fake id to translate
Returns:
boost::uuids::uuid The corresponding real uuid to the fake one, null if it doesnt exist
Definition at line 419 of file Creator.cpp.
References clusterIDMap, and getRealID().
Referenced by autoConnectPrimaryInputs(), autoConnectPrimaryOutputs(), connectCluster(), connectPrimaryInputChannel(), and connectPrimaryOutputChannel().
const std::map< int, boost::uuids::uuid > & cryomesh::manager::Creator::getFibreIDMap () const
get the fibreIDMap Returns:
const std::map<int, boost::uuids::uuid> the fibreIDMap
Definition at line 86 of file Creator.cpp.
References fibreIDMap.
boost::uuids::uuid cryomesh::manager::Creator::getFibreRealID (const intid) const [private]
Helper to retrieve a uuid from a fake int id for fibres. Parameters:
int The fake id to translate
Returns:
boost::uuids::uuid The corresponding real uuid to the fake one, null if it doesnt exist
Definition at line 426 of file Creator.cpp.
References fibreIDMap, and getRealID().
boost::shared_ptr< structures::Bundle > cryomesh::manager::Creator::getMutableBundle ()
Get the mutable create bundle. Returns:
boost::shared_ptr<structures::Bundle> The created bundle
Definition at line 78 of file Creator.cpp.
References bundle.
const std::map< int, boost::uuids::uuid > & cryomesh::manager::Creator::getPatternChannelIDMap () const
get the patternChannelIDMap Returns:
const std::map<int, boost::uuids::uuid> the patternChannelIDMap
Definition at line 90 of file Creator.cpp.
References patternChannelIDMap.
boost::uuids::uuid cryomesh::manager::Creator::getPatternChannelRealID (const intid) const [private]
Helper to retrieve a uuid from a fake int id for pattern channels. Parameters:
int The fake id to translate
Returns:
boost::uuids::uuid The corresponding real uuid to the fake one, null if it doesnt exist
Definition at line 433 of file Creator.cpp.
References getRealID(), and patternChannelIDMap.
Referenced by connectPrimaryInputChannel(), and connectPrimaryOutputChannel().
boost::uuids::uuid cryomesh::manager::Creator::getRealID (const intid, const std::map< int, boost::uuids::uuid > &idmap) const [private]
Retreive a uuid from a fake int id inside a map. Parameters:
int The fake id to translate
std::map<int,boost::uuids::uuid> The map to use for translation
Returns:
boost::uuids::uuid The corresponding real uuid to the fake one, null if it doesnt exist
Definition at line 392 of file Creator.cpp.
Referenced by getClusterRealID(), getFibreRealID(), and getPatternChannelRealID().
void cryomesh::manager::Creator::initialise () [protected]
Helper to initialise the creator.
Definition at line 94 of file Creator.cpp.
References bundle.
Referenced by Creator().
void cryomesh::manager::Creator::loadData (std::stringdatafile)
Translator from config command to actual command. Load the pattern data in from a file
Parameters:
std::string The full file path name of the pattern data file
Definition at line 315 of file Creator.cpp.
References bundle, and patternChannelIDMap.
Referenced by runCommand().
bool cryomesh::manager::Creator::runCommand (const config::ConfigEntry &conf_entry)
Definition at line 98 of file Creator.cpp.
References autoConnectPrimaryInputs(), autoConnectPrimaryOutputs(), connectCluster(), connectPrimaryInputChannel(), connectPrimaryOutputChannel(), createCluster(), and loadData().
Referenced by createFromConfigStream().
Member Data Documentation
std::map< std::string, std::list< std::string > > cryomesh::manager::Creator::acceptedCommandList = Creator::getAcceptedCommandList() [static]
Definition at line 212 of file Creator.h.
Referenced by checkConfigEntry().
boost::shared_ptr<structures::Bundle> cryomesh::manager::Creator::bundle [private]
Definition at line 266 of file Creator.h.
Referenced by autoConnectPrimaryInputs(), autoConnectPrimaryOutputs(), connectCluster(), connectPrimaryInputChannel(), connectPrimaryOutputChannel(), createCluster(), getBundle(), getMutableBundle(), initialise(), and loadData().
std::map<int, boost::uuids::uuid> cryomesh::manager::Creator::clusterIDMap [private]
Definition at line 273 of file Creator.h.
Referenced by createCluster(), getClusterIDMap(), and getClusterRealID().
std::string cryomesh::manager::Creator::databaseFilename [private]
Definition at line 259 of file Creator.h.
const std::string cryomesh::manager::Creator::DEFAULT_DATABASE_FILENAME = 'cryomesh_default.db' [static]
Definition at line 205 of file Creator.h.
std::map<int, boost::uuids::uuid> cryomesh::manager::Creator::fibreIDMap [private]
Definition at line 280 of file Creator.h.
Referenced by getFibreIDMap(), and getFibreRealID().
std::map<int, boost::uuids::uuid> cryomesh::manager::Creator::patternChannelIDMap [private]
Definition at line 287 of file Creator.h.
Referenced by getPatternChannelIDMap(), getPatternChannelRealID(), and loadData().
Author
Generated automatically by Doxygen for cryomesh from the source code.