cryomesh::components::Node
NAME
cryomesh::components::Node -
Node is an accumulation and computational nodal point of impulses.
SYNOPSIS
#include <Node.h>
Inherits cryomesh::dataobjects::DataObjectController< unsigned long int, double >.
Public Types
enum ActivationState { Positive, Negative, None }
Enum representing posible activation states.
enum RecoverySetting { CLEAR_ALL_IMPULSES = 1, CLEAR_ACTIVE_IMPULSES = 2, DEACTIVATE_DURING_RECOVERY = 4 }
Public Member Functions
Node ()
Contructor.
virtual ~Node ()
Destructor.
virtual void update ()
virtual void forceFire ()
Force the node to fire.
virtual boost::shared_ptr
< Impulse > addImpulse (boost::shared_ptr< Impulse > impulse)"
Add incoming Impulse.
virtual void addImpulses (std::list< boost::shared_ptr< Impulse > > impulses)
Add a list of incoming Impulses.
const common::Connector< Node,
Connection > & getConnector () const "
Get the Connector object for this Node.
common::Connector< Node,
Connection > & getMutableConnector ()"
Get the mutable Connector object for this Node.
bool isInputIsolated () const
bool isOutputIsolated () const
void connectInput (boost::shared_ptr< Connection > con)
void connectOutput (boost::shared_ptr< Connection > con)
const ImpulseCollection & getImpulses () const
Get the collection of Impulses for this Node.
const boost::shared_ptr< Impulse > getEmittedImpulse () const
Get the Impulse that is emitted.
boost::shared_ptr< Impulse > getMutableEmittedImpulse ()
Get the mutable Impulse that is emitted.
virtual void emitImpulsePositive ()
Emit a positive impulse to outgoing connections.
virtual void emitImpulseNegative ()
Emit a negative impulse to outgoing connections.
ImpulseCollection & getMutableImpulses ()
Get the mutable collection of Impulses for this Node.
const std::map< common::Cycle,
double > & getActivities () const "
Get the collection of all activities.
double updateActivity ()
Update and get the current activity of the node.
double updateActivity (const common::Cycle &cycle)
Update and get the activity of the node on specific cycle.
double getActivity () const
Get the current activity of the node.
double getActivity (const common::Cycle &cycle) const
Get the activity of the node on specific cycle.
double getActivityThreshold () const
double setActivity (double activity)
Set the current activity of the node.
double setActivity (const common::Cycle &cycle, double activity)
Set the activity at cycle of the node.
boost::shared_ptr
< manager::DatabaseObject > getDatabaseObject () const "
Return a database object for this node.
const spacial::Point & getPosition () const
get the position of the node
void setPosition (const spacial::Point &new_position)
Set the spacial position of the node, remembering to update connections lengths.
ActivationState getLastActivationState () const
Get the last activation state.
void randomise ()
Randomise the nodes state.
virtual void enableDebug (bool b)
bool isTriggered (ActivationState state=None)
Check if Node is currently triggered.
bool isActive (const ActivationState state=None)
Check if Node is currently activated.
bool isLive ()
Check if Node is live, ie active at any point in now or the future.
void destroyAllConnections ()
Destroy all connections.
void destroyAllInputConnections ()
Destroy Input connections by removing them all from both their attached input and output nodes.
void destroyAllOutputConnections ()
Destroy Output connections by removing them all from both their attached input and output nodes.
bool isPrimaryInputAttachedNode () const
bool isPrimaryOutputAttachedNode () const
std::vector< boost::shared_ptr
< Connection > > getPrimaryInputConnections ()"
std::vector< boost::shared_ptr
< Connection > > getPrimaryOutputConnections ()"
std::ostream & printConnections (std::ostream &os, const std::map< boost::uuids::uuid, boost::shared_ptr< Connection > > &all_cons, const std::string formatter='') const
virtual void enableLogging (bool enable)
Whether logging is enabled or not.
virtual const std::map
< unsigned long int, double > & getMap ()"
Get all cycle values.
virtual const
dataobjects::DataObject
< unsigned long int, double > & getDataObject ()"
Get data object.
virtual void refreshDataObject ()
Function to allow refreshing implementation if required by subclasses.
Static Public Member Functions
static boost::shared_ptr< Node > getRandom (const spacial::Point &max_point=MAX_BOUNDING_BOX_POINT)
Static Public Attributes
static const int MAX_ACTIVITIES_LENGTH = 10
static const double MAX_ACTIVITY_THRESHOLD = 3 * Impulse::MAX_ACTIVITY
static const double MIN_ACTIVITY_THRESHOLD = 1 * Impulse::MAX_ACTIVITY
static const spacial::Point MAX_BOUNDING_BOX_POINT = spacial::Point(100, 100, 100)
Protected Member Functions
virtual Node::ActivationState checkActivationState ()
Check level of impulses and decide whether to activate the node.
virtual Node::ActivationState checkFire ()
Check if the object is ready to fire off an impulse and carry it out.
virtual void updateImpulses ()
Update the collection of impulses by one cycle.
virtual void emitImpulse (bool positive)
Emit an impulse to outgoing connections.
virtual double addActivity (common::Cycle, double activity)
Add an activity to the list of activities.
virtual void updatePosition ()
Recalculate state of node and connections based on current position.
virtual void enterRecovery (const int recovery_settings=CLEAR_ALL_IMPULSES)
Protected Attributes
dataobjects::DataObject
< unsigned long int, double > dataObject"
Private Attributes
double activityThreshold
boost::shared_ptr
< common::Connector< Node,
Connection > > connector"
ImpulseCollection impulses
boost::shared_ptr< Impulse > emittedImpulse
dataobjects::DataObject
< common::Cycle, double > activities"
spacial::Point position
ActivationState lastActivationState
Friends
std::ostream & operator<< (std::ostream &os, const Node &obj)
To stream operator.
Detailed Description
Node is an accumulation and computational nodal point of impulses.
A Node represents the end point of one or many connections. Here, Impulses are accumulated and new Impulses generated depending on some determining criteria
Definition at line 38 of file Node.h.
Member Enumeration Documentation
enum cryomesh::components::Node::ActivationState
Enum representing posible activation states. Last activation state.
Enumerator:
Positive
Negative
None
Definition at line 45 of file Node.h.
enum cryomesh::components::Node::RecoverySetting
Enumerator:
CLEAR_ALL_IMPULSES
CLEAR_ACTIVE_IMPULSES
DEACTIVATE_DURING_RECOVERY
Definition at line 49 of file Node.h.
Constructor & Destructor Documentation
cryomesh::components::Node::Node ()
Contructor. Contructor for Node
Definition at line 37 of file Node.cpp.
References activities, connector, emittedImpulse, MAX_ACTIVITIES_LENGTH, and cryomesh::dataobjects::DataObject< U, T >::setDatasetMaximumSize().
cryomesh::components::Node::~Node () [virtual]
Destructor. Destructor for Node
Definition at line 46 of file Node.cpp.
Member Function Documentation
double cryomesh::components::Node::addActivity (common::Cyclecycle, doubleactivity) [protected, virtual]
Add an activity to the list of activities. Parameters:
Cycle cycle The cycle this activity is on
double activity The activity to add
Returns:
The current activity
Definition at line 291 of file Node.cpp.
References activities, and cryomesh::dataobjects::DataObject< U, T >::insert().
Referenced by setActivity().
boost::shared_ptr< Impulse > cryomesh::components::Node::addImpulse (boost::shared_ptr< Impulse >impulse) [virtual]
Add incoming Impulse. Parameters:
boost::shared_ptr<Impulse> impulse The Impulse to add
Returns:
boost::shared_ptr<Impulse> The impulse added, null if none added
Definition at line 141 of file Node.cpp.
References getMutableImpulses(), and cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by addImpulses(), and forceFire().
void cryomesh::components::Node::addImpulses (std::list< boost::shared_ptr< Impulse > >impulses) [virtual]
Add a list of incoming Impulses. Parameters:
std::list<boost::shared_ptr<Impulse> > impulses The Impulses to add
Definition at line 151 of file Node.cpp.
References addImpulse(), getImpulses(), and impulses.
Node::ActivationState cryomesh::components::Node::checkActivationState () [protected, virtual]
Check level of impulses and decide whether to activate the node. Returns:
Node::ActivationState Positive if activity is over threshold, negative if under -threshold, None otherwise
Definition at line 173 of file Node.cpp.
References getActivityThreshold(), Negative, None, Positive, and updateActivity().
Referenced by checkFire().
Node::ActivationState cryomesh::components::Node::checkFire () [protected, virtual]
Check if the object is ready to fire off an impulse and carry it out. Returns:
ActivationState Return the action that was taken
Definition at line 92 of file Node.cpp.
References checkActivationState(), emitImpulseNegative(), emitImpulsePositive(), enterRecovery(), Negative, and Positive.
Referenced by update().
void cryomesh::components::Node::connectInput (boost::shared_ptr< Connection >con)
Definition at line 469 of file Node.cpp.
References getMutableConnector().
void cryomesh::components::Node::connectOutput (boost::shared_ptr< Connection >con)
Definition at line 472 of file Node.cpp.
References getMutableConnector().
void cryomesh::components::Node::destroyAllConnections ()
Destroy all connections.
Definition at line 476 of file Node.cpp.
References destroyAllInputConnections(), and destroyAllOutputConnections().
void cryomesh::components::Node::destroyAllInputConnections ()
Destroy Input connections by removing them all from both their attached input and output nodes.
Definition at line 481 of file Node.cpp.
References getMutableConnector().
Referenced by destroyAllConnections().
void cryomesh::components::Node::destroyAllOutputConnections ()
Destroy Output connections by removing them all from both their attached input and output nodes.
Definition at line 498 of file Node.cpp.
References getMutableConnector().
Referenced by destroyAllConnections().
void cryomesh::components::Node::emitImpulse (boolpositive) [protected, virtual]
Emit an impulse to outgoing connections. Parameters:
bool positive Is the impulse to be emitted positive or negative
Definition at line 199 of file Node.cpp.
References cryomesh::components::Connection::add(), getEmittedImpulse(), cryomesh::components::Connection::getImpulses(), getMutableConnector(), and getMutableEmittedImpulse().
Referenced by emitImpulseNegative(), and emitImpulsePositive().
void cryomesh::components::Node::emitImpulseNegative () [virtual]
Emit a negative impulse to outgoing connections.
Definition at line 195 of file Node.cpp.
References emitImpulse().
Referenced by checkFire().
void cryomesh::components::Node::emitImpulsePositive () [virtual]
Emit a positive impulse to outgoing connections.
Definition at line 191 of file Node.cpp.
References emitImpulse().
Referenced by checkFire().
void cryomesh::components::Node::enableDebug (boolb) [virtual]
Definition at line 545 of file Node.cpp.
virtual void cryomesh::dataobjects::DataObjectController< unsigned long int , double >::enableLogging (boolenable) [inline, virtual, inherited]
Whether logging is enabled or not. Parameters:
bool enable True to enable logging, false otherwise
Definition at line 47 of file DataObjectController.h.
References cryomesh::dataobjects::DataObjectController< U, T >::dataObject.
void cryomesh::components::Node::enterRecovery (const intrecovery_settings = CLEAR_ALL_IMPULSES) [protected, virtual]
Definition at line 115 of file Node.cpp.
References CLEAR_ACTIVE_IMPULSES, CLEAR_ALL_IMPULSES, cryomesh::components::ImpulseCollection::clearActiveImpulses(), cryomesh::common::TimeKeeper::getTimeKeeper(), and impulses.
Referenced by checkFire().
void cryomesh::components::Node::forceFire () [virtual]
Force the node to fire.
Definition at line 80 of file Node.cpp.
References addImpulse(), and cryomesh::components::Impulse::getTriggerImpulse().
const std::map< common::Cycle, double > & cryomesh::components::Node::getActivities () const
Get the collection of all activities. Returns:
std::list<double> & List of activities
Definition at line 259 of file Node.cpp.
References activities, and cryomesh::dataobjects::DataObject< U, T >::getMap().
Referenced by update().
double cryomesh::components::Node::getActivity () const
Get the current activity of the node. Returns:
double The current activity
Definition at line 263 of file Node.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by getDatabaseObject(), isActive(), cryomesh::structures::Mesh::update(), updateActivity(), and cryomesh::structures::Mesh::warp().
double cryomesh::components::Node::getActivity (const common::Cycle &cycle) const
Get the activity of the node on specific cycle. Returns:
double The current activity
Definition at line 267 of file Node.cpp.
References cryomesh::components::ImpulseCollection::getActivity(), and getImpulses().
double cryomesh::components::Node::getActivityThreshold () const
Definition at line 271 of file Node.cpp.
References activityThreshold.
Referenced by checkActivationState(), and cryomesh::components::operator<<().
const common::Connector< Node, Connection > & cryomesh::components::Node::getConnector () const
Get the Connector object for this Node. Returns:
const common::Connector<Node, Connection> & The Connector for this object
Definition at line 84 of file Node.cpp.
References connector.
Referenced by getPrimaryInputConnections(), getPrimaryOutputConnections(), isInputIsolated(), isOutputIsolated(), isPrimaryInputAttachedNode(), isPrimaryOutputAttachedNode(), and cryomesh::components::operator<<().
boost::shared_ptr< manager::DatabaseObject > cryomesh::components::Node::getDatabaseObject () const
Return a database object for this node. Returns:
DatabaseObject
Definition at line 296 of file Node.cpp.
References getActivity(), cryomesh::common::TimeKeeper::getCycle(), getPosition(), cryomesh::common::TimeKeeper::getTimeKeeper(), and cryomesh::common::Cycle::toULInt().
virtual const dataobjects::DataObject<unsigned long int , double >& cryomesh::dataobjects::DataObjectController< unsigned long int , double >::getDataObject () [inline, virtual, inherited]
Get data object. Returns:
dataobjects::DataObject<U,T> & The data object
Definition at line 68 of file DataObjectController.h.
References cryomesh::dataobjects::DataObjectController< U, T >::dataObject, and cryomesh::dataobjects::DataObjectController< U, T >::refreshDataObject().
const boost::shared_ptr< Impulse > cryomesh::components::Node::getEmittedImpulse () const
Get the Impulse that is emitted. Returns:
const boost::shared_ptr< Impulse > The emitted Impulse
Definition at line 247 of file Node.cpp.
References emittedImpulse.
Referenced by emitImpulse().
const ImpulseCollection & cryomesh::components::Node::getImpulses () const
Get the collection of Impulses for this Node. Returns:
const ImpulseCollection & The collection of Impulses for this Node
Definition at line 243 of file Node.cpp.
References impulses.
Referenced by addImpulses(), getActivity(), isLive(), cryomesh::components::operator<<(), and updateActivity().
Node::ActivationState cryomesh::components::Node::getLastActivationState () const
Get the last activation state. Returns:
ActivationState Return the last activation state
Definition at line 314 of file Node.cpp.
References lastActivationState.
Referenced by isTriggered().
virtual const std::map<unsigned long int , double >& cryomesh::dataobjects::DataObjectController< unsigned long int , double >::getMap () [inline, virtual, inherited]
Get all cycle values. Returns:
std::map<unsigned long int, double> & The cycle values
Definition at line 57 of file DataObjectController.h.
References cryomesh::dataobjects::DataObjectController< U, T >::dataObject, and cryomesh::dataobjects::DataObjectController< U, T >::refreshDataObject().
common::Connector< Node, Connection > & cryomesh::components::Node::getMutableConnector ()
Get the mutable Connector object for this Node. Returns:
common::Connector<Node, Connection> & The mutable Connector for this object
Definition at line 88 of file Node.cpp.
References connector.
Referenced by connectInput(), connectOutput(), destroyAllInputConnections(), destroyAllOutputConnections(), and emitImpulse().
boost::shared_ptr< Impulse > cryomesh::components::Node::getMutableEmittedImpulse ()
Get the mutable Impulse that is emitted. Returns:
boost::shared_ptr< Impulse > The mutable emitted Impulse
Definition at line 251 of file Node.cpp.
References emittedImpulse.
Referenced by emitImpulse().
ImpulseCollection & cryomesh::components::Node::getMutableImpulses ()
Get the mutable collection of Impulses for this Node. Returns:
ImpulseCollection & The mutable collection of Impulses for this Node
Definition at line 255 of file Node.cpp.
References impulses.
Referenced by addImpulse(), and update().
const spacial::Point & cryomesh::components::Node::getPosition () const
get the position of the node Returns:
spacial::Point The spacial location of the node
Definition at line 305 of file Node.cpp.
References position.
Referenced by getDatabaseObject(), cryomesh::structures::Mesh::update(), and cryomesh::structures::Mesh::warp().
std::vector< boost::shared_ptr< Connection > > cryomesh::components::Node::getPrimaryInputConnections ()
Definition at line 425 of file Node.cpp.
References getConnector().
std::vector< boost::shared_ptr< Connection > > cryomesh::components::Node::getPrimaryOutputConnections ()
Definition at line 447 of file Node.cpp.
References getConnector().
boost::shared_ptr< Node > cryomesh::components::Node::getRandom (const spacial::Point &max_point = MAX_BOUNDING_BOX_POINT) [static]
Definition at line 26 of file Node.cpp.
Referenced by cryomesh::manipulators::ClusterArchitect::createRandomNodes(), and randomise().
bool cryomesh::components::Node::isActive (const ActivationStatestate = None)
Check if Node is currently activated. Parameters:
ActivationState Positive for positive activity test, Negative for negative activity test, None for any activity test
Returns:
bool True if activated, false otherwise
Definition at line 333 of file Node.cpp.
References getActivity(), Negative, None, and Positive.
bool cryomesh::components::Node::isInputIsolated () const
Definition at line 361 of file Node.cpp.
References getConnector().
Referenced by isPrimaryInputAttachedNode().
bool cryomesh::components::Node::isLive ()
Check if Node is live, ie active at any point in now or the future. Returns:
bool True if live, false otherwise
Definition at line 352 of file Node.cpp.
References getImpulses().
bool cryomesh::components::Node::isOutputIsolated () const
Definition at line 368 of file Node.cpp.
References getConnector().
Referenced by isPrimaryOutputAttachedNode().
bool cryomesh::components::Node::isPrimaryInputAttachedNode () const
Definition at line 375 of file Node.cpp.
References getConnector(), and isInputIsolated().
Referenced by cryomesh::components::operator<<().
bool cryomesh::components::Node::isPrimaryOutputAttachedNode () const
Definition at line 400 of file Node.cpp.
References getConnector(), and isOutputIsolated().
Referenced by cryomesh::components::operator<<().
bool cryomesh::components::Node::isTriggered (ActivationStatestate = None)
Check if Node is currently triggered. Parameters:
ActivationState Positive for positive trigger test, Negative for negative trigger test, None for any trigger test
Returns:
bool True if triggered, false otherwise
Definition at line 323 of file Node.cpp.
References getLastActivationState(), and None.
std::ostream & cryomesh::components::Node::printConnections (std::ostream &os, const std::map< boost::uuids::uuid, boost::shared_ptr< Connection > > &all_cons, const std::stringformatter = '') const
Definition at line 577 of file Node.cpp.
Referenced by cryomesh::components::operator<<().
void cryomesh::components::Node::randomise ()
Randomise the nodes state.
Definition at line 318 of file Node.cpp.
References activityThreshold, emittedImpulse, getRandom(), MAX_ACTIVITY_THRESHOLD, and MIN_ACTIVITY_THRESHOLD.
virtual void cryomesh::dataobjects::DataObjectController< unsigned long int , double >::refreshDataObject () [inline, virtual, inherited]
Function to allow refreshing implementation if required by subclasses.
Reimplemented in cryomesh::components::ImpulseCollection.
Definition at line 76 of file DataObjectController.h.
double cryomesh::components::Node::setActivity (doubleactivity)
Set the current activity of the node. Parameters:
double The current activity value to be set
Returns:
double The activity set
Definition at line 283 of file Node.cpp.
References cryomesh::common::TimeKeeper::getTimeKeeper().
Referenced by updateActivity(), and cryomesh::structures::Mesh::warp().
double cryomesh::components::Node::setActivity (const common::Cycle &cycle, doubleactivity)
Set the activity at cycle of the node. Parameters:
const Cycle & cycle The cycle the activty is on
double The current activity value to be set
Returns:
double The activity set
Definition at line 287 of file Node.cpp.
References addActivity().
void cryomesh::components::Node::setPosition (const spacial::Point &new_position)
Set the spacial position of the node, remembering to update connections lengths. Parameters:
spacial::Point The position to place this node at
Definition at line 309 of file Node.cpp.
References position, and updatePosition().
void cryomesh::components::Node::update () [virtual]
Definition at line 49 of file Node.cpp.
References checkFire(), cryomesh::components::ImpulseCollection::clearActiveImpulses(), cryomesh::dataobjects::DataObjectController< unsigned long int, double >::dataObject, getActivities(), getMutableImpulses(), cryomesh::dataobjects::DataObject< U, T >::insert(), cryomesh::dataobjects::DataObject< U, T >::isLoggingEnabled(), lastActivationState, and updateImpulses().
double cryomesh::components::Node::updateActivity ()
Update and get the current activity of the node. Returns:
double The current activity
Definition at line 275 of file Node.cpp.
References getActivity(), getImpulses(), and setActivity().
Referenced by checkActivationState().
double cryomesh::components::Node::updateActivity (const common::Cycle &cycle)
Update and get the activity of the node on specific cycle. Returns:
double The current activity
Definition at line 279 of file Node.cpp.
References getActivity(), getImpulses(), and setActivity().
void cryomesh::components::Node::updateImpulses () [protected, virtual]
Update the collection of impulses by one cycle.
Definition at line 135 of file Node.cpp.
References cryomesh::components::ImpulseCollection::clearImpulses(), and impulses.
Referenced by update().
void cryomesh::components::Node::updatePosition () [protected, virtual]
Recalculate state of node and connections based on current position.
Definition at line 515 of file Node.cpp.
References connector.
Referenced by setPosition().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream &os, const Node &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Node & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 548 of file Node.cpp.
Member Data Documentation
dataobjects::DataObject<common::Cycle, double> cryomesh::components::Node::activities [private]
Definition at line 461 of file Node.h.
Referenced by addActivity(), getActivities(), and Node().
double cryomesh::components::Node::activityThreshold [private]
Definition at line 433 of file Node.h.
Referenced by getActivityThreshold(), and randomise().
boost::shared_ptr<common::Connector<Node, Connection> > cryomesh::components::Node::connector [private]
Definition at line 440 of file Node.h.
Referenced by getConnector(), getMutableConnector(), Node(), and updatePosition().
dataobjects::DataObject<unsigned long int , double > cryomesh::dataobjects::DataObjectController< unsigned long int , double >::dataObject [protected, inherited]
Definition at line 85 of file DataObjectController.h.
Referenced by cryomesh::components::ImpulseCollection::refreshDataObject(), and update().
boost::shared_ptr<Impulse> cryomesh::components::Node::emittedImpulse [private]
Definition at line 454 of file Node.h.
Referenced by getEmittedImpulse(), getMutableEmittedImpulse(), Node(), and randomise().
ImpulseCollection cryomesh::components::Node::impulses [private]
Definition at line 447 of file Node.h.
Referenced by addImpulses(), enterRecovery(), getImpulses(), getMutableImpulses(), and updateImpulses().
ActivationState cryomesh::components::Node::lastActivationState [private]
Definition at line 475 of file Node.h.
Referenced by getLastActivationState(), and update().
const int cryomesh::components::Node::MAX_ACTIVITIES_LENGTH = 10 [static]
Definition at line 341 of file Node.h.
Referenced by Node().
const double cryomesh::components::Node::MAX_ACTIVITY_THRESHOLD = 3 * Impulse::MAX_ACTIVITY [static]
Definition at line 348 of file Node.h.
Referenced by randomise().
const spacial::Point cryomesh::components::Node::MAX_BOUNDING_BOX_POINT = spacial::Point(100, 100, 100) [static]
Definition at line 362 of file Node.h.
const double cryomesh::components::Node::MIN_ACTIVITY_THRESHOLD = 1 * Impulse::MAX_ACTIVITY [static]
Definition at line 355 of file Node.h.
Referenced by randomise().
spacial::Point cryomesh::components::Node::position [private]
Definition at line 468 of file Node.h.
Referenced by getPosition(), and setPosition().
Author
Generated automatically by Doxygen for cryomesh from the source code.