cryomesh::common::SimpleCollection
NAME
cryomesh::common::SimpleCollection -
SimpleCollection of objects with accessors.
SYNOPSIS
#include <SimpleCollection.h>
Inherits ICollection< SimpleCollection< T > >.
Public Member Functions
SimpleCollection ()
Default constructor.
SimpleCollection (const std::initializer_list< T > &list)
Construct from initializer list.
SimpleCollection (const std::list< T > &list)
Construct by list.
virtual ~SimpleCollection ()
Default destructor.
virtual void clear ()
Clear all objects from collection.
virtual void add (T obj)
Add object to collection.
virtual void add (const std::initializer_list< T > &list)
Add object to collection by initialiser list.
virtual void add (const std::list< T > &list)
Add object to collection by list.
virtual void remove (T obj)
Remove object from collection.
virtual void remove (const std::initializer_list< T > &list)
Remove objects from collection by initialiser list.
virtual void remove (const std::list< T > &list)
Remove objects from collection by list.
virtual T getSum () const
virtual T getMaximum () const
virtual T getMinimum () const
virtual T operator[] (unsigned index) const throw (exceptions::IndexOutOfBoundsException)
Get value at index.
virtual SimpleCollection & invert ()
Invert collection.
virtual SimpleCollection< T > & reverse ()
Reverse collection.
virtual const std::list< T > & getCollection () const
Get underlying collection.
virtual std::list< T > & getMutableCollection ()
Get mutable underlying collection.
virtual int getSize () const
Get underlying collections size.
virtual const SimpleCollection< T > operator+ (const SimpleCollection< T > &obj) const
Non-destructive addition operator.
virtual SimpleCollection< T > & operator+= (const SimpleCollection< T > &obj)
Destructive addition and assignment operator.
virtual SimpleCollection< T > & operator= (const SimpleCollection< T > &obj)
Assignment operator.
virtual bool operator== (const SimpleCollection< T > &obj) const
Comparator operator.
bool operator!= (const SimpleCollection &obj) const
Not comparator operator.
std::list< T > & pad (int front_pad, int back_pad, T pad_value)
Pad Collection.
Protected Member Functions
T getBoundaryValue (bool greater) const
void generateCurve (const double max_y, const unsigned long length)
Generate a curve from boundary value.
Private Attributes
std::list< T > objects
Friends
std::ostream & operator<< (std::ostream &out, const SimpleCollection &obj)
To stream operator.
Detailed Description
template<class T> class cryomesh::common::SimpleCollection< T >
SimpleCollection of objects with accessors.
Definition at line 28 of file SimpleCollection.h.
Constructor & Destructor Documentation
template<class T> cryomesh::common::SimpleCollection< T >::SimpleCollection () [inline]
Default constructor.
Definition at line 34 of file SimpleCollection.h.
template<class T> cryomesh::common::SimpleCollection< T >::SimpleCollection (const std::initializer_list< T > &list) [inline]
Construct from initializer list. Parameters:
std::initialiser_list<T> obj The values to be added to the collection
Definition at line 43 of file SimpleCollection.h.
template<class T> cryomesh::common::SimpleCollection< T >::SimpleCollection (const std::list< T > &list) [inline]
Construct by list. Parameters:
std::list<T> list The list values to be added to the collection
Definition at line 53 of file SimpleCollection.h.
template<class T> virtual cryomesh::common::SimpleCollection< T >::~SimpleCollection () [inline, virtual]
Default destructor.
Definition at line 60 of file SimpleCollection.h.
Member Function Documentation
template<class T> virtual void cryomesh::common::SimpleCollection< T >::add (Tobj) [inline, virtual]
Add object to collection. Parameters:
T obj The value to be added to the collection
Returns:
T The value added to the collection
Definition at line 80 of file SimpleCollection.h.
Referenced by cryomesh::common::SimpleCollection< double >::add(), and cryomesh::common::SimpleCollection< double >::SimpleCollection().
template<class T> virtual void cryomesh::common::SimpleCollection< T >::add (const std::list< T > &list) [inline, virtual]
Add object to collection by list. Parameters:
std::list<T> list The list values to be added to the collection
Definition at line 108 of file SimpleCollection.h.
template<class T> virtual void cryomesh::common::SimpleCollection< T >::add (const std::initializer_list< T > &list) [inline, virtual]
Add object to collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be added to the collection
Definition at line 90 of file SimpleCollection.h.
template<class T> virtual void cryomesh::common::SimpleCollection< T >::clear () [inline, virtual]
Clear all objects from collection.
Definition at line 66 of file SimpleCollection.h.
Referenced by cryomesh::components::Impulse::operator=().
template<class T> void cryomesh::common::SimpleCollection< T >::generateCurve (const doublemax_y, const unsigned longlength) [inline, protected]
Generate a curve from boundary value. Parameters:
const int max_y Boundary value of curve
const int length Length of Impulse
Definition at line 537 of file SimpleCollection.h.
template<class T> T cryomesh::common::SimpleCollection< T >::getBoundaryValue (boolgreater) const [inline, protected]
Definition at line 500 of file SimpleCollection.h.
Referenced by cryomesh::common::SimpleCollection< double >::getMaximum(), and cryomesh::common::SimpleCollection< double >::getMinimum().
template<class T> virtual const std::list<T>& cryomesh::common::SimpleCollection< T >::getCollection () const [inline, virtual]
Get underlying collection. Returns:
const std::list<T> & The collection
Definition at line 298 of file SimpleCollection.h.
Referenced by cryomesh::components::Impulse::operator+=(), cryomesh::common::SimpleCollection< double >::operator+=(), cryomesh::components::operator<<(), cryomesh::components::Impulse::operator=(), cryomesh::common::SimpleCollection< double >::operator=(), cryomesh::components::Impulse::operator==(), and cryomesh::common::SimpleCollection< double >::operator==().
template<class T> virtual T cryomesh::common::SimpleCollection< T >::getMaximum () const [inline, virtual]
Definition at line 205 of file SimpleCollection.h.
template<class T> virtual T cryomesh::common::SimpleCollection< T >::getMinimum () const [inline, virtual]
Definition at line 215 of file SimpleCollection.h.
template<class T> virtual std::list<T>& cryomesh::common::SimpleCollection< T >::getMutableCollection () [inline, virtual]
Get mutable underlying collection. Returns:
std::list<T> & The mutable collection
Definition at line 308 of file SimpleCollection.h.
Referenced by cryomesh::common::SimpleCollection< double >::operator+=().
template<class T> virtual int cryomesh::common::SimpleCollection< T >::getSize () const [inline, virtual]
Get underlying collections size. Returns:
int The collections size
Definition at line 318 of file SimpleCollection.h.
Referenced by cryomesh::common::SimpleCollection< double >::operator[]().
template<class T> virtual T cryomesh::common::SimpleCollection< T >::getSum () const [inline, virtual]
Definition at line 185 of file SimpleCollection.h.
template<class T> virtual SimpleCollection& cryomesh::common::SimpleCollection< T >::invert () [inline, virtual]
Invert collection. Reflect the collection in the x axis
Returns:
SimpleCollection & The inverted object
Reimplemented in cryomesh::components::Impulse.
Definition at line 264 of file SimpleCollection.h.
Referenced by cryomesh::components::Impulse::invert().
template<class T> bool cryomesh::common::SimpleCollection< T >::operator!= (const SimpleCollection< T > &obj) const [inline, virtual]
Not comparator operator. Parameters:
const SimpleCollection & obj RHS object
Returns:
bool True if not equal, false otherwise
Implements cryomesh::common::ICollection< SimpleCollection< T > >.
Definition at line 432 of file SimpleCollection.h.
template<class T> virtual const SimpleCollection<T> cryomesh::common::SimpleCollection< T >::operator+ (const SimpleCollection< T > &obj) const [inline, virtual]
Non-destructive addition operator. Parameters:
const SimpleCollection<T> & obj RHS addition
Returns:
SimpleCollection<T> New object after addition
Implements cryomesh::common::ICollection< SimpleCollection< T > >.
Definition at line 331 of file SimpleCollection.h.
template<class T> virtual SimpleCollection<T>& cryomesh::common::SimpleCollection< T >::operator+= (const SimpleCollection< T > &obj) [inline, virtual]
Destructive addition and assignment operator. Parameters:
const SimpleCollection<T> & obj RHS addition
Returns:
SimpleCollection<T> & This object after addition and assignment
Implements cryomesh::common::ICollection< SimpleCollection< T > >.
Definition at line 346 of file SimpleCollection.h.
template<class T> virtual SimpleCollection<T>& cryomesh::common::SimpleCollection< T >::operator= (const SimpleCollection< T > &obj) [inline, virtual]
Assignment operator. Parameters:
const SimpleCollection<T> & obj RHS assignment
Returns:
SimpleCollection<T> & This object after assignment
Implements cryomesh::common::ICollection< SimpleCollection< T > >.
Definition at line 362 of file SimpleCollection.h.
template<class T> virtual bool cryomesh::common::SimpleCollection< T >::operator== (const SimpleCollection< T > &obj) const [inline, virtual]
Comparator operator. Parameters:
const SimpleCollection<T> & obj RHS object
Returns:
bool True if equal, false otherwise
Implements cryomesh::common::ICollection< SimpleCollection< T > >.
Definition at line 390 of file SimpleCollection.h.
template<class T> virtual T cryomesh::common::SimpleCollection< T >::operator[] (unsignedindex) const throw (exceptions::IndexOutOfBoundsException) [inline, virtual]
Get value at index. Parameters:
unsigned index Index to return
Returns:
T Value at index, 0 if out of bounds
Definition at line 228 of file SimpleCollection.h.
template<class T> std::list<T>& cryomesh::common::SimpleCollection< T >::pad (intfront_pad, intback_pad, Tpad_value) [inline]
Pad Collection. Parameters:
int front_pad Amount of places to pad to front
int back_pad Amount of places to pad to back
T & obj Object to use for pad
Returns:
T & Return the collection
Definition at line 475 of file SimpleCollection.h.
template<class T> virtual void cryomesh::common::SimpleCollection< T >::remove (const std::list< T > &list) [inline, virtual]
Remove objects from collection by list. Parameters:
std::list<T> list The list values to be removed to the collection
Definition at line 167 of file SimpleCollection.h.
template<class T> virtual void cryomesh::common::SimpleCollection< T >::remove (const std::initializer_list< T > &list) [inline, virtual]
Remove objects from collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be removed from the collection
Definition at line 149 of file SimpleCollection.h.
template<class T> virtual void cryomesh::common::SimpleCollection< T >::remove (Tobj) [inline, virtual]
Remove object from collection. Parameters:
T obj The object to be removed from the collection
Definition at line 126 of file SimpleCollection.h.
template<class T> virtual SimpleCollection<T>& cryomesh::common::SimpleCollection< T >::reverse () [inline, virtual]
Reverse collection. Reflect the collection in the y axis
Returns:
SimpleCollection<T> & The inverted object
Definition at line 285 of file SimpleCollection.h.
Referenced by cryomesh::common::SimpleCollection< double >::reverse().
Friends And Related Function Documentation
template<class T> std::ostream& operator<< (std::ostream &out, const SimpleCollection< T > &obj) [friend]
To stream operator. Parameters:
std::ostream & out The output stream
const SimpleCollection & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 447 of file SimpleCollection.h.
Member Data Documentation
template<class T> std::list<T> cryomesh::common::SimpleCollection< T >::objects [private]
Definition at line 551 of file SimpleCollection.h.
Referenced by cryomesh::common::SimpleCollection< double >::add(), cryomesh::common::SimpleCollection< double >::clear(), cryomesh::common::SimpleCollection< double >::generateCurve(), cryomesh::common::SimpleCollection< double >::getBoundaryValue(), cryomesh::common::SimpleCollection< double >::getCollection(), cryomesh::common::SimpleCollection< double >::getMutableCollection(), cryomesh::common::SimpleCollection< double >::getSize(), cryomesh::common::SimpleCollection< double >::getSum(), cryomesh::common::SimpleCollection< double >::invert(), cryomesh::common::SimpleCollection< double >::operator=(), cryomesh::common::SimpleCollection< double >::operator[](), cryomesh::common::SimpleCollection< double >::pad(), cryomesh::common::SimpleCollection< double >::remove(), and cryomesh::common::SimpleCollection< double >::reverse().
Author
Generated automatically by Doxygen for cryomesh from the source code.