cryomesh::common::KeyMappedCollection
NAME
cryomesh::common::KeyMappedCollection -
KeyMappedCollection is a template class of U, a key class which supports getKey(), and T, the object class.
SYNOPSIS
#include <KeyMappedCollection.h>
Public Member Functions
KeyMappedCollection ()
Constructor.
virtual ~KeyMappedCollection ()
Destructor.
void clear ()
Clear all objects from collection.
boost::shared_ptr< T > add (boost::shared_ptr< T > obj)
Add object to collection.
virtual void add (const std::initializer_list< boost::shared_ptr< T > > &list)
Add object to collection by initialiser list.
virtual void add (const std::list< boost::shared_ptr< T > > &list)
Add object to collection by list.
virtual void remove (const std::initializer_list< boost::shared_ptr< T > > &list)
Remove objects from collection by initialiser list.
virtual void remove (const std::list< boost::shared_ptr< T > > &list)
Remove objects from collection by list.
boost::shared_ptr< T > remove (boost::shared_ptr< T > obj)
Add object to collection.
boost::shared_ptr< T > remove (T &obj)
Remove object from collection.
boost::shared_ptr< T > remove (U key)
Remove object from collection bt key.
std::list< U > getKeyList () const
Get keys for underlying connection.
std::vector< boost::shared_ptr< T > > getObjectList () const
Get object list for underlying connection.
boost::shared_ptr< T > getObjectByKey (const U &key)
Get object using key.
std::vector< boost::shared_ptr< T > > getRandomRange (int number) const
const std::map< U, boost::shared_ptr< T > > & getCollection () const
Get maximum value.
std::map< U, boost::shared_ptr< T > > & getMutableCollection ()
Get mutable underlying collection.
int getSize () const
Get underlying collections size.
Protected Attributes
std::map< U, boost::shared_ptr< T > > objects
Detailed Description
template<class U, class T> class cryomesh::common::KeyMappedCollection< U, T >
KeyMappedCollection is a template class of U, a key class which supports getKey(), and T, the object class.
Definition at line 22 of file KeyMappedCollection.h.
Constructor & Destructor Documentation
template<class U, class T> cryomesh::common::KeyMappedCollection< U, T >::KeyMappedCollection () [inline]
Constructor. Constructor for Collection<U,T>
Definition at line 29 of file KeyMappedCollection.h.
template<class U, class T> virtual cryomesh::common::KeyMappedCollection< U, T >::~KeyMappedCollection () [inline, virtual]
Destructor. Destructor for Collection<U,T>
Definition at line 38 of file KeyMappedCollection.h.
Member Function Documentation
template<class U, class T> boost::shared_ptr<T> cryomesh::common::KeyMappedCollection< U, T >::add (boost::shared_ptr< T >obj) [inline]
Add object to collection. Parameters:
boost::shared_ptr<T> obj The object to be added to the collection
Returns:
boost::shared_ptr<T> The object added to the collection
Definition at line 59 of file KeyMappedCollection.h.
Referenced by cryomesh::components::Node::addImpulse(), cryomesh::structures::Bundle::connectCluster(), cryomesh::structures::Cluster::createConnection(), cryomesh::structures::Fibre::createConnections(), and cryomesh::structures::Cluster::createNodes().
template<class U, class T> virtual void cryomesh::common::KeyMappedCollection< U, T >::add (const std::list< boost::shared_ptr< T > > &list) [inline, virtual]
Add object to collection by list. Parameters:
std::list<T> list The list values to be added to the collection
Definition at line 88 of file KeyMappedCollection.h.
template<class U, class T> virtual void cryomesh::common::KeyMappedCollection< U, T >::add (const std::initializer_list< boost::shared_ptr< T > > &list) [inline, virtual]
Add object to collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be added to the collection
Definition at line 70 of file KeyMappedCollection.h.
template<class U, class T> void cryomesh::common::KeyMappedCollection< U, T >::clear () [inline]
Clear all objects from collection.
Definition at line 45 of file KeyMappedCollection.h.
Referenced by cryomesh::structures::Fibre::createConnections().
template<class U, class T> const std::map<U, boost::shared_ptr<T> >& cryomesh::common::KeyMappedCollection< U, T >::getCollection () const [inline]
Get maximum value. Returns:
T The maximum value Get underlying collection
const std::map<U, boost::shared_ptr<T> > & The collection
Definition at line 309 of file KeyMappedCollection.h.
Referenced by cryomesh::structures::Cluster::getConnections(), cryomesh::structures::Cluster::getNodes(), cryomesh::components::ImpulseCollection::operator+=(), cryomesh::components::operator<<(), cryomesh::components::ImpulseCollection::operator=(), and cryomesh::components::ImpulseCollection::operator==().
template<class U, class T> std::list<U> cryomesh::common::KeyMappedCollection< U, T >::getKeyList () const [inline]
Get keys for underlying connection. Returns:
std::list<U> The list of keys
Definition at line 208 of file KeyMappedCollection.h.
template<class U, class T> std::map<U, boost::shared_ptr<T> >& cryomesh::common::KeyMappedCollection< U, T >::getMutableCollection () [inline]
Get mutable underlying collection. Returns:
const std::map<U, boost::shared_ptr<T> > & The mutable collection
Definition at line 319 of file KeyMappedCollection.h.
Referenced by cryomesh::structures::Fibre::connectAllConnections(), cryomesh::structures::Fibre::disconnectAllConnections(), cryomesh::structures::Fibre::trigger(), and cryomesh::structures::Cluster::updateConnectivity().
template<class U, class T> boost::shared_ptr<T> cryomesh::common::KeyMappedCollection< U, T >::getObjectByKey (const U &key) [inline]
Get object using key. Parameters:
U key Key to search for
Returns:
boost::shared_ptr<T> The found object
Definition at line 250 of file KeyMappedCollection.h.
Referenced by cryomesh::structures::Bundle::connectCluster().
template<class U, class T> std::vector<boost::shared_ptr<T> > cryomesh::common::KeyMappedCollection< U, T >::getObjectList () const [inline]
Get object list for underlying connection. Returns:
std::list<U> The list of object values
Definition at line 228 of file KeyMappedCollection.h.
Referenced by cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::getRandomRange(), and cryomesh::structures::Cluster::updateConnectivity().
template<class U, class T> std::vector<boost::shared_ptr<T> > cryomesh::common::KeyMappedCollection< U, T >::getRandomRange (intnumber) const [inline]
Definition at line 261 of file KeyMappedCollection.h.
template<class U, class T> int cryomesh::common::KeyMappedCollection< U, T >::getSize () const [inline]
Get underlying collections size. Returns:
int The collections size
Definition at line 329 of file KeyMappedCollection.h.
Referenced by cryomesh::structures::Fibre::connectAllConnections(), cryomesh::structures::Fibre::getWidth(), cryomesh::structures::operator<<(), and cryomesh::structures::Fibre::trigger().
template<class U, class T> boost::shared_ptr<T> cryomesh::common::KeyMappedCollection< U, T >::remove (boost::shared_ptr< T >obj) [inline]
Add object to collection. Parameters:
T & refobj The object to be added to the collection
Returns:
boost::shared_ptr<T> The object added to the collection
boost::shared_ptr<T> add(T & refobj) { boost::shared_ptr<T> obj = boost::shared_ptr<T>(&refobj); objects[obj->getKey()] = obj; return objects.find(obj->getKey())->second; } Remove object from collection
Parameters:
boost::shared_ptr<T> obj The object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 163 of file KeyMappedCollection.h.
template<class U, class T> virtual void cryomesh::common::KeyMappedCollection< U, T >::remove (const std::list< boost::shared_ptr< T > > &list) [inline, virtual]
Remove objects from collection by list. Parameters:
std::list<T> list The list values to be removed to the collection
Definition at line 124 of file KeyMappedCollection.h.
template<class U, class T> boost::shared_ptr<T> cryomesh::common::KeyMappedCollection< U, T >::remove (Ukey) [inline]
Remove object from collection bt key. Parameters:
U key The ey of the object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 191 of file KeyMappedCollection.h.
template<class U, class T> boost::shared_ptr<T> cryomesh::common::KeyMappedCollection< U, T >::remove (T &obj) [inline]
Remove object from collection. Parameters:
T & obj The object to be removed from the collection
Returns:
boost::shared_ptr<T> The object removed from the collection
Definition at line 177 of file KeyMappedCollection.h.
template<class U, class T> virtual void cryomesh::common::KeyMappedCollection< U, T >::remove (const std::initializer_list< boost::shared_ptr< T > > &list) [inline, virtual]
Remove objects from collection by initialiser list. Parameters:
std::initialiser_list<T> obj The values to be removed from the collection
Definition at line 106 of file KeyMappedCollection.h.
Member Data Documentation
template<class U, class T> std::map<U, boost::shared_ptr<T> > cryomesh::common::KeyMappedCollection< U, T >::objects [protected]
Definition at line 339 of file KeyMappedCollection.h.
Referenced by cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::add(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::clear(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::getCollection(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::getKeyList(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::getMutableCollection(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::getObjectByKey(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::getObjectList(), cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::getSize(), and cryomesh::common::KeyMappedCollection< boost::uuids::uuid, Fibre >::remove().
Author
Generated automatically by Doxygen for cryomesh from the source code.