cryomesh::structures
NAME
cryomesh::structures -
SYNOPSIS
Classes
class Bundle
A Bundle is the collection of clusters and fibres, it represents the system as a whole.
class Cluster
A Cluster is a collection of self-contained nodes and connections along with an associated Mesh, that can be connected up to one another.
class Fibre
A Fibre is a collection of connections that connect one structure to another.
class FibreMap
class Mesh
Mesh is the fabric of connection space and warps and is warped by it.
class NodeMesh
Mesh of nodes and their neighbouring nodes and distances.
Typedefs
typedef std::map
< boost::shared_ptr
< cryomesh::components::Node >
, std::map< boost::shared_ptr
< cryomesh::components::Node >
, double > > NeighbourhoodMap"
Typedef to simplify neighbourhood map structure.
typedef std::map
< boost::shared_ptr
< cryomesh::components::Node >
, std::map< boost::shared_ptr
< cryomesh::components::Node >
, double > >::const_iterator NeighbourhoodMapConstIterator"
Typdef for iterator to neighbourhood map.
Functions
std::ostream & operator<< (std::ostream &os, const Bundle &obj)
std::ostream & operator<< (std::ostream &os, const Cluster &obj)
std::ostream & operator<< (std::ostream &os, const Fibre &obj)
std::ostream & operator<< (std::ostream &os, const NodeMesh &obj)
Typedef Documentation
cryomesh::structures::NodeMesh::NeighbourhoodMap
Typedef to simplify neighbourhood map structure. Map of Nodes to other nodes within their neighbourhood and the distances to them.
Definition at line 19 of file NodeMesh.h.
typedef std::map<boost::shared_ptr<cryomesh::components::Node>, std::map<boost::shared_ptr<cryomesh::components::Node>, double> >::const_iterator cryomesh::structures::NeighbourhoodMapConstIterator
Typdef for iterator to neighbourhood map.
Definition at line 30 of file NodeMesh.h.
Function Documentation
std::ostream& cryomesh::structures::operator<< (std::ostream &os, const NodeMesh &obj)"Parameters:
std::ostream & os The output stream
const NodeMesh & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 306 of file NodeMesh.cpp.
References cryomesh::structures::NodeMesh::printNeighbourhoodActivities(), and cryomesh::structures::NodeMesh::printNeighbourhoods().
std::ostream& cryomesh::structures::operator<< (std::ostream &os, const Cluster &obj)"Parameters:
std::ostream & os The output stream
const Cluster & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 331 of file Cluster.cpp.
References cryomesh::structures::Cluster::getConnections(), cryomesh::structures::Cluster::getNodeMap(), and cryomesh::structures::Cluster::getNodes().
std::ostream& cryomesh::structures::operator<< (std::ostream &os, const Fibre &obj)"Returns:
Pattern To stream operator
Parameters:
std::ostream & os The output stream
const Fibre & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 449 of file Fibre.cpp.
References cryomesh::structures::Fibre::getConnections(), and cryomesh::structures::Fibre::getOutputNodesPattern().
std::ostream& cryomesh::structures::operator<< (std::ostream &os, const Bundle &obj)"Parameters:
std::ostream & os The output stream
const Bundle & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 973 of file Bundle.cpp.
References cryomesh::common::Loggable::MAX, and cryomesh::structures::Bundle::print().
Author
Generated automatically by Doxygen for cryomesh from the source code.