.TH "cryomesh::manager::NodeDatabaseObject" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::manager::NodeDatabaseObject \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NodeDatabaseObject\&.h>\fP
.PP
Inherits \fBcryomesh::manager::DatabaseObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeDatabaseObject\fP (std::string uuid_str, spacial::Point pt, \fBcommon::Cycle\fP cyc, double act)"
.br
.RI "\fICreate object from node variables\&. \fP"
.ti -1c
.RI "\fBNodeDatabaseObject\fP (const std::string &node_table_entry)"
.br
.RI "\fICreate object from the string of entries in the database node table\&. \fP"
.ti -1c
.RI "virtual \fB~NodeDatabaseObject\fP ()"
.br
.RI "\fIDefault destructor\&. \fP"
.ti -1c
.RI "virtual std::string \fBgetInsert\fP (const std::string &table) const "
.br
.RI "\fIGet the string that can be used to insert the sql data\&. \fP"
.ti -1c
.RI "std::string \fBgetUUID\fP () const "
.br
.RI "\fIGet uuid variable\&. \fP"
.ti -1c
.RI "const spacial::Point & \fBgetPoint\fP () const "
.br
.RI "\fIGet point variable\&. \fP"
.ti -1c
.RI "const \fBcommon::Cycle\fP & \fBgetCycle\fP () const "
.br
.RI "\fIGet cycle variable\&. \fP"
.ti -1c
.RI "double \fBgetActivity\fP () const "
.br
.RI "\fIGet activity variable\&. \fP"
.ti -1c
.RI "std::string \fBgetKey\fP (const std::string &key) const "
.br
.RI "\fIReturn the string object associated with a key\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBfindValue\fP (const std::string &entry, const std::map< std::string, std::string > &map)"
.br
.RI "\fIFind entries value in map or return null\&. \fP"
.ti -1c
.RI "static std::map< std::string, 
.br
std::string > \fBgetColumnMapFromEntry\fP (const std::string &entry)"
.br
.RI "\fIParse a string database entry, extract columns and values and return a map\&. \fP"
.ti -1c
.RI "template<class T > static std::string \fBtoString\fP (T obj)"
.br
.RI "\fIConvert an templated object that can be piped to a stream to a string\&. \fP"
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBID_TAG\fP = 'id'"
.br
.ti -1c
.RI "static const std::string \fBX_TAG\fP = 'x'"
.br
.ti -1c
.RI "static const std::string \fBY_TAG\fP = 'y'"
.br
.ti -1c
.RI "static const std::string \fBZ_TAG\fP = 'z'"
.br
.ti -1c
.RI "static const std::string \fBACTIVITY_TAG\fP = 'activity'"
.br
.ti -1c
.RI "static const std::string \fBCYCLE_TAG\fP = 'cycle'"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, 
.br
std::string > \fBcolumns\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBuuid\fP"
.br
.ti -1c
.RI "spacial::Point \fBpoint\fP"
.br
.ti -1c
.RI "\fBcommon::Cycle\fP \fBcycle\fP"
.br
.ti -1c
.RI "double \fBactivity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file NodeDatabaseObject\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcryomesh::manager::NodeDatabaseObject::NodeDatabaseObject\fP (std::stringuuid_str, spacial::Pointpt, \fBcommon::Cycle\fPcyc, doubleact)"
.PP
Create object from node variables\&. \fBParameters:\fP
.RS 4
\fIstd::string\fP The uuid string of the node 
.br
\fIspacial::Point\fP Location of the node 
.br
\fICycle\fP The cycle of the entry 
.br
\fIdouble\fP The activity of the node on the cycle 
.RE
.PP

.PP
Definition at line 13 of file NodeDatabaseObject\&.cpp\&.
.PP
References activity, ACTIVITY_TAG, cryomesh::manager::DatabaseObject::columns, cycle, CYCLE_TAG, ID_TAG, point, cryomesh::common::Cycle::toULInt(), X_TAG, Y_TAG, and Z_TAG\&.
.SS "\fBcryomesh::manager::NodeDatabaseObject::NodeDatabaseObject\fP (const std::string &node_table_entry)"
.PP
Create object from the string of entries in the database node table\&. \fBParameters:\fP
.RS 4
\fIstd::string\fP The string of data taken from a node entry in the database node table 
.RE
.PP

.PP
Definition at line 23 of file NodeDatabaseObject\&.cpp\&.
.PP
References activity, cycle, cryomesh::manager::DatabaseObject::findValue(), cryomesh::manager::DatabaseObject::getColumnMapFromEntry(), point, and uuid\&.
.SS "\fBcryomesh::manager::NodeDatabaseObject::~NodeDatabaseObject\fP ()\fC [virtual]\fP"
.PP
Default destructor\&. 
.PP
Definition at line 60 of file NodeDatabaseObject\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static std::string \fBcryomesh::manager::DatabaseObject::findValue\fP (const std::string &entry, const std::map< std::string, std::string > &map)\fC [inline, static, inherited]\fP"
.PP
Find entries value in map or return null\&. \fBParameters:\fP
.RS 4
\fIstd::string\fP Entry to find 
.br
\fIstd::map<std::string,std::string\fP map to search
.RE
.PP
\fBReturns:\fP
.RS 4
Value of entry 
.RE
.PP

.PP
Definition at line 59 of file DatabaseObject\&.h\&.
.PP
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject()\&.
.SS "double \fBcryomesh::manager::NodeDatabaseObject::getActivity\fP () const"
.PP
Get activity variable\&. \fBReturns:\fP
.RS 4
double The activity variable 
.RE
.PP

.PP
Definition at line 83 of file NodeDatabaseObject\&.cpp\&.
.PP
References activity\&.
.SS "static std::map<std::string, std::string> \fBcryomesh::manager::DatabaseObject::getColumnMapFromEntry\fP (const std::string &entry)\fC [inline, static, inherited]\fP"
.PP
Parse a string database entry, extract columns and values and return a map\&. 
.PP
Definition at line 72 of file DatabaseObject\&.h\&.
.PP
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject()\&.
.SS "const \fBcommon::Cycle\fP & \fBcryomesh::manager::NodeDatabaseObject::getCycle\fP () const"
.PP
Get cycle variable\&. \fBReturns:\fP
.RS 4
\fBcommon::Cycle\fP The cycle variable 
.RE
.PP

.PP
Definition at line 80 of file NodeDatabaseObject\&.cpp\&.
.PP
References cycle\&.
.SS "std::string \fBcryomesh::manager::NodeDatabaseObject::getInsert\fP (const std::string &table) const\fC [virtual]\fP"
.PP
Get the string that can be used to insert the sql data\&. \fBReturns:\fP
.RS 4
the sql command string to insert into this table 
.RE
.PP

.PP
Implements \fBcryomesh::manager::DatabaseObject\fP\&.
.PP
Definition at line 63 of file NodeDatabaseObject\&.cpp\&.
.PP
References ACTIVITY_TAG, CYCLE_TAG, cryomesh::manager::DatabaseObject::getKey(), ID_TAG, X_TAG, Y_TAG, and Z_TAG\&.
.SS "std::string \fBcryomesh::manager::DatabaseObject::getKey\fP (const std::string &key) const\fC [inline, inherited]\fP"
.PP
Return the string object associated with a key\&. ::string The key to search for
.PP
\fBReturns:\fP
.RS 4
std::string The object associated with the search key, '' if not found 
.RE
.PP

.PP
Definition at line 37 of file DatabaseObject\&.h\&.
.PP
References cryomesh::manager::DatabaseObject::columns\&.
.PP
Referenced by cryomesh::manager::PatternDatabaseObject::getInsert(), getInsert(), and cryomesh::manager::ConnectionDatabaseObject::getInsert()\&.
.SS "const spacial::Point & \fBcryomesh::manager::NodeDatabaseObject::getPoint\fP () const"
.PP
Get point variable\&. \fBReturns:\fP
.RS 4
spacial::Point The point variable 
.RE
.PP

.PP
Definition at line 77 of file NodeDatabaseObject\&.cpp\&.
.PP
References point\&.
.SS "std::string \fBcryomesh::manager::NodeDatabaseObject::getUUID\fP () const"
.PP
Get uuid variable\&. \fBReturns:\fP
.RS 4
std::string The uuid variable 
.RE
.PP

.PP
Definition at line 74 of file NodeDatabaseObject\&.cpp\&.
.PP
References uuid\&.
.SS "template<class T > static std::string \fBcryomesh::manager::DatabaseObject::toString\fP (Tobj)\fC [inline, static, inherited]\fP"
.PP
Convert an templated object that can be piped to a stream to a string\&. \fBParameters:\fP
.RS 4
\fIT\fP The object to get a string for 
.RE
.PP

.PP
Definition at line 108 of file DatabaseObject\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBcryomesh::manager::NodeDatabaseObject::activity\fP\fC [private]\fP"
.PP
Definition at line 158 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getActivity(), and NodeDatabaseObject()\&.
.SS "const std::string \fBcryomesh::manager::NodeDatabaseObject::ACTIVITY_TAG\fP = 'activity'\fC [static]\fP"
.PP
Definition at line 122 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getInsert(), and NodeDatabaseObject()\&.
.SS "std::map<std::string, std::string> \fBcryomesh::manager::DatabaseObject::columns\fP\fC [protected, inherited]\fP"
.PP
Definition at line 119 of file DatabaseObject\&.h\&.
.PP
Referenced by cryomesh::manager::ConnectionDatabaseObject::ConnectionDatabaseObject(), cryomesh::manager::DatabaseObject::getKey(), NodeDatabaseObject(), and cryomesh::manager::PatternDatabaseObject::PatternDatabaseObject()\&.
.SS "\fBcommon::Cycle\fP \fBcryomesh::manager::NodeDatabaseObject::cycle\fP\fC [private]\fP"
.PP
Definition at line 151 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getCycle(), and NodeDatabaseObject()\&.
.SS "const std::string \fBcryomesh::manager::NodeDatabaseObject::CYCLE_TAG\fP = 'cycle'\fC [static]\fP"
.PP
Definition at line 129 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getInsert(), and NodeDatabaseObject()\&.
.SS "const std::string \fBcryomesh::manager::NodeDatabaseObject::ID_TAG\fP = 'id'\fC [static]\fP"
.PP
Definition at line 94 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getInsert(), and NodeDatabaseObject()\&.
.SS "spacial::Point \fBcryomesh::manager::NodeDatabaseObject::point\fP\fC [private]\fP"
.PP
Definition at line 144 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getPoint(), and NodeDatabaseObject()\&.
.SS "std::string \fBcryomesh::manager::NodeDatabaseObject::uuid\fP\fC [private]\fP"
.PP
Definition at line 137 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getUUID(), and NodeDatabaseObject()\&.
.SS "const std::string \fBcryomesh::manager::NodeDatabaseObject::X_TAG\fP = 'x'\fC [static]\fP"
.PP
Definition at line 101 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getInsert(), and NodeDatabaseObject()\&.
.SS "const std::string \fBcryomesh::manager::NodeDatabaseObject::Y_TAG\fP = 'y'\fC [static]\fP"
.PP
Definition at line 108 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getInsert(), and NodeDatabaseObject()\&.
.SS "const std::string \fBcryomesh::manager::NodeDatabaseObject::Z_TAG\fP = 'z'\fC [static]\fP"
.PP
Definition at line 115 of file NodeDatabaseObject\&.h\&.
.PP
Referenced by getInsert(), and NodeDatabaseObject()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
