cryomesh::common::Containers
NAME
cryomesh::common::Containers -
Containers contains utility functions for containers.
SYNOPSIS
#include <Containers.h>
Public Member Functions
virtual ~Containers ()
Destructor.
Static Public Member Functions
template<class U , class T > static std::map< boost::shared_ptr< U >, boost::shared_ptr< T > > addMapObjectByCreationObjects (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, std::list< boost::shared_ptr< U > > &colist)
template<class U , class T > static bool deleteByEntry (U &store, const T &id)
template<class T > static boost::shared_ptr< T > deleteMapObjectByUUID (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, const boost::uuids::uuid &id)
template<class T > static const boost::shared_ptr< T > getByUUID (const std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, const boost::uuids::uuid id)
template<class T > static boost::shared_ptr< T > getMutableByUUID (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, boost::uuids::uuid id)
template<class T > static const boost::shared_ptr< T > getByID (const std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, int id)
template<class T > static boost::shared_ptr< T > getMutableByID (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, int id)
template<class U , class T > static void mapByUUID (const std::map< boost::shared_ptr< U >, boost::shared_ptr< T > > &creation_to_real, std::map< boost::uuids::uuid, boost::uuids::uuid > &uuid_map)
template<class U , class T > static std::ostream & print (std::ostream &os, const std::map< U, T > &obj)
Print a mapped collection to an output stream.
template<class T > static std::ostream & print (std::ostream &os, const T &obj)
Print a collection to an output stream.
template<class T > static bool compare (const T &lhs, const T &rhs)
Compare two collections.
template<class T > static T & addMerge (T &lhs, const T &rhs)
Template function to add a collection, rhs, in-place to a collection on lhs.
template<class T > static T add (const T &lhs, const T &rhs)
Template function to add a collection, rhs, non destructively to a collection on lhs.
Protected Member Functions
Containers ()
Protected constructor to prevent instantiation.
Detailed Description
Containers contains utility functions for containers.
Definition at line 27 of file Containers.h.
Constructor & Destructor Documentation
virtual cryomesh::common::Containers::~Containers () [virtual]
Destructor.
cryomesh::common::Containers::Containers () [protected]
Protected constructor to prevent instantiation.
Member Function Documentation
template<class T > static T cryomesh::common::Containers::add (const T &lhs, const T &rhs) [inline, static]
Template function to add a collection, rhs, non destructively to a collection on lhs. Parameters:
T & lhs Left hand side parameter which will be added and left unchanged
const T & rhs Right hand side which will be added and left unchanged
@ return T The merged collection
Definition at line 307 of file Containers.h.
References addMerge().
template<class U , class T > static std::map<boost::shared_ptr<U>, boost::shared_ptr<T> > cryomesh::common::Containers::addMapObjectByCreationObjects (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, std::list< boost::shared_ptr< U > > &colist) [inline, static]
Definition at line 35 of file Containers.h.
template<class T > static T& cryomesh::common::Containers::addMerge (T &lhs, const T &rhs) [inline, static]
Template function to add a collection, rhs, in-place to a collection on lhs. Parameters:
T & lhs Left hand side parameter which will be destructively added into
const T & rhs Right hand side which will be added but left unchanged
@ return T & The merged collection
Definition at line 269 of file Containers.h.
Referenced by add().
template<class T > static bool cryomesh::common::Containers::compare (const T &lhs, const T &rhs) [inline, static]
Compare two collections. Parameters:
const T & lhs First object
const T & rhs Second object
Returns:
bool True of equal, false otherwise
Definition at line 236 of file Containers.h.
template<class U , class T > static bool cryomesh::common::Containers::deleteByEntry (U &store, const T &id) [inline, static]
Definition at line 54 of file Containers.h.
template<class T > static boost::shared_ptr<T> cryomesh::common::Containers::deleteMapObjectByUUID (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, const boost::uuids::uuid &id) [inline, static]
Definition at line 66 of file Containers.h.
template<class T > static const boost::shared_ptr<T> cryomesh::common::Containers::getByID (const std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, intid) [inline, static]
Definition at line 110 of file Containers.h.
template<class T > static const boost::shared_ptr<T> cryomesh::common::Containers::getByUUID (const std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, const boost::uuids::uuidid) [inline, static]
Definition at line 80 of file Containers.h.
template<class T > static boost::shared_ptr<T> cryomesh::common::Containers::getMutableByID (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, intid) [inline, static]
Definition at line 134 of file Containers.h.
template<class T > static boost::shared_ptr<T> cryomesh::common::Containers::getMutableByUUID (std::map< boost::uuids::uuid, boost::shared_ptr< T > > &mapobj, boost::uuids::uuidid) [inline, static]
Definition at line 95 of file Containers.h.
template<class U , class T > static void cryomesh::common::Containers::mapByUUID (const std::map< boost::shared_ptr< U >, boost::shared_ptr< T > > &creation_to_real, std::map< boost::uuids::uuid, boost::uuids::uuid > &uuid_map) [inline, static]
Definition at line 156 of file Containers.h.
template<class U , class T > static std::ostream& cryomesh::common::Containers::print (std::ostream &os, const std::map< U, T > &obj) [inline, static]
Print a mapped collection to an output stream. Parameters:
std::ostream & os Stream to print to
const T & obj object to print out
Returns:
std::ostream & The output stream
Definition at line 183 of file Containers.h.
Referenced by cryomesh::common::SimpleCollection< double >::operator==().
template<class T > static std::ostream& cryomesh::common::Containers::print (std::ostream &os, const T &obj) [inline, static]
Print a collection to an output stream. Parameters:
std::ostream & os Stream to print to
const T & obj object to print out
Returns:
std::ostream & The output stream
Definition at line 210 of file Containers.h.
Author
Generated automatically by Doxygen for cryomesh from the source code.