cryomesh::common::Connector< U, T >
NAME
cryomesh::common::Connector< U, T > -
Connector is a template to add connectable functionality between two classes.
SYNOPSIS
#include <Connector.h>
Public Member Functions
Connector (const unsigned int max_inputs=0, const unsigned int max_outputs=0)
virtual ~Connector ()
bool connectInput (const boost::shared_ptr< T > obj)
Connect a unit to this one as an input.
bool connectInputs (const std::vector< boost::shared_ptr< T > > &list)
Connect a list of units to this one as inputs.
bool connectInputs (const std::initializer_list< boost::shared_ptr< T > > &list)
Connect an initialiser list of units to this one as inputs.
bool connectOutput (const boost::shared_ptr< T > &obj)
Connect a unit to this one as an output.
bool connectOutputs (const std::vector< boost::shared_ptr< T > > &list)
Connect a list of units to this one as outputs.
bool connectOutputs (const std::initializer_list< boost::shared_ptr< T > > &list)
Connect an initialiser list of units to this one as outputs.
bool disconnectInput (const boost::shared_ptr< T > &obj)
Disconnect an input to this unit.
bool disconnectInput (const boost::uuids::uuid &id)
Disconnect an input to this unit.
bool disconnectInputs (const std::vector< boost::shared_ptr< T > > &list)
Disconnect a list of input units from this one.
bool disconnectInputs (const std::initializer_list< boost::shared_ptr< T > > &list)
Disconnect an initialiser list of input units from this one.
bool disconnectInputs (const std::vector< boost::uuids::uuid > &list)
Disconnect a list of input units from this one.
bool disconnectInputs (const std::initializer_list< boost::uuids::uuid > &list)
Disconnect an initialiser list of input units from this one.
bool disconnectAllInputs ()
Disconnect all input units from this one.
bool disconnectOutput (const boost::shared_ptr< T > &obj)
Disconnect an output to this unit.
bool disconnectOutput (const boost::uuids::uuid &id)
Disconnect an output to this unit.
bool disconnectOutputs (const std::vector< boost::shared_ptr< T > > &list)
Disconnect a list of Output units from this one.
bool disconnectOutputs (const std::initializer_list< boost::shared_ptr< T > > &list)
Disconnect an initialiser list of Output units from this one.
bool disconnectOutputs (const std::vector< boost::uuids::uuid > &list)
Disconnect a uuid list of Output units from this one.
bool disconnectOutputs (const std::initializer_list< boost::uuids::uuid > &list)
Disconnect an uuid initiaialiser list of Output units from this one.
bool disconnectAllOutputs ()
Disconnect all Output units from this one.
const std::map
< boost::uuids::uuid,
boost::shared_ptr< T > > & getInputs () const "
Get all inputs.
const std::list
< boost::uuids::uuid > getInputsUUID () const "
const std::list
< boost::uuids::uuid > getOutputsUUID () const "
std::map< boost::uuids::uuid,
boost::shared_ptr< T > > & getMutableInputs ()"
Get all inputs as mutable object.
const std::map
< boost::uuids::uuid,
boost::shared_ptr< T > > & getOutputs () const "
Get all outputs.
std::map< boost::uuids::uuid,
boost::shared_ptr< T > > & getMutableOutputs ()"
Get all outputs as mutable object.
Protected Member Functions
boost::shared_ptr< T > connect (const boost::shared_ptr< T > obj, std::map< boost::uuids::uuid, boost::shared_ptr< T > > &objs, unsigned int max_connections)
Connect up an object using the supplied map.
boost::shared_ptr< T > disconnect (const boost::shared_ptr< T > obj, std::map< boost::uuids::uuid, boost::shared_ptr< T > > &objs)
Disconnect an object using the supplied map.
boost::shared_ptr< T > disconnect (const boost::uuids::uuid &id, std::map< boost::uuids::uuid, boost::shared_ptr< T > > &objs)
Disconnect an object using the supplied map.
Protected Attributes
std::map< boost::uuids::uuid,
boost::shared_ptr< T > > minputs"
std::map< boost::uuids::uuid,
boost::shared_ptr< T > > moutputs"
unsigned int maxInputs
unsigned int maxOutputs
Friends
std::ostream & operator<< (std::ostream &os, const Connector< U, T > &obj)
To stream operator.
Detailed Description
template<class U, class T>class cryomesh::common::Connector< U, T >
Connector is a template to add connectable functionality between two classes.
Represents a template to add connectable funtionality between class U as the central connectable and class T as those objects it can be connected to
Definition at line 33 of file Connector.h.
Constructor & Destructor Documentation
template<class U, class T> cryomesh::common::Connector< U, T >::Connector (const unsigned intmax_inputs = 0, const unsigned intmax_outputs = 0) [inline]
Definition at line 35 of file Connector.h.
template<class U, class T> virtual cryomesh::common::Connector< U, T >::~Connector () [inline, virtual]
Definition at line 39 of file Connector.h.
Member Function Documentation
template<class U, class T> boost::shared_ptr<T> cryomesh::common::Connector< U, T >::connect (const boost::shared_ptr< T >obj, std::map< boost::uuids::uuid, boost::shared_ptr< T > > &objs, unsigned intmax_connections) [inline, protected]
Connect up an object using the supplied map. Parameters:
boost::shared_ptr<T> obj Pointer to the object that is to be connected
std::map<boost::uuids::uuid,boost::shared_ptr<T> > objs The map that will be used to connect the object
unsinged int Maximum connections to allow
Returns:
Pointer to the connected object
Definition at line 655 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::connectInput(), and cryomesh::common::Connector< Fibre, Cluster >::connectOutput().
template<class U, class T> bool cryomesh::common::Connector< U, T >::connectInput (const boost::shared_ptr< T >obj) [inline]
Connect a unit to this one as an input. Parameters:
boost::shared_ptr<T> obj Pointer to the object to be connected as input
Returns:
true if connection succeeds, false otherwise
Definition at line 53 of file Connector.h.
Referenced by cryomesh::structures::Fibre::connectAllConnections(), and cryomesh::common::Connector< Fibre, Cluster >::connectInputs().
template<class U, class T> bool cryomesh::common::Connector< U, T >::connectInputs (const std::vector< boost::shared_ptr< T > > &list) [inline]
Connect a list of units to this one as inputs. Parameters:
std::vector<boost::shared_ptr<T> > list List of pointers to objects to be connected as inputs
Returns:
true if all connections succeed, false otherwise
Definition at line 73 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::connectInputs (const std::initializer_list< boost::shared_ptr< T > > &list) [inline]
Connect an initialiser list of units to this one as inputs. Parameters:
std::initializer_list<boost::shared_ptr< T > > list Initialiser list of pointers to objects to be connected as input
Returns:
true if all connections succeed, false otherwise
Definition at line 97 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::connectOutput (const boost::shared_ptr< T > &obj) [inline]
Connect a unit to this one as an output. Parameters:
boost::shared_ptr<T> obj Pointer to the object to be connected as output
Returns:
true if connection succeeds, false otherwise
Definition at line 122 of file Connector.h.
Referenced by cryomesh::structures::Fibre::connectAllConnections(), and cryomesh::common::Connector< Fibre, Cluster >::connectOutputs().
template<class U, class T> bool cryomesh::common::Connector< U, T >::connectOutputs (const std::vector< boost::shared_ptr< T > > &list) [inline]
Connect a list of units to this one as outputs. Parameters:
std::vector<boost::shared_ptr<T> > list List of pointers to objects to be connected as outputs
Returns:
true if all connections succeed, false otherwise
Definition at line 142 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::connectOutputs (const std::initializer_list< boost::shared_ptr< T > > &list) [inline]
Connect an initialiser list of units to this one as outputs. Parameters:
std::initializer_list<boost::shared_ptr< T > > list Initialiser list of pointers to objects to be connected as outputs
Returns:
true if all connections succeed, false otherwise
Definition at line 167 of file Connector.h.
template<class U, class T> boost::shared_ptr<T> cryomesh::common::Connector< U, T >::disconnect (const boost::shared_ptr< T >obj, std::map< boost::uuids::uuid, boost::shared_ptr< T > > &objs) [inline, protected]
Disconnect an object using the supplied map. Parameters:
boost::shared_ptr<T> obj Pointer to the object that is to be disconnected
std::map<boost::uuids::uuid,boost::shared_ptr<T> > objs The map that will be used to disconnect the object
Returns:
Pointer to the disconnected object, pointer is 0 is object was not found
Definition at line 685 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::disconnectInput(), and cryomesh::common::Connector< Fibre, Cluster >::disconnectOutput().
template<class U, class T> boost::shared_ptr<T> cryomesh::common::Connector< U, T >::disconnect (const boost::uuids::uuid &id, std::map< boost::uuids::uuid, boost::shared_ptr< T > > &objs) [inline, protected]
Disconnect an object using the supplied map. Parameters:
boost::uuids::uuid id The uuid of the object that is to be disconnected
std::map<boost::uuids::uuid,boost::shared_ptr<T> > & objs The map that will be used to disconnect the object
Returns:
Pointer to the disconnected object, pointer is null is object was not found
Definition at line 724 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectAllInputs () [inline]
Disconnect all input units from this one. Returns:
true if all disconnections succeed, false otherwise
Definition at line 332 of file Connector.h.
Referenced by cryomesh::structures::Fibre::disconnectAllConnections().
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectAllOutputs () [inline]
Disconnect all Output units from this one. Returns:
true if all disconnections succeed, false otherwise
Definition at line 500 of file Connector.h.
Referenced by cryomesh::structures::Fibre::disconnectAllConnections().
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectInput (const boost::shared_ptr< T > &obj) [inline]
Disconnect an input to this unit. Parameters:
boost::shared_ptr<T> obj Pointer to the object to be disconnected from input
Returns:
true if disconnection succeeds, false otherwise
Definition at line 193 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::disconnectAllInputs(), and cryomesh::common::Connector< Fibre, Cluster >::disconnectInputs().
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectInput (const boost::uuids::uuid &id) [inline]
Disconnect an input to this unit. Parameters:
boost::uuids::uuid id The unique identifier of the object to be disconnected
Returns:
true if disconnection succeeds, false otherwise
Definition at line 212 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectInputs (const std::vector< boost::shared_ptr< T > > &list) [inline]
Disconnect a list of input units from this one. Parameters:
std::vector<boost::shared_ptr<T> > list List of pointers to objects to be disconnected
Returns:
true if all disconnections succeed, false otherwise
Definition at line 234 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectInputs (const std::initializer_list< boost::shared_ptr< T > > &list) [inline]
Disconnect an initialiser list of input units from this one. Parameters:
std::initializer_list<boost::shared_ptr< T > > list Initialiser list of pointers to objects to be disconnected as inputs
Returns:
true if all disconnections succeed, false otherwise
Definition at line 259 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectInputs (const std::vector< boost::uuids::uuid > &list) [inline]
Disconnect a list of input units from this one. Parameters:
boost::uuids::uuid list List of uuids to objects to be disconnected
Returns:
true if all disconnections succeed, false otherwise
Definition at line 284 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectInputs (const std::initializer_list< boost::uuids::uuid > &list) [inline]
Disconnect an initialiser list of input units from this one. Parameters:
boost::uuids::uuid list Initialiser list of uuids to objects to be disconnected as inputs
Returns:
true if all disconnections succeed, false otherwise
Definition at line 309 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectOutput (const boost::shared_ptr< T > &obj) [inline]
Disconnect an output to this unit. Parameters:
boost::shared_ptr<T> obj Pointer to the object to be disconnected from output
Returns:
true if disconnection succeeds, false otherwise
Definition at line 358 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::disconnectAllOutputs(), and cryomesh::common::Connector< Fibre, Cluster >::disconnectOutputs().
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectOutput (const boost::uuids::uuid &id) [inline]
Disconnect an output to this unit. Parameters:
boost::uuids::uuid id The unique identifier of the object to be disconnected
Returns:
true if disconnection succeeds, false otherwise
Definition at line 379 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectOutputs (const std::vector< boost::shared_ptr< T > > &list) [inline]
Disconnect a list of Output units from this one. Parameters:
std::vector<boost::shared_ptr<T> > list List of pointers to objects to be disconnected
Returns:
true if all disconnections succeed, false otherwise
Definition at line 401 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectOutputs (const std::initializer_list< boost::shared_ptr< T > > &list) [inline]
Disconnect an initialiser list of Output units from this one. Parameters:
std::initializer_list<boost::shared_ptr< T > > list Initialiser list of pointers to objects to be disconnected as Outputs
Returns:
true if all disconnections succeed, false otherwise
Definition at line 426 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectOutputs (const std::vector< boost::uuids::uuid > &list) [inline]
Disconnect a uuid list of Output units from this one. Parameters:
boost::uuids::uuid list List of uuids to objects to be disconnected
Returns:
true if all disconnections succeed, false otherwise
Definition at line 452 of file Connector.h.
template<class U, class T> bool cryomesh::common::Connector< U, T >::disconnectOutputs (const std::initializer_list< boost::uuids::uuid > &list) [inline]
Disconnect an uuid initiaialiser list of Output units from this one. Parameters:
boost::uuids::uuid list Initialiser list of uuids to objects to be disconnected as Outputs
Returns:
true if all disconnections succeed, false otherwise
Definition at line 477 of file Connector.h.
template<class U, class T> const std::map<boost::uuids::uuid, boost::shared_ptr<T> >& cryomesh::common::Connector< U, T >::getInputs () const [inline]
Get all inputs. Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<T> The map of inputs
Definition at line 524 of file Connector.h.
Referenced by cryomesh::structures::Fibre::countConnections(), and cryomesh::structures::Fibre::isConnected().
template<class U, class T> const std::list<boost::uuids::uuid> cryomesh::common::Connector< U, T >::getInputsUUID () const [inline]
Definition at line 528 of file Connector.h.
template<class U, class T> std::map<boost::uuids::uuid, boost::shared_ptr<T> >& cryomesh::common::Connector< U, T >::getMutableInputs () [inline]
Get all inputs as mutable object. Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<T> The map of inputs
Definition at line 566 of file Connector.h.
template<class U, class T> std::map<boost::uuids::uuid, boost::shared_ptr<T> >& cryomesh::common::Connector< U, T >::getMutableOutputs () [inline]
Get all outputs as mutable object. Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<T> The map of outputs
Definition at line 588 of file Connector.h.
template<class U, class T> const std::map<boost::uuids::uuid, boost::shared_ptr<T> >& cryomesh::common::Connector< U, T >::getOutputs () const [inline]
Get all outputs. Returns:
std::map<boost::uuids::uuid, boost::shared_ptr<T> The map of outputs
Definition at line 577 of file Connector.h.
Referenced by cryomesh::structures::Fibre::countConnections(), and cryomesh::structures::Fibre::isConnected().
template<class U, class T> const std::list<boost::uuids::uuid> cryomesh::common::Connector< U, T >::getOutputsUUID () const [inline]
Definition at line 543 of file Connector.h.
Friends And Related Function Documentation
template<class U, class T> std::ostream& operator<< (std::ostream &os, const Connector< U, T > &obj) [friend]
To stream operator. Parameters:
std::ostream & os The output stream
const Connector<U,T> & obj The object to stream
Returns:
std::ostream & The output stream
Definition at line 603 of file Connector.h.
Member Data Documentation
template<class U, class T> unsigned int cryomesh::common::Connector< U, T >::maxInputs [protected]
Definition at line 770 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::connectInput().
template<class U, class T> unsigned int cryomesh::common::Connector< U, T >::maxOutputs [protected]
Definition at line 777 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::connectOutput().
template<class U, class T> std::map<boost::uuids::uuid, boost::shared_ptr<T> > cryomesh::common::Connector< U, T >::minputs [protected]
Definition at line 756 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::connectInput(), cryomesh::common::Connector< Fibre, Cluster >::disconnectAllInputs(), cryomesh::common::Connector< Fibre, Cluster >::disconnectInput(), cryomesh::common::Connector< Fibre, Cluster >::getInputs(), cryomesh::common::Connector< Fibre, Cluster >::getInputsUUID(), and cryomesh::common::Connector< Fibre, Cluster >::getMutableInputs().
template<class U, class T> std::map<boost::uuids::uuid, boost::shared_ptr<T> > cryomesh::common::Connector< U, T >::moutputs [protected]
Definition at line 763 of file Connector.h.
Referenced by cryomesh::common::Connector< Fibre, Cluster >::connectOutput(), cryomesh::common::Connector< Fibre, Cluster >::disconnectAllOutputs(), cryomesh::common::Connector< Fibre, Cluster >::disconnectOutput(), cryomesh::common::Connector< Fibre, Cluster >::getMutableOutputs(), cryomesh::common::Connector< Fibre, Cluster >::getOutputs(), and cryomesh::common::Connector< Fibre, Cluster >::getOutputsUUID().
Author
Generated automatically by Doxygen for cryomesh from the source code.