.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/Defs.h" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/Defs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/shared_ptr.hpp>\fP
.br
\fC#include <boost/scoped_ptr.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcryomesh::Pointer< T >\fP"
.br
.RI "\fI\fBPointer\fP struct to allow typdef of templated smart pointers. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< boost::shared_ptr< components::Node >, std::map< boost::shared_ptr< components::Node > > > \fBNeighbourhoodMap\fP"
.br
.RI "\fI\fBDefs.h\fP. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::map<boost::shared_ptr< components::Node >, std::map<boost::shared_ptr< components::Node > > > \fBNeighbourhoodMap\fP"
.PP
\fBDefs.h\fP. Created on: 26 Jan 2011 Author: SevenMachines<SevenMachines@yahoo.co.uk> 
.PP
Definition at line 14 of file Defs.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
