.TH "/home/niall/Projects/Eclipse/cryomesh/src/components/ImpulseCollection.cpp" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/components/ImpulseCollection.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ImpulseCollection.h'\fP
.br
\fC#include 'common/TimeKeeper.h'\fP
.br
\fC#include 'common/Maths.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::components\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::components::operator<<\fP (std::ostream &os, const ImpulseCollection &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
