.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/Impulse.cpp" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/Impulse.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Impulse\&.h'\fP
.br
\fC#include 'ActivityTimerDistance\&.h'\fP
.br
\fC#include 'common/Maths\&.h'\fP
.br
\fC#include 'common/TimeKeeper\&.h'\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.RI "\fI\fBConnector\&.h\fP\&. \fP"
.ti -1c
.RI "namespace \fBcryomesh::components\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::components::operator<<\fP (std::ostream &os, const Impulse &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
