.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/ImpulseCollection.h" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/ImpulseCollection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Impulse.h'\fP
.br
\fC#include 'common/Cycle.h'\fP
.br
\fC#include 'common/KeyMappedCollection.h'\fP
.br
\fC#include 'dataobjects/DataObjectController.h'\fP
.br
\fC#include <boost/uuid/uuid.hpp>\fP
.br
\fC#include 'common/Debuggable.h'\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::components::ImpulseCollection\fP"
.br
.RI "\fI\fBImpulseCollection\fP represents a collection of \fBImpulse\fP objects. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::components\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
