.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/Impulse.h" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/components/Impulse.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ActivityTimerDistance.h'\fP
.br
\fC#include <common/SimpleCollection.h>\fP
.br
\fC#include 'common/Tagged.h'\fP
.br
\fC#include 'common/Cycle.h'\fP
.br
\fC#include 'common/TimeKeeper.h'\fP
.br
\fC#include <common/Debuggable.h>\fP
.br
\fC#include <list>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::components::Impulse\fP"
.br
.RI "\fI\fBImpulse\fP is a mobile information packet to be passed between Nodes. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::components\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
