.TH "/home/niall/Projects/Eclipse/cryomesh/src/common/exceptions/IndexOutOfBoundsException.h" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/common/exceptions/IndexOutOfBoundsException.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::common::exceptions::IndexOutOfBoundsException\fP"
.br
.RI "\fI\fBIndexOutOfBoundsException\fP is the exception thrown when accessing beyond the bounds of a collection. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::common\fP"
.br
.ti -1c
.RI "namespace \fBcryomesh::common::exceptions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
