.TH "/home/niall/Projects/Eclipse/cryomesh/src/common/KeyMappedCollection.h" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/common/KeyMappedCollection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <list>\fP
.br
\fC#include <boost/shared_ptr.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::common::KeyMappedCollection< U, T >\fP"
.br
.RI "\fI\fBKeyMappedCollection\fP is a template class of U, a key class which supports getKey(), and T, the object class. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::common\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
