.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/state/Pattern.h" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/state/Pattern.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'PatternTag.h'\fP
.br
\fC#include 'BinaryString.h'\fP
.br
\fC#include 'common/Tagged.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <boost/serialization/vector.hpp>\fP
.br
\fC#include <boost/uuid/uuid.hpp>\fP
.br
\fC#include <boost/uuid/uuid_generators.hpp>\fP
.br
\fC#include 'manager/PatternDatabaseObject.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::state::Pattern\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::state\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
