.TH "/home/niall/Projects/Eclipse/cryomesh/src/state/PatternChannel.cpp" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/state/PatternChannel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'PatternChannel.h'\fP
.br
\fC#include <boost/foreach.hpp>\fP
.br
\fC#include <boost/uuid/uuid_generators.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::state\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::state::operator<<\fP (std::ostream &os, const PatternChannel &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
