.TH "/home/niall/Projects/Eclipse/cryomesh/src/state/Pattern.cpp" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/state/Pattern.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Pattern.h'\fP
.br
\fC#include 'PatternTagById.h'\fP
.br
\fC#include 'common/Misc.h'\fP
.br
\fC#include 'common/Maths.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::state\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::state::operator<<\fP (std::ostream &os, const Pattern &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
