.TH "/home/niall/Projects/Eclipse/cryomesh/src/state/PatternChannel.h" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/state/PatternChannel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Pattern.h'\fP
.br
\fC#include 'PatternTag.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <list>\fP
.br
\fC#include <set>\fP
.br
\fC#include <boost/uuid/uuid.hpp>\fP
.br
\fC#include <boost/shared_ptr.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::state::PatternChannel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::state\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
