.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/utilities/SequencerChannels.h" 3 "Thu Jul 7 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/utilities/SequencerChannels.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'state/PatternChannel.h'\fP
.br
\fC#include 'state/Pattern.h'\fP
.br
\fC#include 'state/PatternChannelMap.h'\fP
.br
\fC#include 'SequencerGeneric.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <boost/uuid/uuid.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::utilities::SequencerChannels\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::utilities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
