.TH "/home/niall/Projects/Eclipse/cryomesh/src/state/Sequence.cpp" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/state/Sequence.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Sequence.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <boost/scoped_ptr.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::state\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::state::operator<<\fP (std::ostream &os, const Sequence &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
