.TH "/home/niall/Projects/Eclipse/cryomesh/src/spacial/SphericalPoint.cpp" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/spacial/SphericalPoint.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SphericalPoint.h'\fP
.br
\fC#include 'Point.h'\fP
.br
\fC#include 'common/Maths.h'\fP
.br
\fC#include <math.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::spacial\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::spacial::operator<<\fP (std::ostream &os, const SphericalPoint &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
