.TH "/home/niall/Projects/Eclipse/CPP/cryomesh/src/utilities/Statistician.cpp" 3 "Tue Mar 6 2012" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/CPP/cryomesh/src/utilities/Statistician.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Statistician\&.h'\fP
.br
\fC#include 'structures/Bundle\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.RI "\fI\fBConnector\&.h\fP\&. \fP"
.ti -1c
.RI "namespace \fBcryomesh::utilities\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcryomesh::utilities::operator<<\fP (std::ostream &os, const Statistician &obj)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code\&.
