.TH "/home/niall/Projects/Eclipse/cryomesh/src/manager/TableFormats.h" 3 "Fri Apr 1 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/manager/TableFormats.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcryomesh::manager::TableFormat\fP"
.br
.RI "\fIGeneral structure of a table. \fP"
.ti -1c
.RI "struct \fBcryomesh::manager::NodeTableFormat\fP"
.br
.RI "\fIStruct representing a node table structure. \fP"
.ti -1c
.RI "struct \fBcryomesh::manager::ConnectionTableFormat\fP"
.br
.RI "\fIStruct representing a connections table structure. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::manager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
