.TH "/home/niall/Projects/Eclipse/cryomesh/src/common/Tagged.h" 3 "Mon Mar 14 2011" "cryomesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryomesh/src/common/Tagged.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/uuid/uuid.hpp>\fP
.br
\fC#include <boost/uuid/uuid_generators.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryomesh::common::Tagged\fP"
.br
.RI "\fI\fBTagged\fP class implements uuid tagging of classes. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryomesh\fP"
.br
.PP

.RI "\fI\fBConnector.h\fP. \fP"
.ti -1c
.RI "namespace \fBcryomesh::common\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh from the source code.
